### ISSUE TITLE
Workflow execution info visible in the visibility record

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#1074]
Currently list of workflow executions doesn't include any user provided information about a workflow.
The proposal is to support additional field (description or info) that is included into the visiblity records.

**Comment by wxing1292** [comment]
can we close this issue ? @vancexu

**Comment by vancexu** [comment]
This is supported by search attributes on advanced visibility store. 
https://cadenceworkflow.io/docs/11_search
https://github.com/uber/cadence/blob/master/docs/visibility-on-elasticsearch.md
