### ISSUE TITLE
Query task would failed if it is issued before first DecisionTask is completed

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#1094]
We were seeing below error from query:
cadence --env autobots -do goautobots-prod-0829-sjc1a_2 wf query -qt state -w 03767417-4de7-45cc-8d32-1af65b8118c5
Error: Query failed
Error Details: QueryFailedError{Message: Workflow panic: MutableSideEffect with given ID not found during replay}

**Comment by yiminc** [comment]
That particular error means the code is trying to access a MutableSideEffect by an ID, and there is no such event (marker) in the history. I tried that query later and it worked fine.  So I think the reason   was that the query was issued too fast before the worker has a chance to work on the first task on that workflow, so when the query task is delivered to the worker, there is no such event in the history yet and the query would fail. As soon as the worker was able to catch up the decision task, the query should work as expected.
We need to somehow avoid this error or at least give a more accurate error.

**Comment by meiliang86** [comment]
@andrewjdawson2016 Can you check if this is still relevant?

**Comment by andrewjdawson2016** [comment]
https://github.com/uber/cadence/pull/2825

This diff addresses the issue. Query cannot complete unless at least one decision task has been completed. This diff will make the error message more obvious.
