### ISSUE TITLE
Reduce debug level output of dynamic config

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#1100]
When running cadence service with DEBUG log level there is large number of entries similar to:

`DEBU[2018-09-10T13:25:27-07:00] Failed to fetch key: history.transferTaskBatchSize from dynamic config with err: unable to find key  Service=cadence-history
`
One entry per access of the given key. 
It would be nice to log this message only once per key.

**Comment by vancexu** [comment]
Fix in https://github.com/uber/cadence/pull/1104

**Comment by dmetzgar** [comment]
Also fixes #664
