### ISSUE TITLE
Properly detect and handle more than 1 workflow ID running

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence#1103]

**Comment by meiliang86** [comment]
Should be part of your invariant check? @andrewjdawson2016

**Comment by wxing1292** [comment]
yes, should be part of the invariant check.

some more info on this: currently, all workflow update transaction will do a check on being the current workflow. so even if we have a bug / data resurrection, the blast radius is acceptable.

**Comment by wxing1292** [comment]
same applies to workflow creation
