### ISSUE TITLE
Provide API to return history as blobs

### ISSUE THREAD

**Issue by dmetzgar** [uber/cadence#1143]
Skips deserialization of this data since we don't need to turn history events into strongly-typed objects on the server side.

**Comment by dmetzgar** [comment]
@longquanzheng was this something you already worked on? Is there a public API to get history blobs?

**Comment by longquanzheng** [comment]
No I didn't work on that. Wenquan added that API and it's now public. 
Here is the API IDL: https://github.com/uber/cadence/blob/master/idl/github.com/uber/cadence/admin.thrift#L54
