### ISSUE TITLE
Cross DC - Return Err If Domain Is Effectively Local Domain And Not Active 

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence#1150]

**Comment by meiliang86** [comment]
@yux0 @wxing1292 This seems like an old task. Is it still valid?

**Comment by wxing1292** [comment]
this has something to do with list open / close workflow of a domain which is effectively local (global domain with one target datacenter).

my opinion, the current behavior is ok, i.e. any read operation should not see domain not active.
`this is a feature, not a bug`
