### ISSUE TITLE
SignalWithStart failed due to race condition

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#1162]
{
  "_index": "wl-cadence-sjc1-esr-115",
  "_type": "doc",
  "_id": "AWZArS5VSDPOXG7g8WgA",
  "_score": null,
  "_source": {
    "msg": "helpers.go:78 Uncategorized error",
    "err": "code:internal message:Workflow execution creation condition failed. WorkflowId: 4552ec6a-d99a-4d42-a89a-61ff3b71c6ac, columns: (range_id=0,workflow_id=4552ec6a-d99a-4d42-a89a-61ff3b71c6ac,run_id=30000000-0000-f000-f000-000000000001,visibility_ts=2000-01-01 00:00:00 +0000 UTC,current_run_id=12d37ce2-72a5-4c64-b34e-9357e1d9d8c8,workflow_last_write_version=0,workflow_state=0,[applied]=false,shard_id=6689,type=1,domain_id=e5523a72-26eb-4a97-b04d-69342b47e9dc,task_id=-10)",
    "level": "error",
    "elk": {
      "service_name": "cadence",
      "kafka_topic": "cadence_logs"
    },
    "tenancy": "null",
    "Service": "cadence-frontend",
    "datacenter": "sjc1",
    "tags": [
      "cadence_logs"
    ],
    "deployment-name": "autobots_prod_sjc1a",
    "@timestamp": "2018-10-04T20:03:03.275Z",
    "host": "compute12971-sjc1",
    "@version": "1"
  },
  "sort": [
    1538683383275
  ]
}

**Comment by samarabbas** [comment]
Looks like SignalWithStart logic does account for 'WorkflowIDReusePolicy', so if there is an execution which already completed.  Then sending another signal to the same execution will result in a failure as the default policy is 'WorkflowIdReusePolicyAllowDuplicateFailedOnly'.  
I think we also need to fix error handling in this case.
