### ISSUE TITLE
Integration test becomes flaky

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#1180]
There are some red marks in the last merged commits:
https://github.com/uber/cadence/commits/master

Also on my laptop, running "make cover_ci" sometimes would fail.
They are because for two reason: 
```
*** Test killed: ran too long (11m0s).
FAIL	github.com/uber/cadence/host	712.056s
```
Or
```
    --- FAIL: TestIntegrationSuite/TestActivityCancellation (1.89s)
        <autogenerated>:1: 
            	Error Trace:	integration_test.go:1767
            	Error:      	Should be true
            	Test:       	TestIntegrationSuite/TestActivityCancellation
```
My guess is we hit some performance issue in the last few commits.

**Comment by longquanzheng** [comment]
https://travis-ci.org/uber/cadence/builds/440767443?utm_source=github_status&utm_medium=notification

https://travis-ci.org/uber/cadence/builds/441820429?utm_source=github_status&utm_medium=notification

https://travis-ci.org/uber/cadence/builds/441144876?utm_source=github_status&utm_medium=notification

**Comment by longquanzheng** [comment]
https://travis-ci.org/uber/cadence/builds/442942611?utm_source=github_status&utm_medium=notification

**Comment by longquanzheng** [comment]
looks like our timeout for tests is too short as we are adding more tests. I bump it into 15 mins: https://github.com/uber/cadence/blob/master/Makefile#L23

**Comment by dmetzgar** [comment]
@longquanzheng it looks like this can be closed now that we moved to buildkite

**Comment by longquanzheng** [comment]
Yes let me close it.
