### ISSUE TITLE
Expose server side retry information through describe API

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#1202]
Describe workflow execution behavior is broken when server side retries kicks in for activities.  Currently we expose the following pending activity information:
```
{
      "ActivityID": "57",
      "ActivityType": {
        "name": "hearbeating_activity"
      },
      "State": "STARTED",
      "HeartbeatDetails": "162125\n",
      "LastHeartbeatTimestamp": "2018-10-24T20:15:57Z"
    }
```

If this activity timeouts due to heartbeat timeout it shows the following:
```
{
      "ActivityID": "57",
      "ActivityType": {
        "name": "hearbeating_activity"
      },
      "State": "SCHEDULED",
      "HeartbeatDetails": "",
      "LastHeartbeatTimestamp": "1970-01-01T00:00:00Z"
    }
```

Details and LastHeartbeatTimestamps are cleared.  We need to surface all retryable information in mutable state including previous errors, lastheartbeat, etc.

**Comment by shail** [comment]
Any update on this? Would be helpful for debugging

**Comment by andrewjdawson2016** [comment]
Let's start this task by showing what we want the response to look like. There are at least three interesting points in time to consider: (1) When the activity is running but retries are not exhausted. (2) Retries are exhausted for activity but workflow is not closed. (3) Workflow is closed. We need to make sure the describe workflow API surfaces correct and informative responses in all these cases.

Lets start by:
1. Figuring out what information we want to surface.
2. Write out sample responses in this ticket.

**Comment by yycptt** [comment]
For case 2 and 3, the activity is either succeed or failed, and the information can be accessed by showing history of the workflow. For case 1, I am unable to get a local repro. I think it has already been fixed by [#1204](https://github.com/uber/cadence/pull/1204). See also [#1219](https://github.com/uber/cadence/pull/1219).

**Comment by yycptt** [comment]
need to create an integration test to ensure the behavior is correct.

**Comment by yycptt** [comment]
[PR](https://github.com/uber/cadence/pull/1593) for the integration test.

**Comment by yycptt** [comment]
Just found that the issue still exists for cross-DC. Working on a fix.

**Comment by yycptt** [comment]
Merged. Closing this issue.
