### ISSUE TITLE
Deserialize History Blobs on Client Rather than Server

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#1208]
Cadence frontend reads history for executions from persistence and deserializes them before sending it back to client.  This adds unnecessary load on the frontend as it never does anything with the history before shipping it back to client.  
We need to have another API to GetRawHistory which returns the entire payload as-is back to client and client does the deserialization to thrift object.  This will reduce a lot of load from frontend.

**Comment by wxing1292** [comment]
dup of #1323
