### ISSUE TITLE
Add support for additional SQL connection parameters

### ISSUE THREAD

**Issue by richardbolt** [uber/cadence#1222]
Usage case: allows connections to use TLS and other tuning parameters

The TLS option is close to mandatory when running your SQL db on Azure's hosted MySQL service.

I do have working code and would be very happy to submit a PR.

**Comment by dmetzgar** [comment]
@richardbolt it looks like this is supported [in config](https://github.com/uber/cadence/blob/3ef6d2f8633a9e3bfc83c89a30f0bd93e17e51c3/common/service/config/config.go#L198). Feel free to reopen if this doesn't work for your case.
