### ISSUE TITLE
Defining Activities in a separate file as the workflow

### ISSUE THREAD

**Issue by pedramha** [uber/cadence#1255]
Is it possible to have remote rest services as activities/workers?
And define the endpoints in the workflow?
for example:worker.registerActivitiesImplementations("REST Endpoint");
If not, is there any workaround?
Thanks

**Comment by mfateev** [comment]
I think it can be achieved without modifying the core Cadence SDJK by implementing a RestEndpoint activity. Something like:

```
public interface RestEndpoint {
     ... get ...
     ... put ...
     ... post ...
}

```
Then implementing it to call to any rest service:

```
public class RestEndpointImpl implements RestEndpoint {
    public RestEndpointImpl(String host, int port) {
      ....
    }
    ...  
}


```

Then register it with the worker:

`
worker.registerActivitiesImplementations(new RestEndpointImpl(host, port));
`

In the longer term we want to have a library of such generic activities. You are welcome to contribute to it :).

**Comment by dmetzgar** [comment]
@pedramha do you have any other follow-up for this issue? If not, I'd like to close it.
