### ISSUE TITLE
Operational constraints for workers

### ISSUE THREAD

**Issue by sagikazarmark** [uber/cadence#1266]
While evaluating if Cadence fits our use case or not I found a few things in the documentation after I already played with it.

One of our key requirements that workflows should survive worker restarts/deployments and continue running. I think this is obvious for long running workflows.

In order to achieve this goal, I implemented the first few activities as idempotent and gave the workflows and activities long timeouts and high retry counts. I was able to achieve what I wanted: after a task timed out (because the worker was restarted) it was rescheduled and retried a few times, but then eventually failed if I restarted the workers more times than the set retry count was.

This seemed to be a problem, because I can set those retry counts in the code, but I can't predict if a worker gets into a crash loop because of a task for example. That could easily exhaust the retry count quickly.

Then I found the following:

> At-Most-Once Activity Execution
> Activities need not be idempotent

Which sounds really nice at first, but given the above cases, when a worker restarts in the middle of a task execution, how can Cadence guarantee this?

I couldn't find anything about this in any documentation, so I'm asking here: what are the operation constraints and best practices for running workers to deliver the above guarantee? Is there a way to drain/cordon workers so that they don't receive any more tasks?

Are there any graceful shutdown options for workers?

Thinking about this matter in the cloud native/container/kubernetes context: how can we achieve the above?

My guess is that I somehow have to wait for workers do finish executing all the actions and then restart/deploy the new ones, but this doesn't seem to be really easy to do currently.

I'm really curious about the the best practices, because unwanted restarts do happen, deployments do happen.

If I missed an existing documentation, please feel free to point me there first.

Thanks a lot!

**Comment by dmetzgar** [comment]
Check out Maxim's talk here: https://youtu.be/-BuIkhlc-RM?t=790
I have it start from the point where he goes into worker failures. We should improve the landing site and provide links to some in-depth exploration of the features.

**Comment by sagikazarmark** [comment]
@dmetzgar Thanks for the quick answer.

Let me see if I get this straight: In case of a worker failure

- I'm either lucky and my activity just finishes execution, the workflow can continue running
- or the activity fails with a timeout error and I have to remediate it (eg. check how far the activity got with it's job and either continue or rollback and restart)

Obviously the second option is what concerns me. If I understand this right I should wait for the activity to either timeout or succeed. But what are retries for then?

If I configure an activity to be retried, it won't timeout until all the retry options are exhausted. In an unfortunate case my activity could actually succeed, but not report the success back. In that case retrying a non-idempotent activity is not an option.

**Comment by mfateev** [comment]
I would rely on remediation only for non idempotent activities. The idempotent ones better rely on retries. As far as retries I wouldn't specify the maximum retry count but the retry expiration period. And it is OK to set the retry period for a very large interval. Then assuming that you have monitoring and alarming in place you'll get paged about the constant activity failure loop and fix it with a new deployment unblocking the workflow.

**Comment by sagikazarmark** [comment]
@mfateev thanks, makes sense.

I think it would make sense to document this as a part of a set of best practices:

1. Retry non-idempotent actions manually in a workflow (with potentially necessary cleanup first)
2. Rely on cadence to retry idempotent actions
