### ISSUE TITLE
Creating generic workers and activities

### ISSUE THREAD

**Issue by pedramha** [uber/cadence#1269]
I am trying to create a generic service, which receives a URL from a workflow, makes a call to the URL and return the payload to the workflow. But I am not able to register the activity, nor send a URL to it from the workflow. Is this possible?
Is it also possible to avoid giving Domain and TASK_LIST to the worker thereby making it more generic(and give server IP instead/specify it from workflow)?
This is my code:

    public interface CallRestEndpoint {
        @ActivityMethod
        String makeRequest(String URL) throws IOException;
    }

    public static class CallRestEndpointImpl implements CallRestEndpoint {

        public String makeRequest(String url) throws IOException {
            java.net.URL url1 = new URL(url);
            URLConnection yc = url1.openConnection();
            BufferedReader in = new BufferedReader(
                    new InputStreamReader(
                            yc.getInputStream()));
            String inputLine;
            StringBuffer results=new StringBuffer();
            while ((inputLine = in.readLine()) != null)
            {
                results.append(inputLine);
            }
            in.close();
            return  results.toString();
        }
    }
    public static void main(String[] args) throws ExecutionException, InterruptedException {
        //avoid getting the domain and TASK_LIST here-but rather the IP of the server
        Worker.Factory factory = new Worker.Factory(DOMAIN);
        Worker worker = factory.newWorker(TASK_LIST);
        //avoid writing workflow related code here if possible
        worker.registerActivitiesImplementations(new CallRestEndpointImpl());
        factory.start();
    }
And this is the workflow code I have(in a separate file):

    public class workflowInst {
        public static void main (String[] args) throws Exception{
            WorkflowClient workflowClient=WorkflowClient.newInstance(DOMAIN);
            WorkflowOptions options=new WorkflowOptions.Builder().setWorkflowId("test").build();
            workflowClient.newWorkflowStub(RestService.class,options);
        }
    }

**Comment by mfateev** [comment]
Your activity implementation looks fine. 
As far as workflow I don't see any workflow implementation here, so I'm not sure if it has any issues.
The workflow code you posted is supposed to start workflow instances. It actually not doing it as the workflow stub is created but never used. You probably want to add something like:

```
RestService rest =  workflowClient.newWorkflowStub(RestService.class,options);
rest.whateverWorkflowMethod(...); // to wait for workflow to complete
// or
WorkflowClient.start(rest::whateverWorkflowMethod, ...); // async start
```
