### ISSUE TITLE
Range delete for replication task processor

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#1272]
We still use complete replication task api to individually delete replication task after we are done processing them.  This eats up lots of cassandra capacity.  Let's move to range deletes like we did for transfer and timer tasks.
Also I think we do not handle throttle errors gracefully on complete, which results in leaking some of the replication tasks.

**Comment by yux0** [comment]
With Kafka deprecation. The replication task processor is deprecated. The new approach uses batch complete operation.
