### ISSUE TITLE
Ignore status filter if user specify both ID and status for listing executions

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#1293]
We have limited number of secondary indexes.  We should ignore the status filter if the user calls list workflow execution with both workflow execution ID and status filter.

**Comment by vancexu** [comment]
Allow this is a little bit confusing, will put off doing this. After new visibility completed, we can allow multiple filter.

**Comment by vancexu** [comment]
This will be done as part of https://github.com/uber/cadence/issues/1630
