### ISSUE TITLE
High availability setup

### ISSUE THREAD

**Issue by h7kanna** [uber/cadence#1307]
Are there any guidelines to operate Cadence in production in a high availability setup like how to do load balancing from cadence workers to cadence frontend? How to scale up cadence servers?

**Comment by sagikazarmark** [comment]
Any update?

**Comment by dharmjit** [comment]
Hi Team, I am also looking for any doc on this as i am also considering cadence for one of my project.

**Comment by r-tock** [comment]
Hi, we are exploring Cadence over Airflow and would love pointers on how this is set up

**Comment by mfateev** [comment]
We recommend using HelmChart to deploy to k8s. This is the simplest option.
We don't have the documentation yet. Feel free to ask help at the[ Cadence Slack channel.](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTQyYjcxZDM2YTIxMTZkMzQ0NjgxYmI3OWY5ODhiOTliM2I5MzA4NTM4MjU4YzgzZDkwNGEzOTUzNTBlNDk3Yjc)
