### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by h7kanna** [uber/cadence#1308]
Hello team,

Can the team please publish a roadmap for cadence project?
I understand that preferences would be aligned to Uber's goals. 
But a public roadmap may help in adoption of the project.

In particular,  I personally have below queries.
1) Are there any plans to move to GRPC for communication similar to https://github.com/jaegertracing/jaeger/issues/773. 
Currently Cadence uses TChannel which inhibits developing client side libraries in other languages.

2) Is there a plan to support alternative interface to Frontend (HTTP/Swagger spec)?

3) Any plans to make Cadence more cloud-native(Kubernetes friendly).
 I am working on deploying Cadence to Kubernetes and develop 'cadence-operator' to orchestrate the deployment.

4) Ringpop is not under active development. What does it mean for Cadence?
https://github.com/uber/ringpop-go
Will the team accept alternative the membership logic implementations, For example using https://github.com/hashicorp/memberlist or https://github.com/hashicorp/serf.

5) What is the plan to make SQL datastore implementation production ready?

Thanks.
Harsha

**Comment by mfateev** [comment]
1. Yes, we do plan to switch to GRPC in 2019.
2. We didn't plan it as internally at Uber there is no need. But we would gladly accept external contributions in this area. I believe that after switching to GRPC it would become simpler as proto generator is pretty pluggable.
3. Could you specify what exactly is needed from the Cadence to become Kubernetes friendly?
4. We plan to get rid of Ringpop. As Cadence already uses a strongly constistent database it can be used to implement a similar component.
5. We are actively working on it. I believe it will be production ready in Q1.

**Comment by h7kanna** [comment]
Thanks @mfateev 
I will post more Kubernetes specific questions as I work on the operator.

**Comment by sagikazarmark** [comment]
I guess the main question regarding Kubernetes is the optimal way of joining new instances to an existing cluster when scaling up, as well as an optimal production setup in light of the load.

I'm not familiar with ringpop, but I'm guessing some sort of orchestrator could manage the list of existing members and pass that list as a JSON file to starting instances.

**Comment by StevenACoffman** [comment]
I would also like to see a Cadence activity that runs a Kubernetes job to completion. For instance, in Airflow, we use AirFlow Operators to generate Kubernetes jobs, so that we can run heterogeneous finite, run-to-completion tasks in various languages. The orchestration/pipeline/workflow is the piece we do not have a great solution for.

**Comment by mfateev** [comment]
I think that we need to start to think about libraries of Cadence activities for specific sets of use cases. For example K8s integration, gRPC activity proxies, HTTP actiivty proxies, etc.

**Comment by meetchandan** [comment]
Hi @mfateev -- Sorry if I sound off-topic?
Is this discussion about support of operators like we have in Airflow?

What is the best way to run a bigquery job with cadence?
