### ISSUE TITLE
Stuck workflow detection due to lost decision task

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#1381]
Loosing a decision task could result in stuck workflow executions.  Mostly this happens due to a bug on Cadence Server which results in dropping DecisionTask.  We need to have some generic protection in place to either prevent workflow executions resulting from loosing decisions or atleast some kind of alerting mechanism when this happens.  
One potential idea is to always create decision task schedule to start timeout and run some kind of heuristic to detect stuck executions and re-inject decisions.

**Comment by wxing1292** [comment]
Expose API to refresh all task using [mutableStateTaskRefresher](https://github.com/uber/cadence/blob/master/service/history/mutableStateTaskRefresher.go)

**Comment by meiliang86** [comment]
@andrewjdawson2016 This should be part of your scanner? Also What @wxing1292 mentioned should be the resolution.
