### ISSUE TITLE
Open record not showing up until first decision

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#1406]
Cron workflow will create next execution with delayed first decision task.

Currently, the visibility record is created only after first decision scheduled.

**Comment by andrewjdawson2016** [comment]
Let's sync up with Bowei on the best approach here. He has a lot of context on visibility.

**Comment by yycptt** [comment]
The issue also exists for workflow retry. During backoff, list open workflow returns no record for the workflow. 

To repro this bug, use a workflow that returns directly (return an error if testing retry), then specify a cronSchedule or retry policy in startWorkflowOptions. Run this workflow and check cadence-web's open workflow or use cli to list open workflows. There will be no records.

**Comment by yycptt** [comment]
Besides fixing the bug, more information should be exposed through list open workflow API, for example, next scheduled time, failing reason, etc.
