### ISSUE TITLE
protect cron from complete

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#1419]
we have a bug where the cron schedule was not replicated to passive cluster, so after failover, the workflow will not schedule next run when it complete.

We could have some logic to protect this. For example, in the now passive cluster (which previously was active and know the workflow is cron), when it receive the complete workflow event, it should do something. For example, it should call the new active cluster directly to start the cron again.

**Comment by yycptt** [comment]
Will create a failover integration test for cron workflow.

**Comment by yycptt** [comment]
The bug still exists for retry and cron workflow if failover happens during the first run. 

PR for the fix and integration test: https://github.com/uber/cadence/pull/1715
