### ISSUE TITLE
Improve Docker setup

### ISSUE THREAD

**Issue by sagikazarmark** [uber/cadence#1448]
The current official docker images and the provided docker files are quite huge and could use some optimization. Here is a list of optimizations I suggest:

- Do not install debug tools (vim, tcpdump, netcat) in the image by default
- Use an alpine image for production instead of jessie
- Build using the latest go version (1.11.5 at the time)
- Since MySQL support is coming, consider moving schema and storage specific tasks to separate images and use them as init containers
- Move the dockerfile to the repository root and instead of cloning the repo copy the files from the local repo (this is kinda the standard way)

I'm happy to provide a PR for addressing the above if you agree or further discuss here if necessary.

**Comment by mfateev** [comment]
This one might contain some ideas:
https://towardsdatascience.com/slimming-down-your-docker-images-275f0ca9337e
