### ISSUE TITLE
Implement clean host shutdown to avoid errors during deployments

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#1454]
Currently deployments lead to small number of intermittent request failures. While it is not catastrophic it still affects availability metrics and might alert customers. 
This issue is to implement clean service hosts shutdown to avoid any errors in case of scheduled deployments.

**Comment by vitarb** [comment]
Looking at the data, there is indeed a strong correlation between deployments and availability drops. We currently observe availability drops down to 80-90% during the deployment time. To address this issue we should handle SIGTERM signal that is sent a few seconds before SIGKILL by our deployment infrastructure to notify the ring about shard ownership changes ensuring that old host is still online while ownership change is inflight.

**Comment by demirkayaender** [comment]
This is done
