### ISSUE TITLE
Dedup signals

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber/cadence#1477]
It would be useful if cadence server could handle dedupping of signals. I discovered the usefulness of this feature when writing archival signal processing. Basically the customer experience should be that for a target workflow execution only one signal will ever be delivered. If multiple signals are sent then the cadence server will handle dedupping and only deliver one signal.

**Comment by mfateev** [comment]
I don't think we are going to support this feature. The reason is that it would require storing each signal id in the mutable state and also is not going to . work with continue as new.
