### ISSUE TITLE
Add attempts field to ActivityTaskCompleted event

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#1482]
It might be useful to understand why activity took so long to execute.

**Comment by anish531213** [comment]
Hi @mfateev, attempts field is already added to ActivityTaskStarted event. Do we want to:
1. Move that to ActivityTaskCompleted  and other(ActivityTaskFailed, Canceled, Timeout) etc.
2. Keep in both ActivityTaskStarted and 1.
3. Keep just in ActivityTaskStarted.

**Comment by meiliang86** [comment]
I think it should be enough to have this in ActivityTaskStarted. @mfateev you can reopen this if you think otherwise.
