### ISSUE TITLE
Document security reporting process

### ISSUE THREAD

**Issue by wrycu** [uber/cadence#1483]
It would be great to have the readme indicate the proper process for reporting security issues - be it sending an e-mail to security@uber.com, some other mailing list, or filing an issue with a particular format.

**Comment by samarabbas** [comment]
I have created a [Security](https://github.com/uber/cadence/labels/Security) label for filing security issues with Cadence server.  I also update the readme with instructions.  In the meantime please file a github issue and label it accordingly.

**Comment by wrycu** [comment]
Thanks. I don't have an issue to report - sorry if I gave that impression.
