### ISSUE TITLE
Add information about all parents to the child WorkflowExecutionStarted event

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#1484]
In some scenarios a workflow might want to signal parent of its parent for example. Currently there is no easy way to get information about any parent which is not the direct one.
The proposal is to add information about all the parents to the WorkflowExecutionStarted event.

**Comment by mfateev** [comment]
Also add this information to DescribeWorkflowExecution result.

**Comment by prsadh** [comment]
Is this issue still available to take up if I want to contribute?
