### ISSUE TITLE
docker/README.md doesn't describe how to connect to local docker with Cadence-Cli

### ISSUE THREAD

**Issue by vkuzmin-uber** [uber/cadence#1491]
https://github.com/uber/cadence/blob/0ead74abb625e7dd525a9656548f9fafd6de75ec/docker/README.md tells how to start up server

```
cd $GOPATH/src/github.com/uber/cadence/docker
docker-compose up
```

How to run cli.
Use Cadence-CLI with `docker run --rm ubercadence/cli:master`

If I run it to register new domain, I get error:

```
docker run --rm ubercadence/cli:master --do swn-dev1 domain register -rd 7
Error: Register Domain operation failed.
Error Details: code:unknown message:received unknown error calling service: "cadence-frontend", procedure: "WorkflowService::RegisterDomain", err: dial tcp 127.0.0.1:7933: getsockopt: connection refused
('export CADENCE_CLI_SHOW_STACKS=1' to see stack traces)
```

I guess that because it started in docker, 127.0.0.1 is not a correct address here. I tried to provide --address flag but it failed with timeout.

Can we improve document and provide some example how to run "domain register" using "Cadence-CLI with `docker run --rm ubercadence/cli:master`" ?

**Comment by vkuzmin-uber** [comment]
The link to file https://github.com/uber/cadence/blob/0ead74abb625e7dd525a9656548f9fafd6de75ec/docker/README.md#L17

**Comment by keeblerelvis** [comment]
You need to specify "host" as the network. Like this:
docker run --network=host --rm ubercadence/cli:master --domain test1 domain register

**Comment by vkuzmin-uber** [comment]
Confirm, it works now! I will provide pull-request with fix to README file.

**Comment by vkuzmin-uber** [comment]
Pull request: https://github.com/uber/cadence/pull/1495

**Comment by longquanzheng** [comment]
Looks like the PR is merged. Feel free to open it again if you still have any problems @vkuzmin-uber
