### ISSUE TITLE
Timeout errors counting against our SLO

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber/cadence#1497]
When frontend PollForDecisionTask is invoked it will call into matching to get a task to dispatch. The context given to the frontend RPC request is passed along to matching service. If the context times outs then it will time out for both frontend and matching at the same time. A context timeout on matching should return emptyPollForDecisionTaskResponse, but by the time matching gets the context closed and tries to return back to frontend, frontend has already timeout. We then log an error on frontend and emit a timeout metric. This falsely counts against our SLO. What we actually want is for matching to return a emptyPollForDecisionTaskResponse in time for frontend to get that response. 

Possible solution: shorten the timeout on the context given to matching by some very small amount. This will cause matching to timeout still with time to return back to frontend.

**Comment by yycptt** [comment]
[#1548](https://github.com/uber/cadence/pull/1548)

**Comment by yycptt** [comment]
Merged. Closing the issue.
