### ISSUE TITLE
What are best practices for cadence deployments

### ISSUE THREAD

**Issue by rajeshbr** [uber/cadence#1498]
I am evaluating Cadence for one of my projects. I am required to create hundreds of thousands of workflows in Async mode. When I am trying to start ten thousand workflows with two worker threads I am getting the following errors after 4000 workflows are created. 
In workflow starter
>Caused by: ServiceBusyError(message:Too many outstanding requests to the cadence service)

And the following warning message in Cadence server

>WARN[2019-02-28T12:22:14+05:30] Too many pendind tasks.                       Service=cadence-history shard-id=1 wf-cluster=active wf-component=transfer-queue-processor

I have 
>scheduleToCloseTimeoutSeconds=300

for Activity and 
>executionStartToCloseTimeoutSeconds = 900

for workflow

Also are there any references for Cadence cluster setup? I am not able to find anything related on google!

**Comment by samarabbas** [comment]
@rajeshbr Are you using Cadence development docker to run this scale test?  My guess is cluster is not provisioned appropriately for the expected workload.  We are still working on documentation for setting up Cadence clusters.  In the meantime I recommend joining our [slack channel](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTI5Yzc5ODYwMjg1ZmI3NmRmMTU1MjQ0YzQyZDc5NzMwMmM0NjkzNDE5MmM0NzU5YTlhMmI4NzIzMDhiNzFjMDM) and we can work through your setup questions there.

**Comment by samarabbas** [comment]
**Feedback From Slack Channel**

- The database tools are not really mentioned very clearly / linked from the main documentation
- The different server roles (worker, frontend, ...) are not obvious in much of the documentation, and there is no docker setup that splits them out
- The database upgrade documentation mentions some calls with versions, but its not clear how you know what version you need if you update:
```
./cadence-sql-tool --ep $SQL_HOST_ADDR -p $port --driver mysql --db cadence_visibility update-schema -d ./schema/mysql/v57/cadence/versioned -v x.x -y -- executes a dryrun of upgrade to version x.x
```
- The implications and architecture for picking MySQL are not obvious. It looks like this is aimed at a single master DB.
- Bug in https://github.com/uber/cadence/blob/master/tools/sql/handler.go#L83 - message talks about Keyspace, actually should be database parameter
- Not much information about the config beyond the basics. Error message for not having a dynamic config file in the right place isn't great:
```
2019/09/25 16:00:41 error creating file based dynamic config client, use no-op config client instead. error: Stat : The system cannot find the path specified.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x159c86a]
```
- More generally, I think it would be helpful with the docker quickstart setups if the webui could allow you to create a domain, and do a better job of explaining that since it's an overloaded term

**Comment by samarabbas** [comment]
The server initialization is super-flaky in the face of setup mistakes.  ClusterMetadata is not set in development_mysql.yaml and results in the following panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x159c86a]

goroutine 1 [running]:
main.(*server).startService(0xc00040f680, 0xc00029ffb0, 0xc000035180)
        E:/stuff/cadence/cmd/server/server.go:135 +0x94a
main.(*server).Start(0xc00040f680)
        E:/stuff/cadence/cmd/server/server.go:79 +0x73
```

**Comment by longquanzheng** [comment]
> The server initialization is super-flaky in the face of setup mistakes. ClusterMetadata is not set in development_mysql.yaml and results in the following panic:
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x0 pc=0x159c86a]
> 
> goroutine 1 [running]:
> main.(*server).startService(0xc00040f680, 0xc00029ffb0, 0xc000035180)
>         E:/stuff/cadence/cmd/server/server.go:135 +0x94a
> main.(*server).Start(0xc00040f680)
>         E:/stuff/cadence/cmd/server/server.go:79 +0x73
> ```

the panic will be fixed in : https://github.com/uber/cadence/pull/2608

**Comment by longquanzheng** [comment]
related to https://github.com/uber/cadence/issues/2609

**Comment by michaldul** [comment]
> We are still working on documentation for setting up Cadence clusters.

@samarabbas Are there any updates in that matter? I wonder where should I learn how to run more than a single server instance.

**Comment by mfateev** [comment]
At this point we recommend using [Helm Chart ](https://hub.kubeapps.com/charts/banzaicloud-stable/cadence)and we planning to get much better documentation in the Q1 next year.

**Comment by mattsleiman-discovery** [comment]
Any updates on the documentation? My team is starting a new project and we are planning to use Cadence. We aren't using Kubernetes so we can't use the Helm Chart linked above. Any documentation on how to run a Cadence cluster would be very helpful to us.

**Comment by Andrew4d3** [comment]
I would like some updates about this

**Comment by longquanzheng** [comment]
@Andrew4d3 we are working on https://cadenceworkflow.io/ and there are new updates in it recently. There are also working docs in https://docs.google.com/document/d/1tQyLv2gEMDOjzFibKeuVYAA4fucjUFlxpojkOMAIwnA/edit# that will be moved to there as well.

**Comment by longquanzheng** [comment]
https://cadenceworkflow.io/docs/operation-guide/setup/
