### ISSUE TITLE
ActivityCancellation does not result in new DecisionTask

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#1513]
When decider makes a activity cancellation decision and activity is not started, we write 2 events to history 'ActivityTaskCancelRequested' and 'ActivityTaskCanceled'.  'ActivityTaskCanceled' event should result in new DecisionTask being created as the decider may be clocked on activity completion before it makes workflow close decision.
This could result into workflow getting stuck.

**Comment by algobardo** [comment]
What is the status on this?

**Comment by samarabbas** [comment]
This fix is scheduled for this sprint.  Fix will be included in the next release of server.
