### ISSUE TITLE
CLI: support restart failed workflow

### ISSUE THREAD

**Issue by vancexu** [uber/cadence#1524]
Currently, if user wants to restart a failed workflow (with same workflowID and input), user has to copy wid and input then use CLI startWorkflow. 
It might be useful to add a `restart` command as a shortcut: given failed workflowID, auto fetch input and start the workflow.

**Comment by mfateev** [comment]
On the server side it is just Reset to the history before the first decision.

**Comment by longquanzheng** [comment]
We already have CLI to reset any workflow including failed ones.

**Comment by vancexu** [comment]
With eventv2 and reset, will user have access to previous failed workflow? @longquanzheng

**Comment by longquanzheng** [comment]
> With eventV2 and Reset, will user have access to previous failed workflow? @longquanzheng
> I thought Reset to a decision means everything after that decision will be dropped and not visible

Yes user will have the access to reset any failed WFs as long as the history is not deleted yet. 
Reset only allows resetting to decision finish event. It doesn't have to be decision task completed event. In this case, the decision finish event can be WF timeouted/failed.

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence/pull/1552
