### ISSUE TITLE
DescribeTaskList should include backlogHint

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber/cadence#1527]
Currently DescribeTaskList only returns information about the pollers. This API would be more useful if it also included things like backlogHint. This involves cli changes, plumbing through frontend and returning this value out of matching service.

**Comment by andrewjdawson2016** [comment]
And anything else you think would be useful to return out of matching for visibility into tasklist.

**Comment by yycptt** [comment]
longPollExpirationInterval and maxTasklistIdleTime maybe?

**Comment by yycptt** [comment]
Merged. Closing this issue. [#1542]( https://github.com/uber/cadence/pull/1542)
