### ISSUE TITLE
Verify backlogHint computation is correct for sticky task lists

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber/cadence#1528]
Since decision tasks in sticky task list expire after 5 seconds it is likely that we have a bug in computing backlog hint for decision tasks in sticky task lists. 

There are two pieces to this task:
- Check if a bug exists
- Fix the bug if it exists

**Comment by yycptt** [comment]
No bug found. Working on an integration test to double verify the backlogCountHint computation.

**Comment by yycptt** [comment]
Confirmed. Closing the issue.
