### ISSUE TITLE
cadence web shows invalid start and end time for workflow execution with mysql

### ISSUE THREAD

**Issue by pgohite** [uber/cadence#1529]
Cadence version: 0.5.5
Cadence web version: 3.2.2
Database: MYSQL: 5.7
Environment: Docker
Below, UI pages shows invalid start and end time:

![Screen Shot 2019-03-13 at 11 19 51 AM](https://user-images.githubusercontent.com/7144331/54315294-f3dae580-459a-11e9-8a8d-9ec9869951ed.png)

RPC call which fetches the data from server also returns invalid start & end time:
![Screen Shot 2019-03-13 at 11 21 41 AM](https://user-images.githubusercontent.com/7144331/54315625-d1959780-459b-11e9-86d3-7d0e63524752.png)

Execution history has correct time:
![Screen Shot 2019-03-13 at 11 20 16 AM](https://user-images.githubusercontent.com/7144331/54315559-add25180-459b-11e9-9eff-b8af8e8542ab.png)

History CLI output:
(EventId:1, Timestamp:1552500601045272685, EventType:WorkflowExecutionStarted, Version:-24, WorkflowExecutionStartedEventAttributes:(WorkflowType:(Name:main.DeploymentWorkflow), TaskList:(Name:demo), Input:["arg1"], ExecutionStartToCloseTimeoutSeconds:60, TaskStartToCloseTimeoutSeconds:10, ContinuedExecutionRunId:6cffd406-9dc9-430a-9ecb-c92c28d08e85, Initiator:CronSchedule, ContinuedFailureDetails:[], LastCompletionResult:[], Attempt:0, CronSchedule:*/10 * * * *, FirstDecisionTaskBackoffSeconds:599))
(EventId:2, Timestamp:1552501200052930670, EventType:DecisionTaskScheduled, Version:-24, DecisionTaskScheduledEventAttributes:(TaskList:(Name:demo), StartToCloseTimeoutSeconds:10, Attempt:0))
(EventId:3, Timestamp:1552501200059833232, EventType:DecisionTaskStarted, Version:-24, DecisionTaskStartedEventAttributes:(ScheduledEventId:2, Identity:16193@localhost@demo, RequestId:32b69aa8-7eb4-4173-a6ed-6d3bc7ddbb65))
(EventId:4, Timestamp:1552501200067769995, EventType:DecisionTaskCompleted, Version:-24, DecisionTaskCompletedEventAttributes:(ExecutionContext:[], ScheduledEventId:2, StartedEventId:3, Identity:16193@localhost@demo, BinaryChecksum:eae45b8da05ba5479aa5089e6dbaaa94))
(EventId:5, Timestamp:1552501200067776615, EventType:ActivityTaskScheduled, Version:-24, ActivityTaskScheduledEventAttributes:(ActivityId:0, ActivityType:(Name:main.dummyActivity), TaskList:(Name:demo), Input:["arg1"], ScheduleToCloseTimeoutSeconds:60, ScheduleToStartTimeoutSeconds:60, StartToCloseTimeoutSeconds:60, HeartbeatTimeoutSeconds:20, DecisionTaskCompletedEventId:4))
(EventId:6, Timestamp:1552501200074834174, EventType:ActivityTaskStarted, Version:-24, ActivityTaskStartedEventAttributes:(ScheduledEventId:5, Identity:16193@localhost@demo, RequestId:1515ca02-0edc-4434-90dc-2235e3508e74, Attempt:0))
(EventId:7, Timestamp:1552501200082855913, EventType:ActivityTaskCompleted, Version:-24, ActivityTaskCompletedEventAttributes:(Result:["Done"], ScheduledEventId:5, StartedEventId:6, Identity:16193@localhost@demo))
(EventId:8, Timestamp:1552501200082859716, EventType:DecisionTaskScheduled, Version:-24, DecisionTaskScheduledEventAttributes:(TaskList:(Name:localhost:d3d716f1-fd08-42f4-936f-52964b49c11c), StartToCloseTimeoutSeconds:10, Attempt:0))
(EventId:9, Timestamp:1552501200161900407, EventType:DecisionTaskStarted, Version:-24, DecisionTaskStartedEventAttributes:(ScheduledEventId:8, Identity:16193@localhost@demo, RequestId:ac1392d5-5675-47a6-9167-fa850957275e))
(EventId:10, Timestamp:1552501200168760428, EventType:DecisionTaskCompleted, Version:-24, DecisionTaskCompletedEventAttributes:(ExecutionContext:[], ScheduledEventId:8, StartedEventId:9, Identity:16193@localhost@demo, BinaryChecksum:eae45b8da05ba5479aa5089e6dbaaa94))
(EventId:11, Timestamp:1552501200169498679, EventType:WorkflowExecutionContinuedAsNew, Version:-24, WorkflowExecutionContinuedAsNewEventAttributes:(NewExecutionRunId:3764629a-a0a7-4331-9e3c-7e45465025c9, WorkflowType:(Name:main.DeploymentWorkflow), TaskList:(Name:demo), Input:["arg1"], ExecutionStartToCloseTimeoutSeconds:60, TaskStartToCloseTimeoutSeconds:10, DecisionTaskCompletedEventId:10, BackoffStartIntervalInSeconds:600, Initiator:CronSchedule, FailureDetails:[], LastCompletionResult:[]))

**Comment by venkat1109** [comment]
Able to reproduce this on my laptop.
