### ISSUE TITLE
Activity RetryPolicy does not work well for host specific tasklist

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#1533]
Cadence server adjusts ScheduleToStartTimeout(Queue Timeout) to be the same as ExpirationInterval specified for RetryOptions.  This does not work well when client wants to use task routing for host specific tasklist, as it requires to have much smaller ScheduleToStartTimeout so the task can be retried on a different host in case of host failure.

**Comment by samarabbas** [comment]
One of the issues for Cadence in this particular case, it has no way to identify if the tasklist is host specific or not.  So currently there is no way to associate different behavior for RetryPolicy based on type of activity tasklist.  
We might need to think about a high level abstraction for activity host specific tasklist which might make it easier for Server to associate different behavior for configured retry policy.

**Comment by dmetzgar** [comment]
@yycptt move to client

**Comment by yycptt** [comment]
Moved to client side https://github.com/uber-go/cadence-client/issues/697
