### ISSUE TITLE
List open/closed workflow execution APIs return empty result when calling it from non-active cluster

### ISSUE THREAD

**Issue by yux0** [uber/cadence#1541]
The list open/closed workflow execution APIs return empty result when calling them from a non-active cluster.

E.g.
Calling list open workflow on a local domain (active in cluster ABC) from a cluster DEF will return an empty result.

The behavior is different from other workflow APIs which throws DomainNotActive Error.

**Comment by wxing1292** [comment]
the behavior is expected since the underlying domain is essentially a global domain
