### ISSUE TITLE
Signal should not trigger cron workflow

### ISSUE THREAD

**Issue by yycptt** [uber/cadence#1595]
[#1589](https://github.com/uber/cadence/pull/1589) fix the case that a cron workflow runs immediately when startWorkflowExecution is called. But there're still some similar bugs. 

1. If a cron workflow is currently wait for its next run and a signal is sent to that workflow, it will run immediately as a decision task is scheduled. 
2. SignalWithStartWorkflowExecution will ignore cron schedule and start the workflow immediately.

**Comment by yux0** [comment]
Item 1 fixed in #1838
Item 2 consider as expected behavior for now
