### ISSUE TITLE
Question regarding cadence usecase

### ISSUE THREAD

**Issue by AshishThakur** [uber/cadence#1677]
We are currently evaluating cadence for a use case where we have few microservices which talk to each other via an event bus. Each of these microservices emit events to an SNS topic and we use lambda functions as event handlers to invoke the next microservice. Most of this is involved around creating some business objects via multiple sources. In the current system we have challenges regarding the audibility in the overall lifecycle of creation of the business object. Could cadence serve as a good use case here?

**Comment by mfateev** [comment]
Cadence is a perfect fit for such use case. There are multiple internal Uber services using it exactly to orchestrate fault tolerant microservice interactions.[ Here is](https://eng.uber.com/customer-obsession-ticket-routing-workflow-and-orchestration-engine/) a public blog entry from one of our customers. 

Join [Cadence Slack channel](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTI5Yzc5ODYwMjg1ZmI3NmRmMTU1MjQ0YzQyZDc5NzMwMmM0NjkzNDE5MmM0NzU5YTlhMmI4NzIzMDhiNzFjMDM) for the specific questions.

**Comment by AshishThakur** [comment]
Thanks @mfateev
