### ISSUE TITLE
Unable to use docker (instead of docker-compose) to get Cadence Server started

### ISSUE THREAD

**Issue by ramkumarkb** [uber/cadence#1713]
I am unable to use docker-compose in our (restricted) environment but am able to use docker command. So, instead, I tried to use the plain docker commands (by following what is in the docker-compose.yml file). However, I am unable to start Cadence due to the error:
`error: failed to connect to <IP_Address>:9042 due to error: Keyspace 'cadence' does not exist`

Looks like there is some issue with the `cadence-cassandra-tool`

How can I make this work? What else should I do apart from the following docker commands? Thank you for any pointers or suggestions.

Docker Commands Used:
1. `docker run --name cassandra -p 9042:9042 -d cassandra:3.11`
2. `docker run --name statsd -p 8080:80 -p 2003:2003 -p 8125:8125 -p 8126:8126 -d hopsoft/graphite-statsd`
3. `docker run --name cadence -p 7933:7933 -p 7934:7934 -p 7935:7935 -p 7939:7939 -d --link cassandra --link statsd -e "CASSANDRA_SEEDS=cassandra" -e "STATSD_ENDPOINT=statsd:8125" ubercadence/server:0.5.6`
4. `docker run --name cadence-web -p 8088:8088 -d --link cadence -e "CADENCE_TCHANNEL_PEERS=cadence:7933" ubercadence/web:3.1.2`

**Comment by longquanzheng** [comment]
Can you try clean up your docker environment and start over(using docker-compose):
```
docker system prune -a
```

**Comment by wxing1292** [comment]
> I am unable to use docker-compose in our (restricted) environment but am able to use docker command. So, instead, I tried to use the plain docker commands (by following what is in the docker-compose.yml file). However, I am unable to start Cadence due to the error:
> `error: failed to connect to <IP_Address>:9042 due to error: Keyspace 'cadence' does not exist`
> 
> Looks like there is some issue with the `cadence-cassandra-tool`
> 
> How can I make this work? What else should I do apart from the following docker commands? Thank you for any pointers or suggestions.
> 
> Docker Commands Used:
> 
> 1. `docker run --name cassandra -p 9042:9042 -d cassandra:3.11`
> 2. `docker run --name statsd -p 8080:80 -p 2003:2003 -p 8125:8125 -p 8126:8126 -d hopsoft/graphite-statsd`
> 3. `docker run --name cadence -p 7933:7933 -p 7934:7934 -p 7935:7935 -p 7939:7939 -d --link cassandra --link statsd -e "CASSANDRA_SEEDS=cassandra" -e "STATSD_ENDPOINT=statsd:8125" ubercadence/server:0.5.6`
> 4. `docker run --name cadence-web -p 8088:8088 -d --link cadence -e "CADENCE_TCHANNEL_PEERS=cadence:7933" ubercadence/web:3.1.2`

there is a `start.sh` in the docker dir, please run that script to setup the schema
another way to initialize the scheme is to call `make install-scheme`

**Comment by longquanzheng** [comment]
looks like this env variable is not working:
```
-e "CASSANDRA_SEEDS=cassandra" 
```

check from the log:
```
	
"DataStores": {
            "cass-default": {
                "Cassandra": {
                    "Hosts": "cassandra",
                    "Port": 0,
                    "User": "",
                    "Password": "",
                    "Keyspace": "cadence",
                    "Consistency": "One",
                    "Datacenter": "",
                    "MaxQPS": 0,
                    "MaxConns": 0
                },
                "SQL": null
            },
```

**Comment by longquanzheng** [comment]
Confirmed that somehow the cadence-cassandra-tool in docker image is broken. But cadence-server is actually working:
```
longer@~/gocode/src/github.com/uber/cadence:(log4)$ docker exec -it cadence  ./cadence-server
NAME:
   cadence - Cadence server

USAGE:
   cadence-server [global options] command [command options] [arguments...]

VERSION:
   0.0.1

COMMANDS:
     start,   start cadence server
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --root value, -r value    root directory of execution environment (default: ".") [$CADENCE_ROOT]
   --config value, -c value  config dir path relative to root (default: "config") [$CADENCE_CONFIG_DIR]
   --env value, -e value     runtime environment (default: "development") [$CADENCE_ENVIRONMENT]
   --zone value, --az value  availability zone [$CADENCE_AVAILABILTY_ZONE]
   --help, -h                show help
   --version, -v             print the version
longer@~/gocode/src/github.com/uber/cadence:(log4)$ docker exec -it cadence  ./cadence-cassandra-tool
longer@~/gocode/src/github.com/uber/cadence:(log4)$
```

We will fix that later. For now you can our make command to install schema manually:

**Comment by ramkumarkb** [comment]
@longquanzheng @wxing1292 : Thank you very much for your reply. We tried a whole bunch of things and finally made it work! Here is the quick summary of what did not work and what worked:
### Run make 
Unfortunately, since we are working in a linux env with restricted policies, we are unable to run `make install-schema` - as this needs all the Go dependencies and complete make env with all the permissions.
### Try after installing docker-compose binary
This was more promising that the 1st option. Our docker engine is `v 1.12.6`. We downloaded the binary of docker-compose and changed the version of the docker-compose.yml to `2.1` (instead of 3). We also made some corresponding changes in the docker-compose.yml file (as per version 2.1), adding `network_mode: bridge` for each of the service.

But this also had the same outcome that the Cadence could not connect to the Cassandra for running the schema setup.

### Step that finally got it working 👍 

1. Run Cassandra container first - using the simple docker command above
2. Copy the cadence binary from Cadence container to local linux directory 
`docker exec -i cadence sh -c 'cat /cadence.tar' > cadence.tar`
3. Set all the environment variables and run each command of `cadence-cassandra-tool` one-by-one listed in the file https://github.com/uber/cadence/blob/master/docker/start.sh
4. Start the Cadence Container with the flag `"SKIP_SCHEMA_SETUP=true"`

If you want me to document the exact steps further, let me know. I can add it somewhere, so that someone else can also benefit from this exercise.

Thank you again for the pointers 🙏
