### ISSUE TITLE
Optimize read from Cassandra for timer task and transfer task

### ISSUE THREAD

**Issue by dmetzgar** [uber/cadence#1764]
Every time we notify the timer processor that there are new timers, we read from Cassandra for new tasks. Because we have 16K shards, this result in lots of c* reads. We could send the timer info when we send the notification so it does not need to read from Cassandra. But then we need something that periodically reads from Cassandra to reconcile.

**Comment by meiliang86** [comment]
@yycptt is this still valid with your new task processing logic?

**Comment by yycptt** [comment]
Yes. New task processing logic will not change how tasks are loaded from persistence.
