### ISSUE TITLE
Report the first scheduling time in the DescribeWorkflow API

### ISSUE THREAD

**Issue by algobardo** [uber/cadence#1810]
The start time for cron jobs is the time the previous workflow finishes. This is confusing when exposing the start time to users.

My suggestion is to add a FirstScheduled field that reports the time of the first DecisionTaskScheduled event.

**Comment by wxing1292** [comment]
@yycptt is this still relevant?

**Comment by yycptt** [comment]
This can be closed. Describe workflow will return execution time which is when the workflow will actually start.
