### ISSUE TITLE
historyEngine: Refactor RespondDecisionTaskCompleted into smaller methods

### ISSUE THREAD

**Issue by venkat1109** [uber/cadence#182]
RespondDecisionTaskCompleted is a single long method with a whole bunch of switch cases / if / else logic. Difficult to read/maintain/test. One idea for simplifying this would be to create separate handlers for each decisionType and maintain a lookup table of decisionTypeToDecisionHandlers.

**Comment by dmetzgar** [comment]
Refers to https://github.com/uber/cadence/blob/686fa47b770b0c1eaba02aea6a3c52f214e40392/service/history/historyEngine.go#L1007

**Comment by dmetzgar** [comment]
@wxing1292 I think you may have already done this refactoring in the 3+DC branch.

**Comment by wxing1292** [comment]
this is already done in master

**Comment by wxing1292** [comment]
#1938 #1944 #1951 #1955 #1957
