### ISSUE TITLE
No build version info is exposed via /metrics for prometheus

### ISSUE THREAD

**Issue by aned** [uber/cadence#1840]
/metrics should be exposing build version information.

**Comment by shreyassrivatsan** [comment]
I dont think we do this currently.. Is there a specific format for build version metrics that we should be exposing?

**Comment by aned** [comment]
An example from the alertmanager: 

alertmanager_build_info{branch="master",goversion="go1.12",instance="blah:9093",job="blah-alertmanager",revision="6749f9faa9b87f4ca153481e8ab4332c89f0360b",version="0.17.0"}
--

**Comment by shreyassrivatsan** [comment]
Is this build version of the binary running or of the prometheus client? Is this necessarily required for prometheus metrics emission? We do not currently keep track of much of this information - though can certainly extract this if necessary..

**Comment by aned** [comment]
The above one was just an example. Each component (prometheus, alertmanager, grafana, m3db, snmp_exporter, etc) have _build_info metric. It's for housekeeping purposes, to make sure all instances are running the same code.
