### ISSUE TITLE
Need to flush buffer before closing workflow 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#1845]
Otherwise reset may losing signals since reset doesn't read from bufferEvents.
Secondly, it is also important to store the events in history instead of bufferEvents forever.

This will require some refactoring of mutableStateBuilder to let workflow closing event also bufferable(showBufferEvent() ):
1. Terminate
2. Cancel
3. Timeout
4. Failed
5. ? ContinuedAsNew/Complete

**Comment by wxing1292** [comment]
#2668
