### ISSUE TITLE
Prometheus invalid names

### ISSUE THREAD

**Issue by jontro** [uber/cadence#1848]
We are still receiving warning about invalid promotheus metric names. (Using master as of today)

The following names are invalid
```
cadence-activity-endtoend-latency
cadence-activity-execution-latency
cadence-activity-poll-latency
cadence-activity-poll-no-task
cadence-activity-poll-succeed
cadence-activity-poll-total
cadence-activity-response-latency
cadence-activity-task-completed
cadence-decision-execution-latency
cadence-decision-poll-latency
cadence-decision-poll-no-task
cadence-decision-poll-succeed
cadence-decision-poll-total
cadence-decision-response-latency
cadence-decision-task-completed
cadence-DescribeDomain_cadence-latency
cadence-DescribeDomain_cadence-request
cadence-poller-start
cadence-PollForActivityTask_cadence-latency
cadence-PollForActivityTask_cadence-request
cadence-PollForDecisionTask_cadence-latency
cadence-PollForDecisionTask_cadence-request
cadence-RecordActivityTaskHeartbeat_cadence-latency
cadence-RecordActivityTaskHeartbeat_cadence-request
cadence-RespondActivityTaskCompleted_cadence-latency
cadence-RespondActivityTaskCompleted_cadence-request
cadence-RespondDecisionTaskCompleted_cadence-latency
cadence-RespondDecisionTaskCompleted_cadence-request
cadence-sticky-cache-hit
cadence-sticky-cache-size
cadence-tasklist-queue-latency
cadence-worker-start
cadence-workflow-completed
cadence-workflow-endtoend-latency
```

I also get the following waring about a duplicate descriptor 
`"error in prometheus reporter","error":"a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"history_size\", help: \"history_size histogram\", constLabels: {}, variableLabels: [stats_type operation]} has different label names or a different help string"`

All errors are reported in metrics.go:130 with log level warn. See attached file for raw errors
[logs-from-cadence-in-cadence-7b96b47767-vwk6w.txt](https://github.com/uber/cadence/files/3178387/logs-from-cadence-in-cadence-7b96b47767-vwk6w.txt)

**Comment by shreyassrivatsan** [comment]
So the ones listed above are client side metrics. Are you seeing these metrics on the server side? We have not made changes on the client side yet as lot of teams use these legacy metrics internally - so need to figure a proper path forward on those..

**Comment by shreyassrivatsan** [comment]
For the client, you can ensure that you only emit prometheus compatible metrics by using the tally sanitizer.. tally provides a Sanitizer to ensure metrics are compatible with different backends.. 

Here is a sample of how you can set that up.. Let me know if you run into any issues with that.. 

```
var (
	_safeCharacters = []rune{'_'}

	_sanitizeOptions = tally.SanitizeOptions{
		NameCharacters: tally.ValidCharacters{
			Ranges:     tally.AlphanumericRange,
			Characters: _safeCharacters,
		},
		KeyCharacters: tally.ValidCharacters{
			Ranges:     tally.AlphanumericRange,
			Characters: _safeCharacters,
		},
		ValueCharacters: tally.ValidCharacters{
			Ranges:     tally.AlphanumericRange,
			Characters: _safeCharacters,
		},
		ReplacementCharacter: tally.DefaultReplacementCharacter,
	}
)

// create scope using
scopeOpts := tally.ScopeOptions{
	CachedReporter: reporter,
	Separator:      prometheus.DefaultSeparator,
	SanitizeOptions: &_sanitizeOptions,
}
```

**Comment by jontro** [comment]
I've just started up the server using a config similar to this: https://github.com/uber/cadence/blob/master/config/development_prometheus.yaml 

Prometheus is only scraping those metrics. No workers or clients have been connected. I'm using the java client and have only started one workflow (which was closed before upgrading the server from 0.5.7 to master)

**Comment by shreyassrivatsan** [comment]
Not sure where exactly they are coming from.. Probably the background scanner workflow.. I did not want to use the tally sanitizer in the server code, but given that we have system workflows its probably necessary.. This enables the metric sanitizer when creating a prom metrics reporter - #1852 1852

**Comment by shreyassrivatsan** [comment]
#1852 should fix the above. Closing this..
