### ISSUE TITLE
Record more started time/errors for retried activities

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#1873]
Right now we only record the last started time when writing down the started event. This is super confusing for customers even for us.

We don't have to record all of them, but it will be nice to have a limit like at most 5 of them can be recorded down.

**Comment by dizUber** [comment]
During using the Cadence, we found one activity will fail to schedule on all the machines, the last time it fails by timeout. But the failure records in the process will help debugging the issue.

**Comment by martinxsliu** [comment]
Hi all, is there any progress on this issue? We're looking at adopting Cadence, in part as a potential replacement for our existing background workers. Currently, if an activity fails and is retried, there is no way to see what the error message is that caused the failure which makes it difficult to debug. This feature is something that comes out of the box with traditional job workers like Sidekiq or Celery.
