### ISSUE TITLE
Cleanup of history events due to failure in StartWorkflowExecution

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#193]
History engine first creates the history of new execution in the events table and then create the mutable state in executions table.  It is possible that it writes the events but fails on the second write.  We current leak all those stale executions in cassandra.  
We need to come up with a mechanism to detect all those stale entries and remove them.

**Comment by dmetzgar** [comment]
@samarabbas @andrewjdawson2016 is this still valid?

**Comment by wxing1292** [comment]
#2499
