### ISSUE TITLE
Archival workflow should treat activity panic as non-retryable error

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber/cadence#1959]
If upload/delete activity panics this does not get treated as a non-retryable error. We should treat it as such.

**Comment by yycptt** [comment]
We should really consider add a "Retryable Error" field to retry policy

**Comment by mfateev** [comment]
All errors are retryable by default. So adding such field doesn't make sense.

**Comment by mfateev** [comment]
@andrewjdawson2016 Have you tried adding activity panic to the policy list of non-retryable errors?

**Comment by yycptt** [comment]
If user wants to retry only on one types of error, then he/she needs to list all other errors as non-retryable

**Comment by yycptt** [comment]
Adding activity panic error to the policy list of non-retryable errors is how I plan to resolve this problem.

**Comment by mfateev** [comment]
I'm not sure if there is a use case that retries only on one type of error and doesn't retry timeouts.

**Comment by yycptt** [comment]
One use case I can think of is when creating a session, I only want to retry the creation activity when there're too many outstanding sessions. On timeout, it should return an error to the user. 

For archival, I think right now we only want to retry on context timeout (@andrewjdawson2016 please confirm). But we will have to list all other errors we return. 

Another reason is that if user activity can generate lots of errors, but only want to retry on some of them. I think maybe it would be easier for them to specify the error they want to retry plus the timeout errors?
