### ISSUE TITLE
Queue start workflow requests

### ISSUE THREAD

**Issue by dmetzgar** [uber/cadence#2044]
When starting a workflow, we have the option to allow multiple runs with the same workflow id that run in parallel. We can also reject if there's a running workflow with the same id. One option we don't have is to queue the request to start the workflow until the currently running workflow is complete. 

The way around this today is to use SignalWithStart. But what this means is that the workflow has to have its own logic to check for signals at the end and do a continueasnew. Instead, it would be preferable to have another option for start workflow that allows queuing up start requests on a given workflow id.

**Comment by mfateev** [comment]
Correction: Cadence by design doesn't allow multiple runs with the same workflow ID that run in parallel. The worklowIdReusePolicy applies only to already completed workflows.

What is the use case that requires queuing workflows with the same ID?

**Comment by dmetzgar** [comment]
@bogdanovich can explain the use case better.

One question: if we call SignalWithStart and don't process the signals in the running workflow, what happens to the signals?

**Comment by mfateev** [comment]
If the workflow code doesn't consume them they are lost. It is responsibility of the workflow code to drain the signal channel using Channel.ReceiveAsync before completing.

**Comment by bogdanovich** [comment]
The use case: 
Organization admin uploads CSV file to import new employees into an organization. We don't allow parallel CSV upload workflows for the same organization, but we also don't want to restrict admins from uploading multiple files, and eventually want to process all the files one by one. Right now we would have to use signals for implementing this functionality in the workflow code. 
It would have been really useful if this functionality could be provided out of the box as an option to start a workflow.
