### ISSUE TITLE
Domain specific throttler for server api calls

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#2052]
Cadence server has multiple system protections in place like:
1) Throttle request on API handler if request rate breaches certain threshold on a host
2) Throttle persistence request if particular host starts making too many persistence calls

Although these system protection serves as good protections when system is collectively under tremendous load but does not prevents against noisy neighbor problems.  A single domain can eat all the credits for a system throttler and result in very degraded experience for domains which are within reasonable bounds.

This issue is created to have a separate domain specific throttler which penalizes the heavy hitters before start penalizing low traffic domains.

**Comment by shreyassrivatsan** [comment]
#2208 is the v0.1 of a domain specific rate limiter.
