### ISSUE TITLE
DNS mode doesn't work

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#2063]
{"level":"warn","ts":"2019-06-19T02:34:47.711Z","msg":"Could not resolve host","address":"mycadence-10-frontend","error":"lookup mycadence-10-frontend on 100.64.0.10:53: no such host","logging-call-at":"ringpop.go:254"}
{"level":"fatal","ts":"2019-06-19T02:34:47.711Z","msg":"Membership monitor creation failed","service":"cadence-worker","error":"ringpop creation failed: No hosts found, and bootstrap requires at least one","logging-call-at":"service.go:183","stacktrace":"github.com/uber/cadence/common/log/loggerimpl.(*loggerImpl).Fatal\n\t/go/src/github.com/uber/cadence/common/log/loggerimpl/logger.go:139\ngithub.com/uber/cadence/common/service.(*serviceImpl).Start\n\t/go/src/github.com/uber/cadence/common/service/service.go:183\ngithub.com/uber/cadence/service/worker.(*Service).Start\n\t/go/src/github.com/uber/cadence/service/worker/service.go:129\nmain.execute\n\t/go/src/github.com/uber/cadence/cmd/server/server.go:228"}

**Comment by longquanzheng** [comment]
looks like I forgot to put port in the address...retrying..

**Comment by longquanzheng** [comment]
Try on pod:
```
root@mycadence-10-cassandra-0:/# nslookup mycadence-10-frontend
Server:		100.64.0.10
Address:	100.64.0.10#53

** server can't find mycadence-10-frontend: NXDOMAIN

```

**Comment by longquanzheng** [comment]
also:
```
root@mycadence-10-cassandra-0:/# nslookup mycadence-10-frontend.default.svc.cluster.loca
Server:		100.64.0.10
Address:	100.64.0.10#53

** server can't find mycadence-10-frontend.default.svc.cluster.loca: NXDOMAIN

root@mycadence-10-cassandra-0:/#
```

**Comment by sagikazarmark** [comment]
It should be `mycadence-10-frontend.default.svc.cluster.local`

I'm guessing the `publishNotReadyAddresses` solved this problem.

**Comment by longquanzheng** [comment]
Resolved the issue with 
```
publishNotReadyAddresses
```
