### ISSUE TITLE
Add server API to update an activity/workflow retry policy

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#2071]
In some cases an activity or a workflow that is being retried has misconfigured retry policy.
It would be useful to be able to update it while activity is in retry loop. 

For example the maximumRetryInterval is set to 1 day, but underlying issue is already fixed and we don't want to wait for the retry to happen in 20 hours.

Through this new management API it should be possible to force immediate retry.

**Comment by wxing1292** [comment]
dup of #2651 #2652
