### ISSUE TITLE
Workflow execution fails when a worker is restarted on the same workflow service client

### ISSUE THREAD

**Issue by johncburns1** [uber/cadence#2078]
We're in the process of writing a .NET Cadence client and ran into an issue while unit testing workflows.  When we start a worker, execute a workflow, stop the worker, start it again, and then try and execute another workflow, the first workflow completes, but any workflow after the first hangs during the `client.ExecuteWorkflow()` call, eventually failing with a `START_TO_CLOSE` timeout.  I replicated this behavior by munging the greetings [cadence-samples](https://github.com/samarabbas/cadence-samples/) workflow.  See the loop in `func main()`:
```
package main

import (
    "context"
    "time"

    "go.uber.org/cadence/client"
    "go.uber.org/cadence/worker"
    "go.uber.org/zap"

    "github.com/pborman/uuid"

    "github.com/samarabbas/cadence-samples/cmd/samples/common"
)

// This needs to be done as part of a bootstrap step when the process starts.
// The workers are supposed to be long running.
func startWorkers(h *common.SampleHelper) worker.Worker {
    // Configure worker options.
    workerOptions := worker.Options{
        MetricsScope: h.Scope,
        Logger:       h.Logger,
    }
    return h.StartWorkers(h.Config.DomainName, ApplicationName, workerOptions)
}

func startWorkflow(h *common.SampleHelper) client.WorkflowRun {
    workflowOptions := client.StartWorkflowOptions{
        ID:                              "greetings_" + uuid.New(),
        TaskList:                        ApplicationName,
        ExecutionStartToCloseTimeout:    time.Minute,
        DecisionTaskStartToCloseTimeout: time.Minute,
    }
    return h.StartWorkflow(workflowOptions, SampleGreetingsWorkflow)
}

func main() {

    // configure service client
    var h common.SampleHelper
    h.SetupServiceConfig()

    // Loop:
    //  - start a worker
    //  - start a workflow
    //  - block and wait for workflow result
    //  - stop the worker
    for i := 0; i < 3; i++ {

        // start the worker
        // execute the workflow
        workflowWorker := startWorkers(&h)
        workflowRun := startWorkflow(&h)

        // create context
        // get workflow result
        var result string
        ctx, cancel := context.WithCancel(context.Background())
        err := workflowRun.Get(ctx, &result)
        if err != nil {
            panic(err)
        }

        // log the result
        h.Logger.Info("Workflow Completed", zap.String("Result", result))

        // stop the worker
        // cancel the context
        workflowWorker.Stop()
        cancel()
    }
}
```

### Background: 
We ([Jeff Lill](https://github.com/jefflill) and I) noticed this issue during unit testing workflows in our .NET Cadence client.  When we run our workflow tests individually they all pass, but when we run multiple at a time (sequentially, not in parallel), we see the behavior described above.  This is because of the cleanup done in the .NET Cadence client `dispose()` method called after a test completes (pass or fail).  One of the dispose behaviors is to stop workers created during a test.  When the next test runs, new workers are created using the same workflow service client, and this is where the issue arises.

**Comment by meiliang86** [comment]
Please get help from the slack channel if it is still an issue for you.
