### ISSUE TITLE
Return workflow close status as part of query response

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#2080]
Currently query returns some result even if workflow was terminated. And it is not possible to find out if the workflow still running without additional API calls.

**Comment by yycptt** [comment]
I think we need some discussion on the user experience.

For example:
Adding new client side API for returning the close status when querying workflow, or just change the existing API?
Is there any other information we want to add besides close status?

**Comment by andrewjdawson2016** [comment]
https://github.com/uber/cadence/commit/cc54edd9b52d5787791ae5e473f37ae2b35427c8
