### ISSUE TITLE
Query timeout for cron workflows

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#2100]
Query request to a workflow that is waiting for cron interval to create the first decision task times out.

**Comment by bonifaido** [comment]
Just experienced this when using the CronSchedule in a Workflow. Other than that the workflow finishes and renews correctly.

<img width="1391" alt="Screen Shot 2019-08-01 at 2 31 54 PM" src="https://user-images.githubusercontent.com/23779/62293933-08484d80-b46a-11e9-8030-6a3d62bac633.png">

**Comment by andrewjdawson2016** [comment]
https://github.com/uber/cadence/pull/2825

**Comment by andrewjdawson2016** [comment]
![Uploading Screen Shot 2019-11-17 at 2.46.07 PM.png…]()

**Comment by andrewjdawson2016** [comment]
```
~/Desktop/cadence(MatchingQueryRefactor) » ./cadence --do samples-domain wf query --wid cron_sample_wf --qt state                                    dandrew@dandrew-C02XW40XJGH6
Error: Query workflow failed.
Error Details: BadRequestError{Message: workflow must handle at least one decision task before it can be queried}
('export CADENCE_CLI_SHOW_STACKS=1' to see stack traces)
```

**Comment by andrewjdawson2016** [comment]
This has been resolved.
