### ISSUE TITLE
expose error for failing activity with retry policy

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#2111]
Currently, if an activity is failing and has retry policy, there is no easy way for user to know what is going on until it finally give up and write the final result/error to history.

This cause lots of hard time in debugging/investigation especially if the retry has long expiration time.

We need a way to expose this error info, probably via DescribeWorkflow?

**Comment by mfateev** [comment]
Duplicate of https://github.com/uber/cadence/issues/698
