### ISSUE TITLE
Matching engine error on TTL

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#2160]
{"level":"error","ts":"2019-07-02T15:38:59.727-0700","msg":"Operation failed with internal error.","service":"cadence-matching","error":"InternalServiceError{Message: CreateTasks operation failed. Error : Request on table cadence.tasks with ttl of 630720000 seconds exceeds maximum supported expiration date of 2038-01-19T03:14:06+00:00. In order to avoid this use a lower TTL, change the expiration date overflow policy or upgrade to a version where this limitation is fixed. See CASSANDRA-14092 for more details.}","metric-scope":19,"logging-call-at":"persistenceMetricClients.go:592","stacktrace":"github.com/uber/cadence/common/log/loggerimpl.(*loggerImpl).Error\n\t/Users/longer/gocode/src/github.com/uber/cadence/common/log/loggerimpl/logger.go:133\ngithub.com/uber/cadence/common/persistence.(*taskPersistenceClient).updateErrorMetric\n\t/Users/longer/gocode/src/github.com/uber/cadence/common/persistence/persistenceMetricClients.go:592\ngithub.com/uber/cadence/common/persistence.(*taskPersistenceClient).CreateTasks\n\t/Users/longer/gocode/src/github.com/uber/cadence/common/persistence/persistenceMetricClients.go:486\ngithub.com/uber/cadence/service/matching.(*taskListDB).CreateTasks\n\t/Users/longer/gocode/src/github.com/uber/cadence/service/matching/db.go:122\ngithub.com/uber/cadence/service/matching.(*taskWriter).taskWriterLoop\n\t/Users/longer/gocode/src/github.com/uber/cadence/service/matching/taskWriter.go:174"}

**Comment by andrewjdawson2016** [comment]
Have not seen this again
