### ISSUE TITLE
Provide options when continue as new with search attributes

### ISSUE THREAD

**Issue by vancexu** [uber/cadence#2184]
Currently, search attributes are not rolled over when continue as new.
Need to add options for users to choose whether we need copy search attributes in the new run

**Comment by dmetzgar** [comment]
Can you add tasks for Go and Java clients as well?

**Comment by vancexu** [comment]
https://github.com/uber-go/cadence-client/issues/798
https://github.com/uber/cadence-java-client/issues/347

**Comment by dmetzgar** [comment]
Thanks!

**Comment by vancexu** [comment]
https://github.com/uber/cadence/pull/2293
