### ISSUE TITLE
Need to be able to pass on SearchAttributes to child workflows

### ISSUE THREAD

**Issue by shreyassrivatsan** [uber/cadence#2204]
From user - For SearchAttributes: Is there any way to pass SearchAttribute for childworkflows? I have checked that it's not getting passed implicitly. 
I cannot even find an explicit way of doing so. We pass the SearchAttribute in StartWorkflowOptions and ExecuteWorkflow takes the StartWorkflowOptions as a parameter but ExecuteChildWorkflow doesn't have such parameter.

**Comment by vancexu** [comment]
https://github.com/uber/cadence/pull/2266
https://github.com/uber-go/cadence-client/pull/802
