### ISSUE TITLE
persistence: setup tests against multiple versions of mysql

### ISSUE THREAD

**Issue by venkat1109** [uber/cadence#2211]
Currently, the test suite runs only against mysql 5.7. It's desirable to run against all supported versions to make sure we don't accidentally break interoperability.

**Comment by cuongleqq** [comment]
Hi @venkat1109, what is the status of this? I'd like to use mysql version 8.0.x but I am not sure if this is a good setup or I must use 5.7 to make sure nothing bad might happen? Thanks.

**Comment by longquanzheng** [comment]
> Hi @venkat1109, what is the status of this? I'd like to use mysql version 8.0.x but I am not sure if this is a good setup or I must use 5.7 to make sure nothing bad might happen? Thanks.

Hi @cuongleqq it should work for MySQL 8. Lmk if you run into any issues
