### ISSUE TITLE
Cadence plugin points

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber/cadence#2214]
As cadence grows in popularity, third parties are going to want to bind cadence to their own technology stacks. This creates two issues:
1. It will result in the core cadence engine having loads of direct dependencies. 
2. It will force third part authors to write code in cadence core. 

A better model is that cadence is a skeleton and just the set of dependencies needed to run cadence are loaded at build time. These dependencies could be everything from the database used to the archiver implementation. A DSL should define which plugins will get used. In this world two things identify a cadence build: the DSL defining the plugins to load and the version of the cadence server. 

This task needs to be prioritized somewhat soon because otherwise the cadence story around loading dependencies will become unmaintainable.

**Comment by demirkayaender** [comment]
This is done now.
