### ISSUE TITLE
misleading error message

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#222]
history engine handling DecisionType_RequestCancelExternalWorkflowExecution has incorrect error message, when the domain is not specified in the decision attributes, the error says:"Unable to schedule activity across domain: ."

**Comment by dmetzgar** [comment]
@yiminc, given [this section](https://github.com/uber/cadence/blob/2cf0577af28bf4c8e68bf7949b9716ff70419f06/service/history/historyEngine.go#L1185) in historyEngine, I think this is no longer the case. Can this issue be closed?
