### ISSUE TITLE
START_TO_CLOSE timeout

### ISSUE THREAD

**Issue by kaushiksriram100** [uber/cadence#2274]
I am Very new to cadence. Please excuse my ignorance. 

I am running a simple helloworld example (multiple workers and triggering in a for loop multiple times). Intermittently I get the below errors.. 

I am not looking for help to troubleshoot this particular error trying to understand why such errors happens at a macro level. Which timeout variable does the below mention. The activity timeout or workflow timeout?  

`2019-07-25T00:20:40.869Z	ERROR	helloworld/helloworld.go:53	Activity say Hello failed:	{"Domain": "samples-domain", "TaskList": "sk_helloworld", "WorkerID": "14327@ip-11-25-2-6@sk_helloworld", "WorkflowType": "main.DemoWorkflow", "WorkflowID": "helloworld_5e260e8f-1fe9-43e3-9ab2-84da3f2bf18f", "RunID": "3c0aa9e5-dbb1-4a25-8fee-7e029544c084", "error": "TimeoutType: START_TO_CLOSE"}
main.DemoWorkflow`

This is what I have in my code. 

//in worker/workflow definition. 
ao := workflow.ActivityOptions{
		ScheduleToStartTimeout: 3 * time.Second,
		StartToCloseTimeout:    3 * time.Second,
	}

// in trigger - startWorkflow
workflowOptions := client.StartWorkflowOptions{
		ID:                              "helloworld_" + uuid.New(),
		TaskList:                        ApplicationName,
		ExecutionStartToCloseTimeout:    time.Minute,
		DecisionTaskStartToCloseTimeout: time.Minute,
	}

**Comment by mfateev** [comment]
The best way to troubleshoot such issue is to look at the workflow execution history (events tab) in the UI (found at localhost:8088). Or use Cadence[ command line interface](https://cadenceworkflow.io/docs/08_cli) to see it.

My guess is that the activity worker listens on a different task list than the task list workflow uses to schedule an activity. Task list is essentially a queue that is used to deliver activity tasks to activity workers.

**Comment by mfateev** [comment]
Feel free to join [Cadence slack channel](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTQyYjcxZDM2YTIxMTZkMzQ0NjgxYmI3OWY5ODhiOTliM2I5MzA4NTM4MjU4YzgzZDkwNGEzOTUzNTBlNDk3Yjc) to get support.
