### ISSUE TITLE
Better way to manage release versions

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#2316]
Related to https://github.com/uber/cadence/issues/2311
and 
https://github.com/uber/cadence/issues/2307

Today we have cadence server release version: https://github.com/uber/cadence/releases
go-client release version:
https://github.com/uber-go/cadence-client/releases
java-client release version:
https://github.com/uber/cadence-java-client/releases

Also we have: 
Library version: https://github.com/uber/cadence/blob/master/common/rpc.go#L32 (for metrics)
Feature version: https://github.com/uber/cadence/blob/master/common/rpc.go#L41 (for rejecting request from client that is newer than server)
CLI version: https://github.com/uber/cadence/blob/master/tools/cli/app.go#L30

We need to come up with instructions to manage them.

**Comment by longquanzheng** [comment]
Talked to @meiliang86 , library version is not being used

**Comment by demirkayaender** [comment]
Done
