### ISSUE TITLE
Feature: Enable local activities to be run by name

### ISSUE THREAD

**Issue by danielcorin** [uber/cadence#2327]
I have a workflow to which I send a string argument. That string argument is the name of an activity which I want to run locally (since I can't pass the activity function as an arg as it isn't serializable).

What I want to do:
```go
package ...

activity.RegisterWithOptions(MyActivity, activity.RegisterOptions{Name: constants.MyActivityName})

...

func MyWorkflow(ctx workflow.Context, activityName string) error {
    future := workflow.ExecuteLocalActivity(aCTX, activityName)
    ...
}

func MyActivity(ctx context.Context) error {
    ...
}
```

Presently, Cadence does not allow this -- it only allows local activities to be started by passing the function to `ExecuteLocalActivity`

In the interim, I am maintaining a map that looks looks like this:

```go
map[string]func(context.Context) error{
    constants.MyActivityName: MyActivity,
}
```
and get my function via the string input to the workflow.

However, it would be nice to have this feature work in the same way it does for workflows and non-local activities. Right now, the execution appears to proceed as if the activity were a no-op.

**Comment by meiliang86** [comment]
Moved to client repo.
