### ISSUE TITLE
Naming about DecisionHeartbeatTimeout

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#2334]
This is a new name that may not be easy to accept. So the intention is for RespondDecisionTaskComplete with ForceCreateNewDecision=true && len(decisions)==0 . 

When exceeding that timeout, we want to timeout the decision and clear stickyness, so that next decision will be rescheduled to another worker.

We invented a new word "Heartbeat" to describe this behavior. Because this behavior is like decision is just hearbeating without making any progress(decision).

But maybe we can use some other names.
Wenquan has a new name "Continuation". 
Or maybe "ForceContinuation" or "ForceContinuationWithNoDecisions" can be more accurate because decision can also continue with other conditions:
```
createNewDecisionTask := !isComplete && (hasUnhandledEvents ||
			request.GetForceCreateNewDecisionTask() || activityNotStartedCancelled)
```

**Comment by longquanzheng** [comment]
IMO "ForceContinuationWithNoDecisions" can be a good option because it is most accurate. But it is a little long.

**Comment by mfateev** [comment]
DecisionContinuationExpirationInterval
