### ISSUE TITLE
Global throttler per Domain for API calls

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#2346]
Currently we only throttle API calls per domain based per host.  Although this is useful to throttle domains hitting the system hard, but is significant operational overhead to manage these limits per domain per host.  As each time we increase the size of cluster this limit needs to be adjusted.
This issue is created to throttle domains based on aggregated request rate for the entire cluster.  Some high level requirements are:

1. Enforce request rates aggregated across the entire cluster
2. Ability to dynamically change quotas for the entire domain or for specific API call
3. Ability to assign priority to certain API calls like StartWorkflowExecution, Signal, etc to give precedence when system is overloaded.

**Comment by mkolodezny** [comment]
https://github.com/uber/cadence/pull/3169
https://github.com/uber/cadence/pull/3161
