### ISSUE TITLE
Document manual migration steps

### ISSUE THREAD

**Issue by sagikazarmark** [uber/cadence#2347]
The [helm chart](https://github.com/banzaicloud/banzai-charts/tree/master/cadence) is going to recommend a setup where database is manually configured by the operator and migrations are ran manually as well.

It would be nice to have an official documentation for that.

**Comment by sagikazarmark** [comment]
https://github.com/banzaicloud/banzai-charts/blob/master/cadence/migrations.md

**Comment by ibarrajo** [comment]
Hi! we are pleased to announce that we recently released official Cadence Helm charts.

Here's the [announcement](https://cadenceworkflow.io/blog/2024/10/01/announcing-cadence-helm-charts-v0/) and [cadence-charts repo](https://github.com/uber/cadence-charts):
