### ISSUE TITLE
Adjust cache size automatically based on shard allocation

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#2350]
Every shard has the following 2 caches which mostly contribute to the memory consumption on history host:

1. MutableStateCache
2. EventsCache

These caches have their own knobs to configure the maximum size per shard, which makes it very hard to define these knobs in a generic fashion for various cluster sizes.  
The idea is to have a simpler knob which is defined per host which automatically adjust the size of caches placed on that host evenly.

**Comment by wxing1292** [comment]
This should be done as part of host capacity control, i.e. host level coroutine worker pool, mutable state cache
