### ISSUE TITLE
Query workflows that use a specific version

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#2409]
To support removal of deprecated branches of getVersion call there is a need to count and query worklfows that are using a specific version of the _getVersion_ API call given a _changeID_.

I'm not sure if this feature can rely on the custom search attributes in their current form as the _workflowVersions_ attribute should contain a list of [changeID, version] pairs.

**Comment by snaftaly** [comment]
Hi, is the getVersion API call planned to return whether a workflow (and how many workflows) is using the DefaultVersion for a specific change ID?

**Comment by mfateev** [comment]
It will be implemented through enhanced visibility (list/count) API: https://github.com/uber/cadence/issues/2495

https://github.com/uber/cadence/issues/2409

**Comment by vancexu** [comment]
@snaftaly yes.
When list workflows, you will be able to search by `CadenceChangeVersion = <changeID>-<version>`
When show history of a specific workflow, you will also see "<changeID>-<version>" in UpsertSearchAttributeEvent.

Note this feature will require advanced visibility enabled on ElasticSearch.

**Comment by snaftaly** [comment]
Hi @vancexu , I see that the cadence client code for querying the API for workflow version is merged. I wanted to make sure if this is already supported in the server, and if so, from which version. Thanks!

**Comment by vancexu** [comment]
> Hi @vancexu , I see that the cadence client code for querying the API for workflow version is merged. I wanted to make sure if this is already supported in the server, and if so, from which version. Thanks!

Hi server side release is not done, we may do a release at end of Oct, (after which there will also be a client release)

However to use this feature now, the only thing need on server side (v0.9.0) is allowlist new search attributes "CadenceChangeVersion" as keyword type. see https://cadenceworkflow.io/docs/11_search on how to allowlist it manually.

**Comment by vancexu** [comment]
Go client v0.10.1 
Java client not available yet: https://github.com/uber/cadence-java-client/issues/421
 
To search default version, use query like `CadenceChangeVersion != 1` or `CadenceChangeVersion not in (1,2,3)` (before `missing` or `not exist` is supported in advanced query). 

Note this feature requires advanced visibility on server side (is ElasticSearch)
