### ISSUE TITLE
Getting Response from long running task

### ISSUE THREAD

**Issue by SUNSHINE99** [uber/cadence#2416]
My use case involves creating tasks for a user which is pushed onto his task list, he picks a task and works on that task(the user may take days to complete the task) and submits the result.

How can I model this use case using uber cadence?

Thank you

**Comment by mfateev** [comment]
It depends on how you define "picks a task". The most common approach to model human tasks is to have an activity that inserts that task into an external database that user uses to list tasks to work on. Then each time the task state changes to claimed, returned, completed, etc. a signal is send to the workflow to keep track of the task state.

If all you want is to complete the task asynchronously use[ asynchronous activity completion](https://cadenceworkflow.io/docs/07_goclient/12_activity_async_completion).

**Comment by mfateev** [comment]
I recommend joining [Cadence Slack Channel ](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTQyYjcxZDM2YTIxMTZkMzQ0NjgxYmI3OWY5ODhiOTliM2I5MzA4NTM4MjU4YzgzZDkwNGEzOTUzNTBlNDk3Yjc)to discuss.

**Comment by SUNSHINE99** [comment]
Thanks @mfateev  for the quick reply.

I have posted my follow up questions on cadence slack channel.
