### ISSUE TITLE
Add static sharding support to MySQL

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#2422]
It looks like there are database drivers that perform static sharding. They don't look too complicated to integrate:

https://golangexample.com/go-package-for-sharding-databases/
https://github.com/evalphobia/wizard

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence/pull/4498
https://github.com/uber/cadence/pull/4504
https://github.com/uber/cadence/pull/4561
