### ISSUE TITLE
SignalExternalWorkflowDecision with empty RunID results in signal dispatch failure

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#2434]
Looks like if user sends a decision with empty RunID than we create a transfer task with incorrect information for TargetRunID resulting is 'SignalExternalWorkflowExecutionFailed' instead of sending the signal to current run.

**Comment by wxing1292** [comment]
@vancexu is this still relevant?

**Comment by vancexu** [comment]
There was a race condition, when SignalExternalWorkflow with empty RunID happens, the target run A may already ContinueAsNew with new RunID B, which result in `SignalExternalWorkflowExecutionFailed`.
