### ISSUE TITLE
best practice for injecting dependency into activities

### ISSUE THREAD

**Issue by hankduan** [uber/cadence#2438]
The activity is very easy when it is self contained (i.e. send an http request, manipulate a string etc). What is the best practice to inject dependencies into these activities (i.e. injecting a db client so that an activity can update a db entry)?

i.e. 
```
func init() {
	activity.Register(Activity)
}

func Activity(ctx context.Context, status string) error {
	// need instance of dbClient
        dbClient.updateStatus(status)
	return nil
}
```

To get instance of dbClient, I can 
1) store the dbClient globally under a singleton or something, but I'm trying to avoid globals. 
2) construct the client in the activity, but that means I'm reconstructing the client over and over again

What is the best practice for this? It feels like I'm missing something important since this should be a very common use case (sorry I'm new to Go, so maybe there is something language-specific to this solution).

**Comment by mfateev** [comment]
You can pass anything your activity needs via the context to your activity. 

Here is how it works:

1) Before you start your worker, set whatever you need as value to a context (below code happen at where you setup your worker):

```
    myThriftClient := ... // create my thrift client
    myContext := context.WithValue(context.Background(), "my_thrift_client", myThriftClient)

```


2) Use the context created in step1 as BackgroundActivityContext of the worker options that you use to start your worker:

```
    workerOptions := cadence.WorkerOptions{
		MetricsScope:          myScope,
		Logger:                myLogger,
		BackgroundActivityContext: myContext,
	}
    worker := cadence.NewWorker(service, domain, taskList, workerOptions)

```


3) In your activity code, retrieve your thrift client from the context: 

```
    func MyActivity(ctx context.Context) error { 
      myThriftClient := ctx.Value("my_thrift_client").(ThriftClient)
      // now you can make thrift calls using myThriftClient
    }

```

**Comment by hankduan** [comment]
Really appreciate the detailed response @mfateev !
