### ISSUE TITLE
Improved multi-tenancy support in Cadence

### ISSUE THREAD

**Issue by shreyassrivatsan** [uber/cadence#2469]
## Overview

As Cadence starts getting used for more important use cases it is imperative that we provide more guarantees to our customers to ensure that one bad user does not affect other users on the system. To this end there are a number of safeguards that can be built. This document goes over our goals and how we plan to achieve them.

### Goals

- Isolation - implement quotas across all layers of the system. Quotas implemented should be soft quotas and allow for organic growth
- Graceful Degradation - allow for graceful degradation, while implementing a priority system allowing forward progress of high priority domains
- SLA for customers - define SLA metrics that we can report back to customers. Start tracking the same for our alerts

### Non-Goals

- Improved permissioning - only the right person can act on workflows 
- Scalable task list processing - related but something we know needs to be designed and implemented
- Multi-cluster deployments and how to manage them to provide better availability is another area of investigation which we need to tackle. That is left to a separate discussion, with this document focussing solely on multi-tenancy.

### Usage Monitoring

To drive all the multi-tenancy work it is necessary to gain global usage monitoring stats to feed into the described features. We plan to build out an aggregation layer that can allow us to accumulate stats for API calls per domain, timer/transfer queue usage per domain, task list usage per domain etc. These will allow us to make global decisions around throttling which we are not able to do now.

### Rate limiting

Rate limiting on our front end handlers will be improved to enable domain and API specific limits. We will start off with two level rate limits - a first level domain rate limit, followed by a second global rate limit. Initially these will be host level limits. Once we have our usage monitoring infrastructure setup, it will allow us to enforce global rate limits on a per API level.

### Decision Throttling

Misbehaving workflows causing repeated decision failures and retries is a major source of issues in our system. These can cause a flurry of decisions which fail, timeout, get re-queued and timeout again. We do have some protections where we do not requeue decisions immediately if they fail multiple times, we wait for the decision timeout, but even in this case if a large number of workflows run into this issue, this will stress our system with useless work. The idea to deal with such issues with domain specific rate limits on task lists for decisions. 

- Use usage monitoring tooling to aggregate and rate limit task list dispatch on a per domain basis
- Add dynamic rate limits on decision dispatch

### Tasklists with priority queues

From a task dispatch perspective one of the major issues we face is around misbehaving workflows hogging up our task processing queues. On failed decisions (non-deterministic errors), we retry decisions and place them in the same queue along with other outstanding tasks for that tasklist. Such tasks contend with any valid tasks for that task list. The proposal is to build out priority task queues within a task list, with the history service ensuring that retried decisions go into lower priority queues allowing for regular task dispatch to proceed without issues. This feature along with throttling sub-queues in the history service will ensure that consistently failing domains and bursts of traffic do not affect other domains in the system.

### Throttling sub-queues

One of the common use cases for Cadence is to have regularly scheduled jobs, generally timers firing at a particular time to run a workflow. This is a common use case for calculating some information at the end of a month. During such scenarios, expiring the large number of timers firing cause decision dispatch delays in additional domains. This may also happen if a single workflow starts many child workflows and blocks transfer queue processing. 

The idea is to build a throttling sub-queue primitive, wherein we will maintain a counter of tasks per domain (host/global) and when this exceeds a certain limit the timer/transfer queue processing for that domain will go to its own software queue, maintaining its own per domain cursors in the mutable state. Additionally the task workers will be updated to support multiple priorities, with the domains taking more resources being directed to lower priority queues. This will ensure that tasks from other domains can continue to make forward progress while the surge of tasks from large domains can be worked through independently. 

### Scalable Task Lists

This change is already available to users, but it’s put here for completeness. Task lists originally resided in a single host and were a bottleneck if many tasks were to be dispatched. Users who would like to process many timers in the above described scenario would have to spread the tasks across many different task lists. Scalable task lists allow us to spread a task list across many hosts and dynamically change how it is spread, thereby removing this as a bottleneck. We do need to do additional work to automatically scale up task list to span hosts when they are taking up too many resources on a single host.

**Comment by gorillapower** [comment]
Really interested in this functionality, @shreyassrivatsan do have any updates to share on this?

**Comment by fuhengwu2021** [comment]
Is this done or still in progress? It seems done according to https://eng.uber.com/cadence-multi-tenant-task-processing/, but this PR is still open?

**Comment by longquanzheng** [comment]
> Is this done or still in progress? It seems done according to https://eng.uber.com/cadence-multi-tenant-task-processing/, but this PR is still open?

@fuhengwu2021 I would consider this as done. 
It's not implemented exactly the same as described in this issue. 
Instead of per tasklist, we have done lots of work to make sure multiple domain can be running in isolated ways and be able to configure the rate of tasks per domain.
