### ISSUE TITLE
admin tools for deleting tasks need implement mysql one in the future

### ISSUE THREAD

**Issue by lihannan99** [uber/cadence#2479]
Right now we have `DeleteTask` in cassandra, 
We also need to implements this functions in` sqlexecutionManager.go` when we use sql for tasks.

**Comment by yycptt** [comment]
I don't think DeleteTask has been implemented for sql. There's still a TODO in the code which references this issue. https://github.com/uber/cadence/blob/master/common/persistence/sql/sqlExecutionManager.go#L773
