### ISSUE TITLE
Performance of Uber Cadence

### ISSUE THREAD

**Issue by meiskalt7** [uber/cadence#2528]
Hello, I read that Uber Cadence is fast orchestration engine. But when I made my sample of workflow processing with 3 very simple activities and started 1000 workflows then cadence processed them around 20 seconds(50 workflow per second). It's not so good performance in my opinion. Or maybe I did something wrong? 

I tried to replace Activity to LocalActivity and performance increased to 200 workflow per second. We need speed like this for our project but using Activity not LocalActivity.

**Starter of workflows in my microservice:**
```
    @GetMapping("/startWithTimer")
    public String startWithTimer() {
        StopWatch stopWatch = StopWatch.createStarted();
        WorkflowClient workflowClient = WorkflowClient.newInstance(DOMAIN);

        int size = 1000;
        List<CompletableFuture> futures = new ArrayList<>(size);
        for (int i = 0; i < size; i++) {
            CarOrderingWorkflow workflow = workflowClient.newWorkflowStub(CarOrderingWorkflow.class);
            CompletableFuture<Void> future = WorkflowClient.execute(workflow::orderCar, "orderId" + i);
            futures.add(future);
        }

        while (futures.stream().anyMatch(completableFuture -> !completableFuture.isDone())) {
        }

        System.out.println("TIME: " + stopWatch.getTime(TimeUnit.MILLISECONDS));
        stopWatch.stop();
        return "started";
    }
```

**Сadence workflow sample:**

main function
```
    @Override
    public void run(String... args) {
        Worker.Factory factory = new Worker.Factory(SampleConstants.DOMAIN);
        for (int i = 0; i < 2; i++) {
            final Worker workerForCommonTaskList = factory.newWorker(TASK_LIST);
            workerForCommonTaskList.registerWorkflowImplementationTypes(CarOrderingWorkflowImpl.class);
            workerForCommonTaskList.registerActivitiesImplementations(new CarOrderingActivitiesImpl());
        }
        factory.start();
        System.out.println("Worker started for task list: " + TASK_LIST);
    }
```

**Workflow:**

```
public class CarOrderingWorkflowImpl implements CarOrderingWorkflow {

    private final ActivityOptions options =
            new ActivityOptions.Builder()
                    .setScheduleToCloseTimeout(Duration.ofSeconds(2))
                    .setRetryOptions(
                            new RetryOptions.Builder()
                                    .setInitialInterval(Duration.ofMillis(500))
                                    .setExpiration(Duration.ofSeconds(10))
                                    .setDoNotRetry(IllegalArgumentException.class)
                                    .build())
                    .build();
    private final CarOrderingActivities activities =
            Workflow.newActivityStub(CarOrderingActivities.class, options);

    @Override
    public void orderCar(String orderId) {
        try {
            StopWatch stopWatch = StopWatch.createStarted();
            String orderCity = activities.getOrderCity(orderId);
            String driverId = activities.getFreeDriver(orderCity);
            String result = activities.setDriverToOrder(orderId, driverId);
            System.out.println(stopWatch.getTime(TimeUnit.MILLISECONDS));
        } catch (ActivityException e) {
            throw e;
        }
    }
}
```

**Activities:** (only return String objects, very simple)
```
public class CarOrderingActivitiesImpl implements CarOrderingActivities {

    @Override
    public String getOrderCity(String orderId) {
        return "Nsk";
    }

    @Override
    public String getFreeDriver(String orderCity) {
        return "driverId";
    }

    @Override
    public String setDriverToOrder(String orderId, String driverId) {
        return "1";
    }
}
```

**Comment by meiskalt7** [comment]
And?

**Comment by samarabbas** [comment]
@meiskalt7 Can you try [Cadence Helm Chart](https://hub.helm.sh/charts/banzaicloud-stable/cadence) contributed by Banzai Cloud?  This is the simplest way to deploy a production ready cluster for Cadence at this point.  Multiple users of Cadence are able to use it to deploy Cadence server on their own premises.  
I would also recommend to join our [slack channel](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTI5Yzc5ODYwMjg1ZmI3NmRmMTU1MjQ0YzQyZDc5NzMwMmM0NjkzNDE5MmM0NzU5YTlhMmI4NzIzMDhiNzFjMDM).  You will get much faster response time on it and we can quickly walk you through any deployment related questions on our operations channel.

**Comment by sagikazarmark** [comment]
> the readme should be updated to say that it shouldn't be used in production

@Vorror actually, it kinda already does

<img width="606" alt="Screenshot 2019-09-20 at 22 16 42" src="https://user-images.githubusercontent.com/1226384/65356327-78668a80-dbf4-11e9-8c1e-d33417bf622a.png">

**Comment by Vorror** [comment]
@sagikazarmark 
Even if you want users to infer that it's _only_ for development, as far as I can tell, the _**only**_ information on running cadence is that docker info. Which is why the following comment can be made by @meiskalt7 

> I assume that you are using our developer docker

That assumption can be made because there's no other information on how to run cadence in production. It's not a stretch of the imagination that someone would take that docker file and then run it on production.

I appreciate the time and effort that it requires to create 'production' ready docker files, but there should be at least a readme on the knobs that should be tweaked.

**Comment by sagikazarmark** [comment]
@Vorror I'm not arguing that the documentation could be better for a production setup (although there is one more confusion here: there _are_ docker images for a production setup, only the docker compose environment is intended for development), I merely pointed out that the docker-compose setup is clearly for development purposes only and I'm not sure where else should it be mentioned.

As @samarabbas mentioned, currently the Helm chart is the closest thing to a public production setup guide. Even if you don't run Cadence on Kubernetes, you can examine the configuration options and generate the configuration file.

**Comment by samarabbas** [comment]
@Vorror We do acknowledge that our public documentation is quite inadequate at this point especially around production cluster setup.  There are already multiple issues tracking lack of documentation for various areas including production config and setup.  More recently we started to track feedback using [this](https://github.com/uber/cadence/issues/2576) issue.

This particular issue was filed as performance problem with Cadence.  So if you don't have any more questions about performance I would like to close this out.  I'll be willing to work through your deployment related questions on our slack channel as we are working to improve documentation in this area.
