### ISSUE TITLE
Configure Cadence to use HTTP/2

### ISSUE THREAD

**Issue by hankduan** [uber/cadence#2534]
Is there a way to configure cadence to use HTTP/2?

**Comment by hankduan** [comment]
Sorry for so many questions, but is there any way to configure cadence to go through http/1? I saw in https://github.com/uber/cadence/issues/348 that it _might_ be possible?

**Comment by mfateev** [comment]
@samarabbas

**Comment by samarabbas** [comment]
Cadence now uses [yarpc](https://github.com/yarpc/yarpc-go) which already has support for exposing our existing thrift handlers as http.  This could be achieved by simply initializing yarpc dispatcher with http inbound.  Currently we statically [initialize](https://github.com/uber/cadence/blob/master/common/service/config/rpc.go#L66) Cadence server with tchannel inbound.  It should be a relatively straight forward to add support for also initializing the server using http inbound.  
We don't have resources to work on this right now, but I will be willing to work with you if you are up for it.

**Comment by hankduan** [comment]
Yea sounds good. Can you point me to what is needed (I.e which files need to be modified) to make the change?

**Comment by anthonydmitriyev** [comment]
Is there any progress on this?

I looked into switching the transport to HTTP, but it appears that `ringpop-go` lib has a hard dependency on TChannel transport (common/service/config/ringpop.go)

**Comment by hankduan** [comment]
@mfateev Is the grpc migration still on track to finish by end of this year? If not, do you have a new timeline that you can share?

**Comment by mfateev** [comment]
Currently we are targeting beginning of Q1.

**Comment by hankduan** [comment]
Thanks!
