### ISSUE TITLE
[Feature] Add support for Postgres

### ISSUE THREAD

**Issue by hazcod** [uber/cadence#2536]
Postgress support would add support for PostgreSQL or even [cockroach-db](https://github.com/cockroachdb/cockroach) which is optimized for high-available cloud scenarios.

One would need to reimplement https://github.com/uber/cadence/tree/78d84ea199b0bba2828df3461e4e7b9a40edf5fd/common/persistence/sql/storage/mysql for postgres.

I started the work in https://github.com/uber/cadence/pull/2537 , but will probably need some help here.

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence/pull/2836

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence/pull/2889

**Comment by sheerun** [comment]
#2836 Is merged, so this is implemented? Are there docs how to use Cadence with Posgres?

**Comment by shudhanshh** [comment]
I'm also having the same issue can't find any docs to connect with Postgres?
