### ISSUE TITLE
cadence is too big ? have any lite version could replace ?

### ISSUE THREAD

**Issue by Jamlee** [uber/cadence#2544]
cadence is too big ? have any lite version could replace ?

**Comment by mfateev** [comment]
What are your requirements and use case and what do you mean by "too big"?

**Comment by Jamlee** [comment]
it is too complex for my case and is high overhead. Could you consider making a lite version that only depend on mysql ?

**Comment by mfateev** [comment]
We do have a version that depends only on mysql. 

It would be interesting to understand your use case and see what would be the simplest solution that solves it.

**Comment by Jamlee** [comment]
i depend  a `job manger`, because i not good to write mutiple thread. i would to monitor and log      threads(gocoroutine) in my web page. it is suite for that have long-runtime task  and need ensure result (eg: send email, create vm ...)

**Comment by mfateev** [comment]
It sounds like Cadence is a good fit for the use case.
