### ISSUE TITLE
Callback hook on timeout

### ISSUE THREAD

**Issue by hankduan** [uber/cadence#2572]
Is there a way to add a callback hook when a workflow times out?

**Background**:
Each of my workflow periodically updates its state to a DB (i.e. stateA -> stateB -> stateC -> completed/failed)

**Question**:
On a time out, is there a way for me to add a hook so I can update my DB state to "timeout", so it doesn't get stuck in one of the transient state forever?

I can alternatively query the workflow for state periodically and update my DB using an external monitoring task, but it's not really a nice solution. 

I can also set a timer that fires right before the workflow times out (i.e. timeout-1min) to update the DB I guess, but this solution is also not as nice.

**Comment by mfateev** [comment]
We recommend to not use workflow execution timeout for any business logic. It is purely to limit resource utilization in case of forgotten and other workflows.

Use timers for any business related logic. So I believe your last solution of using a timer before exiting a workflow is the best one.

**Comment by hankduan** [comment]
Cool, thanks!
