### ISSUE TITLE
Visibility authorization in Elastic

### ISSUE THREAD

**Issue by szaluzhskiy** [uber/cadence#2573]
Visibility requires ElasticSearch(ES) to be installed and connected to Cadence server. In out production installation, ES server requires service authentication by certificate. ES client used in Cadence server does not allow to authenticate in ES. 

ES client - https://github.com/uber/cadence/blob/master/common/elasticsearch/client.go

**Comment by vancexu** [comment]
Hi @szaluzhskiy , 
In your environment, what client do you use and how do you usually connect with authentication? We use `github.com/olivere/elastic`, I wonder will adding option of `SetHttpClient` help you?

Also do you think you can help working on add this? Because Cadence team doesn't have such authentication in ES so it would be a little bit inconvenient for us to work on it.

**Comment by szaluzhskiy** [comment]
Hi @vancexu!
  We can try to make this improvement. Seems like not a big deal.
  But what I have faced. I need to run cadence server locally from IDE (GoLand). 

  My steps were:

1.   Run go build ./... from root
2.   Install cassandra schema to local Cassandra DB
3.   Run cmd/server/cadence.go

  Error
  `# command-line-arguments
cmd/server/cadence.go:34:30: undefined: historyService
cmd/server/cadence.go:34:46: undefined: matchingService
cmd/server/cadence.go:34:63: undefined: frontendService
cmd/server/cadence.go:34:80: undefined: workerService
cmd/server/cadence.go:77:13: undefined: newServer`

**Comment by szaluzhskiy** [comment]
Hi @vancexu,
I'll try to make a this client extension. In order to test locally I need to run Cadence server. 
What is the most easy way to start server locally?

I try to run
`go build github.com/uber/cadence/cmd/server/cadence.go`

And get `2019/09/23 23:02:56 Loading configFiles=[./config/base.yaml ./config/development.yaml]
2019/09/23 23:07:58 Config file corrupted.PublicClient.HostPort: zero value`

**Comment by vancexu** [comment]
@szaluzhskiy 
To build cadence server, under root `github.com/uber/cadence/` run `make bins` or `make cadence-server`. 
Then start dependencies systems including database (mysql or cassandra), elasticsearch, kafka&zookeeper.
Then use ES cadence config by copy `./config/development.-es.yaml` to `./config/development.yaml`
Then start cadence server by `./cadence-server start`
