### ISSUE TITLE
Dumping ground for things missing in the documentation

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#2576]
Feel free to comment on this issue about concepts, patterns and anti-patterns that Cadence documentation is missing. 
We are going to use this thread later to improve the documentation.

**Comment by mfateev** [comment]
From Slack:

_- Don't create workers per request. You could create one at start and then use it.
- Your workflow and activities can be with the same worker or even different-remote workers. Time responses will be slower in the second approach though. If you want it faster, use local activities.... etc ... etc..._

**Comment by hm0** [comment]
Tips for possible configurations: developer (the default), production (arguable subjective but at least some tips for proper configuration)...

**Comment by sagikazarmark** [comment]
Not really "missing", but I would add visually improvement of the documentation. For example increase line height for better readability.

**Comment by hazcod** [comment]
I really missed explanation of the basic client primitives (Future, Select, ...) in a tutorial.
