### ISSUE TITLE
Create Cadence domain without a running Cadence instance

### ISSUE THREAD

**Issue by sagikazarmark** [uber/cadence#2578]
I would like to create a Cadence domain in the underlying storage without actually running Cadence service.

My use case is moving Cadence from one storage to another (without preserving anything, but the domain), but I can imagine it to be useful for bootstrapping Cadence store for the first time.

The store CLI utility might be a good place for this.

**Comment by wxing1292** [comment]
#2612: first moving domain logic into common

**Comment by wxing1292** [comment]
#2624: then add capability to use domain handler from admin domain CLI

**Comment by sagikazarmark** [comment]
Thanks!
