### ISSUE TITLE
Flaky unit tests

### ISSUE THREAD

**Issue by yycptt** [uber/cadence#2585]
```
--- FAIL: TestMatchingEngineSuite/TestConcurrentPublishConsumeActivities (1.03s)
      matchingEngine_test.go:909: 
            	Error Trace:	matchingEngine_test.go:909
            	            				matchingEngine_test.go:751
            	Error:      	Not equal: 
            	            	expected: 0
            	            	actual  : 1
            	Test:       	TestMatchingEngineSuite/TestConcurrentPublishConsumeActivities
```

**Comment by samarabbas** [comment]
Another Flaky test: 
TestTimerQueueProcessorSuite/TestTimerUserTimers_SameExpiry

PR is failed on: 
https://github.com/uber/cadence/pull/2568

**Comment by samarabbas** [comment]
Another one:

FAIL: TestUpdateSchemaTestSuite (13.86s) | 7s
-- | --
  | require.go:765:
  | Error Trace:	updatetest.go:83
  | updateTask_test.go:63
  | Error:      	Expected nil, but got: gocql.errorFrame{frameHeader:gocql.frameHeader{version:0x84, flags:0x0, stream:1920, op:0x0, length:145, customPayload:map[string][]uint8(nil), warnings:[]string(nil)}, code:8704, message:"Cannot drop user type update_test_3381071236719446981.cluster_replication_config as it is still used by user type domain_replication_config"}
  | Test:       	TestUpdateSchemaTestSuite
  | --- FAIL: TestUpdateSchemaTestSuite/TestDryrun (13.57s)
  | testing.go:820: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
