### ISSUE TITLE
Admin command to dump membership ring information

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#2586]
It is very hard to get visibility into membership ring for any Cadence cluster.  We need an admin API to dump status for all roles/hosts/shards/tasklists/etc

**Comment by d-vignesh** [comment]
Hi @longquanzheng, can i work on this issue?

**Comment by demirkayaender** [comment]
Do you already know what you need to do here or do you need help with pointers?

**Comment by d-vignesh** [comment]
I do not have much idea on this @demirkayaender , could you please help with some pointers
