### ISSUE TITLE
Include next run ID on failed event for workflow retry

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#2595]
We should also include the next run ID when the workflow execution fails and gets retried due to RetryPolicy.  Similar to ContinueAsNew event.

**Comment by anish531213** [comment]
We record ContinueAsNew event when workflow gets retried due to RetryPolicy. Verified in sample workflow.
<img width="1401" alt="Screen Shot 2019-12-22 at 4 55 19 PM" src="https://user-images.githubusercontent.com/14882675/71553478-d6112c80-29c4-11ea-8c26-dea72e0c2b5f.png">
