### ISSUE TITLE
[Feature] Add support for ScyllaDB

### ISSUE THREAD

**Issue by kop** [uber/cadence#2607]
Scylla is a drop-in Apache Cassandra alternative written in C++ instead of Java.

It would be great if Cadence could support it, since it becomes more widely used.

Currently, when I try to use Cadence with Scylla, I get:

`ProtocolError("cql_version '3.4.4' is not supported by remote (w/ native protocol). Supported versions: [u'3.3.1']",)`.

So basically, the main question is there any serious reason why `3.4.4` is required?

**Comment by mfateev** [comment]
We are closely watching Scylla and believe it is a viable long term alternative to Cassandra. But Cadence heavily relies on lightweight transactions to guarantee consistency and Scylla does not support them yet. [Here is the related issue ](https://github.com/scylladb/scylla/issues/1359) to get them added.

**Comment by artyomturkin** [comment]
Was able to start cadence (docker) with scylla 3.2 with experimental features (also docker).
Had to update cadence start script not to check cql version, but very quick test (starting non existing task through cli) showed that cadence works with scylla!

Is there a test suit that can be run to verify scylla compatibility?

**Comment by giautm** [comment]
scylla has removed experimental features flag, so LWT is officially supported

**Comment by slayerjain** [comment]
Does this mean that scylla would be supported now and this issue can be closed? 🙂

**Comment by longquanzheng** [comment]
Hey folks, 
Just let you know, I am working on https://github.com/uber/cadence/issues/3514 
this will enable us to implement any NoSQL database including ScyllaDB. After the NoSQL plugin model is done, I am planning to implement ScyllaDB and AWS Keyspace as they are more similar to Cassandra. 

@slayerjain

**Comment by slayerjain** [comment]
@longquanzheng This is great news!

**Comment by meiliang86** [comment]
@artyomturkin It would be great if you can post some tips/steps on what you have done so far, so others can follow.

**Comment by artyomturkin** [comment]
The only thing I did was modify one function in [docker/start.sh](https://github.com/uber/cadence/blob/master/docker/start.sh) to, pretty much, remove the check. This is a dirty hack, so use at your own risk :smile: 

```
wait_for_cassandra() {
    server=`echo $CASSANDRA_SEEDS | awk -F ',' '{print $1}'`
    sleep 30
    echo 'cassandra started'
}
```
