### ISSUE TITLE
Website: slack invite link on cadenceworkflow.io is broken

### ISSUE THREAD

**Issue by mattbailey** [uber/cadence#2614]
Slack invite on the site just returns:

> This invite link is no longer active.
> If you have an @paypal.com or @visa.com email address, you can still create an account.
> If not, please check with the person who shared the invite link with you to ask for an invitation.

**Comment by mfateev** [comment]
Weird, I'm able to sign up using the same link and an incognito browser window

**Comment by mfateev** [comment]
Are you using [this link?](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTQyYjcxZDM2YTIxMTZkMzQ0NjgxYmI3OWY5ODhiOTliM2I5MzA4NTM4MjU4YzgzZDkwNGEzOTUzNTBlNDk3Yjc)

**Comment by mattbailey** [comment]
> Are you using [this link?](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTQyYjcxZDM2YTIxMTZkMzQ0NjgxYmI3OWY5ODhiOTliM2I5MzA4NTM4MjU4YzgzZDkwNGEzOTUzNTBlNDk3Yjc)

sorry, should have been more specific, was using the one in the top right of the bar on the site (https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTI5Yzc5ODYwMjg1ZmI3NmRmMTU1MjQ0YzQyZDc5NzMwMmM0NjkzNDE5MmM0NzU5YTlhMmI4NzIzMDhiNzFjMDM) that new one works!

**Comment by wxing1292** [comment]
#2697
