### ISSUE TITLE
Matching Engine stops delivering tasks

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#263]
We uncovered an issue in our upgrade testing today where matching engine stopped delivering tasks for some tasklists.  Ack Level was stuck at a lower value and I can see more tasks in tasklist beyond the ack level.  Restarting all matching engine nodes fixed the problem, and caused all stuck workflow executions to make progress.  
Losing decision scheduled tasks can cause stuck workflows as they are not protected by timeouts.  In this case we didn't lose tasks but just matching engine stopped delivering those tasks due to some bug.

Stuck Workflow:
select * from open_executions ;

 domain_id                            | domain_partition | start_time               | run_id                               | workflow_id                                  | workflow_type_name
--------------------------------------+------------------+--------------------------+--------------------------------------+----------------------------------------------+------------------------------------------------------------------------------
 70de1505-7b4a-4762-83ac-363cebde7077 |                0 | 2017-06-27 23:04:37+0000 | 1a331bc9-2193-4073-969f-68ce28d630e4 | 91047fac-3452-4e43-b6d1-e848a739cc39-16-7209 | code.uber.internal/devexp/cadence-server/health/driver.stressWorkflowExecute
 70de1505-7b4a-4762-83ac-363cebde7077 |                0 | 2017-06-27 23:04:35+0000 | a383c1f1-175f-4550-8c3c-dd51b87ef113 | 4813f9d4-bf52-4a4c-a868-782db860802d-13-7209 | code.uber.internal/devexp/cadence-server/health/driver.stressWorkflowExecute
 70de1505-7b4a-4762-83ac-363cebde7077 |                0 | 2017-06-27 23:04:35+0000 | b5ce35ef-b175-4de9-b76f-cd8ea65f87ce | 5081ee9e-c8e9-4c17-9590-597962b595f4-17-7273 | code.uber.internal/devexp/cadence-server/health/driver.stressWorkflowExecute
 70de1505-7b4a-4762-83ac-363cebde7077 |                0 | 2017-06-27 23:04:06+0000 | 888f4697-89dd-4bd8-8f2b-0258e8a5d79c |  90201a11-cc57-48da-b165-46ce8e5326ff-6-6986 | code.uber.internal/devexp/cadence-server/health/driver.stressWorkflowExecute

History for one of the stuck workflow:
1, 2017-06-27T23:04:37Z, WorkflowExecutionStarted: (WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.stressWorkflowExecute), TaskList:(Name:testTaskList-41), Input:[len=176], ExecutionStartToCloseTimeoutSeconds:300, TaskStartToCloseTimeoutSeconds:60, Identity:106@compute2470-dca1@)
2, 2017-06-27T23:04:37Z, DecisionTaskScheduled: (TaskList:(Name:testTaskList-41), StartToCloseTimeoutSeconds:60)

One of the stuck tasklist:
select * from tasks where domain_id = 70de1505-7b4a-4762-83ac-363cebde7077 and task_list_name = 'testTaskList-41' and task_list_type = 0;

 domain_id                            | task_list_name  | task_list_type | type | task_id | range_id | task                                                                                                                                                                          | task_list
--------------------------------------+-----------------+----------------+------+---------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------
 70de1505-7b4a-4762-83ac-363cebde7077 | testTaskList-41 |              0 |    0 |  800005 |        9 |  {domain_id: 70de1505-7b4a-4762-83ac-363cebde7077, workflow_id: '5081ee9e-c8e9-4c17-9590-597962b595f4-17-7273', run_id: b5ce35ef-b175-4de9-b76f-cd8ea65f87ce, schedule_id: 8} |                                                                                                   null
 70de1505-7b4a-4762-83ac-363cebde7077 | testTaskList-41 |              0 |    0 |  800006 |        9 | {domain_id: 70de1505-7b4a-4762-83ac-363cebde7077, workflow_id: '4813f9d4-bf52-4a4c-a868-782db860802d-13-7209', run_id: a383c1f1-175f-4550-8c3c-dd51b87ef113, schedule_id: 26} |                                                                                                   null
 70de1505-7b4a-4762-83ac-363cebde7077 | testTaskList-41 |              0 |    0 |  800007 |        9 |  {domain_id: 70de1505-7b4a-4762-83ac-363cebde7077, workflow_id: '91047fac-3452-4e43-b6d1-e848a739cc39-16-7209', run_id: 1a331bc9-2193-4073-969f-68ce28d630e4, schedule_id: 2} |                                                                                                   null
 70de1505-7b4a-4762-83ac-363cebde7077 | testTaskList-41 |              0 |    1 |  -12345 |        9 |                                                                                                                                                                          null | {domain_id: 70de1505-7b4a-4762-83ac-363cebde7077, name: 'testTaskList-41', type: 0, ack_level: 800004}

(4 rows)

**Comment by samarabbas** [comment]
I also see the following logs on matching engine:
helpers.go:38 Persistent store operation failure. Operation Details: {taskType: 0, taskList: testTaskList-4}

**Comment by tamer-eldeeb** [comment]
I believe I understand what was going on here. This should be fixed by #271.
More details:

In the past the only way the matching engine would detect that it no longer owns a task list was when it attempts to write a task to Cassandra and fails due to RangeID condition. Due to sync matching, writing tasks to Cassandra is rare. 
If a matching engine loses the ownership of a task list and gets it back, it would not recognize that it was lost (until it tries to write to Cassandra). This could lead it to be unaware of tasks that were written to Cassandra in the period the ownership was lost.
