### ISSUE TITLE
Add terminateIfRunning WorkflowIDReusePolicy

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#2653]
It common scenario when a workflow should be started with new parameters. Terminating and then starting workflow has race conditions. Adding terminateIfRunning WorkflowIDReusePolicy would allow to eliminate race conditions.

**Comment by wxing1292** [comment]
termination & start a new can be done by similar to `continue as new`
this should be easy to do since after the refactor of DB layer & business logic layer, terminate the currently running workflow & start a new workflow can be done within one transaction.

**Comment by kaustubhmallik** [comment]
Is it still available to be picked up? If yes, I would love to take it.

**Comment by mfateev** [comment]
Yes, I'm not aware about anyone working on this.

**Comment by kaustubhmallik** [comment]
Hi, @mfateev @wxing1292 apologies for the delayed response. I was trying to wrap my head around the cadence server and client codebase. As I understood it, the following steps are needed:

1. Append the new policy `TerminateIfRunning` in `enum WorkflowIdReusePolicy`, in [shared.thrift](https://github.com/uber/cadence-idl/blob/master/thrift/shared.thrift#L106) file. 
2. Add a new workflow reuse policy in the [internal/client.go](https://github.com/uber-go/cadence-client/blob/master/internal/client.go#L481) and [client/client.go](https://github.com/uber-go/cadence-client/blob/master/client/client.go#L388). Make other relevant changes in the client to send the new policy while creating workflows.
3. Handle the new policy in the cadence server [canary/client.go](https://github.com/uber/cadence/blob/master/canary/client.go), and do the steps necessary to ensure that existing workflow is terminated before creating a new one.

Obviously, the last step is the critical one. I will try to further specify the exact sub-steps needed in the final part. I know it's a lot to ask for, but it would be a big help if you guys can point me to any design/high-level architecture document, or something else that would help me to have a better understanding of the cadence server.

**Comment by mfateev** [comment]
3. canary is a process used to test availability of the service. The actual implementation logic is in the https://github.com/uber/cadence/blob/ee3d5f45043a0a79767d2aca2fafe8f535f47952/service/history/historyEngine.go#L488

**Comment by mfateev** [comment]
@samarabbas Would you be able to give the sequence of steps needed to change the historyEngine?

**Comment by wxing1292** [comment]
@vancexu plz provide some details about signal with start, that code should really be cleaned up

my understanding, the followings should be done
1. merge start workflow execution with signal with start workflow execution (underlying business logic)
2. add the corresponding terminal & start policy to workflow ID reuse policy
3. treat terminal & start something similar to signal with start

**Comment by vancexu** [comment]
Yes wenquan, I will pick it up as promised long long time ago ..

**Comment by vancexu** [comment]
https://github.com/uber/cadence/issues/2653

**Comment by vancexu** [comment]
This feature will be ready in server 0.13.0 and related client releases.
