### ISSUE TITLE
Admin CLI - Admin delete workflow cannot set target server address

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence#2663]
Admin delete workflow use both `address` attr to set connection to server & connection to Cassandra
The ideal solution should be bypassing server to get the mutable state

**Comment by longquanzheng** [comment]
fix in https://github.com/uber/cadence/pull/2761

bypassing server is a little more unfriendly: user need to pass domianID and numShards. Let's have the minimum fix for now. We can create a new issue for it and see if we still want to do that way.
