### ISSUE TITLE
server image tags >= 0.9.0 don't run

### ISSUE THREAD

**Issue by zhaytee** [uber/cadence#2664]
Hey folks.

Trying to run the latest `server` Docker image hosted on DockerHub, tag `0.9.3`. Looks like there might be an issue with the entrypoint script not being marked as executable or something? Tags `0.9.0`, `0.9.1`, and `0.9.3` all have this issue:

```bash
$ docker run -it --rm ubercadence/server:0.9.3
/bin/bash: /start-cadence.sh: Permission denied
```

So I walked back in time and found that the latest 0.8 tag (`0.8.6`) is fine:

```bash
$ docker run -it --rm ubercadence/server:0.8.6
2019/10/14 04:41:41 Loading config; env=docker,zone=,configDir=/etc/cadence/config
2019/10/14 04:41:41 Loading configFiles=[/etc/cadence/config/docker.yaml]
(rest snipped)
```

I'll be using `0.8.6` in my k8s cluster for now, but just wanted to raise a red flag about those latest image releases. I'd rather use them, but they don't seem to execute as expected.

Thank you.

**Comment by wxing1292** [comment]
pending #2665

**Comment by wxing1292** [comment]
please use the latest release 0.9.4: https://hub.docker.com/r/ubercadence/server/tags

**Comment by wxing1292** [comment]
I have already verified locally, @zhaytee could you double verify?
Make sure to upgrade to Cassandra 0.22 schema version before rollout

**Comment by meiliang86** [comment]
Closing this as the bad images have been removed and new images are published.
