### ISSUE TITLE
Server exited with error when trying to create domain during Cassandra initialization

### ISSUE THREAD

**Issue by mingfang** [uber/cadence#2694]
I’m using the command until cadence --domain $CADENCE_CLI_DOMAIN domain describe || cadence --domain $CADENCE_CLI_DOMAIN domain register; as a test for when cadence has started and ready. It looks like this command actually halts cadence if it is in the middle of initializing cassandra. This is error
```
2019/10/20 02:37:03 Schema updated from 0.21 to 0.22                                              
2019/10/20 02:37:03 UpdateSchemeTask done                                                         2019/10/20 02:37:03 gocql: unable to dial control conn 172.27.215.236: dial tcp 172.27.215.236:9042: connect: connection refused                                                                   
2019/10/20 02:37:03 error creating Keyspace:gocql: unable to create session: control: unable to connect to initial hosts: dial tcp 172.27.215.236:9042: connect: connection refused                
2019/10/20 02:37:03 error: failed to connect to 250.2.162.9:9042 due to error: Keyspace 'cadence_ visibility' does not exist                                                                        
2019/10/20 02:37:03 error: failed to connect to 250.2.162.9:9042 due to error: Keyspace 'cadence_ visibility' does not exist                                                                        
2019/10/20 02:37:03 no connections were made when creating the session                            
2019/10/20 02:37:03 error: failed to connect to 250.2.162.9:9042 due to error: Keyspace 'cadence_ visibility' does not exist                                                                        
2019/10/20 02:37:04 error: failed to connect to 250.2.162.9:9042 due to error: Keyspace 'cadence_ visibility' does not exist                                                                        
2019/10/20 02:37:04 no connections were made when creating the session                            
2019/10/20 02:37:04 Loading config; env=docker,zone=,configDir=/etc/cadence/config                
2019/10/20 02:37:04 Loading configFiles=[/etc/cadence/config/docker.yaml]                         
2019/10/20 02:37:04 error: failed to connect to 250.2.162.9:9042 due to error: Keyspace 'cadence_ visibility' does not exist                                                                        
2019/10/20 02:37:04 error: failed to connect to 250.2.162.9:9042 due to error: Keyspace 'cadence_ visibility' does not exist                                                                        
2019/10/20 02:37:04 Incompatible versionsunable to create CQL Client: no connections were made when creating the session                                                                           
2019/10/20 02:37:04 Command exited with error: exit status 1 
```

The problem is in this line from my Terraform automation
https://github.com/mingfang/terraform-k8s-modules/blob/master/modules/cadence/server/main.tf#L53

**Comment by wxing1292** [comment]
1. cadence server cannot start until target schema versions (one for execution, one for visibility) are met.
2. the log showed here is from cadence-cassandra-tool, which has nothing to do with cadence cli.
3. the command showed is cadence cli, which dependents on cadence server (which is not started yet).
4. the error log says connection refused:
  `error creating Keyspace:gocql: unable to create session: control: unable to connect to initial hosts: dial tcp 172.27.215.236:9042: connect: connection refused `
5. according to the dependency & schema version check, did you tried using cadence-cassandra-tool to setup the visibility keyspace? you can ref this: https://github.com/uber/cadence/blob/master/Makefile#L236

**Comment by mingfang** [comment]
@wxing1292 Thanks for troubleshooting this. 
As discussed, I believe you're correct in thinking that this problem was actually caused by the Cassandra being unstable around the same time as the schema is being created.

**Comment by wxing1292** [comment]
according to the analysis, the correct solution should be #2696 + error handling + proper retry
existing cadence cassandra / sql tool does not handle error well.

close in favor of #2696
