### ISSUE TITLE
Make buildkite pipeline page public

### ISSUE THREAD

**Issue by sevein** [uber/cadence#2698]
Would it be possible to make the buildkite pipeline public? That would allow external contributors to access build reports.

Buildkite [announced support for public build pages](https://buildkite.com/changelog/46-public-build-pages-for-open-source) back in February.  It can be set up here: https://buildkite.com/uber/cadence/settings/pipeline (admin privileges needed).

**Comment by wxing1292** [comment]
@sevein cadence server / java client / go client pipelines are all public now

**Comment by sevein** [comment]
Amazing! Thank you! :clap: :clap: :clap:
