### ISSUE TITLE
Make sure to tag all logs with domainName and domainID

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#270]

**Comment by dmetzgar** [comment]
@samarabbas, is this still something you want in all logs?

**Comment by dmetzgar** [comment]
@shreyassrivatsan does your work cover logs as well?

**Comment by shreyassrivatsan** [comment]
> @shreyassrivatsan does your work cover logs as well?

I was only looking at metrics. A large portion of our logs already have domain names or IDs on them, but not all..

**Comment by dmetzgar** [comment]
Closing this. If there are specific areas where these tags are missing we should create separate issues.
