### ISSUE TITLE
Size protections on query result size

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber/cadence#2712]
Decide what size limits we want to put on query results. We do not write query results to database so we can support fairly large result sizes but this should still be bounded.

**Comment by andrewjdawson2016** [comment]
We should also enforce size limits for query input.

Another thing to consider if there are actually two things we care about for result sizes
- The result size of a single query limit
- The result size of all buffered queries answered on a single decision task - this sum should be limited as well

Lets start with emitting metrics on query sizes and go from there on enforcing limits.

**Comment by meiliang86** [comment]
IMO this limit should be quite small, if that's the case single query limit should be enough.
Large payloads will likely cause performance issues in various parts of the system and should be discouraged.
If customer really wants large result back then we should think about supporting streaming.

**Comment by andrewjdawson2016** [comment]
I will also emit metrics on number of query results included per decision task this will allow us to know if one limit is enough or if we need both a sum limit and a per query limit. I think you might be right that one limit is enough.
