### ISSUE TITLE
Running AddSearchAttribute CLI command locally without ElasticSearch installed results in nil reference 

### ISSUE THREAD

**Issue by ntayyab** [uber/cadence#2726]
Repro steps for running it on a onebox cadence setup without ES.

./cadence --domain samples-domain adm cl asa --search_attr_key NewKey7 --search_attr_type 1
Are you trying to add key [NewKey7] with Type [Keyword]? Y/N
y
Error: Add search attribute failed.
Error Details: code:internal message:panic: runtime error: invalid memory address or nil pointer dereference

**Comment by vancexu** [comment]
@ntayyab Thanks for reporting this. 
We will fix it to return proper error details. 

Are you trying to use search attributes on store other than ES?

**Comment by ntayyab** [comment]
No. I am new to Cadence and was just testing out different commands. I guessed on the failure that this particular one expects ES (which I didn't have) but I felt the error message could be better so I opened this issue.

**Comment by vancexu** [comment]
Got it, thank you.

**Comment by ntayyab** [comment]
thanks for the fix @vancexu
