### ISSUE TITLE
Do renaming of decision task and query task

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber/cadence#2728]
Currently decision task can mean the following things
- A query task which cannot produce decisions
- A decision task with queries on it to run after reply
- A decision task with no queries on it

These multiple meanings make for a confusing looking API. Instead we should have a pattern that looks like

```
type WorkflowTaskType int

const (
    DecisionTask WorkflowTaskType = iota
    QueryTask
)

type QueryTask struct {
    ...
}

type DecisionTask struct {
    ...
    // one of the fields here will be query
}

WorkflowTask struct {
    WorkflowTaskType WorkflowTaskType
    // only one of the following will be non-nil
    QueryTask *QueryTask
    DecisionTask *DecisionTask
}
```

**Comment by swayamraina** [comment]
@andrewjdawson2016 this seems to be a stale issue. Wanted to check if this is required and can be picked up?

**Comment by meiliang86** [comment]
Not required, and probably won't be picked up. This is purely naming change suggestion and would not indicate any bugs in the system. Closing for now.
