### ISSUE TITLE
Worker Resources and Scheduling

### ISSUE THREAD

**Issue by xiaodiannao** [uber/cadence#2734]
Hi everyone, 

First of all I want to thank you for this amazing project. I started playing with cadence a couple of days ago and I'm impressed. One thing that I'm struggling to understand is the queueing in task lists and the criteria which is used by cadence to decide when and using which worker to execute a specific activity.

In the documentation I see the following: 

> A worker polls for a message only when it has spare capacity, so it never gets overloaded.
Automatic load balancing across a large number of workers.

Keeping that in mind I created a workflow that launches a task which uses 100% CPU for 30 seconds on all cores. I then start 2 workers and start the cpu intensive workflow 2 times. Workflow1 is launched on worker1 while workflow2 is launched on worker2. The weird thing is now, both activities are executed immediately on worker1. I expected the worker to first finish activity1 and then activity2.

In a second example I created a workflow which launches an activity for every CPU core. Each of these activities again generate 100% CPU load for 30 seconds. I then again launch 2 workers and trigger the workflow 2 times. In this example workflow1 is started on worker1 and workflow2 is started on worker2. Now 4 activities are executed using worker1 and the other 4 activities are executed using worker2. Here again I expected the activities to be executed one by one, since the "capacity" of the workers is 0 no?

So my question is: Is is possible to configure Cadence to schedule activities only if enough CPU and memory are available? What is the criteria for a worker to be "overloaded" as described in the documentation?

Thank you and best regards

**Comment by mfateev** [comment]
Thank you for the interest in Cadence. You have to specify the limit on how many parallel activities a worker is allowed to pick up. The default limit is pretty high that's why you see a single worker picking them up. The configuration parameter is WorkerOptions.MaxConcurrentActivityExecutionSize.

**Comment by xiaodiannao** [comment]
Hi @mfateev thanks for your quick response. Ah so the workers are limited by WorkerOptions.MaxConcurrentActivityExecutionSize and not by system resources such as CPU and memory? Is there a way to achieve what I'm trying to do (allow workers to pick up work based on system resources)?

**Comment by wxing1292** [comment]
Currently worker does not have the ability to analyze CPU util / load + mem usage for worker side resource based load balancing, users need to manually configure the number concurrent execution of decision / activity per worker.

**Comment by xiaodiannao** [comment]
@wxing1292 ah okay that't what I suspected, thanks for your reply! Do you know of a way to solve this by e.g. combining it with docker swarm? Say, execute resource intensive activities in a docker container and let docker swarm analyze & manage system resources.

**Comment by wxing1292** [comment]
everything is static for now:
[go worker configs](https://github.com/uber-go/cadence-client/blob/75078a95a1299fc8156ae185451ae7e0269e7d31/internal/worker.go#L59)
[go worker config default values](https://github.com/uber-go/cadence-client/blob/072e408387dc3b620a2fc35ef96f8bbe990f8a90/internal/internal_worker.go#L56)

**Comment by xiaodiannao** [comment]
Ah so the number of concurrent activity executions is static for a specific worker, I see. But wouldn't it be possible to dynamically start and stop workers (e.g. using the CLI) depending on docker swarm system resources monitoring? E.g. a simple script which polls for docker swarm memory usage and if memory is available it spins up additional Cadence workers.

**Comment by wxing1292** [comment]
The idea to dynamically increase / decrease # of coroutines / threads in go / java client lib is certainly possible, but in reality, after proper load testing (assuming that user will load test their system based on different use case), this functionality will be used less frequently.

so to sum up:
1. since this is not a high priority issue, this feature is not currently on our roadmap
2. any contribution will be welcomed

**Comment by xiaodiannao** [comment]
Alright makes sense, thanks a lot @wxing1292 I'm closing this issue
