### ISSUE TITLE
Support Postgres and others

### ISSUE THREAD

**Issue by BrendanBall** [uber/cadence#2756]
[issue 854](https://github.com/uber/cadence/issues/854) says `We should rely on general SQL interface so the actual DB implementation can be swappable.` however all the talk and existing issues very explicitly reference mysql and it seems likely that cadence will end up only supporting mysql 100% correctly. Is the plan to only officially support mysql or at least only support it until it's production ready before supporting other databases like postgres?

**Comment by meiliang86** [comment]
We are working on the Postgres integration. Currently there is no plan to support other databases.

**Comment by dimchansky** [comment]
@meiliang86 when do you plan to have it in master branch? this month/year, next year?

**Comment by dctc42** [comment]
The repo has a Postgres schema folder. Is this not officially supported? I guess I'm confused about why Postgres support is being requested when there is a Postgress folder under schema.

**Comment by sheerun** [comment]
Is postgres support beta or stable?

**Comment by mfateev** [comment]
It is not stable yet

**Comment by sheerun** [comment]
@mfateev How about mysql?

**Comment by mfateev** [comment]
MySQL is used in production my multiple users.

**Comment by ringods** [comment]
@mfateev besides issue #3086, is it clear what is whitholding the PostgreSQL support to be marked as stable and production ready? 

If so, can this info be converted to GH issues (and linked to this ticket) so this work can be started as a contribution?

**Comment by longquanzheng** [comment]
Hey everyone, I am the author of the Posgres plugin. I have fixed bugs in Postgres recently so hopefully it's getting stable. Some folks already using in production. Let me know if you hit any issues. I am more than happy to help.

**Comment by ringods** [comment]
@longquanzheng do you also contribute this fix to github.com/temporalio/temporal?

**Comment by longquanzheng** [comment]
@ringods hey I am sorry I don’t have time to contribute to forked projects. But they are both MIT licenses so welcome to merge the commits, you might need to solve some conflicts as the projects started to diverge.
