### ISSUE TITLE
Unblock transfer queue processor by writing tasks back with higher IDs

### ISSUE THREAD

**Issue by tamer-eldeeb** [uber/cadence#279]
Currently, failing to completely process one transfer task (e.g. because matching engine is down, or visibility store write is failing) would block the progress of the transfer queue processor goroutine (and, in extreme cases, causes the entire history service node to log fatal and restart).
Instead of blocking, it is better to rewrite the task back to cassandra with a higher task ID. This allows processing other tasks until the task is picked up again, and hopefully the reason for failing to process the task in the first place would be resolved by that time.

**Comment by tamer-eldeeb** [comment]
Also consider writing to a side / dead-letter queue and alert when processing repeatedly fails so that the failures can be inspected (e.g. a bug in the code prevents task from being processed)

**Comment by dmetzgar** [comment]
@wxing1292 has already implemented a DLQ as part of cross-DC.
