### ISSUE TITLE
Don't run `go generate` for every build.

### ISSUE THREAD

**Issue by alexshtin** [uber/cadence#2819]
Recently `go-generate` target was added to `Makefile` and used as prerequisite for `bins_nothrift` target which makes it run for every build. This adds extra 50 seconds (warm run) and 200 seconds (cold run) to build time on my laptop.
The `go-generate` target aims to build mocks that are already in the repo. What is the point of regenerating them before every build but not on demand?

**Comment by wxing1292** [comment]
I have made a change to only generate mocks during testing. let me know if that is good enough.

**Comment by mfateev** [comment]
50-200 additional seconds for each test run sounds excessive.

**Comment by wxing1292** [comment]
are you referring to buildkite tests or local `make test`?
local make test will only run that onces

**Comment by alexshtin** [comment]
Once per every `make test` run. I still don't understand why do you want to regenerate them automatically. Running something like `make mocks` manually every time when mocks needs to be regenerated makes more sense to me.

**Comment by wxing1292** [comment]
i agree that go generate mocks is slow, the reason to make it as a dependency of test is to make sure mocks are up to date.

i will create a new target `release` which depends on `go-generate` and `test` then.

**Comment by wxing1292** [comment]
changes landed FYI
