### ISSUE TITLE
Decision stickiness timeout get overridden by startToCloseTimeout

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#2849]
Saw the following history reported by someone on slack channel with seems to suggest stickiness timeout is getting overriden by decision start to close timeout.  This results in unnecessary delay for the execution if worker restarts.

```
{
        "eventId": 7,
        "timestamp": 1574260217237103760,
        "eventType": "DecisionTaskScheduled",
        "version": -24,
        "taskId": 46137794,
        "decisionTaskScheduledEventAttributes": {
            "taskList": {
                "name": "ms-insurance-contract-2-s88rj:b5610a78-e3cc-48fc-8f6f-fe739912cf66"
            },
            "startToCloseTimeoutSeconds": 60,
            "attempt": 0
        }
    },
    {
        "eventId": 8,
        "timestamp": 1574260231686748206,
        "eventType": "ChildWorkflowExecutionCompleted",
        "version": -24,
        "taskId": 47185920,
        "childWorkflowExecutionCompletedEventAttributes": {
            "result": "eyJpbnN1cmFuY2VDb250cmFjdCI6bnVsbCwibXV0YXRlZEluc3VyYW5jZUNvbnRyYWN0cyI6bnVsbCwiY29tcGVuc2F0aW9uIjpudWxsLCJ2YWxpZGF0aW9uUmVwb3J0Ijp7Im1pc21hdGNoZXMiOltdfSwia2luZCI6bnVsbCwicHJvZHVjdCI6bnVsbCwiY29udHJhY3RJZCI6bnVsbCwiYWRkZW5kdW1JZCI6bnVsbCwidGVybWluYXRpb25JZCI6bnVsbCwicmVxdWVzdElkIjpudWxsLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6e319",
            "domain": "sample2",
            "workflowExecution": {
                "workflowId": "734fd806-3f2d-31d3-bde8-82c4778b902f",
                "runId": "0250493c-0bc6-48f3-b4f7-f68987b66716"
            },
            "workflowType": {
                "name": "ProcessPropertyContractWorkflow::process"
            },
            "initiatedEventId": 5,
            "startedEventId": 6
        }
    },
    {
        "eventId": 9,
        "timestamp": 1574260277165142453,
        "eventType": "DecisionTaskTimedOut",
        "version": -24,
        "taskId": 47185922,
        "decisionTaskTimedOutEventAttributes": {
            "scheduledEventId": 7,
            "startedEventId": 0,
            "timeoutType": "SCHEDULE_TO_START"
        }
    },
    {
        "eventId": 10,
        "timestamp": 1574260277165153472,
        "eventType": "DecisionTaskScheduled",
        "version": -24,
        "taskId": 47185923,
        "decisionTaskScheduledEventAttributes": {
            "taskList": {
                "name": "INSURANCE_CONTRACT_MAIN"
            },
            "startToCloseTimeoutSeconds": 60,
            "attempt": 0
        }
    },
    {
        "eventId": 11,
        "timestamp": 1574260277169433769,
        "eventType": "DecisionTaskStarted",
        "version": -24,
        "taskId": 47185926,
        "decisionTaskStartedEventAttributes": {
            "scheduledEventId": 10,
            "identity": "1@ms-insurance-contract-2-s88rj",
            "requestId": "9c9dbdc7-51e9-4c3a-aa1d-2e5a6a95e5ed"
        }
    },
    {
        "eventId": 12,
        "timestamp": 1574260278810656785,
        "eventType": "DecisionTaskCompleted",
        "version": -24,
        "taskId": 47185929,
        "decisionTaskCompletedEventAttributes": {
            "scheduledEventId": 10,
            "startedEventId": 11,
            "identity": "1@ms-insurance-contract-2-s88rj"
        }
    },
```

**Comment by szaluzhskiy** [comment]
The version of Cadence server used on environment is v0.9.5 Release

**Comment by szaluzhskiy** [comment]
One notice on other support channel is that WorkflowClient.start should be used instead of WorkflowClient.execute. Can this point potentially resolve situation?

**Comment by samarabbas** [comment]
@szaluzhskiy I don't think start vs execute would make a difference.  Start is asynchronous API to start workflow execution and immediately returns back with a RunId.  Execute is synchronous API which starts a workflow and waits for it to complete before returning back. 
First can you confirm that your pods are restarting or overloaded, which might result in DecisionTimeout and workflow execution to be moved to a different host.  While we investigate why sticky timeout is getting overridden with StartToClose timeout, I would also suggest to set a smaller value for DecisionTaskTimeout when starting your workflow execution (10s or 5s).

**Comment by szaluzhskiy** [comment]
@samarabbas I need some time to reproduce this case and fix if pods are really overloaded and restarted. I'll back asap here

**Comment by samarabbas** [comment]
Just a quick update.  I tried to repro this  locally to see if stickiness timer kicks in after 5 seconds when the decision timeout is 60 seconds and it worked as expected.  So at this point I'm not sure what is the trigger which caused 5 seconds sticky timeout to not kick in for that particular execution.

@szaluzhskiy it will be great if you can provide more instructions on how to reproduce this?

**Comment by mfateev** [comment]
It would be nice if the service included into the event the time the timer (or timeout) had to fire at and that it was delayed due to some internal service factors (like being busy or down).

**Comment by samarabbas** [comment]
It would be nice feature, but I don't think it is the service delay in this case.  The timeout happens exactly after 1 minute which is the DecisionStartToClose timeout.

**Comment by szaluzhskiy** [comment]
At the moment I'm still in progress of root cause analysis, just have intermediate observation.
During DecisionTaskTimeouted in client(worker) logs next errors:

 - Caused by: com.uber.cadence.EntityNotExistsError: Decision task not found.
- ErrorResponse id=4768 errorType=Timeout message=call to procedure "HistoryService::StartWorkflowExecution" of service "cadence-history" from caller "cadence-frontend" timed out after 998.873868ms
- ErrorResponse id=21977 errorType=Timeout message=call to procedure "HistoryService::RespondDecisionTaskCompleted" of service "cadence-history" from caller "cadence-frontend" timed out after 998.914984ms
