### ISSUE TITLE
Fix NameExec for bulk insert in Postgres library(sqlx) 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#2863]
In sqlx, with NameExec, if there are more than one records to insert, we will see errors like:
```
InternalServiceError{Message: applyTasks failed. Failed to create replication tasks. Error: InternalServiceError{Message: createReplicationTasks failed. Error: pq: got 12 parameters but the statement requires 4}}
          
```

This is because of a bug in sqlx library that it doesn't handle the **$X** correctly when expanding the query template into real SQL.

For example, for 3 records,
It should be 
```
INSERT INTO ... $1,$2,$3,$4),($5,$6,$7,$8),($9,$10,$11,$12)
```
Instead of 
```
INSERT INTO ... $1,$2,$3,$4),($1,$2,$3,$4),($1,$2,$3,$4)
```

**Comment by longquanzheng** [comment]
https://github.com/longquanzheng/sqlx/commit/9400aeba572ddb3f41494b4553d91fa4a0dc33c4

**Comment by longquanzheng** [comment]
This still needs work. This is an open issue in the PR that I found but not solved yet.

**Comment by joeandaverde** [comment]
I submitted a PR to sqlx that should resolve this issue: https://github.com/jmoiron/sqlx/pull/579
