### ISSUE TITLE
Race condition in server start up logic

### ISSUE THREAD

**Issue by yycptt** [uber/cadence#2874]
Currently all services uses the same dataStore map 

When service starts up, it will modify the maxQPS field of the dataStore and use the modified value to create a persistence factory. This introduces a race condition on the maxQPS field.

To fix it, we need to make a deep copy of persistence config for each service so that services won't affect each other.

**Comment by luowenking1** [comment]
The issue was addressed by the pr https://github.com/uber/cadence/pull/3062
