### ISSUE TITLE
Go client: Deprecate or Change workflow.Register to require workflow name

### ISSUE THREAD

**Issue by vkuzmin-uber** [uber/cadence#2891]
Simple registration method in Go workflow.Register(<WorkflowFunction>) doesn't require name and become a "default" choice of users. I see that Cadence actually still use name but generates it using related path to function from GOPATH.
Today I observed the project where after refactoring, it got "orphan" workflows and Cadence worker reported periodically error:
"error: unable to find workflow type: code.internal/data/jobs/workflow.MonitorResourceWorkflow. Supported types: ["code.internal/data/jobs/cadence.MonitorResourceWorkflow"]

This error was not critical and this is why it took month to realize it. It seems that domain expiration time doesn't affect "orphan" workflows.

I suggest one of the option:
- Deprecated simple workflow.Register and recommend to use workflow. RegisterWithOptions instead that requires name (and make name required if it's not yet)
- or change workflow.Register to require second param that is a custom name of workflow.

Apart from flexibility in refactoring, it gives clearer point that client/frontend part doesn't require Workflows function but name only really and only worker needs it.

With more adoption of Cadence in a world this problem will become more critical and this is why I recommend to change it before it hurts more customers.

**Comment by mfateev** [comment]
Another option is to with Java approach of not using the whole path for name. For example Java uses ShortClassName::methodName. So if the class is moved to another package the workflow name doesn't change. In go we could use the workflow function  name.
So in the above example it would be MonitorResourceWorkflow.

BTW the user must alarm on the decision task failures which are always indication of a serious problem.

**Comment by vkuzmin-uber** [comment]
> Another option is to go with Java approach of not using the whole path for name. For example Java uses ShortClassName::methodName. So if the class is moved to another package the workflow name doesn't change. In go we could use the workflow function name.
> So in the above example it would be MonitorResourceWorkflow.
> 
If Java using it already, it can be good solution. Note that in my example, user changed package name and this is why I'd recommend to not use package.FunctionName but FunctionName may have collision with higher probability.

Also in this case Cadence needs somehow to make this change seamless and convert long names to short names of existing workflows or use short names for new workflows only and still allow long names for "old" workflow.  

> BTW the user must alarm on the decision task failures which are always indication of a serious problem.
Agree, but error in log was missed and client and workers worked fine for new workflows and this is why upgrade was treated as successful.

**Comment by mfateev** [comment]
Failing decision tasks are always retried. So in their case the decision failure metric was always non zero. It should be a very BIG red flag. So missing logs during upgrade is not an excuse.

**Comment by meiliang86** [comment]
Moved to client repo.
