### ISSUE TITLE
Code to be deprecated

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence#2917]
After 2DC is fully deprecated, remove the following files / lines:
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/historyEngine.go#L1045-L1054
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/historyEngine.go#L2265-L2275
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/historyReplicator.go
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/historyReplicator_test.go
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableState.go#L140
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableState.go#L212-L213
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L109
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L217-L232
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L259-L260
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L283
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L357-L359
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L3882
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L3960
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L4180-L4189
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L4221-L4223
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L451-L455
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L494-L496
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L507-L510
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L529-L531
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L548-L557
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L559-L582
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/stateBuilder.go#L111-L116
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/stateBuilder.go#L186-L189
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/workflowResetor.go
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/workflowResetor_mock.go
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/workflowResetor_test.go
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/workflowExecutionContext.go#L116-L129
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/workflowExecutionContext.go#L961-L1138

Change the following lines:
https://github.com/uber/cadence/blob/9ecec8e62d06306fcb2c11747fbe930547d4436d/service/history/mutableStateBuilder.go#L4240
```go
return (e.GetReplicationState() != nil || e.GetVersionHistories() != nil) &&
		e.domainEntry.GetReplicationPolicy() == cache.ReplicationPolicyMultiCluster
```

to 

```go
return e.domainEntry.GetReplicationPolicy() == cache.ReplicationPolicyMultiCluster
```

**Comment by yux0** [comment]
Those are clean up
