### ISSUE TITLE
Get rid of Cassandra Map for data resurrection 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#2921]
Today we are seeing more resurrection issues in Prod cluster, the items we deleted in timerMap and activityMap can be resurrected back and causing mutableState corrupted. 

As we have moved events into eventCache, it's not big problem anymore if we put the maps into mutableState record. 

The only concern is that every activity heartbeat will be updating the whole mutableState record instead of one item in the map. But this should be fine because it is not common use case that user would do heartbeating for many activities -- if so, we could furthur optimize it by batching the heartbeating.  On the other hand, this will solve the tombstone issues for our activtyMap and timerMap.

**Comment by demirkayaender** [comment]
Cassandra resurrection issues are solved with Cassandra v4 and Cadence v1+
