### ISSUE TITLE
Anti-pattern: Sending signals to self in local activities and close workflow(Failed/Complete/Cancel/ContinueAsNew) 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#2934]
consider a workflow example like this:
```
SampleWorkflow(ctx workflow.Context) error{
    ...
    err := executeLocalActivity(activityToSendSignalToSelf).Get(nil)
    if err != nil{
        return err
    }
    err := executeLocalActivity(activityBToValidateStatus).Get(nil)
    if err != nil{
        return err
    }
    ...
}
```
Note that activityToSendSignalToSelf is sending a signal to itself, mostly will succeed with Cadence high availability.
*activityBToValidateStatus* is to do some validation with external calls.

If the service that activityB is calling is unavailable, then the workflow will run into a infinite loop:

* 1. Cadence server schedule a decision
* 2. Worker started a decision, then trigger activityToSendSignalToSelf, because there is a decision in flight(in process), the received signal has to be saved into buffered events (). 
* 3. Worker then started activityBToValidateStatus, but failed, so workflow attempts to return an error as workflow result --> internally, this means worker tries to ResponDecisionTaskCompleted with WorkflowFailed decision. 
* 4. When Cadence server process this ResponDecisionTaskCompleted, it becomes DecisionTaskFailed because there is a buffered events (https://github.com/uber/cadence/blob/bb555046fdf0ae14316b1928ffdabdb8d47675dc/service/history/decisionTaskHandler.go#L402 ). So it records DecisionTaskFailed and then schedule a next decision. Then it start to do 1. again.

The above loop only get break only the external service becomes available back. If activityBToValidateStatus keeps returning error, this loop will keep going on and consume lots of resources for Cadence server and customer workers. 

The same will apply if activityA and activityB are one single activity. 
The same loop will also happen if the decision after signal self tries to Complete/Cancel/ContinueAsNew. But failing is the most common case because the code looks more natural. 

Here are several ways to fix it:
* a). Not using local activity to send signal to self -- use regular activity instead
* b). Not closing workflow in the same decision after sending signal to self -- not returning to workflow function(any error or not error).
* c). Revert the order of activityA and activityB -- always send signal to self as the very last step. It's sometimes hard to guarantee because you may not know where is the decision boundary.
* d). If possible, put an identifier in requstedID in send signal request.  this would dedup the signal so that even local activity is triggered again, it won't send another signal and being put into buffer. 
By default the requestedID is filled by client with random UUID, so there is not dedup for each decision.

<del>Also to mitigate, use this config https://github.com/uber/cadence/blob/master/service/history/service.go#L128  to limit the number of signals that a workflow execution can receive.</del>

Step back, mostly the reason that customers want to send signal to self is because signal is immutable and never lost even in case of workflow reset and XDC replication. 
Ideally, Cadence should support signal self as part of a decision, instead of letting customers using an activity to send signal -- this will not only prevent this issue, but also improve the performance and coding experience of using Cadence: https://github.com/uber/cadence/issues/2935

**Comment by mfateev** [comment]
Signal to self is logically the same thing as a marker. We need to fix the XDC logic to reapply certain markers the same way we reapply signals.

**Comment by longquanzheng** [comment]
related to https://github.com/uber/cadence/pull/3715

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence/pull/3776 this PR will protect workflows from getting terminated
