### ISSUE TITLE
BindOnIP: 0.0.0.0 does not work with multi host cluster setup

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#2942]
If history service host is started with the following config:
```
history:
    rpc:
      port: 7934
      bindOnIP: 0.0.0.0
```

It results in Host Identity to be set as  the following:
```
"address":"[::]:7934"
```

Which means all history host in the ring will end up with same identity.  This causes atleast 2 issues with rest of the stack (There may be more):

1. ShardController logic relies on Identity of the host to acquire shards.  Now all hosts will have the same Identity.
2. Client routing also relies on Identity to route requests to history hosts.  This also causes all routing logic to not work at all.

Probably a much better solution is to have ringpop use something else for identity rather than ip:port.   Ringpop provides an interface where you can override identity.  Ringpop.New takes Identity as an option which could be used override Identity instead of using "host:port".

**Comment by sagikazarmark** [comment]
In a multi-host environment hostname has a chance of being unique, but I wouldn't mind a config option for this either.

**Comment by taylanisikdemir** [comment]
There's a broadcast address config now. It can be used to give unique identities to service instances. https://github.com/cadence-workflow/cadence/pull/6288
