### ISSUE TITLE
Terminating CRON schedule

### ISSUE THREAD

**Issue by michaldul** [uber/cadence#2948]
There is some information on https://cadenceworkflow.io/docs/07_goclient/16_distributed_cron how to enable a CRON schedule, but I haven't found anything about disabling a schedule.

Is there any documentation on this?

**Comment by mfateev** [comment]
Call cancel or terminate on the workflow to disable the cron workflow. It can be done through CLI as `cadence -do <domain> workflow [cancel|terminate] --wid <workflowID>` or through service client.

BTW you can use https://stackoverflow.com/questions/tagged/cadence-workflow to ask Cadence related questions.
