### ISSUE TITLE
Activity dispatching optimization

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence#2965]
Currently, when client does respond decision task completed and schedule 100 activities, each activity will have corresponding transfer task, and matching service will serve each task to worker.

We can do some optimization on worker & server to reduce unnecessary task dispatching.
1. worker, when responding decision task completed, can optionally provide how many activity task it can handle (in the same request)
2. server, when seeing the above request, can start some activity directly, i.e. bypassing the generation of activity transfer task & push to matching & client long poll for task
3. server will return the activity started to client in the respond decision task completed response.

**Comment by mfateev** [comment]
Good idea. 
I would simplify it even further. Add "started" flag to ScheduleActivityTask decision. Then no reply (besides respond decision task completion success) is needed.

**Comment by wxing1292** [comment]
one more thing that can possibly be done:

1. worker, when responding decision task completed, can optionally provide how many activity task it can handle (in the same request)
2. server, when seeing the above request, can start some activity directly, i.e. bypassing the generation of activity transfer task & push to matching & client long poll for task
3. before writing the remaining un-started activity (activity with retry policy only, since these are at least once execution) task to db, try pushing these task to matching service for sync match (e.g. wait for 1 to 2 second), if sync matching is a success, the corresponding transfer task can be omitted.
4. server will return the decision task completed response.
