### ISSUE TITLE
Cadence documentation typo

### ISSUE THREAD

**Issue by AndrewPanov** [uber/cadence#2981]
[Here](https://cadenceworkflow.io/docs/06_javaclient/01_quick_start) under 

> No Hello printed.

It is `> docker docker run ...` now, but it's likely `> docker run ...`

I hadn't found where to push merge request with correct version, so I've opened issue. Sorry for any inconvenience it may cause.

**Comment by just-at-uber** [comment]
Hi @AndrewPanov ,

I've addressed the typo in this PR here: https://github.com/uber/cadence/pull/3031

Thanks
