### ISSUE TITLE
[QUESTION] Is there a way to query cron schedule?

### ISSUE THREAD

**Issue by crux-ymironoff** [uber/cadence#2985]
Hi, I can submit recurring cron style requests, but I cannot seem to find a way to query cron schedule. Workflow descriptions only display the next scheduled execution time not the actual schedule. Is there a way to do this via cli or programmatically?

**Comment by mfateev** [comment]
The cron is part of the WorkflowExecutionStarted event which is always the first event in the history. You can get it through CLI:

`cadence -do <domain> workflow show --wid <workflowID> -eid 1`
