### ISSUE TITLE
Unable to create SQL connection on master branch

### ISSUE THREAD

**Issue by kewu21** [uber/cadence#2989]
Detail error is "Unknown system variable 'transaction_isolation' "

I can confirm that 
```
connectAttributes:
    tx_isolation: 'READ-COMMITTED'
```
is correctly generated as part of config/docker.yaml, but still got the error. Suspect `plugin/mysql/` got some unexpected changes that make the setting above not respected.

**Comment by meiliang86** [comment]
I assume this is fixed. Fell free to reopen if the issue still persists and we will investigate.
