### ISSUE TITLE
Add flag in domain metadata to allow auto-failover

### ISSUE THREAD

**Issue by meiliang86** [uber/cadence#3013]
This is to allow Cadence to exercise failover on behalf of the customer/domain owner.
If this is enrolled, Cadence will do failover on behalf of the user with some preset schedule (which can be config/dynamic config). This will need to work with ignore LISA = true.

If customer set ignore lisa = false then this will be opted out and value from LISA is honored.

**Comment by vancexu** [comment]
This should be transparent to open source community, since we use DomainData.

Closed as no work.
