### ISSUE TITLE
Cassandra SSL in official 0.10.4 release?

### ISSUE THREAD

**Issue by Grindiron** [uber/cadence#3025]
Hi Cadence developers 👋,

Do you have a rough eta for when Cadence server 0.10.4 is to be released? Moreover will this release include the Cassandra SSL feature merged back in November? (see: #2769 )

**Comment by meiliang86** [comment]
Yes it should be in a few days. There's a regression that we are working on to fix and that's the release blocker.

**Comment by Grindiron** [comment]
Thanks for the prompt response @meiliang86. Closing out "issue" as my query has now been answered.
