### ISSUE TITLE
noisy error logging

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#305]
Seeing this error a lot which is pretty noisy. We might want to suppress this error if we think this could happen in normal case and does not indicate an error (for example during handling the timeout task while the workflow execution is already completed):
time="2017-08-08T14:04:50-07:00" level=error msg="helpers.go:38 Persistent store operation failure. Operation Details: " Service=cadence-history deployment-name= execution-id="a8df7e9f-0dc3-45f3-a3da-1be0c67619a9_9971" run-id=445ea712-075b-4945-a235-77e1a4c80f13 shard-id=1 store-operation=get-wf-execution wf-component=history-cache wf-error="EntityNotExistsError({Message:Workflow execution not found.  WorkflowId: a8df7e9f-0dc3-45f3-a3da-1be0c67619a9_9971, RunId: 445ea712-075b-4945-a235-77e1a4c80f13})" wf-event-id=2010

**Comment by samarabbas** [comment]
Duplicate #313
