### ISSUE TITLE
FrontEnd: DescribeDomain needs request nil check 

### ISSUE THREAD

**Issue by sivakku** [uber/cadence#306]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbb27ba]

goroutine 112407350 [running]:
code.uber.internal/devexp/cadence-server/vendor/github.com/uber/cadence/service/frontend.(*WorkflowHandler).DescribeDomain(0xc420bf0180, 0x7f9ecedb6210, 0xc42935b3d0, 0x0, 0x0, 0x0, 0x0)
	code.uber.internal/devexp/cadence-server/vendor/github.com/uber/cadence/service/frontend/handler.go:182 +0xfa
code.uber.internal/devexp/cadence-server/vendor/github.com/uber/cadence/.gen/go/cadence.(*tchanWorkflowServiceServer).handleDescribeDomain(0xc4205cdcc0, 0x7f9ecedb6210, 0xc42935b3d0, 0x138b120, 0xc470e650e0, 0x13a9fa0, 0xc4259168b0, 0x1385aa0, 0xc93400, 0xc434909220)
	code.uber.internal/devexp/cadence-server/vendor/github.com/uber/cadence/.gen/go/cadence/tchan-cadence.go:621 +0x113
code.uber.internal/devexp/cadence-server/vendor/github.com/uber/cadence/.gen/go/cadence.(*tchanWorkflowServiceServer).Handle(0xc4205cdcc0, 0x7f9ecedb6210, 0xc42935b3d0, 0xc4634eb671, 0xe, 0x138b120, 0xc470e650e0, 0xc4434c98c0, 0x1f, 0xe207ba, ...)
	code.uber.internal/devexp/cadence-server/vendor/github.com/uber/cadence/.gen/go/cadence/tchan-cadence.go:536 +0x221
code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go/thrift.(*Server).handle(0xc4203665a0, 0x7f9ecedb6190, 0xc4434c9680, 0x137f280, 0xc4205cdcc0, 0x0, 0xc4634eb671, 0xe, 0xc49bb03b00, 0x0, ...)
	code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go/thrift/server.go:139 +0x32a
code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go/thrift.(*Server).Handle(0xc4203665a0, 0x7f9ecedb6190, 0xc4434c9680, 0xc49bb03b00)
	code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go/thrift/server.go:213 +0x1a7
code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go.(*handlerMap).Handle(0xc420da18c0, 0x7f9ecedb6190, 0xc4434c9680, 0xc49bb03b00)
	code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go/handlers.go:118 +0xf2
code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go.channelHandler.Handle(0xc4203fa600, 0x7f9ecedb6190, 0xc4434c9680, 0xc49bb03b00)
	code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go/handlers.go:126 +0x96
code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go.(*Connection).dispatchInbound(0xc4bf931200, 0x20000247d, 0xc49bb03b00, 0xc4b8f0c240)
	code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go/inbound.go:195 +0x3c5
created by code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go.(*Connection).handleCallReq
	code.uber.internal/devexp/cadence-server/vendor/github.com/uber/tchannel-go/inbound.go:131 +0x1370

**Comment by vancexu** [comment]
Closed this, and Create more generous issue: https://github.com/uber/cadence/issues/581
