### ISSUE TITLE
Proposal: Add cassandra username and password config values to docker/config_template.yaml

### ISSUE THREAD

**Issue by kfoxb** [uber/cadence#3063]
We're currently overwriting the config_template in our own docker image, but we wouldn't have to do this if these keys were in the config_template.yaml file.

Here's what I propose the keys should look like:
user: {{ default .Env.CASSANDRA_USER "" }}
password: {{ default .Env.CASSANDRA_PASSWORD "" }}

It looks like in this pull request https://github.com/uber/cadence/pull/299/files#diff-ba4cd460bd2d61f93b2b4bc4f8750faa we're already looking for these values and only adding authentication when they're set so this shouldn't affect other users that are not using authentication.

**Comment by nhernandez2** [comment]
Also consider the change in **start.sh** that makes the connection to the database.

`cqlsh -u $CASSANDRA_USER -p $CASSANDRA_PASSWORD --cqlversion=3.4.4 $server`

**Comment by longquanzheng** [comment]
@kfoxb @nhernandez2 PR is out. Feel free to give some comments :D

**Comment by kfoxb** [comment]
@longquanzheng Our company has switched to using Temporal actually since I opened this, so I probably won't be able to test it. It is exactly what I was looking for though, thank you for implementing it.

**Comment by nhernandez2** [comment]
@kfoxb Temporal already implement it? I also added a ticket for this. https://github.com/temporalio/temporal/issues/513

**Comment by longquanzheng** [comment]
It's merged in master and will be included in the coming release.
