### ISSUE TITLE
Support search attributes in SQL persistence

### ISSUE THREAD

**Issue by sagikazarmark** [uber/cadence#3074]
For low-throughput scenarios adding Elastic as a requirement is an overkill.

Please add support for search attributes when using SQL persistence.

**Comment by sheerun** [comment]
Is it currently possible to use both SQL persistence and Elasticsearch for indexing?

**Comment by meiliang86** [comment]
@sheerun Yes. You can use SQL persistence with ES for visibility.

**Comment by sheerun** [comment]
I cannot figure out the configuration needed
