### ISSUE TITLE
Workflow Worker out of memory

### ISSUE THREAD

**Issue by elyashivlavi** [uber/cadence#3075]
In our system we have workflows that runs for a week or more (waiting on signals/timers).
We have around 32K such active workflows.
It seems like all the workflows are live in the workflow workers, which eventually led to High memory consumption and worker crashes.
The workflows recovered successfully, but I wonder if there is any way to overcome this issue - is there a way to tell the workflow worker to "release" a workflow once it's in select statement, or anything similar that will assist the memory consumption?

**Comment by mfateev** [comment]
Use worker.SetStickyWorkflowCacheSize to reduce the cache size.

**Comment by elyashivlavi** [comment]
Works like a charm. Thanks!
