### ISSUE TITLE
Error "unable to decode argument" if return nil in local activity

### ISSUE THREAD

**Issue by olegmedvedev** [uber/cadence#3083]
Not possible to make LocalActivity that returns nil in result. Workflow fails with
```
  "reason": "cadenceInternal:Generic",
  "details": "unable to decode argument: 0, **struct {}, with json error: EOF",
```

I've made a sample to demonstrate this problem:
https://github.com/olegmedvedev/cadence-local-activity-sample

**Comment by meiliang86** [comment]
Moved to https://github.com/uber-go/cadence-client/issues/943
