### ISSUE TITLE
postgresql: stuck on waiting for "completed" child-workflows

### ISSUE THREAD

**Issue by Gurpartap** [uber/cadence#3086]
Currently, a bit of a showstopper for postgresql [integration](https://github.com/uber/cadence/issues/2756) when using child workflows.

Some workflows get stuck on waiting for child-workflows to finish. Even when the child-workflows have been marked completed, the parent doesn't produce a ChildWorkflowExecutionCompleted event.

Reproducible by restarting workers mid-execution.

Using postgresql-11. All in a single task list.

**Comment by Gurpartap** [comment]
- https://uber-cadence.slack.com/archives/CL22WDF70/p1577738091115100
- https://uber-cadence.slack.com/archives/CL22WDF70/p1582935913171700

**Comment by Gurpartap** [comment]
Given that a workflow waiting on child-workflows [can't be reset](https://github.com/uber/cadence/issues/2951), terminating and restarting the workflows is, perhaps, the only recourse.

**Comment by longquanzheng** [comment]
Is it related to this? https://github.com/uber/cadence/pull/3484
If yes then it should be fixed. 
I am the author of this postgres plugin, Let me know if you have any issue. Willy to help!

**Comment by meiliang86** [comment]
Closing this for now. @Gurpartap let us know if you see further issue.
