### ISSUE TITLE
WorkflowTypeFilter

### ISSUE THREAD

**Issue by xiaodiannao** [uber/cadence#3092]
Hi everyone,
I'm trying to list workflows using the ListClosedWorkflows and ListOpenWorkflows functions, and I was wondering what the `WorkflowTypeFilter` does exactly?
Best regards

**Comment by yycptt** [comment]
WorkflowType basically means the name of the workflow. 

When you register your workflow, you can optionally specify a name. This name becomes its WorkflowType. If you do not specify the name, then the full path to that workflow function will be used as the name and WorkflowType.
