### ISSUE TITLE
CLI: list-partition is broken

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#3093]
The "cadence tasklist list-partition" is broken as it doesn't accept, but expects the task list flag.
[Looking at the code](https://github.com/uber/cadence/blob/f4648ae27430a5f27043a6e9503e6818cf2e0dd0/tools/cli/taskList.go#L25) we see that the flag is indeed missing.

**Comment by yycptt** [comment]
Seems like this is fixed by https://github.com/uber/cadence/pull/3094
