### ISSUE TITLE
build: integrate with fossa for licensing analysis

### ISSUE THREAD

**Issue by venkat1109** [uber/cadence#3103]
Documentation

https://github.com/fossas/fossa-cli
https://github.com/fossas/fossa-cli/ https://github.com/fossas/fossa-cli/blob/master/docs/integrations/golang.md#go 

Example:
https://github.com/uber/prototool/blob/dev/.buildkite/pipeline.yml

**Comment by meiliang86** [comment]
Example of makefile change: https://github.com/uber/prototool/blob/9d0c231bf5ef7f5b709967d56503ca3f6729cf3d/Makefile

**Comment by ivar51dub** [comment]
Hi folks,

looks like you've got most of the docs posted here, but I'll re-post + add:

Example PR from Uber Protocol project: https://github.com/uber/prototool/pull/448/commits/9d0c231bf5ef7f5b709967d56503ca3f6729cf3d

Integration docs: https://github.com/fossas/fossa-cli/

Specific parameters for GO: https://github.com/fossas/fossa-cli/blob/master/docs/integrations/golang.md#go

prototool github repo: https://github.com/uber/prototool
prototool buildkite yaml file: https://github.com/uber/prototool/blob/dev/.buildkite/pipeline.yml
protocode makefile: https://github.com/uber/prototool/blob/dev/Makefile

Please let us know if you have any questions.

ravi
