### ISSUE TITLE
Search workflow by name & status

### ISSUE THREAD

**Issue by just-at-uber** [uber/cadence#3118]
API currently returns an error when trying to search by workflow name & workflow status. It would help users to be able to filter based on multiple filter types to reduce the search set.

<img width="1169" alt="Screen Shot 2020-03-16 at 10 39 07 AM" src="https://user-images.githubusercontent.com/58960161/76786093-d1624600-6773-11ea-8d31-9d979c54d412.png">

**Comment by demirkayaender** [comment]
This is working now.
