### ISSUE TITLE
Prometheus Metrics double define certain types, causing ingestion issues

### ISSUE THREAD

**Issue by AngerM-DD** [uber/cadence#3120]
We are seeing issues in the prometheus metrics because it appears Cadence defines the same types multiple times:
```
{"log":"time=\"2020-03-17T23:25:50Z\" level=error msg=\"reading text format failed: text format parsing error in line 2722: second HELP line for metric name \\\"signal_info\\\"\"\n","stream":"stdout","time":"2020-03-17T23:25:50.489860784Z","meta":{"env":"staging"},"kubernetes":{"pod_name":"wavefront-collector-zf6q2","namespace_name":"monitoring","container_name":"wavefront-collector","docker_id":"1b3546740c9e5b7260502a225f595615662c92b5d84e06081d35a296ddc17157"}}
```
I double checked by connecting to to the cadence pods and accessing the `/metrics` page and I can see the `singal_info` defined twice on said page.

**Comment by AngerM-DD** [comment]
To add additional info: I am seeing this in my branch recently built off of master (sha: `ee3c672a3126ef5bbbeb5ae28249d7ebf6eaf9ca`) as well as a previously built branch that was pre 0.11 (sha: `8554d88ffaea91e6b614b3dde8f1e0ce3f6efb6f`)

**Comment by wahyd4** [comment]
Hi Cadence team, we are experiencing a similar issue here which caused the issue of our metrics cannot be parsed. The error message we got from our New Relic collector is 
```
time="2020-07-14T07:11:31Z" level=warning msg="fetching Prometheus: http://10.0.0.229:9090/metrics (10.0.0.229:9090)" component=Fetcher error="text format parsing error in line 1925: second HELP line for metric name \"signal_info\""
```

The metrics content around line 1925 is

![image](https://user-images.githubusercontent.com/836576/87395861-5dd32700-c5f5-11ea-820a-7d01fb216d07.png)

And the docker images I am using for this case is the latest which just released about 4 days ago. 
```
ubercadence/server:master-auto-setup
DIGEST:sha256:fe54952afe688f9894eba136e77aff8d877b3c20736de171920f28134bbec0fd
```
