### ISSUE TITLE
API: Task list queue size

### ISSUE THREAD

**Issue by jiaxuyang** [uber/cadence#3125]
I want to get task list queue size, in order to scale the works dynamically.  Maybe in return of DescTaskList?

**Comment by mfateev** [comment]
Currently this query is not supported. Use ScheduleToStart latency metric for autoscaling.

**Comment by kaustubhmallik** [comment]
Hi @mfateev @meiliang86, I would like to take this up, if not picked by someone else already. 😄

**Comment by demirkayaender** [comment]
We added Tasklist backlog metrics late summer which should be addressing this issue. Let us know if you need help adding to your dashboards.
