### ISSUE TITLE
Makefile - go build -i flag

### ISSUE THREAD

**Issue by kaushiksriram100** [uber/cadence#3128]
Is it reasonable to get rid of `-i` flag in go build commands here ? https://github.com/uber/cadence/blob/master/Makefile#L126-L142

It generally results in a 'permission denied' error specially when system packages are being built and archived. 

`/usr/local/go/pkg/linux_amd64/net.a: permission denied`

Deployment pipelines may not have root privileges to perform the above operation. Just a thought.

**Comment by meiliang86** [comment]
@vytautas-karpavicius Can you check if this makes sense?
