### ISSUE TITLE
Testing framework does not support .Times(0) on mocks

### ISSUE THREAD

**Issue by evanfuller** [uber/cadence#3148]
I am testing a workflow where I call a few activities in sequence. If activity A fails, then the workflow should be aborted, and activity B should not be called. I have written the following test code:

```
	m.env.OnActivity(m.workflow.ActivityA, mock.Anything, mock.Anything).Return(&myStruct{}, nil)
	m.env.OnActivity(m.workflow.ActivityB, mock.Anything, mock.Anything).Times(0)
	m.env.ExecuteWorkflow(m.workflow.Start, myArg)
```

When I run this test, I get the following error from the workflow:

```
    --- FAIL: TestMyWorkflow/TestSecondActivityIsNotCalled (0.45s)
        my_test.go:60: PASS:	github.com/.../workflow.(*MyWorkflow).ActivityA-fm(string,string)
        my_test.go:60: FAIL:	github.com/.../workflow.(*MyWorkflow).ActivityB-fm(string,string)
            		at: [workflow_testsuite.go:225 my_test.go:92]
        my_test.go:60: FAIL: 1 out of 2 expectation(s) were met.
            	The code you are testing needs to make 1 more call(s).
            	at: [my_test.go:60 suite.go:126 suite.go:134]
```

Could the mocks be updated to support `.Times(0)`?

**Comment by mfateev** [comment]
I believe you want the env.[AssertNotCalled](https://godoc.org/github.com/stretchr/testify/mock#Mock.AssertNotCalled) exposed. 
As a workaround use env.SetOnActivityStartedListener interceptor to check that activity of a certain type is not called.
