### ISSUE TITLE
History: Speed up acquisition of shards on ring membership change

### ISSUE THREAD

**Issue by venkat1109** [uber/cadence#315]
Whenever the ring membership changes, the history engine re-evaluates the shards it owns and subsequently acquires new shards, releases shards no longer owned. This whole process today, is performed by a single go-routine that goes over the shards from 1..N serially, calling UpdateShard (CAS) to claim ownership of new shards.  This is not great with large number of shards, say, 16k, when the median latency of UpdateShard is in the ~100ms range i.e. When nodes go down, the history engine quickly disowns the shards, but slowly acquires new shards. This can make shards unavailable for a short period of time during node failures or deployments.

Short Term:
**Proposal: Spin up multiple shardControllers per history node**
Today, all 16k shards are handled by the same shardController, but it doesn't have to be. We can have a configurable policy, say, max of 4k shards per shardController. This will both (1) Speed up acquisition of shards (2) Reduce lock contention

**Long Term: Come up with a design for graceful shard handoff**

**Comment by demirkayaender** [comment]
This is supported for matching now and more history improvements are coming soon
