### ISSUE TITLE
newbie's cluster operational questions

### ISSUE THREAD

**Issue by xxbbxb** [uber/cadence#3151]
People hi,
After spending some time looking at this repo, and google for documentation. I've got some questions regarding cluster architecture, so please help with understanding:
1. In-cluster cadence sharding: is it done using hash? Are nodes act independently? if it is so, then how you solve conflicts caused by: "oops my node went down for a while"? (I do understand that last part may be solved on a developers side, but i'm interested from operations side how workflow will act in this situation)
2. Any guide about adding/removing nodes to cluster? All done dynamically?
3. Please advice videos or articles to check with 0 code, and business, mostly about operational/support side

Thanks in advance.

**Comment by mfateev** [comment]
1. Cadence uses two levels of hashing. The first hashes workflow ids to a fixed number of shards. Then the second hashes shards to nodes using consistent hashing. As the membership of the cluster changes the shards are moved to the healthy nodes. So if a node is down in a second all its shards are relocated to other healthy nodes. 
2. You can add and remove them any time. 
3. See https://www.youtube.com/watch?v=5M5eiNBUf4Q for more info on internal service architecture.

We don't yet have a good operational documentation.

**Comment by xxbbxb** [comment]
Good to know. Sad that i did not found this video before asking. So shard is a unit that continuously moving among cluster servers on restarts or other probable failures, every move is persisted using compare and set.
`executions` table has a partition key `shard_id` it looks as a good place to get very large rows (which is not good for cassandra), so i believe that shard number must be pretty large to avoid that. Thank you
