### ISSUE TITLE
Error updating ack level for shard when running multiple replicas

### ISSUE THREAD

**Issue by BenjaDiaz** [uber/cadence#3202]
We have set up Cadence to run on top of our Nomad orchestrator and are having the following issue in cadence-history when setting more than one replica:

```
{
    "level": "error",
    "ts": "2020-04-16T13:12:33.783Z",
    "msg": "Error updating ack level for shard",
    "service": "cadence-history",
    "shard-id": 1,
    "address": "172.17.0.6:7934",
    "component": "transfer-queue-processor",
    "cluster-name": "active",
    "error": "Failed to update shard. Previous range ID: 4216; new range ID: 4217",
    "operation-result": "OperationFailed",
    "logging-call-at": "queueAckMgr.go:219",
    "stacktrace": "github.com/uber/cadence/common/log/loggerimpl.(*loggerImpl).Error\n\t/cadence/common/log/loggerimpl/logger.go:134\ngithub.com/uber/cadence/service/history.(*queueAckMgrImpl).updateQueueAckLevel\n\t/cadence/service/history/queueAckMgr.go:219\ngithub.com/uber/cadence/service/history.(*queueProcessorBase).processorPump\n\t/cadence/service/history/queueProcessor.go:198"
}
```

Is there any configuration we might be missing? Or is there any documentation on setting Cadence up on production environments (besides the quickstart in the Cadence docker docs)?

**Comment by yux0** [comment]
This happens when there is shard movement and is expected to recover after retry.

**Comment by meiliang86** [comment]
Yeah this is because cadence uses optimistic locking and shard movement can happen. As @yux0 mentioned it is transient and nothing needs to happen from your perspective.
Let us know if you see this as a persistent issue.

**Comment by mfateev** [comment]
If this issue is not intermittent then it indicates that your hosts don't see each other. Make sure that you don't use bind 0.0.0.0 in your config. Instead bind to the host address.
