### ISSUE TITLE
Can we have an activity functions that can have callback lambda as a parameter

### ISSUE THREAD

**Issue by shawel** [uber/cadence#3211]
I have an activity that performs long running process that takes a callback to update status occasionally.  I wanted to update a workflow query method based on that stream activity. Is this possible. From my experiment activity methods do not take lambda functions and returns null. E.g 

```
@queryMethod // defined in workflow interface
String status;

workflowMain() {
// activity method is a long running activity that takes a callback to update status. 
    activity.activityMethod(callbackfunction {
         call(currentStatus) {
            status = currentStatus 
         }
    }) 
}
```
Is there an alternative to get similar data ?

Thanks

**Comment by mfateev** [comment]
There are a couple of options. 

1.  Activity sends signal to the workflow with its status updates.
2. Activity heartbeats with the status and client gets it using DescribeWorkflowExecution API.

The drawback of the (1) is that such signals increase the workflow history size. It is OK up to tens of thousands of signals, but is not a good idea if the number of updates is unbounded.

**Comment by shawel** [comment]
Ok @mfateev thanks. Option 1 could work for me. I have considered option 2. For option 1 to work you would have to introduce workflow code in to the activity correct?  I wanted to decouple the workflow methods from activity function itself. The processing function already had a callback parameter which was a neat way to report on progress without touching the class itself

**Comment by mfateev** [comment]
You can use untyped workflow stub to send signal. See WorkflowClient.[newUntypedWorkflowStub](https://github.com/uber/cadence-java-client/blob/56b5aeab1ca3cb1268d9432e40caef3bb3a9ba7d/src/main/java/com/uber/cadence/client/WorkflowClient.java#L237).

**Comment by shawel** [comment]
Ok thanks @mfateev . I will look in to it. Great work with cadence!
