### ISSUE TITLE
CLI option list task list partitions

### ISSUE THREAD

**Issue by szaluzhskiy** [uber/cadence#3223]
Hi!

Looks like some problems with new option in CLI

`/etc/cadence # cadence --ad cadence-frontend:7933 --do domain_1 tasklist lp --tl TASK_LIST_1
Error: Operation ListTaskListPartitions failed.
Error Details: code:invalid-argument message:failed to encode "thrift" response body for procedure "MatchingService::ListTaskListPartitions" of service "cadence-matching" from caller "cadence-frontend": failed to write field 0 (TStruct): failed to write field 10 (TList): invalid [0]: value is nil`

**Comment by szaluzhskiy** [comment]
Stacktrace
`
Error: Operation ListTaskListPartitions failed.
Error Details: code:invalid-argument message:failed to encode "thrift" response body for procedure "MatchingService::ListTaskListPartitions" of service "cadence-matching" from caller "cadence-frontend": failed to write field 0 (TStruct): failed to write field 10 (TList): invalid [0]: value is nil
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack(0xd, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/uber/cadence/tools/cli.printError(0x1ca49e0, 0x28, 0x2058e20, 0xc000628080)
        /cadence/tools/cli/util.go:518 +0x2ad
github.com/uber/cadence/tools/cli.ErrorAndExit(0x1ca49e0, 0x28, 0x2058e20, 0xc000628080)
        /cadence/tools/cli/util.go:529 +0x49
github.com/uber/cadence/tools/cli.ListTaskListPartitions(0xc0000f6840)
        /cadence/tools/cli/taskListCommands.go:83 +0x33f
github.com/uber/cadence/tools/cli.newTaskListCommands.func2(0xc0000f6840)
        /cadence/tools/cli/taskList.go:57 +0x2b
github.com/urfave/cli.HandleAction(0x18b2de0, 0x1d15dc0, 0xc0000f6840, 0xc0000bae00, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.Command.Run(0x1c6f7f2, 0xe, 0x0, 0x0, 0xc000389ed0, 0x1, 0x1, 0x1cc4034, 0x41, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x991
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0000e7860, 0xc0000f6580, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:379 +0x7fa
github.com/urfave/cli.Command.startApp(0x1c676f0, 0x8, 0x0, 0x0, 0xc0003fc0f0, 0x1, 0x1, 0x1c81979, 0x18, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:298 +0x817
github.com/urfave/cli.Command.Run(0x1c676f0, 0x8, 0x0, 0x0, 0xc0003fc0f0, 0x1, 0x1, 0x1c81979, 0x18, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:98 +0x11dc
github.com/urfave/cli.(*App).Run(0xc0000e7040, 0xc00003a090, 0x9, 0x9, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6ab
main.main()
        /cadence/cmd/tools/cli/main.go:33 +0x4b
`

**Comment by szaluzhskiy** [comment]
Some additional question, why I can see 1000 records of TaskListPartitionMetadata

![image](https://user-images.githubusercontent.com/3520290/80592935-f27fad00-8a28-11ea-9d04-fe35124a1999.png)

**Comment by anish531213** [comment]
Fixed in #3342
