### ISSUE TITLE
Slack invite link is no longer active

### ISSUE THREAD

**Issue by ashleyelder** [uber/cadence#3225]
This same issue [was fixed in Sept 2019](https://github.com/uber/cadence/pull/2619).

This is the slack link in the top right corner of https://cadenceworkflow.io/: 

https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTQyYjcxZDM2YTIxMTZkMzQ0NjgxYmI3OWY5ODhiOTliM2I5MzA4NTM4MjU4YzgzZDkwNGEzOTUzNTBlNDk3Yjc

**Comment by mfateev** [comment]
Updated link

https://join.slack.com/t/uber-cadence/shared_invite/zt-dvjoiacm-1U2UM4R4mMxKhaRogEx_OQ
