### ISSUE TITLE
Remove the previous execution when reset a workflow

### ISSUE THREAD

**Issue by JuanPalacios** [uber/cadence#3235]
Hello,

We would like to remove the previous failed/timeout executions when we reset a workflows, for us it is not right to have two workflows ids(businees id) with two diferent status in cassandra and ES.

Thanks

**Comment by meiliang86** [comment]
Multiple runs can happen even if you don't do reset (e.g. you do continueAsNew or do cron). So it is a valid case and you should expect to see multiple runs (but with different status).
Cadence guarantees that there's only one run that is open at any given of time.

**Comment by JuanPalacios** [comment]
Then it is imposible to manage the failed or timeout workflows because always they are to be in the same status and it is not possible to do anything, the only thing that can we do is to create new executions instead of manage the fai/timeout ones?
