### ISSUE TITLE
Feature: Allow users to complete activities by ActivityID

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#325]
Asynchronous completion of activities require users to durable store tasktoken for the activity so it can be completed asynchronously using it.
This feature is having the capability to allow users to provide their own activityIDs generated using some business identifier which can be used to complete activities using those IDs asynchronously without having the need to store tasktokens.
This introduces another failure case where we need to guarantee these IDs are unique and fail activity schedule if user tries to schedule an activity using invalid identifier.

**Comment by vancexu** [comment]
This is done as part of https://github.com/uber/cadence/pull/434
