### ISSUE TITLE
Add new ParentClosePolicy for continueAsNew

### ISSUE THREAD

**Issue by vancexu** [uber/cadence#3258]
Currently there are 3 ParentClosePolicy: Terminate, RequestCancel, Abandon.

Customer would like to have a new policy that mix Terminate and Abandon for ContinueAsNew workflow. When parent continueAsNew, use Abandon policy for child; for the rest close status, use Terminate policy.

**Comment by mfateev** [comment]
I think it is not a new policy, but an additional flag. Something like enforceOnParentContinueAsNew defaulting to false.
