### ISSUE TITLE
History Engine: Limit number of decisions in RespondDecisionTaskCompleted

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#326]
UpdateWorkflowExecution has size limitations.  We need to enforce a limit on number of decisions within RespondDecisionTaskCompleted to make sure we don't run into Cassandra size limitation issues for LWT.

**Comment by dmetzgar** [comment]
@samarabbas is this work already complete?

**Comment by dmetzgar** [comment]
Already addressed by #1897
