### ISSUE TITLE
Not able to recover workflow after worker crash

### ISSUE THREAD

**Issue by cserankur** [uber/cadence#3267]
we created a workflow that has few activities defined. While running this workflow, if the worker pod crashes, it does not resume automatically. The workflow is marked as failed. **what is the best way to handle this?** 

Below is the sample of parent workflow:
````
func ParentWorkflow(ctx workflow.Context, value interface{}) (string, error) {
	ao := workflow.ActivityOptions{
		ScheduleToCloseTimeout: time.Second * 60,
		ScheduleToStartTimeout: time.Second * 60,
		StartToCloseTimeout:    time.Second * 60,
		HeartbeatTimeout:       time.Second * 10,
		WaitForCancellation:    false,
	}
	ctx = workflow.WithActivityOptions(ctx, ao)

	var result string
	future := workflow.ExecuteActivity(ctx, Activity1, "Activity1")
	if err := future.Get(ctx, &result); err != nil {
		return "", err
	}
        // More activities removed from here

	workflow.GetLogger(ctx).Info("Done", zap.String("result", result))
	return "Workflow completed", nil
}
````
command to invoke this workflow:
````
docker run --network=host --rm ubercadence/cli:master --domain SimpleDomain workflow start --tl SimpleWorker --wt ParentWorkflow --et 180 --input 5
````

**Comment by wxing1292** [comment]
take a look at the retry policy on activity?
https://cadenceworkflow.io/docs/07_goclient/06_retries

**Comment by cserankur** [comment]
yes, we have gone through it. It focuses mainly on the retry of activities and child workflows. The workflow triggered by the command line does not get recovered. I could not find much on defining retry options using command line.

**Comment by wxing1292** [comment]
> ...if the worker pod crashes, it does not resume automatically. ...

i assume the activity may got timeout and 

> ```go
> if err := future.Get(ctx, &result); err != nil {
>    return "", err
> }
> ```

will return an err

what is the err returned?

**Comment by meiliang86** [comment]
Filed https://github.com/uber/cadence/issues/3289

**Comment by meiliang86** [comment]
Cadence supports retry option on the parent workflow. It's just not exposed through the CLI right now. Before we have #3289 you can try to start the workflow from the Cadence client and there you can specify retry options.

**Comment by cserankur** [comment]
Thanks @meiliang86. I will try that out.

**Comment by cserankur** [comment]
Sorry, I forgot to update here, the retry option with go client worked. Thanks.
