### ISSUE TITLE
apache airflow comparison

### ISSUE THREAD

**Issue by allyraza** [uber/cadence#331]
how is it different compared to apache airflow still in incubator process. I wonder what are key differences I see a lot of similarities.

**Comment by allyraza** [comment]
I have not had much time to look into cadence, but after spending some time browsing through the code I can see what you guys trying to achieve it not exactly a workflow engine in a traditional sense. You can't compare it with airflow what I see you guys trying to achieve transactional semantics with some queuing mechanism.

**Comment by samarabbas** [comment]
Can you clarify what you mean by "workflow engine in a traditional sense"?  Most of the "traditional" workflow engines expose some kind of DSL to represent long running applications.  In that sense both Cadence and AirFlow are non-traditional engines as they allow users to express their application as regular code.
Having said that, it should be pretty straightforward to expose any DSL on top of Cadence.  Here is an example which how to write a workflow definition which parses a DSL and executes steps in the provided definition:
https://github.com/samarabbas/cadence-samples/tree/master/cmd/samples/dsl

**Comment by samarabbas** [comment]
Resolving this task as I have answered the original question.  
Feel free to reactivate if you have more questions.

**Comment by nikhil-rzp660** [comment]
Hi @samarabbas , Does this comparison changes or has any more points as of March 2020?

**Comment by sw-yx** [comment]
Just tacking on some HN discussions for people who might find this in future:

- https://news.ycombinator.com/item?id=19732447
- https://news.ycombinator.com/item?id=23349507
- https://news.ycombinator.com/item?id=23844177

(i work at temporal and this github issue came up)
