### ISSUE TITLE
M3DB support

### ISSUE THREAD

**Issue by reidlai** [uber/cadence#3315]
**Is your feature request related to a problem? Please describe.**
I am now building backend tech stack based on golang.  Is there any plan to integrate cadance with M3DB instead of Cassandra?  Because Cassandra setup is too heavy compared with golang stack

**Proposed Solution**
M3DB is golang based and also maintained by Uber.  If Cadance has adaptor to allow deveoper to choose between M3DB and Cassandra, it will be great.

**Additional context**
If setting up Cassandra, zookeeper is also required.  So K8S sizing cannot be trimmed down  due to JVM heap size.

**Comment by meiliang86** [comment]
M3DB is a time series database that is not suitable for what Cadence needs. We provide MySQL and postgresSQL support out of box in additional to cassandra. See if that works for you.
