### ISSUE TITLE
Retry Policy is not propagated on continue as new

### ISSUE THREAD

**Issue by bbassingthwaite** [uber/cadence#3329]
**Describe the bug**
When starting a workflow with a RetryPolicy, if/when that workflow does a continue as new, the new workflow that starts does NOT carry across the RetryPolicy from its previous run.

**To Reproduce**
Yes

**Steps to reproduce the behavior:**
1) Start a workflow with a RetryPolicy
2) Have that workflow ContinueAsNew
3) Observe that the new workflow does not have a RetryPolicy

**Expected behavior**
I would expect the new workflow to inherit its previous workflow's RetryPolicy

**Screenshots**
N/A

**Additional context**
N/A

**Comment by yycptt** [comment]
I think the bug is at client side, the `RetryPolicy` field is not set when creating the `continueAsNew` decision. https://github.com/uber-go/cadence-client/blob/master/internal/internal_task_handlers.go#L1491
