### ISSUE TITLE
Connecting to Postgresql with SSL

### ISSUE THREAD

**Issue by rphadake** [uber/cadence#3344]
Hi, 

Does Cadence support connecting to PostgreSQL using SSL? Can you please help me point to the documentation for required config options?

Looks like there is no support:
https://github.com/uber/cadence/blob/master/common/persistence/sql/sqlplugin/postgres/plugin.go
var errTLSNotImplemented = errors.New("tls for postgres has not been implemented")

Thanks,
Ram

**Comment by longquanzheng** [comment]
Hi @rphadake ,it's completed in https://github.com/uber/cadence/pull/3488 
thanks to @nadilas 
You can try it out in the master docker image. 

@meiliang86 I think we will include that in next minor release.
