### ISSUE TITLE
Exploring Cadence For Use in our Organization

### ISSUE THREAD

**Issue by omkar1707** [uber/cadence#3348]
We are exploring cadence for having infinite running workflows. Looking for answers to below questions
- Does cadence is good in such use case?
- If yes, What will happen if one of the workflows is running from the last 6 months and it received over millions of signals and now we are redeploying the system with new features? How much time a workflow will take (for replay) after a system restart to come to the last known state?
- What will happen if two signals are trying the modify the state of data maintained by workflow?

**Comment by meiliang86** [comment]
[ContinueAsNew](https://cadenceworkflow.io/docs/go-client/continue-as-new/) is what you need to prevent your workflow from growing infinitely.
Signals will be serialized in side your workflow. (Think about the go channel experience.)
