### ISSUE TITLE
yarpc: replace test mocks with thrfitrw mocks

### ISSUE THREAD

**Issue by sivakku** [uber/cadence#339]

**Comment by sivakku** [comment]
updating on what i was thinking before: At some time, we should use the mocks that are generated by thriftrw than the ones that are generated earlier by us for history and matching client.

https://github.com/uber/cadence/tree/master/common/mocks/(HistoryClient, MatchingClient).

**Comment by dmetzgar** [comment]
Closing as won't fix.
