### ISSUE TITLE
Docker Hub latest image out-of-date

### ISSUE THREAD

**Issue by mattsleiman-discovery** [uber/cadence#3417]
**Describe the bug**
The image tagged "latest" on Docker Hub ([link](https://hub.docker.com/r/ubercadence/server/tags?page=1&name=latest)) was last updated 9 months ago. There was a release 22 days ago. I see the image tagged "latestRelease-auto-setup" was updated at that time but the "latest" image was not. Should the "latest" tag not be used?

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
Go to [here](https://hub.docker.com/r/ubercadence/server/tags?page=1&name=latest) and it shows latest was last updated 9 months ago.

**Expected behavior**
The image tagged "latest" is kept up-to-date with Cadence releases.

**Comment by vancexu** [comment]
For now, we only maintain "latestRelease-auto-setup" for each release. Please use that tag if possible.
(we don't maintain "latest" tag anymore because of multiple reason, such as confusion and it is reserved for other purpose in docker)

**Comment by mattsleiman-discovery** [comment]
Understood. Thanks for the info.
