### ISSUE TITLE
cassandra: incorrect workflow status in visibility keyspace

### ISSUE THREAD

**Issue by Gurpartap** [uber/cadence#3425]
**Describe the bug**
Cadence server fails to update visibility tables with workflow completion info.

Even though, in `cadence.executions`, the workflow `close_status` is `1` (completed), the workflow still exists in `cadence_visibility.open_executions`.

This also means the workflow is listed on `cadence listall --open` command, but `wf desc` shows `"CloseStatus": "COMPLETED"`.

Similarly, it is shown as open in the UI list, but as "Completed" when selecting it directly.

Such workflows stick around in these interfaces even past their retention period (3d).

**To Reproduce**
It is a recurring behaviour when either my cluster is under load (timeouts), or when I'm restarting/updating the workflow workers often, or perhaps a combination of the two.

I don't currently have an exact path to reproduce it.

**Expected behavior**
When a workflow completes normally, the expected behaviour is to also mark it closed in the visibility keyspace.

**Additional context**
This has been happening since I began with cadence v0.10.x and in current v0.13.x.

Perhaps visibility correctness needs additional checks and retries when the status sync fails.

I have only tried this on a 3 node cassandra cluster with about 1000 per min workflow churn.

**Comment by Gurpartap** [comment]
Don't know if this history server log entry is related or not (v0.13.0):

```json
{
  "level": "error",
  "ts": "2020-08-02T14:17:52.487Z",
  "msg": "Operation failed with internal error.",
  "service": "cadence-history",
  "error": "InternalServiceError{Message: DeleteWorkflowCurrentRow operation failed. Error: Operation timed out - received only 1 responses.}",
  "metric-scope": 9,
  "shard-id": 2,
  "logging-call-at": "persistenceMetricClients.go:556",
  "stacktrace": "github.com/uber/cadence/common/log/loggerimpl.(*loggerImpl).Error\n\t/cadence/common/log/loggerimpl/logger.go:134\ngithub.com/uber/cadence/common/persistence.(*workflowExecutionPersistenceClient).updateErrorMetric\n\t/cadence/common/persistence/persistenceMetricClients.go:556\ngithub.com/uber/cadence/common/persistence.(*workflowExecutionPersistenceClient).DeleteCurrentWorkflowExecution\n\t/cadence/common/persistence/persistenceMetricClients.go:313\ngithub.com/uber/cadence/service/history/task.(*timerTaskExecutorBase).deleteCurrentWorkflowExecution.func1\n\t/cadence/service/history/task/timer_task_executor_base.go:230\ngithub.com/uber/cadence/common/backoff.Retry\n\t/cadence/common/backoff/retry.go:99\ngithub.com/uber/cadence/service/history/task.(*timerTaskExecutorBase).deleteCurrentWorkflowExecution\n\t/cadence/service/history/task/timer_task_executor_base.go:236\ngithub.com/uber/cadence/service/history/task.(*timerTaskExecutorBase).deleteWorkflow\n\t/cadence/service/history/task/timer_task_executor_base.go:123\ngithub.com/uber/cadence/service/history/task.(*timerTaskExecutorBase).executeDeleteHistoryEventTask\n\t/cadence/service/history/task/timer_task_executor_base.go:114\ngithub.com/uber/cadence/service/history/task.(*timerActiveTaskExecutor).Execute\n\t/cadence/service/history/task/timer_active_task_executor.go:98\ngithub.com/uber/cadence/service/history.(*timerQueueActiveProcessorImpl).process\n\t/cadence/service/history/timerQueueActiveProcessor.go:262\ngithub.com/uber/cadence/service/history.(*taskProcessor).processTaskOnce\n\t/cadence/service/history/taskProcessor.go:253\ngithub.com/uber/cadence/service/history.(*taskProcessor).processTaskAndAck.func1\n\t/cadence/service/history/taskProcessor.go:206\ngithub.com/uber/cadence/common/backoff.Retry\n\t/cadence/common/backoff/retry.go:99\ngithub.com/uber/cadence/service/history.(*taskProcessor).processTaskAndAck\n\t/cadence/service/history/taskProcessor.go:233\ngithub.com/uber/cadence/service/history.(*taskProcessor).taskWorker\n\t/cadence/service/history/taskProcessor.go:156"
}
```

**Comment by Gurpartap** [comment]
Post the 3d retention period, cadence took care of deleting them from `cadence` keyspace. However, I had to delete the "forgotten" rows from `cadence_visibility.open_executions` manually.

**Comment by Gurpartap** [comment]
Could this have anything do with a botched canary deploy? Result of a non-deterministic version update?

Say there are 5 instances of workerv2 running (at `workflow version 2`). Then…

```go
version := workflow.GetVersion(ctx, "test", workflow.DefaultVersion, 3)

// do A

if version == 3 {
    // do B
}
```

…when I deploy workersv3 "one by one" (rolling deploy), both workersv2 and workersv3 are going to be running at the same time.

Some workflows are probably going to get marked as `version 3` via a workersv3 instance, go to sleep, and then get run through a workersv2 instance. Then probably go to sleep again and wake up as v3. Totally botched up.

Could such a non-deterministic update cause the original "incorrect workflow status in visibility store"?

Regardless, it's probably better to completely deploy `if version == 3 { … }` part before incrementing the workflow version. Version changes warrant a two step deploy. This needs to be documented.

**Comment by longquanzheng** [comment]
Sorry for the late response. Is the issue resolved? 

I am not sure if that's a bug. @vancexu are you aware of any similar issue?

Also, Workflow visibility shouldn't be related to versioning, or DeleteWorkflowCurrentRow timeouts. 
But I saw some misbehavior in Cassandra when undering heavy load that it may lose some writes. There is a dynamic config the help throttling the requests to database so that it won't stress out Cassandra.
