### ISSUE TITLE
Cadence-cassandra-tool connection to AWS Keyspace 

### ISSUE THREAD

**Issue by smukk9** [uber/cadence#3427]
I am using AWS keyspace service for cadence cassandra store. When trying to using the cadence-cassandra-tool for schema migration i see two issues

1.  Partitioner Issue:
     Error: update the token ring due to error: Unsupported partitioner 'com.amazonaws.cassandra.DefaultPartitioner'
2. Consistency level:
    Error: consistency level ANY is not supported for this operation. Supported consistency levels are: ONE, LOCAL_QUORUM, LOCAL_ONE

**To Reproduce**
Need AWS keyspace connection details

**Steps to reproduce the behavior:**
1. docker run --rm -it ubercadence/server:0.11.0 bash
2. export the following env variable for cadence-cassandra-tool:
        export CASSANDRA_HOST=
        export CASSANDRA_PORT=
        export CASSANDRA_USER= 
        export CASSANDRA_PASSWORD=
        export CASSANDRA_ENABLE_TLS=
        export CASSANDRA_TLS_VERIFY_HOST=
        export CASSANDRA_TLS_CA=
        export CADENCE_KEYSPACE=cadence
        export VISIBILITY_KEYSPACE=cadence_visibility

3. cadence-Cassandra-tool setup-schema -v 0.0

**Expected behavior**
to connect to AWS keyspace and create the schema

**Screenshots**
NA

**Additional context**
I could not find any pointers for Partitioner issue. AWS documents mentions that hey support gocql but only basic example provided https://docs.aws.amazon.com/keyspaces/latest/devguide/using_go_driver.html which does not talk about setting the partitioner. 

For consistency level issue, AWS Keyspace does not support Any and only support ONE, LOCAL_QUORUM, LOCAL_ONE as show in the error. When i checked in cadence-cassandra-tool i see that defaultconsistency as ALL as seen here
https://github.com/uber/cadence/blob/01d2d1a475827257861b3e39846357d6f3e9def9/tools/cassandra/cqlclient.go#L64. is there a way to specify the consistency like the other flags as environment variable ?

**Comment by smukk9** [comment]
for consistency level issue i following issue that is updated in the latest release https://github.com/gocql/gocql/pull/1422

**Comment by longquanzheng** [comment]
@smukk9 I have looked into AWS Keyspace, it won't work directly even we fix the consistency levels. The big gap in Keyspace is it doesn't support Batch of LWTs. 
I have a plan to workaround that, I am planning to get it done by end of the year as I also need it.
