### ISSUE TITLE
Excessive worker persistence queries due to cadence-sys-executions-scanner-workflow

### ISSUE THREAD

**Issue by jw-doordash** [uber/cadence#3433]
On a new cadence instance running 0.13.x, cadence worker pods are continuously calling GetWorkflowExecution and ReadHistoryBranch.

Before starting application workflows, these happened at a rate of 25-75 requests per second per pod, and after starting workflows this increased to hundreds of requests per second per pod.

This is happening during cadence-sys-executions-scanner-workflow, which is running continuously.

**Comment by andrewjdawson2016** [comment]
https://github.com/uber/cadence/blob/master/common/service/dynamicconfig/constants.go#L309 this dynamic config controls if this workflow starts up when the service boots up. Your options are 

1. Use our dynamic file based config to disable workflow. 
2. Simply terminate the workflow that this domain starts

**Comment by jw-doordash** [comment]
Thanks - I will disable it for now.

**Comment by sagikazarmark** [comment]
@andrewjdawson2016 what does this workflow do? Should we be aware of anything if we disable it?

Also, is this a bug or it's working as intended? Would be nice to learn more before just disabling it.

Thanks!

**Comment by meiliang86** [comment]
@sagikazarmark This is a scanner that we use to fix some consistency issue in Cassandra. The inconsistency is due to the nature of Cassandra, not related to Cadence.
