### ISSUE TITLE
How to connect to outside Cadence Server

### ISSUE THREAD

**Issue by dibeshdas151995** [uber/cadence#3449]
I am unable to connect to the external Cadence Server, in the saga class I have updated the required files. 

package com.cadence.onlinefood;
import java.time.Duration;
import com.uber.cadence.client.WorkflowClient;
import com.uber.cadence.client.WorkflowException;
import com.uber.cadence.worker.Worker;
import com.uber.cadence.workflow.Workflow;

public class OnlineFoodBookingSaga {

	  static final String TASK_LIST = "OnlineFood";

	  @SuppressWarnings("CatchAndPrintStackTrace")
	  public static void main(String[] args) {
		  
	    String host = "http://dev213.ebiz.abc.com";
	    int port = 13979;
	    String domain = "mac1";

		  
	    Worker.Factory factory = new Worker.Factory(host, port, domain);
	    final Worker workerForCommonTaskList = factory.newWorker(TASK_LIST);
	    workerForCommonTaskList.registerWorkflowImplementationTypes(OnlineFoodBookingWorkflowImpl.class);
	    OnlineFoodBookingActivities onlineFoodBookingActivities = new OnlineFoodBookingActivitiesImpl();
	    workerForCommonTaskList.registerActivitiesImplementations(onlineFoodBookingActivities);

	    factory.start();
	    System.out.println("Worker started for task list: " + TASK_LIST);

	    WorkflowClient workflowClient = WorkflowClient.newInstance(host, port, domain);
	    
	    // now we can start running instances of our saga - its state will be persisted
	    OnlineFoodBookingWorkflow firstBooking = workflowClient.newWorkflowStub(OnlineFoodBookingWorkflow.class);
	    try {
	    	firstBooking.orderFood("Ramesh");

	    	
	    	Workflow.sleep(Duration.ofMinutes(2));
	    	
	    	firstBooking.orderFood("Suresh");
	    } catch (WorkflowException e) {
	      e.printStackTrace();
	    }

	    System.exit(0);
	  }
}

**Comment by meiliang86** [comment]
Start Cadence Server Docker images, then try to run WorkflowTests. You should follow pattern there to initialize your clients.
