### ISSUE TITLE
[Question] Would cadence be fit in use cases where latency is critical?

### ISSUE THREAD

**Issue by nagibcs** [uber/cadence#3456]
Hello, Thanks for the interesting work done in Cadence. I came upon cadence which looked very interesting but I can't find enough information on it's performance and I'm wondering if it would be fit my case where latency is critical?
My use case is a shopping cart checkout use case that involves orchestrating 6 to 10 services (depending on the cart contents) and the latency requirements are < 10 seconds and the number of workflows can go up to a 50 workflows/second.  

Another question, what did you miss in other BPM systems that made you write your own orchestrator?

**Comment by meiliang86** [comment]
Yes it is possible. We have used Cadence for similar use cases and don't see a problem.

**Comment by nagibcs** [comment]
@meiliang86 Thanks for the reply! I would appreciate if you have any references
also, out of curiosity,  what did you miss in other BPM systems that made you write your own orchestrator?
