### ISSUE TITLE
Invoke an application through shell script from workflow activity

### ISSUE THREAD

**Issue by MAMAMIA9** [uber/cadence#3457]
**Is your feature request related to a problem? Please describe.**
We have an application running on a linux server. We use a shell script invoke that application. 
Let's assume :
the application : GreetingAppilaction
the script: ./<script_name.sh> <arg1> <arg2>

Now I have deployed cadence on a server and written a workflow which executes this script by using Java Runtime exec library. The application is already running on the same server and invoking the command manually successfully  trigger the application. But through cadence workflow  I am facing issues. The problem is that the application is running on a host linux box and the cadence server is running as a separate docker container on the that box. And when we try to run the script_name.sh script from the workflow, since the workflow is hosted on a docker environment, it is unable to recognise the application which is running on the host VM box outside of the container. I need to figure out a way to trigger this command from the workflow so that the application running on the box is triggered.

Does Uber cadence workflow have any support for this??

Attaching some sample to mimic the logic:

_Worker Register_
```
public class WorkerRegister {
        public static void main(String[] args) {
             Worker.Factory workerFactory = new Worker.Factory(host, port, domain);
             Worker worker = workerFactory.newWorker(Constants.TASK_LIST);
             worker.registerWorkflowImplementationTypes(GreetingWorkflowImpl.class);
             worker.registerActivitiesImplementation(new GreetingActivitiesImpl());
             workerFactory.start();
}
```
_Workflow Impl_
```
public static class GreetingWorkflowImpl implements GreetingWorkflow {
            private final GreetingActivities activities = Workflow.newActivityStub(GreetingActivities.class);
            @Override
            public String invokeApplication(String arg1, String arg2) {
                        return activities.executeCommand(arg1, arg2);
           }
}
```
_Worker Activity Impl_

```
class GreetingActivitiesImpl implements GreetingActivities {
           @Override
            public void executeCommand(String arg1, arg2) {
                       try {
                               String command = "<scrpit_location>/./script_name.sh" +  arg1  + arg2;
                               Process proc = Runtime.getRuntime().exec(command);
                         } catch (IOException e) { // catch exception}
          }
}
```

_Workflow client code_
```
public class WorkerClientClass{
           public static void main(String[] args) {
                      WorkflowClient workflowClient = WorkflowClient.newInstance(host, port, domain);
                      GreetingWorkflow workflow = workflowClient.newWorkflowStub(GreetingWorkflow.class);
                      try {
                                 workflow.invokeApplication("arg1", "arg2"); 
                       } catch (WorkflowException e) { // catch logic }
                    System.out.println("\Workflow successfully completed.\n");
                    System.exit(0);
}
```

Please note that if I run the application from the box using the script it is running properly. From the workflow when I try to run I am not seeing anything being run. Cadence logs are also useless cannot figure out anything from the logs.

**Comment by MAMAMIA9** [comment]
On top of this I had one more doubt, when we try to run a workflow to connect to the host box and not any docker container. So as per my assumption the workflow code should be able to recognize the host application location and invoke the script accordingly.  Can someone help me explain this as well??

**Comment by meiliang86** [comment]
Assuming you have a set of activity workers that shares a task list, Cadence server can distribute your activity task to any of them. If you have a special worker and on that at worker can run the activity, you can designate a special task list for that worker, and use it when you schedule the activity.
Downside obviously is that you have a single point of failure for that activity.

**Comment by meiliang86** [comment]
BTW I am not sure why you want to swallow the exception in the activity. If you don't do that you should be able to see what error you got during your run.
