### ISSUE TITLE
XDC setup documentation 

### ISSUE THREAD

**Issue by smukk9** [uber/cadence#3464]
**Is your feature request related to a problem? Please describe.**
There is great documentation on how XDC is done in cadence in the docs section, but there is no mention of how to set that up either locally or in any environment. I went through documentation but i do not see any mention of how to setup XDC between two regions. 

**Proposed Solution**
A documentation that shows how to setup two cadence cluster (not sure how DB is setup in XDC) acting as active-passive and test the cross DC replication and fail over. Any one should be able to replicate the setup locally using docker

**Additional context**
Cadence is a great project however, without a description on how to setup XDC for fail overs, not many user may feel comfortable in adopting. 

I am happy to help in contributing if i can get some pointer on this setup.

**Comment by longquanzheng** [comment]
Best start point I know is https://github.com/uber/cadence/blob/master/config/development_active.yaml
https://github.com/uber/cadence/blob/master/config/development_standby.yaml
to understand what to configure XDC in two Cadence clusters. 
Then use CLI command to update active cluster to do a failure: https://github.com/uber/cadence/blob/fc856d5af50ec2ece4bf55c143985bdc63054c71/tools/cli/domain.go#L82

It would be great if you can contributing some document while you are learning it.

**Comment by longquanzheng** [comment]
@yux0 
We have completely deprecated Kafka, should we remove the Kafka section in the example configs? https://github.com/uber/cadence/blob/master/config/development_active.yaml

**Comment by smukk9** [comment]
Thanks for the sharing the details. I will go through and get back if i have questions. 

Do you have a sample without kafka dependency ?

**Comment by longquanzheng** [comment]
> Thanks for the sharing the details. I will go through and get back if i have questions.
> 
> Do you have a sample without kafka dependency ?

Hi I am making a PR to remove the kafka dependency: https://github.com/uber/cadence/pull/3555

**Comment by demirkayaender** [comment]
Documentation can be found here: https://cadenceworkflow.io/docs/concepts/cross-dc-replication/#running-in-production
