### ISSUE TITLE
Cadence pods fail to start Helm chart 0.10 app version 0.13.0

### ISSUE THREAD

**Issue by marcelocquadros** [uber/cadence#3477]
The cadence pods are failing to start with CrashLoopBackOff status. Only cassandra pod is running fine.  

All pods are showing the message below:

cassandra schema version compatibility check failed: version mismatch for keyspace/database: "cadence". Expected version: 0.27 cannot be greater than Actual version: 0.0

k logs -f cadence-frontend-7f9cc5f5-w7hd7 -n cadence
 dockerize -template /etc/cadence/config/config_template.yaml:/etc/cadence/config/docker.yaml
 exec cadence-server --root /etc/cadence --env docker start --services=frontend
2020/08/25 15:02:45 Loading config; env=docker,zone=,configDir=/etc/cadence/config
2020/08/25 15:02:45 Loading configFiles=[/etc/cadence/config/docker.yaml]
2020/08/25 15:02:45 cassandra schema version compatibility check failed: version mismatch for keyspace/database: "cadence". Expected version: 0.27 cannot be greater than Actual version: 0.0

To reproduce the issue:
kubernetes 1.17
Helm 2.16.9 or 3.3.0
```cmd
 helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
 helm repo update

 helm install --name my-release --namespace cadence banzaicloud-stable/cadence
```

**Comment by sagikazarmark** [comment]
@marcelocquadros my guess is the migration job couldn't complete for some reason. Unfortunately, I can't reproduce the issue.

One thing that _could_ cause this is that the cluster you launched is not big enough, causing cassandra startup time to be very large and the migration to run out of retries.

I'd suggest watching the installation process and see if the schema setup job succeeds or fails.

You could also install Cassandra separately, run the migrations manually and install Cadence without managing Cassandra and running migrations. There are detailed instructions for that in the Helm chart readme.

**Comment by marcelocquadros** [comment]
I checked it again and I have a problem with cassandra pod restarting before migrations complete. 
<img width="1101" alt="Screen Shot 2020-08-27 at 14 58 50" src="https://user-images.githubusercontent.com/6987368/91491434-66707b80-e88a-11ea-9d4e-ee3ae179261b.png">

Using the temporal/helm-chart I'm able to run everything with success. I couldn't understand why, since they are using the same cassandra/incubator charts.

**Comment by sagikazarmark** [comment]
Well, this isn't a chart issue then, but an infrastructural one (small cluster, not enough resources, etc).

The temporal charts come with a few settings by default that speed up the cassandra startup time. These configurations are suitable for a dev installation: https://github.com/temporalio/helm-charts/blob/master/values.yaml#L331-L338

The same settings can be found in the Cadence chart: https://github.com/banzaicloud/banzai-charts/blob/master/cadence/values.dev.yaml

**Comment by marcelocquadros** [comment]
Well, I will close this issue, due I am not sure if this is a problem with the chart or if there is something wrong with my environment. Even though this is a sufficiently large cluster. Anyway, I tried to install using values.dev.yaml and the result was the same. If I discover the problem I post the answer.

Tks for your attention!

**Comment by kalrashubham49** [comment]
I am facing same issue , any guiding steps for using temporal charts
