### ISSUE TITLE
Postgres plugin has a faulty SQL statement

### ISSUE THREAD

**Issue by chris-rcn** [uber/cadence#3482]
**Describe the bug**
Some data does not get persisted when it should.

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
1. Poll for an activity.
2. Bounce the history node.
3. Attempt to complete the activity.  Receive "activity not found".

**Expected behavior**
The activity completes.

**Screenshots**
None

**Additional context**
Here is the fix:

	diff --git a/common/persistence/sql/sqlplugin/postgres/execution_maps.go b/common/persistence/sql/sqlplugin/postgres/execution_maps.go
	index dc518896..d0044bbf 100644
	--- a/common/persistence/sql/sqlplugin/postgres/execution_maps.go
	+++ b/common/persistence/sql/sqlplugin/postgres/execution_maps.go
	@@ -45,15 +45,12 @@ run_id = $4`
	        setKeyInMapQueryTemplate = `INSERT INTO %[1]v
	 (shard_id, domain_id, workflow_id, run_id, %[4]v, %[2]v)
	 VALUES
	 (:shard_id, :domain_id, :workflow_id, :run_id, :%[4]v, %[3]v)
	 ON CONFLICT (shard_id, domain_id, workflow_id, run_id, %[4]v) DO UPDATE
	-  SET shard_id = excluded.shard_id,
	-      domain_id = excluded.domain_id,
	-      workflow_id = excluded.workflow_id,
	-         run_id = excluded.run_id,
	-      %[4]v = excluded.%[4]v `
	+  SET (shard_id, domain_id, workflow_id, run_id, %[4]v, %[2]v)
	+  = (:shard_id, :domain_id, :workflow_id, :run_id, :%[4]v, %[3]v)`

**Comment by longquanzheng** [comment]
Hi @chris-rcn , how is the the Cadence running with Postgres for you? would you mind share some experience? There are folks in the community that are very interested in Postgres too. :D

**Comment by chris-rcn** [comment]
Working well.  I'm not aware of any other issues.

**Comment by longquanzheng** [comment]
Closed as the issue has be resolved.
