### ISSUE TITLE
Enforce Context Timeout in Persistence Layer

### ISSUE THREAD

**Issue by yycptt** [uber/cadence#3519]

**Comment by longquanzheng** [comment]
Is there any background we are doing this? I am guessing there are some issues like goroutine leakage /memory?

**Comment by yycptt** [comment]
In general, as those persistence calls are just RPC calls, we think it makes sense to set different context timeout for each call based on needs, instead of using a background context for a pre-defined timeout.

More specifically, for sync frontend API calls (like start workflow), we should release the current execution lock after the ctx for the API call exceeds deadline. While for now, we will hold the lock until DB call returns and we don't have control over when DB call will return. (For more context, check comments in this diff: https://github.com/uber/cadence/pull/3515). For task processing, a task shouldn't take a long time to process, if a DB call takes a long time during task processing, that task should back off and retry, instead of keep wait the for the response from DB and blocking other tasks from being processed.
