### ISSUE TITLE
optimize query when there is no change to the history

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#352]
we could send down some opaque task token in query result so when next time client send query, it sends along with the token, and we could check if there is any change to history and return immediately if there is no change to history.

**Comment by samarabbas** [comment]
Is this even needed after support for sticky query?

**Comment by dmetzgar** [comment]
@andrewjdawson2016 this looks like something you're already doing as part of sync-rr. Do you want to close this as duplicate?

**Comment by wxing1292** [comment]
close this task since sticky query is already rolled out
