### ISSUE TITLE
Allow configuring proto version to connect to Cassandra in config

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3536]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/uber/cadence/issues/3516
Cadence cannot connect to Cassandra of other versions. 

**Proposed Solution**
1. Test Cadence with other Cassandra versions see if it works(all e2e integ test passing)
2. If works, then allow configuring the proto version 

**Additional context**
N/A

**Comment by noiarek** [comment]
@longquanzheng @meiliang86 Do you team mind if I grab this ticket? I would start working on this next weekend.
