### ISSUE TITLE
Add headers to activity and start workflow requests

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#354]
Most request/reply protocols use headers to pass additional information about request. It would simplify forwarding such requests (like HTTP or TChannel) if headers are supported directly.
If headers were supported then adding request encoding information wouldn't require any server side changes.

**Comment by h7kanna** [comment]
Hi @mfateev , I tried to add context propagation using Opentracing/Jaeger as an experiment. 
It is a very naive attempt(I did this for a demo). 

I added opentracing binary carrier to workflow execution as a blob. This solution assumes only cadence-client is responsible for propagation.

Can you please share the plan to support this feature. If someone is not already working on it, I will continue working on this.

Also please suggest a more efficient way (if any) to do this.

https://github.com/h7kanna/cadence/commit/e18f47f293bf05ec7c6920b0b8b2f0f5b2ed75a9

https://github.com/h7kanna/cadence-client/commit/94518205dc2e26b26079edc55e8eaed5e3ee10ba

Thanks,
Harsha

**Comment by mfateev** [comment]
Harsha, it looks reasonable. I would prefer more generic header that is key->blob_value to support future extensions instead of a single carrier blob field. Let me consult with my local Jaeger experts to see if I'm missing something.

**Comment by h7kanna** [comment]
Hi @mfateev,
Also, I have few more questions. Please clarify whenever possible for you.
I think sampling rate of Jaeger client should be configured to 100% if all the workflows should be traced. It will be a scale issue.  Moreover, jaeger agent is UDP based with an in-memory queue, so can be lossy.
Actually what I was looking for is the trace of the workflow end to end based on a business key. Jaeger can provide that view but may not be reliable and also not searchable by a business key(unless it is the trace id). Also, long-running workflows will be another problem.

I started digging into this issue based on your answer for https://github.com/uber-go/cadence-client/issues/318. But want to know if there is a plan for any cadence UI or API with end-to-end workflow execution trace view that does not depend on jaeger? 

Thanks,
Harsha

**Comment by mfateev** [comment]
Could you elaborate on your use case? Are you trying to get some analytic of a single workflow execution, or your goal is to track requests from client app all way down through the chain of services including Cadence based ones?

**Comment by h7kanna** [comment]
Actually both.
1) Workflow execution history as a tree including input output of the activities from visibility API.
2) Trace down through the chain of services including cadence.

**Comment by h7kanna** [comment]
I think the relevant issue for first use case is https://github.com/uber/cadence/issues/418
Apologize for mixing up my questions.

**Comment by mfateev** [comment]
1. You already can get workflow execution history through the GetWorkflowExecutionHistory API. The UI is coming soon.
2. We are working on this one with the Jaeger team. The complexity is around requirements of not persisting a Jaeger context in the history as it might contains some time sensitive or even security related information.

**Comment by h7kanna** [comment]
Thanks for your prompt responses.
I will keep refining the code changes I did and add tests. Let me know the approach Jaeger team proposes.

**Comment by szaluzhskiy** [comment]
I have exactly same demand on production project. We use cadence as a part of complex business flow. So business workflow is starting at API gateway goes through number of microservices before cadence, than cadence orchestration layer, and last part again set of microservices. Where I need to provide: 
1. Possibility to make tracing of end to end flow, based on business key.
2. To escape saving of sensitive data
3. Use Zipkin as tracing server

**Comment by shreyassrivatsan** [comment]
@szaluzhskiy I'd like to understand your requirements a bit more. For tracing support, we are looking at adding opentracing support in cadence which should allow you to use zipkin. But limiting what information we save from the tracing baggage is likely not possible.. 

For the use case of sending sensitive data and ensuring it isn't saved anywhere in Cadence - is that related to tracing data or some separate requirements around authorization/tenancy?

**Comment by szaluzhskiy** [comment]
Talking about our requirement
 "To escape saving of sensitive data"

Actually it's more important to support a possibility to continue existing traceId which was stared at the beginning of business transaction before coming to Cadence.
 
Talking about sensitive information, I agree it's minor point in dealing with traces in Cadence. 
And at the same time it's important as separate requirement to think how to get around of authorization, because Cadence is storing state of workflow. And workflow can has a sensitive info in state variables. If have any kind of guide how to deal with sensitive data in Cadence you are welcome to share it.

**Comment by shreyassrivatsan** [comment]
> Talking about sensitive information, I agree it's minor point in dealing with traces in Cadence.
> And at the same time it's important as separate requirement to think how to get around of authorization, because Cadence is storing state of workflow. And workflow can has a sensitive info in state variables. If have any kind of guide how to deal with sensitive data in Cadence you are welcome to share it.

For storing sensitive information Cadence provides a `DataConverter` interface in the both [Go](https://github.com/uber-go/cadence-client/blob/master/encoded/encoded.go) and [Java](https://github.com/uber/cadence-java-client/blob/master/src/main/java/com/uber/cadence/converter/DataConverter.java) clients. While the server itself does not look at or do anything with the data stored, the DataConverter will ensure that sensitive information isn't stored in plain on the server side..

**Comment by dmetzgar** [comment]
#1731

**Comment by shreyassrivatsan** [comment]
#1731 adds server side support for propagating headers across workflows. Server side changes are in progress.

**Comment by izishared** [comment]
@shreyassrivatsan could you please specify the number of ticket for implementing this functionality in Java client?
