### ISSUE TITLE
Provide clusterMetadata.clusterInformation.<clusterName>.rpcName a default value as "cadence-frontend"

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3559]
**Is your feature request related to a problem? Please describe.**
Because today we have hardcoded the RPC names to be "cadence-frontend/history/matching".
See https://github.com/uber/cadence/blob/befd8954e06a1ee178d6d3eb168628282053d95d/cmd/server/cadence/server.go#L110

So it's useless to allow putting a different config. In fact, only "cadence-frontend" will work. 

**Proposed Solution**
Same as the title. In reading the config, set the default value when it's empty. Update config comments, update sample configs.

**Additional context**

**Comment by swayamraina** [comment]
@longquanzheng Not sure if I got this correct, Do we need to move the server name as default to cadence-frontend for all

**Comment by longquanzheng** [comment]
> @longquanzheng Not sure if I got this correct, Do we need to move the server name as default to cadence-frontend for all

I just corrected the title. This issue is only for fixing the service name in the `clusterInformation` for XDC feature

**Comment by swayamraina** [comment]
ok, so `ClusterInformation` has this variable `rpcName` which we want to give a default value of 'cadence-frontend'?
I guess this can be done via `UnmarshalYAML `

should be fine right @longquanzheng ?

**Comment by longquanzheng** [comment]
> ok, so `ClusterInformation` has this variable `rpcName` which we want to give a default value of 'cadence-frontend'?
> I guess this can be done via `UnmarshalYAML `
> 
> should be fine right @longquanzheng ?

that sounds like a good idea to me. We haven't used default values in annotaions, but I think it's better than hardcoding.

**Comment by longquanzheng** [comment]
implemented in https://github.com/uber/cadence/pull/3825
