### ISSUE TITLE
Push images to ghcr.io

### ISSUE THREAD

**Issue by sagikazarmark** [uber/cadence#3576]
Docker Hub is going to enforce new rate limits as of November which won't work for a lot of users. Push images to ghcr.io as well, so we can keep using Cadence without image pull authentication!

Thanks!

**Comment by longquanzheng** [comment]
I can open ghcr.io
Is that a website?

**Comment by sagikazarmark** [comment]
https://github.blog/2020-09-01-introducing-github-container-registry/

**Comment by just-at-uber** [comment]
Hi there,

You can find a draft PR with integration changes for ghcr here:
https://github.com/uber/cadence/pull/3708

We are waiting for some feature changes from GitHub before we can proceed with the change.

Thanks.
