### ISSUE TITLE
status filter is not working in listing workflows

### ISSUE THREAD

**Issue by meetchandan** [uber/cadence#3593]
`./cadence --do samples-domain workflow list --workflow_id <wf_id> --status completed` 
`./cadence --do samples-domain workflow list  --workflow_id <wf_id> --status continueasnew` 
`./cadence --do samples-domain workflow list  --workflow_id <wf_id> --status terminated` 

All of the above commands return the same response.
The status filter does not work.

Please refer the screenshot attached.

<img width="1406" alt="Screen Shot 2020-10-06 at 4 54 37 PM" src="https://user-images.githubusercontent.com/8505196/95232520-aaee2000-0815-11eb-9c5c-ea7812de0959.png">

P.S. I am using mysql as the DB

**Comment by longquanzheng** [comment]
@meetchandan which database you are using? It may be a bug of the DB plugin.  It will be super useful for us to reproduce with this information. Thanks

**Comment by meetchandan** [comment]
hi, i am using mysql
