### ISSUE TITLE
Increase default timeout seconds for Reset command and add description about timeout issues

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3596]
**Is your feature request related to a problem? Please describe.**
Using Reset command with CLI will get `code:deadline-exceeded message:timeout` easily because reset requires replay in the server. It's quite resource consuming, depending on the length/size of the history.

By default the CLI context timeout is only 5 seconds:
https://github.com/uber/cadence/blob/63bdb5d7a04285cf57992c574639c9d911c7001a/tools/cli/defs.go#L54

This is mostly not enough for production use cases.

Right now people can provide a global flag "--context_timeout" or "--ct" to override the timeout, but it's not friendly, and few people are ware of this global option.

**Proposed Solution**
Increase the default timeout of Reset command(only), to a value like 1 minute.
Also add description to the Reset command to let people know that they can override it with the global options 

**Additional context**
From a slack convo: https://uber-cadence.slack.com/archives/CL22WDF70/p1601986927134000

**Comment by lazy-ninja** [comment]
@longquanzheng, I would like to take this up!

**Comment by meiliang86** [comment]
@lazy-ninja That would be awesome! Please feel free to!

**Comment by lazy-ninja** [comment]
Thanks, @meiliang86.

**Comment by d-vignesh** [comment]
Hi @longquanzheng, can i work on this issue
