### ISSUE TITLE
Let ListCloseWorkflows allow ordering by StartTime or CloseTime without changing dynamic config

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3621]
**Is your feature request related to a problem? Please describe.**
Today ListCloseWorkflows by default will list by StartTime, same as List OpenWorkflows, and using a dynamic config `EnableReadFromClosedExecutionV2` to decide whether or not ordering by CloseTime.
This is a wrong place using dynamic config. It should be an option in the request and CLI command. 

And only Cassandra has implemented it, SQL doesn't support ordering by CloseTime, but the indexes are created.

**Proposed Solution**
1. Providing an option for ListCloseWorkflows to sort by CloseTime and remove the dynamic config `EnableReadFromClosedExecutionV2`.
Even though we keep the default behavior of using StartTime, this will be a backward compatibility if anyone setting EnableReadFromClosedExecutionV2 to true. 
So we must make clear release instruction for that.  

2. Implement ordering by CloseTime in SQL.

**Additional context**

**Comment by longquanzheng** [comment]
@vancexu Correct me if my issue is incorrect, and any addition information to proceed.

**Comment by vancexu** [comment]
Hi @longquanzheng, yes it is doable. 
Is there some real use case for sorting close workflow by start time? the current implementation is majorly because we assume customer always want sorting by closetime for closed workflow (and default by start time sometimes lead to confusing result in UI/CLI since they cannot find a recent closed workflow)

**Comment by meiliang86** [comment]
Agree that we should give user this option instead of controlling through dynamic config.
We can also default to one option and document in our CLI.
