### ISSUE TITLE
Cassandra GetDomain still fetches result after DeleteDomain

### ISSUE THREAD

**Issue by anish531213** [uber/cadence#3629]
**Describe the bug**
If we run the Cassandra unit test multiple time for MetadataPersistenceSuiteV2, the test is failing with this weird issue. `An error is expected but got nil.` This is happening because delete is not deleting the record although the request is sucessful.

**To Reproduce**
Is the issue reproducible? 
Yes

**Steps to reproduce the behavior:**
I have included some print statement and uploaded a branch `aanish/cassandra-delete-issue`
Please pull this branch.
Then run the Cassandra unit test for MetadataPersistenceSuiteV2 from https://github.com/uber/cadence/blob/58879efb2d6486d3edfedf502fd0cefd045f50fe/common/persistence/persistence-tests/cassandra_test.go#L44
Run this multiple times. You would get the test failing with these outputs.
`Delete domain completed delete-domain-test-name 5f085e78-5bd4-4428-80a3-69a945c70cef`
`Get domain complete <nil> delete-domain-test-name 5f085e78-5bd4-4428-80a3-69a945c70cef`
As you can see the delete is completed but it is still getting the domain with same Id. Actually the GetDomain should have returned EntityNotExistError.

**Comment by andrewjdawson2016** [comment]
@anish531213 I ran this test suite 10 times on master and it passed every time? Is it possible you changed something in the clean up or test logic?
