### ISSUE TITLE
0.15.0 breaks existing deployments due to gocql revert

### ISSUE THREAD

**Issue by AngerM** [uber/cadence#3648]
**Describe the bug**
The revert of the gocql changes I had put in previously with https://github.com/uber/cadence/pull/2928 in have been reverted by 84631abd24980c7321585d8dbcc0204c3fe9632b, this breaks existing deployments and we cannot upgrade as this ancient version of gocql is not compatible with most modern deployments of Cassandra.

**To Reproduce**
Is the issue reproducible? 
- YES

**Comment by yycptt** [comment]
Hi @AngerM, we have reverted that change in v0.15.1 patch release. 

Hope this will fix the issue you're facing. Thanks!
