### ISSUE TITLE
Slack Link Broken

### ISSUE THREAD

**Issue by paulkass** [uber/cadence#3662]
**Describe the bug**
The README slack link is broken. I found this issue from 2 weeks ago: https://github.com/uber/cadence/issues/3564, and i tried that link. Broken as well.

**To Reproduce**
Is the issue reproducible? 
Yes

**Steps to reproduce the behavior:**
A clear and concise description of the reproduce steps.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here, E.g. Stackstace, workflow history.

**Comment by meiliang86** [comment]
Thanks for reporting. This is fixed now.
Unfortunately slack invitation link expires periodically so we need to continue to update it once in a while.
