### ISSUE TITLE
Automatically enable scalable tasklists  

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3677]
**Is your feature request related to a problem? Please describe.**
People always run into this issue when their business scale up to more workflows and activities. 

In the past, Cadence recommended using multiple tasklists to start workflow/activity. The idea is quite simple. You just need to make a list of tasklists and randomly pick one when starting workflows. And then when starting workers, let them listen to all the tasklists. 

Today, Cadence has a feature called “Scalable tasklist”. It will distribute tasks of a tasklist to multiple Matching service nodes. By default this feature is not enabled because there is some performance penalty on the server side.

However, it is not straightforward to use the feature as it required some config changes. 

**Proposed Solution**
Automatically enable the scalable tasklist when matching see a tasklist is overloaded.

**Additional context**
There are lots of this discussion in the Slack. This feature will reduce the friction of using significantly for large scale usecases.

**Comment by demirkayaender** [comment]
This is coming soon.
