### ISSUE TITLE
Getting error "pq: parameter "ssl" cannot be changed now " when connecting to postgres using tls

### ISSUE THREAD

**Issue by mkalavala** [uber/cadence#3756]
**Describe the bug**
The following statements are generating error "pq: parameter "ssl" cannot be changed now "

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
1. generate private key and self signed certificate 
openssl req       -newkey rsa:2048 -nodes -keyout pg_private.key     -x509 -days 365 -out pg_sca.crt
2. Run the postgresql container in ssl mode. 

- The dockerfile contents are
     FROM postgres:11-alpine
     COPY ./pg_keys/pg_sca.crt /var/lib/postgresql/server.crt
     COPY ./pg_keys/pg_private.key /var/lib/postgresql/server.key
     RUN chmod 600 /var/lib/postgresql/server.key
     RUN chown postgres:postgres /var/lib/postgresql/server.key
- Build the image
   docker build --tag mypg:1.0 .
- run the container
  docker run -e POSTGRES_PASSWORD=postgres -p 35432:5432 -d --name postgres mypg:1.0 \\n  -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt \\n  -c ssl_key_file=/var/lib/postgresql/server.key

3. Bring up the cadence server locally
docker-compose -f docker-compose-postgres.yml up -d
4. create cadence database and user.
CREATE ROLE cadence
                         WITH ENCRYPTED PASSWORD 'cadence'
                         LOGIN NOINHERIT;
      GRANT cadence to postgres;
      CREATE DATABASE cadence
                          WITH OWNER = 'cadence';
      CREATE DATABASE cadence_visibility
                                WITH OWNER = 'cadence';
      REVOKE ALL ON DATABASE cadence FROM PUBLIC;
5. open the bash terminal inside cadence server container
6. copy the pg_sca.crt to /etc/db/tls/database.crt
7. Export the following variables
/etc/cadence # export SQL_PLUGIN=postgres
/etc/cadence # export SQL_HOST="10.0.0.196"
/etc/cadence # export SQL_PORT=35432
/etc/cadence # export SQL_DATABASE=cadence
/etc/cadence # export SQL_PASSWORD=cadence
/etc/cadence # export SQL_USER=cadence
8. run cadence-sql-tool cadence-sql-tool --tls --tls-ca-file /etc/db/tls/database.crt -q 
setup-schema -v 0.0

**Expected behavior**
the cadence schema should be created successfully with out any errors

**Comment by longquanzheng** [comment]
@mkalavala Thanks for reporting the issue. Looks like the error is because we are passing a wrong parameter "ssl" which is unnecessary, because "sslmode" is already "require". 
I had made a PR out for fixing it. It's working for me locally: https://github.com/uber/cadence/pull/3758

And also built an image for you, could you also confirm the fix by using this image? `ubercadence/qlong-server:0.05`

**Comment by longquanzheng** [comment]
updated command `CREATE ROLE cadence
WITH ENCRYPTED PASSWORD cadence` to `CREATE ROLE cadence
WITH ENCRYPTED PASSWORD 'cadence'`

**Comment by mkalavala** [comment]
i'm getting the following error when i use the self signed certificate. but the solution works for the CA certificate
2020/11/16 14:27:51 x509: certificate signed by unknown authority

**Comment by longquanzheng** [comment]
close it as the PR is merged and will be released soon.
