### ISSUE TITLE
TaskList need to clean leaky metadata

### ISSUE THREAD

**Issue by vancexu** [uber/cadence#380]
Server can leak decision task metadata (type = 0, taskid = -12345) if there are no pollers.
Need to have a way to clean those left tasks.

**Comment by dmetzgar** [comment]
@vancexu is this still valid? Can we close it?

**Comment by vancexu** [comment]
I think this issue is still there, but relatively not important/urgent, since it's a rare case there are only tasklist but no pollers. 
One way to fix is to add some sort of scanning, which I think is on the road map.

**Comment by demirkayaender** [comment]
Closing due to low priority, please reach out if you still need help with this.
