### ISSUE TITLE
Refactor expirationTimestamp for mutableState

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3800]
In the discussion https://github.com/uber/cadence/pull/3780#pullrequestreview-536843118

We think it's a better idea if expirationTimestamp is not required from caller of historyService, or completely remove from the request attribute. This will make the service/mutableState more self-contained, and less error-prone.

**Comment by osho-20** [comment]
would like to work on this.

**Comment by demirkayaender** [comment]
@osho-20  how about you contact me over our Slack workspace? I can find you a project.
