### ISSUE TITLE
Restart timed_out workflow.

### ISSUE THREAD

**Issue by ru90** [uber/cadence#3804]
Hello I create a workflow with 2 activities.
Scenario. one activities is completed while executing second, URL link to which I need to communicate is down. Now when that URL is up workflows is timed out. So How can I restart Timed out workflow?
I implement this I go language.

**Comment by longquanzheng** [comment]
Use reset command to reset to last decision completed will do it for you. See document for CLI in cadenceworkflow.io

**Comment by longquanzheng** [comment]
Thanks for asking the question. I have posted your question and answer in this Stack and close the issue: https://stackoverflow.com/questions/65104070/how-to-restart-a-timeouted-failed-canceled-terminated-cadence-workflow/65104071#65104071

**Comment by ru90** [comment]
Thank you
