### ISSUE TITLE
Add ability to restart failed workflow execution from the middle

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#381]
Currently there is no way to restart failed workflow from the point of failure or completed workflow from some point in the middle if some bug was fixed.

The proposal is to create a new execution with the same workflowID which contains copy of partial history of the workflow run being restarted. For this to work correctly the copy of history should be analyzed and either all open activities failed or may be requeued if not started yet.

The other hard problem is to figure out up to which point a history should be copied. Having that multiple activities can be failing and rescheduled from multiple coroutines there is no clear way to determine what part of history should not be copied.

**Comment by yaronsumel** [comment]
Hey @mfateev .. Is this new feature in some future plans ?

**Comment by mfateev** [comment]
It is being worked on and should be available within a quarter.

**Comment by yaronsumel** [comment]
Great.. Thanks !

**Comment by dmetzgar** [comment]
Related to #620

**Comment by samarabbas** [comment]
Related PR #1352 #1377 #1411

**Comment by dmetzgar** [comment]
@longquanzheng reset is now released, can this issue be closed?

**Comment by longquanzheng** [comment]
Yes, it should be closed

**Comment by longquanzheng** [comment]
@dmetzgar let's have some document for external customer: https://github.com/uber/cadence/pull/1821
