### ISSUE TITLE
Add query to return a list of available queries for the workflow instance

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#382]
The list should also include documentation about each query semantic and accepted arguments.

**Comment by dmetzgar** [comment]
Cadence Web is actually [working around](https://github.com/uber/cadence-web/pull/12) this by attempting to call a query and parsing the list of names from the returned error. It doesn't include the parameters though.

**Comment by mfateev** [comment]
And it is broken for Java which returns this list in a different error string

**Comment by mfateev** [comment]
Requires https://github.com/uber/cadence/issues/390

**Comment by demirkayaender** [comment]
this should already be supported, closing it.
