### ISSUE TITLE
Get timedout workflow list

### ISSUE THREAD

**Issue by ru90** [uber/cadence#3820]
How can I get list of workflow with "timedout" status using cadence cli. I their any api to do so in Go. So that I can reset that workflows

**Comment by longquanzheng** [comment]
In CLI:
```
./cadence --domain sample-domain wf list --status timeout
```

**Comment by longquanzheng** [comment]
https://stackoverflow.com/questions/65119595/how-to-get-a-list-workflows-based-on-some-filtering-like-timeout-workflowtype/65119596#65119596

Btw you can also use batch reset if you have advanced visibility:
```
./cadence --doamin <> wf reset-batch --query "some query to find workflows" --reset_type <> --reason "..."
```
