### ISSUE TITLE
Delete cadence domain?

### ISSUE THREAD

**Issue by ru90** [uber/cadence#3827]
How to delete cadence  domain?

**Comment by longquanzheng** [comment]
What is the reason that you want to delete a domain? It’s not supported because simply delete the domain will cause corruption to existing tasks and data associated to the domain. So it’s generally recommended to register another one instead.

**Comment by ru90** [comment]
I Just created samples-domain for testing purpose. Now after completion of testing I need to clean it up. thats the only reason.

**Comment by longquanzheng** [comment]
https://stackoverflow.com/questions/65154054/can-i-or-how-to-delete-a-cadence-workflow-domain/65154055#65154055
I summarized it here.
