### ISSUE TITLE
Add DescribeWorkflowExecution to the Cadence API

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#384]
Here is SWF spec for it:

http://docs.aws.amazon.com/amazonswf/latest/apireference/API_DescribeWorkflowExecution.html

It is used to poll for workflow completion by tests and CLI. 

Another option to consider is to use Cadence query API and add this as a new query type.

**Comment by yiminc** [comment]
API is added, but we might want to add more info to the response, which could be a new issue.
