### ISSUE TITLE
Improvement: Use string instead of number for workflow status in search workflow query

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3855]
Right now we can do this List command:
```
./cadence list --status timedout
```
However in search 
```
./cadence list --query "Status=5"
```
It requires to remember the mapping from a number to status. https://cadenceworkflow.io/docs/concepts/search-workflows/#query-capabilities This is very inconviment.

**Comment by yycptt** [comment]
Addressed by https://github.com/uber/cadence/pull/3865
