### ISSUE TITLE
SQL: More lenient schema migrations

### ISSUE THREAD

**Issue by JosefWN** [uber/cadence#3857]
**Is your feature request related to a problem? Please describe.**

- When running SQL schema initializations/migrations, we are currently using the `--quiet` flag on `create` to suppress the error that the database already exists, this also risks suppressing other errors. In some cases the database might already exist but not be initialized such as in a production context, but in a local dev environment it might not.
- Running `update-schema` on a downgrade to a lower version will currently fail, because the schema migrations expect at least the same version. `helmfile` for example doesn't support rollbacks, so it will be hard for us to differentiate between up- and downgrades using for example `helm` hooks.

**Proposed Solution**

- Do not fail on `create` if the database already exists, or exit with an exit code that allows us to differentiate between a failure when the database already exists, and other failures.
- Since there are no schema down-migrations, I'm assuming that all up-migrations are backwards compatible. In that case, `update-schema` could ensure that _at least_ the requested version has been migrated to. In other words, if we are on `v0.2` but trying to migrate "up to" `v0.1`, the migration would not throw an error (since `v0.2` is backwards compatible).

**Additional context**

Using Cadence `v0.15.1` with Postgres.

**Comment by ibarrajo** [comment]
Closing this since schemas have been considerably updated since the ticket was opened.

https://github.com/uber/cadence/tree/master/schema/cassandra/cadence/versioned
