### ISSUE TITLE
Slack invitation link in README not working

### ISSUE THREAD

**Issue by Blaubunt** [uber/cadence#3885]
Hello,
I am new to Cadence and wanted to join the Slack community. Sadly the link in the Readme guides me to a page where I have to enter a @visa Email-Adress to get access.
Is there a possibility to get a new invite link or another way to join the community?

**Comment by longquanzheng** [comment]
have you got it yet? @meiliang86 may know how to fix it

**Comment by meiliang86** [comment]
Checked just now and works for me.
