### ISSUE TITLE
ListTaskList API with SQL implementation may return incomplete result

### ISSUE THREAD

**Issue by yux0** [uber/cadence#3911]
**Describe the bug**
ListTaskList API with SQL implementation may return incomplete result

**To Reproduce**
Is the issue reproducible? 
- TODO

**Steps to reproduce the behavior:**
A clear and concise description of the reproduce steps.

**Expected behavior**
ListTaskList API should return all tasklist

**Screenshots**

**Additional context**
The ListTaskList uses domain ID as one of the orders. The domainID in SQL translate to byte array. However, the byte array of minUUID is not started from the beginning.

**Comment by Shaddoll** [comment]
Another fix: https://github.com/uber/cadence/pull/5558
