### ISSUE TITLE
Release is not gzipped

### ISSUE THREAD

**Issue by jacobsevart** [uber/cadence#3922]
**Describe the bug**
Release is named `.tar.gz` but is actually a plain tar archive, not gzipped.

**To Reproduce**
Is the issue reproducible? Yes

**Steps to reproduce the behavior:**
A clear and concise description of the reproduce steps.

```
wget https://github.com/uber/cadence/releases/download/v0.18.0/docker.tar.gz
tar -xvzf docker.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

tar -xvf docker.tar.gz
(succeeds)
```

**Expected behavior**
Release should unzip.

**Comment by yycptt** [comment]
Thanks for catching this @jacobsevart 

I just updated the 0.18.0 release so it's gzipped now. Please try again.

**Comment by jacobsevart** [comment]
Thanks!
