### ISSUE TITLE
Brew install Cadence CLI

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3932]
It's better than running from docker container :-)

**Comment by git-hulk** [comment]
I have created cadence-cli homebrew in my repo: https://github.com/git-hulk/homebrew-cadence

```shell 
% brew tap git-hulk/cadence
% brew install cadence-cli
```

the `cadence`  name has token by others at [homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cadence.rb), so uber cadence should use another name if wants to merge into homebrew core repo.

**Comment by longquanzheng** [comment]
> I have created cadence-cli homebrew in my repo: https://github.com/git-hulk/homebrew-cadence
> 
> ```shell
> % brew tap git-hulk/cadence
> % brew install cadence-cli
> ```
> 
> the `cadence` name has token by others at [homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cadence.rb), so uber cadence should use another name if wants to merge into homebrew core repo.

Thanks! I think `cadence-cli` is fine too.

**Comment by git-hulk** [comment]
hi, @longquanzheng 

I also add the cadence server and tools into the homebrew and named it `uber-cadence`. You can have a try, I will file a PR to homebrew-core if the name and formula is ok.

```
% brew untap git-hulk/cadence
% brew tap git-hulk/cadence
% brew install uber-cadence
```

```
cadence-server --root /usr/local/etc/cadence start
2021/03/16 11:18:49 Loading config; env=development,zone=,configDir=/usr/local/etc/cadence/config
2021/03/16 11:18:49 Loading configFiles=[/usr/local/etc/cadence/config/base.yaml /usr/local/etc/cadence/config/development.yaml]
2021/03/16 11:18:49 gocql: unable to dial control conn 127.0.0.1: dial tcp 127.0.0.1:9042: connect: connection refused
```

**Comment by longquanzheng** [comment]
> hi, @longquanzheng
> 
> I also add the cadence server and tools into the homebrew and named it `uber-cadence`. You can have a try, I will file a PR to homebrew-core if the name and formula were ok.
> 
> ```
> % brew untap git-hulk/cadence
> % brew tap git-hulk/cadence
> % brew install uber-cadence
> ```
> 
> ```
> cadence-server --root /usr/local/etc/cadence start
> 2021/03/16 11:18:49 Loading config; env=development,zone=,configDir=/usr/local/etc/cadence/config
> 2021/03/16 11:18:49 Loading configFiles=[/usr/local/etc/cadence/config/base.yaml /usr/local/etc/cadence/config/development.yaml]
> 2021/03/16 11:18:49 gocql: unable to dial control conn 127.0.0.1: dial tcp 127.0.0.1:9042: connect: connection refused
> ```

If adding other binaries like server and sql/cassandra tool, is it possible to add other folders from release like "config/ schema/? Because cadence-server and sql/cassandra tool is relying on them to run. Without those files the binary is not going to be very useful.

**Comment by git-hulk** [comment]
the config file has copied into ` /usr/local/etc/cadence/` dir but the not schema, I would have a look at the schema path.

**Comment by git-hulk** [comment]
Hello, @longquanzheng  I have added the cadence server/tools and schema files into brew install. You can have a look at it:

https://github.com/git-hulk/homebrew-cadence

: )

**Comment by longquanzheng** [comment]
https://github.com/Homebrew/homebrew-core/pull/74494
