### ISSUE TITLE
Wildcard search for workflows

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3962]
**Is your feature request related to a problem? Please describe.**
Need to search using LIKE operator with search attributes? eg, WorkflowType LIKE `workflowType-prefix.*` 
Right now the workflowType is using keyword type for performance reason so it doesn't support wildcard search.

https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html
```
keyword fields are untokenized but slow at performing wildcard queries (especially patterns with leading wildcards).
```
**Proposed Solution**
Option 1: Change some field from keyword to wildcard
Option 2: Add a new customWildcardField like the customStringField: https://github.com/uber/cadence/blob/master/schema/elasticsearch/v7/visibility/index_template.json#L51

And let the CLI command support Wildcard query 

**Additional context**
https://uber-cadence.slack.com/archives/CL22WDF70/p1612547454065200

For now, user may do option1 on theirselves and then construct the query and send to ES directly if they want to use it.

**Comment by Ikonwa** [comment]
https://vulte.ng/referee/ac453d23c4aa423d8cce6564942c46f8

**Comment by prithvi2226** [comment]
Hey 

> **Is your feature request related to a problem? Please describe.** Need to search using LIKE operator with search attributes? eg, WorkflowType LIKE `workflowType-prefix.*` Right now the workflowType is using keyword type for performance reason so it doesn't support wildcard search.
> 
> https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html
> 
> ```
> keyword fields are untokenized but slow at performing wildcard queries (especially patterns with leading wildcards).
> ```
> 
> **Proposed Solution** A clear and concise description of what you want to happen. Option 1: Change some field from keyword to wildcard Option 2: Add a new customWildcardField like the customStringField: https://github.com/uber/cadence/blob/master/schema/elasticsearch/v7/visibility/index_template.json#L51
> 
> And let the CLI command support Wildcard query
> 
> **Additional context** https://uber-cadence.slack.com/archives/CL22WDF70/p1612547454065200
> 
> For now, user may do option1 on theirselves and then construct the query and send to ES directly if they want to use it.

Hey @longquanzheng ! this issue has piqued my interest into contributing to this workflow engine. Was wondering if this issue is still active and open? Thanks
