### ISSUE TITLE
schema update: terminate self on schema version mismatch

### ISSUE THREAD

**Issue by venkat1109** [uber/cadence#398]
Today, when someone accidentally updates the schema to a version that's incompatible with the server code, the behavior is undefined. Since the schema is already versioned, a somewhat better approach here would be for the server to watch the schema version in the background and abort itself when there is a mismatch.

**Comment by madhuravi** [comment]
Created an issue for this already :) https://github.com/uber/cadence/issues/397

**Comment by madhuravi** [comment]
closing as duplicate
