### ISSUE TITLE
.gen: rename subdirectory for 1.16 compatibility

### ISSUE THREAD

**Issue by buyology** [uber/cadence#3980]
Starting from 1.16:

>  In module mode, the <code>go</code> command now disallows import paths that
>  include non-ASCII characters or path elements with a leading dot character
>  (<code>.</code>). Module paths with these characters were already disallowed, […]
>  so this change affects only paths within module subdirectories.

So attempting to compile packages depending on `uber/cadence` will fail with:

```
../../vendor/go.uber.org/cadence/internal/client.go:30:2: malformed import path "go.uber.org/cadence/.gen/go/cadence/workflowserviceclient": leading dot in path element
../../vendor/go.uber.org/cadence/internal/internal_workflow_testsuite.go:39:2: malformed import path "go.uber.org/cadence/.gen/go/cadence/workflowservicetest": leading dot in path element
../../vendor/go.uber.org/cadence/internal/activity.go:29:2: malformed import path "go.uber.org/cadence/.gen/go/shared": leading dot in path element
```

As per https://github.com/golang/go/issues/43985#issuecomment-777809802:

> **The only specific affected module we know of so far is go.uber.org/cadence**, but because the affected import statement is an internal package it could be fixed for external consumers by an internal-only change within a patch release for that module (namely, **moving the packages currently in the .gen subdirectory to another location and updating the imports within the module)**. 

(emphasis added)

**Comment by Groxx** [comment]
Yea, seems like it's picky all the time.  With just `eval "$(gimme 1.16)"` and:
```go
// main.go
package main
import "go.uber.org/cadence/workflow"
func main() {
    _ = workflow.NewDisconnectedContext()
}

// go.mod
module temp
```
I get (among other failures):
```
go: downloading golang.org/x/text v0.3.0
temp imports
	go.uber.org/cadence/workflow imports
	go.uber.org/cadence/.gen/go/shared: malformed import path "go.uber.org/cadence/.gen/go/shared": leading dot in path element
```
so this probably has to be done pretty soon.

**Comment by buyology** [comment]
Looks like this is going to be relaxed in 1.16.1: https://github.com/golang/go/issues/43985#issuecomment-786866468

**Comment by Groxx** [comment]
Excellent.  Thank you for the update!  I'll wait on these, it'd be better to not force the breakage if we don't have to.

**Comment by buyology** [comment]
With the [recent 1.16.2 release](https://github.com/golang/go/issues?q=milestone%3AGo1.16.2+label%3ACherryPickApproved) this is no longer an issue. Closing.
