### ISSUE TITLE
Bug: Canary tries to create a domain with retention=0 which is not allowed by the default MinRetention

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3985]
See https://github.com/uber/cadence/blob/663f74cf81acb69aad1db3451b9201da89a5653a/canary/client.go#L54

And https://github.com/uber/cadence/blob/663f74cf81acb69aad1db3451b9201da89a5653a/common/domain/const.go#L27

**Comment by yycptt** [comment]
Retention = 0 is required for the archival canary test to pass I think.

In the default dynamicconfig for local environment we have set the min retention day to 0. https://github.com/uber/cadence/blob/master/config/dynamicconfig/development.yaml#L4

For other environments the domain should be manually registered for now. This is a known issue: https://github.com/uber/cadence/issues/2001

We can probably add a logic in canary to only register the domain in local/development environment.
