### ISSUE TITLE
archived workflows not appearing in cadence ui

### ISSUE THREAD

**Issue by makaeladalley** [uber/cadence#3986]
My team is currently using a filestore implementation of history archival. I've inserted that section of the config template below. We are running into an issue where our archived workflows are not appearing in the cadence ui. 

We have confirmed the workflows outside of our set retention period are being properly archived to the default filestore location `"file:///tmp/cadence_archival/development"` and we do have history & visibility archival enabled for all of our domains. However, we are unable to see any workflows on the archival page of the cadence ui. We've been stuck for a couple weeks trying to find a solution to this issue.

Don't hesitate to reach out if you need more information about our setup - ANY help here would be greatly appreciated. Thank you!

**Comment by makaeladalley** [comment]
`    archival:
      
      history:
        status: "enabled"
        enableRead: true
        provider:
          filestore:
            fileMode: "0666"
            dirMode: "0766"
      visibility:
        status: "enabled"
        enableRead: true
        provider:
          filestore:
            fileMode: "0666"
            dirMode: "0766"
    domainDefaults:
      archival:
        history:
          status: "enabled"
          URI: "file:///tmp/cadence_archival/development"
        visibility:
          status: "enabled"
          URI: "file:///tmp/cadence_vis_archival/development"`

**Comment by yycptt** [comment]
Are you able to get archived workflow history or visibility records through CLI commands?

History:
`cadence --do <domain> workflow show --wid <archived workflowID> --rid <archived workflow runID>`
This is the same command as getting non-archived history, it will also automatically check archival is history not found in the main storage.


Visibility:
`cadence --do <domain> workflow listarchived -q <visibility query>`
For filestore the query will look like `WorkflowType = "xxx"` or `CloseTime >= <nano value or time string in time.RFC3339 format>`

**Comment by erikpaulmiller** [comment]
I believe the issue might lie in the fact that we (@makaeladalley) are using a helm chart and 4 containers for the server level (ie history/frontend/worker/matching are separated) and the visibility and history files are stored locally and not in a shared / accessible location for all.  Has anyone seen this?
