### ISSUE TITLE
Scavenger in postgres missing task lists leading to build-up of cruft

### ISSUE THREAD

**Issue by kraney** [uber/cadence#4018]
**Describe the bug**
When using the Postgres DB layer, there's a scavenger than runs to clean up expired tasks and task lists. There's a bug in the query that does this that makes it skip potentially large numbers of task lists, and as a result those never get cleaned up.

Roughly speaking, the query as written will scavenge at most the first 32 task lists in each domain.

**To Reproduce**
Is the issue reproducible? 
Yes

**Steps to reproduce the behavior:**
 1. Run cadence using the postgres storage driver
 2. Run workflows over the course of at least 12 hours. (Scavenger runs at 12-hour intervals)
 3. Look for stale entries in the task_lists table that should have expired. Many will, but some may not.

**Expected behavior**

Old task_lists entries and tasks entries should be deleted.

**Comment by longquanzheng** [comment]
Fix is merged
