### ISSUE TITLE
version tag in server binary is wrong(never updated)

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4052]
**Describe the bug**
https://github.com/uber/cadence/blame/1de8cd411c79c4b869a5cf83a51b576818e5f85c/cmd/server/cadence/cadence.go#L158

it should be consistent with the released tag.

**To Reproduce**
Is the issue reproducible? 
- yes

**Steps to reproduce the behavior:**
```
./cadence-server
NAME:
   cadence - Cadence server

USAGE:
   cadence-server [global options] command [command options] [arguments...]

VERSION:
   0.0.1

COMMANDS:
   start,   start cadence server
   help, h  Shows a list of commands or help for one command
```

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here, E.g. Stackstace, workflow history.

**Comment by git-hulk** [comment]
How about refactoring the CHANGELOG with a more readable format and read the version from it when compiling? like:

https://github.com/bitleak/kvrocks/blob/unstable/Changelog#L3

It is as simple as reading the version from the first line and last field

**Comment by longquanzheng** [comment]
> compiling

that means the version is depending on the changelog. Distribution of the binary must be with the file, which is not what we are doing today.

**Comment by longquanzheng** [comment]
> How about refactoring the CHANGELOG with a more readable format and read the version from it when compiling? like:
> 
> https://github.com/bitleak/kvrocks/blob/unstable/Changelog#L3
> 
> It is as simple as reading the version from the first line and last field

I believe the right way to do it is using build time variable, like that introduced in this blog: https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications
We can do it with our dockerfile

**Comment by git-hulk** [comment]
> > How about refactoring the CHANGELOG with a more readable format and read the version from it when compiling? like:
> 
> > 
> 
> > https://github.com/bitleak/kvrocks/blob/unstable/Changelog#L3
> 
> > 
> 
> > It is as simple as reading the version from the first line and last field
> 
> 
> 
> I believe the right way to do it is using build time variable, like that introduced in this blog: https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications
> 
> We can do it with our dockerfile

yeah, what I mean was also set the version when building with ldflags and the version can be extracted from CHANGELOG

**Comment by longquanzheng** [comment]
> > > How about refactoring the CHANGELOG with a more readable format and read the version from it when compiling? like:
> > 
> > 
> > > 
> > 
> > 
> > > https://github.com/bitleak/kvrocks/blob/unstable/Changelog#L3
> > 
> > 
> > > 
> > 
> > 
> > > It is as simple as reading the version from the first line and last field
> > 
> > 
> > I believe the right way to do it is using build time variable, like that introduced in this blog: https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications
> > We can do it with our dockerfile
> 
> yeah, what I mean was also set the version when building with ldflags and the version can be extracted from CHANGELOG

got it. Yeah that works too. I was thinking about using the version from the version tag we passed in as image tag. What you suggests is probably more doable. Thanks

**Comment by git-hulk** [comment]
hi @longquanzheng  Would you file a PR to fix this issue?

**Comment by longquanzheng** [comment]
> > > > How about refactoring the CHANGELOG with a more readable format and read the version from it when compiling? like:
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > https://github.com/bitleak/kvrocks/blob/unstable/Changelog#L3
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > It is as simple as reading the version from the first line and last field
> > > 
> > > 
> > > I believe the right way to do it is using build time variable, like that introduced in this blog: https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications
> > > We can do it with our dockerfile
> > 
> > 
> > yeah, what I mean was also set the version when building with ldflags and the version can be extracted from CHANGELOG
> 
> got it. Yeah that works too. I was thinking about using the version from the version tag we passed in as image tag. What you suggests is probably more doable. Thanks

actually, I think using ChangeLog is not right. The version should only follow the release tag. For example, the latest master branch shouldn't use 0.19 or 0.18, because they are not. The version should only be provided when we release, providing through docker build image. 

The default version tag, however should be unknown version, may be 0.0 instead of 0.01

**Comment by git-hulk** [comment]
I agreed the latest master should be an unknown version, but it's weird that the version also is unknown when building from the source.

**Comment by longquanzheng** [comment]
> I agreed the latest master should be an unknown version, but it's weird that the version also is unknown when building from the release source.

that's a good point. We should provide instructions in the README that when building from release tag, you can add the release version with it, does that work for you?

**Comment by git-hulk** [comment]
aha, it's ok for me.

**Comment by longquanzheng** [comment]
> aha, it's ok for me.

sounds good. This should be very simple work. I will find some time to do it. For the existing releases, you probably can cherry-pick into the version tag that you are building.

**Comment by git-hulk** [comment]
cool, thanks @longquanzheng
