### ISSUE TITLE
Expose Kafka version for configuration 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4068]
https://github.com/uber/cadence/blob/28fd61d8e83e0439476b57b37527b4a1c9bc51a0/common/messaging/kafka/clientImpl.go#L91

This need to be allowed to configured, so that Cadence can work with different versions of Kafka.

**Comment by mistikel** [comment]
I would like to take this one @longquanzheng

**Comment by longquanzheng** [comment]
done in https://github.com/uber/cadence/pull/4072
