### ISSUE TITLE
Proposal: TLS authentication/encryption support for gRPC

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4095]
**Is your feature request related to a problem? Please describe.**
Similar to this closed issue https://github.com/uber/cadence/issues/2018 
We should provide TLS options/configuration for clients talking to Cadence server.

**Proposed Solution**
There could be two steps:
* For external clients talking to server, It seems pretty straightforward if following https://grpc.io/docs/guides/auth/ This is highest priority. 
* For Cadence server nodes talking to each others and cross cluster/XDC also require to configure private key to Cadence server

**Additional context**
This is only for authentication. 
Authorization is in https://github.com/uber/cadence/issues/3920 and we are working on JWT/OAuth based authorization.

**Comment by tfcace** [comment]
Hi @longquanzheng, the definition of "clients talking to Cadence server" may be ambiguous.
For starters, I came here from our Slack discussion over gRPC and AuthN, and expected to also see something relating to AuthN in the `cadence-web` (falls under _client to Cadence server_).

Additionally, your second bullet confuses me, as AFAIK, clients communicate with the Cadence server over the frontend service at 7933, yet you state that this port will continue to use TChannel. In that regard, I would have expected Workers to also be able to authenticate against the frontend.

Thanks in advance :)

**Comment by longquanzheng** [comment]
@tfcace thanks for the feedback. 

Yeah, the "clients" here include `cadence-web` and SDK starter/worker. As long as they use gRPC library to send requests with TLS, server will accept the requests.

To understand the second point -- All services including Frontend/Matching/History/Worker will continue to use TChannel for intercommunication. As we don't have a replacement for Ringpop yet, which is implemented based on TChannel. Therefore each service will have to expose two port -- a gRPC port and a TChannel port. External traffic from "clients" -- worker/starter/web will only need to talk to the gRPC port, which TChannel port is for internal purpose. 

For certificates -- Cadence server will only need to be configured with public key for validation. It's all up to users to manage certificates.
