### ISSUE TITLE
Archived workflows are visible in `archived tab` before retention period

### ISSUE THREAD

**Issue by polyansky-syberry** [uber/cadence#4096]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: master-auto-setup
- Client version: 2.7.8
- Client langauge: Java

**Describe the bug**
After setting GCP archival with retention of 1 day, I am able to see all workflows execution in both tabs: `workflow` and `archival`

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
Update config_template.yaml as follows:
![image](https://user-images.githubusercontent.com/65544802/113093909-76be4f80-91f9-11eb-8e46-6886c2a39fc2.png)
Set values for the variables in compose file:
![image](https://user-images.githubusercontent.com/65544802/113093993-99e8ff00-91f9-11eb-8a2e-fc023f33a4cb.png)

Run a workflow.

**Expected behavior**
Before retention period archival tab is clean

**Screenshots**
![image](https://user-images.githubusercontent.com/65544802/113092684-22b26b80-91f7-11eb-8814-f0adfee8ce19.png)
![image](https://user-images.githubusercontent.com/65544802/113092703-2e059700-91f7-11eb-80a4-bd83923d8fc5.png)

**Comment by meiliang86** [comment]
This is by design, as your workflow is archived at **close** time, and will be removed from DB after **retention**. Retention happens usually after workflow close.

**Comment by longquanzheng** [comment]
@polyansky-syberry  Let me add more explanation: there are two features: history archival and visibility archival. 
Visibility is archived when workflow is closed, disregarding the domain retention. 

The domain retention will apply on to history archival : when history is about to delete, Cadence will archive the history before deletion. 

This sounds a bit weird. But visibility records is much smaller than history, so there is no need to make the optimization. Instead, put the visibility record into archival when workflow closing.

**Comment by longquanzheng** [comment]
I confirmed that it is working as expected.  

When runnning
```
cadence --do samples-domain wf listarchived -q "WorkflowType='main.helloWorldWorkflow'"
```
 can return all closed workflow that with and without history archived, if you use 
```
cadence --do samples-domain wf show -w <workflowID>
```
will only return you workflow that are not archived. 
If you need to get history that are archived, a RunID is required:
```
cadence --do samples-domain wf show -w <workflowID> -r <runID>
```

**Comment by longquanzheng** [comment]
Here is some improvement to help 
https://github.com/uber/cadence/pull/4112

**Comment by polyansky-syberry** [comment]
Got it. Thank you for the response, it was very useful for me.
