### ISSUE TITLE
Flaky integration test

### ISSUE THREAD

**Issue by meiliang86** [uber/cadence#4103]
The following postgres test seems to fail very often. Check the latest buildkite runs.

--- FAIL: TestIntegrationSuite/TestCronWorkflow (8.48s)
--
  | integrationTest.go:1251:
  | Error Trace:	integrationTest.go:1251
  | Error:      	Not equal:
  | expected: 0
  | actual  : 2
  | Test:       	TestIntegrationSuite/TestCronWorkflow
  | Messages:   	Still Flaky?: backoffSeconds: 2 ((1617319554003603000-1617319551908876000) - (1617319552003603000-1617319552002996000)), targetBackoffSeconds: 3

**Comment by longquanzheng** [comment]
related to https://github.com/uber/cadence/issues/3540

**Comment by longquanzheng** [comment]
The bug is because after refactoring, this line of code is not working anymore 
https://github.com/uber/cadence/blob/7bd91051360214181464b87325615631a1712bb7/host/integrationTest.go#L1237

**Comment by longquanzheng** [comment]
Close this one, but we will still need to fix #3540
