### ISSUE TITLE
Expose remaining retries in `workflow.Context`

### ISSUE THREAD

**Issue by tcrayford** [uber/cadence#4113]
**Is your feature request related to a problem? Please describe.**

We have a service that tracks "this workflow errored", to display errors to the customer, but we want that to only be triggered when there are no more retries left and the workflow has definitely errored.

**Proposed Solution**

@longquanzheng says there's a retry counter, but it's not currently exposed. See https://uber-cadence.slack.com/archives/CM4K75Y7R/p1617639731019300?thread_ts=1617628906.014100&cid=CM4K75Y7R

**Additional context**

None

**Comment by yycptt** [comment]
Is your workflow retry policy based on expiration time or maximum attempts? If it's the second one, I think `workflow.Info` returned by `workflow.GetInfo(ctx)` contains an `Attempt` field that can be used.

https://github.com/uber-go/cadence-client/blob/master/workflow/workflow.go#L177 
https://github.com/uber-go/cadence-client/blob/b1375e6a0c919655685bc4b4e275ce8204f89d54/internal/workflow.go#L736

**Comment by longquanzheng** [comment]
@tcrayford I closed this issue. But feel free to open it again if you still need help
