### ISSUE TITLE
Add requestID field to createWorkflowExecution request

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#412]
I'm trying to start workflow using Java TChannel client. I'm getting the following error when running against the local docker:

InternalServiceError(message:CreateWorkflowExecution operation failed. Error: invalid UUID "")
It looks like the error is returned by cassandraPersistence:
https://github.com/uber/cadence/blob/master/common/persistence/cassandraPersistence.go#L756

The relevant server log entries:

cadence_1    | time="2017-11-11T18:26:51Z" level=debug msg="Received StartWorkflowExecution. WorkflowID: 5ed7391d-612b-4aa6-a8d0-4742b9ee22b6" Service=cadence-frontend
cadence_1    | time="2017-11-11T18:26:51Z" level=debug msg="Start workflow execution request domain: test" Service=cadence-frontend
cadence_1    | time="2017-11-11T18:26:51Z" level=debug msg="Start workflow execution request domainID: f09d79d9-ebfe-4941-97c1-f173b34db4da" Service=cadence-frontend
cadence_1    | time="2017-11-11T18:26:51Z" level=info msg="Created RPC dispatcher outbound for service 'cadence-history' for host '172.19.0.4:7934'"
cadence_1    | time="2017-11-11T18:26:51Z" level=debug msg="Assigning transfer task ID: 1048576" Service=cadence-history shard-id=0 wf-component=shard-controller
cadence_1    | time="2017-11-11T18:26:51Z" level=debug msg="Assigning new timer (timestamp: 2017-11-11 18:27:11.446508875 +0000 UTC, seq: 1048577) ackLeveL: 0001-01-01 00:00:00 +0000 UTC" Service=cadence-history shard-id=0 wf-component=shard-controller
cadence_1    | time="2017-11-11T18:26:51Z" level=info msg="Range updated for shardID '0'.  RangeID: 2, StartSequence: 2097152, EndSequence: 3145728" Service=cadence-history shard-id=0 wf-component=shard-controller wf-event-id=3000

**Comment by mfateev** [comment]
I've validated that workflow creation through Cadence CLI succeeds against the same docker service instance.

**Comment by mfateev** [comment]
The root cause is missing requestID field in the createWorkflowExecution request. Keeping the issue open until Cadence service reports this missing field better than InternalServiceError.

**Comment by yux0** [comment]
Added validation of request id in StartWorkflowExecution.
PR: https://github.com/uber/cadence/pull/1319
