### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [uber/cadence#4124]
(base) [jw@cn05 cadence]$ sudo HTTP_PROXY=<...> HTTPS_PROXY=<...> -j1 release
make --no-print-directory go-generate
running go generate ./..., this takes almost 5 minutes...
go: downloading go.uber.org/cadence v0.16.1-0.20210330222409-fcc703e94e2f
go: downloading go.uber.org/yarpc v1.52.1-0.20210303193224-b2caa40d56b6
go: downloading go.uber.org/zap v1.13.0
go: downloading cloud.google.com/go v0.56.0
go: downloading go.uber.org/thriftrw v1.25.0
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading go.uber.org/atomic v1.5.1
go: downloading google.golang.org/api v0.26.0
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading go.uber.org/fx v1.10.0
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading golang.org/x/net v0.0.0-20201031054903-ff519b6c9102
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading gonum.org/v1/gonum v0.7.0
go: downloading go.uber.org/multierr v1.4.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.3.0
go: downloading golang.org/x/text v0.3.4
go: downloading gopkg.in/validator.v2 v2.0.0-20180514200540-135c24b11c19
go: downloading github.com/jmoiron/sqlx v1.2.1-0.20200615141059-0794cb1f47ee
go: downloading google.golang.org/protobuf v1.25.0
updating copyright headers
.bin/copyright
touch: cannot touch '.build/copyright': No such file or directory
make[2]: *** [Makefile:325: copyright] Error 1
make[1]: *** [Makefile:379: go-generate] Error 2
make: *** [Makefile:382: release] Error 2
(base) [jw@cn05 cadence]$

**Comment by longquanzheng** [comment]
what command did you execute?

**Comment by LutzWeischerFujitsu** [comment]
Sorry, ;-). 

sudo HTTP_PROXY=<...> HTTPS_PROXY=<...> make VERBOSE=1 -j1 release
