### ISSUE TITLE
[Feature Request]  return search attributes that can be used advanced visibility 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4139]
**Is your feature request related to a problem? Please describe.**
It will make https://github.com/uber/cadence-web/issues/281 possible 

**Proposed Solution**
Return the data from this value: https://github.com/uber/cadence/blob/d0a8f7e6a9297bd898ea5b10ded20f0277a8980f/service/frontend/adminHandler.go#L190

add this to the existing API “describeCluster” 

follow these two PRs:
https://github.com/uber/cadence-idl/pull/62
https://github.com/uber/cadence/pull/4136

To add the information
**Additional context**
N/A

**Comment by neel229** [comment]
Can I take this issue?

**Comment by longquanzheng** [comment]
> Can I take this issue?

Absolutely. Actually it’s better to add this to the existing API “describeCluster” 

you can follow these two PRs:
https://github.com/uber/cadence-idl/pull/62
https://github.com/uber/cadence/pull/4136

**Comment by neel229** [comment]
I guess the PR solving this issue has already merged right?

**Comment by longquanzheng** [comment]
> I guess the PR solving this issue has already been merged right?

Which PR? No, I thought you will open new PR to solve it

**Comment by neel229** [comment]
Okay, I actually thought that we have to make an api which returned the attributes which would then later on used by the search feature and I thought it was completed by PR#4136

**Comment by neel229** [comment]
> > I guess the PR solving this issue has already been merged right?
> 
> Which PR? No, I thought you will open new PR to solve it 

Yup, that was the plan :)

**Comment by longquanzheng** [comment]
> Okay, I actually thought that we have to make an api which returned the attributes which would then later on used by the search feature and I thought it was completed by PR#4136

No, that PR only return  persistence info. We want the ES valid fields info here. So you will open a new PR to return it like that PR

 I link to that PR just for you to follow

**Comment by longquanzheng** [comment]
> > > I guess the PR solving this issue has already been merged right?
> > 
> > 
> > Which PR? No, I thought you will open new PR to solve it
> 
> Yup, that was the plan :)

Thanks 😃lmk if you still have questions

**Comment by neel229** [comment]
> > Okay, I actually thought that we have to make an api which returned the attributes which would then later on used by the search feature and I thought it was completed by PR#4136
> 
> No, that PR only return persistence info. We want the ES valid fields info here. So you will open a new PR to return it like that PR
> 
> I link to that PR just for you to follow

Okay, I guess I have concrete view of the problem now.

**Comment by longquanzheng** [comment]
@neel229 
I am so sorry, just realized that the API actually already exists: https://github.com/uber/cadence/blob/30702c2e0620d7176da5847221029a9dfb3013fa/service/frontend/workflowHandler.go#L3057

If you are still interested in contributing, would you mind moving to this one? https://github.com/uber/cadence/issues/3962
