### ISSUE TITLE
Introduce wildcard search for advanced search visibility

### ISSUE THREAD

**Issue by spmistry** [uber/cadence#4141]
**Is your feature request related to a problem? Please describe.**
Need to generate custom attributes that can be indexed and searched for ES 7.9+ 
Would be worth having the same wildcard search flexibility for some of the available search attributes as well.

**Proposed Solution**
Introduce new custom wildcard field. ==> CustomWildcardField
Would be worth switching a bunch of search Attributes to all use wildcard search since its a drop in replacement for keyword search but that would expect different handing across ES versions below 7.9
* DomainID
* WorkflowID    
* WorkflowType 

**Additional context**
[Elastic Ref](https://www.elastic.co/elasticon/archive/2020/global/elasticsearch-introducing-the-wildcard-field)
Would also help with Issue #3962

**Comment by ibarrajo** [comment]
Closing this issue, since related one was closed: https://github.com/uber/cadence/issues/3962
