### ISSUE TITLE
"Failed to update DNS" error logs 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4143]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: 
- Client version:
- Client langauge:

**Describe the bug**
Error logs in 
**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
A clear and concise description of the reproduce steps.
Run 0.20.0 in prod

**Expected behavior**

**Screenshots**
<img width="571" alt="Screen Shot 2021-04-19 at 10 12 25 AM" src="https://user-images.githubusercontent.com/4523955/115276430-d83a5580-a0f7-11eb-9f9d-896ab0bc8919.png">

**Additional context**
Add any other context about the problem here, E.g. Stackstace, workflow history.

**Comment by longquanzheng** [comment]
This is due to misconfig:
https://github.com/uber/cadence/blob/30702c2e0620d7176da5847221029a9dfb3013fa/config/development.yaml#L113
https://github.com/banzaicloud/banzai-charts/blob/a92b3c1cc1b63c654f625c9a53828aeb7b75aeac/cadence/templates/server-configmap.yaml#L174

 these two configurations, should both be the frontend DNS

**Comment by Gurpartap** [comment]
> This is due to misconfig:
> 
> https://github.com/uber/cadence/blob/30702c2e0620d7176da5847221029a9dfb3013fa/config/development.yaml#L79
> 
> https://github.com/uber/cadence/blob/30702c2e0620d7176da5847221029a9dfb3013fa/config/development.yaml#L113
> 
> these two configurations, should both be the frontend DNS
> 
> See examples in https://github.com/banzaicloud/banzai-charts/blob/a92b3c1cc1b63c654f625c9a53828aeb7b75aeac/cadence/templates/server-configmap.yaml#L174

For those of us deploying the docker images directly, there are some new environment variables to set:

```
FRONTEND_SERVICE           = "cadence-frontend.service.consul"
PRIMARY_FRONTEND_SERVICE   = "cadence-frontend.service.consul"
SECONDARY_FRONTEND_SERVICE = "cadence-frontend.service.consul"
```

https://github.com/uber/cadence/pull/4084 – [pr diff](https://github.com/uber/cadence/pull/4084/files)
