### ISSUE TITLE
Feature request: Dashboard to view workflow information

### ISSUE THREAD

**Issue by ryanwalls** [uber/cadence#418]
Similar to SWF, it would be great if there was a dashboard to view workflow/activity status and the event history.  

Something simple like was used here would be a good starting point: https://www.youtube.com/watch?v=-LRghQzfF8k

**Comment by mfateev** [comment]
We are currently working on open sourcing the Cadence UI. I'm going to keep this issue open until it is released.

**Comment by samarabbas** [comment]
Today we open sourced the web UI for Cadence server: https://github.com/uber/cadence-web

**Comment by samarabbas** [comment]
@ryanwalls give it a try and resolve this task if you think this is good enough for your needs.

**Comment by samarabbas** [comment]
@ryanwalls closing this issue for now.  Feel free to file feature requests on [cadence-web](https://github.com/uber/cadence-web) repo.

**Comment by ryanwalls** [comment]
@samarabbas Thanks.  This is working well for us!  Sorry I forgot to report back.
