### ISSUE TITLE
Support Cassandra 4.x and add warning/error logs when using 3.x after year of 2033

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4200]
About https://github.com/uber/cadence/blob/9b4aaa67a447e5158eb5a0c0a1dfdc9239352f68/common/persistence/cassandra/cassandraVisibilityPersistence.go#L45

(Yeah I know it's just 2021 today)

By the time of 2033, users should use Cassandra version 4.0+(Cadence should have support it), otherwise Cadence will not be able to clean up some records with TTL

This is because the max support time is 2038-01-19T03:14:06+00:00 in Cassandra 2.x/3.x using int32 presentation
See more details in https://issues.apache.org/jira/browse/CASSANDRA-14092 , https://en.wikipedia.org/wiki/Year_2038_problem  and
 https://fossies.org/linux/apache-cassandra/CASSANDRA-14092.txt

**Comment by rmcotton-emporix** [comment]
i think given cassandra 3 versions are EOL and PaaS solutions are already stating to not support Cassandra 3 is probably more of a driver to support Cassandra 4. Are there any plans?

https://cassandra.apache.org/_/download.html
https://www.instaclustr.com/blog/instaclustrs-support-for-cassandra/

**Comment by demirkayaender** [comment]
Cadence has been on v4 for a while and plan to switch to v5 whenever it's validated
