### ISSUE TITLE
Using error struct instead of additional return parameter

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4273]
Using error struct instead of additional return parameter is a standard of Golang.
We should change the interfaces in shardCRUD and taskCRUD to follow it. 

https://github.com/uber/cadence/blob/6e3a78deba86530e069aeeeac27be561b7594d96/common/persistence/nosql/nosqlplugin/interfaces.go#L195

https://github.com/uber/cadence/blob/6e3a78deba86530e069aeeeac27be561b7594d96/common/persistence/nosql/nosqlplugin/interfaces.go#L326

Also queueCRUD

And then remove IsConditionFailedError from the interface to be consistent

**Comment by yycptt** [comment]
@longquanzheng I guess it is done and we can close the issue?

**Comment by longquanzheng** [comment]
Yes 👍
