### ISSUE TITLE
Memory leak in executing cadence workflows

### ISSUE THREAD

**Issue by suman-anand-grab** [uber/cadence#4274]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: v0.10.5
- Client version: v0.10.5
- Client langauge: Golang

**Describe the bug**
We have observed that propagateCancel method seems to be holding on to the memory over the period of time and doesn't get garbage collected. As a result it results in a gradual memory spike. This can be seen in the memory snapshot attached where the execution begins from processTask of *baseWorker and we use activityTaskHandler for executing the activities

**To Reproduce**
Is the issue reproducible? 
- [No]

**Steps to reproduce the behavior:**
This has only happened in the production environment so far. We haven't been able to replicate it yet

**Expected behavior**
Ideally the code shouldn't be holding on to the memory

**Screenshots**
<img width="661" alt="Screen Shot 2021-06-15 at 9 35 18 AM" src="https://user-images.githubusercontent.com/34230289/121979957-affc6980-cdbd-11eb-95de-717d31fb41ef.png">

**Additional context**
Add any other context about the problem here, E.g. Stackstace, workflow history.

**Comment by longquanzheng** [comment]
Thanks for reporting.

The screenshot shows that memory leak is in client, not server. Can you upgraded to the latest version to see if that still exists? It will be much easier to fix on the latest version.

**Comment by suman-anand-grab** [comment]
Thanks for the update. Will give it a try with latest version

**Comment by suman-anand-grab** [comment]
Thanks for suggestion @longquanzheng . The library upgrade 0.17.0 resolved the memory leak issue :)
