### ISSUE TITLE
cadence-cli images in docker hub are not properly taged

### ISSUE THREAD

**Issue by MatthewHou** [uber/cadence#4305]
**Version of Cadence server, and client(which language)**
N/A

**Describe the bug**
The recently updated cadence cli image `ubercadence/cli:master` is version `0.19.0` and has dropped the support for older cadence server. 

The cli image in docker hub is not properly version tagged and the `master` tag keeps getting overwritten with newer versions with breaking changes.

Please properly version all (old and new) cli releases in docker hub. 

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
N/A
**Expected behavior**
All cli releases should be versioned in on docker hub
**Screenshots**
N/A
**Additional context**
N/A

**Comment by longquanzheng** [comment]
That’s a good point. We never done this in our release process. I will add it and backfill the tags today. 

Also you can try to install the older version of home brew https://stackoverflow.com/questions/68217385/what-is-clientversionnotsupportederror-and-how-to-resolve-it

**Comment by longquanzheng** [comment]
0.21.3 is uploaded. I am doing others

**Comment by longquanzheng** [comment]
ubercadence/cli:0.19.2 image is uploaded. 

Is that enough for you? @MatthewHou 

Versions older than this version cannot compile with my current setup, probably it's requiring some older Golang.
We will make sure release process to upload CLI image in the future.

**Comment by longquanzheng** [comment]
@MatthewHou `ubercadence/cli:0.20.0` should work for all server lower than 0.20 as well. That's because the CLI version doesn't change from 0.12 to 0.20

**Comment by MatthewHou** [comment]
Thank you @longquanzheng 
We are running server 0.13.0. And I've verified that cli 0.20.0 works as expected

**Comment by longquanzheng** [comment]
Also instruction to install old CLI via homeberw: https://github.com/uber/cadence/discussions/4457
