### ISSUE TITLE
Mutable State and History Events may be out of sync when DB timeout happens

### ISSUE THREAD

**Issue by Shaddoll** [uber/cadence#4316]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: 0.22.x

**Describe the bug**
When DB timeout happens, mutable state and history events of a workflow may be out of sync which will cause history corruption. Here is an example of history corruption,

```
{
    "branch_id": "ab57643b-b75e-4be1-b29b-6ba1290f986c",
    "node_id": 446,
    "payload": "WQ8ACgwAAAABCgAKAAAAAAAAAb4KABQWkBcMF6WZ+AgAHgAAAAUKACMAAAAAAAAAAAoAJAAAAAACYAcPDABaCgAKAAAAAAAAAbwLABQAAAAmMTE4QGFnZW50NzQ2OS1kY2E4QGNhZGVuY2UtYmVuY2gtdGwtMTQLAB4AAAAkNTg2ZjFhODctMDE4ZC00ZWY2LTk0NDMtOTk2YTk3ODNkNzJiAAAA",
    "payload_encoding": 1,
    "shard_id": 5404,
    "tree_id": "ca82b07a-2fab-4eda-a70d-844a49b24f6a",
    "txn_id": -39847696
}
{
    "branch_id": "ab57643b-b75e-4be1-b29b-6ba1290f986c",
    "node_id": 446,
    "payload": "WQ8ACgwAAAACCgAKAAAAAAAAAb4KABQWkBcJQ9uEWwgAHgAAAAcKACMAAAAAAAAAAAoAJAAAAAACYAcKDABuCgAKAAAAAAAAAbwKABQAAAAAAAAAAAgAHgAAAAEAAAoACgAAAAAAAAG/CgAUFpAXCUPbqrkIAB4AAAAECgAjAAAAAAAAAAAKACQAAAAAAmAHCwwAUAwACgsACgAAABNjYWRlbmNlLWJlbmNoLXRsLTE0AAgAFAAAAB4KAB4AAAAAAAAAAAAAAA==",
    "payload_encoding": 1,
    "shard_id": 5404,
    "tree_id": "ca82b07a-2fab-4eda-a70d-844a49b24f6a",
    "txn_id": -39847692
}
{
    "branch_id": "ab57643b-b75e-4be1-b29b-6ba1290f986c",
    "node_id": 448,
    "payload": "WQ8ACgwAAAABCgAKAAAAAAAAAcAKABQWkBcUpt4qkAgAHgAAABIKACMAAAAAAAAAAAoAJAAAAAACcAAADAC+CwAKAAAAAzI1OQoAFAAAAAAAAAGdAAAA",
    "payload_encoding": 1,
    "shard_id": 5404,
    "tree_id": "ca82b07a-2fab-4eda-a70d-844a49b24f6a",
    "txn_id": -40894465
}
{
    "branch_id": "ab57643b-b75e-4be1-b29b-6ba1290f986c",
    "node_id": 449,
    "payload": "WQ8ACgwAAAABCgAKAAAAAAAAAcEKABQWkBcY6nprvwgAHgAAAAUKACMAAAAAAAAAAAoAJAAAAAACcAADDABaCgAKAAAAAAAAAb8LABQAAAAmMTEwQGFnZW50OTM5Mi1kY2E4QGNhZGVuY2UtYmVuY2gtdGwtMTQLAB4AAAAkNWViZDczM2QtZjU3Zi00OGEzLThlNWItNGZkM2MyYjgzZjI3AAAA",
    "payload_encoding": 1,
    "shard_id": 5404,
    "tree_id": "ca82b07a-2fab-4eda-a70d-844a49b24f6a",
    "txn_id": -40894468
}
```

The payloads of the data are 
```
{"eventId":446,"timestamp":1625824806184524280,"eventType":"DecisionTaskStarted","version":0,"taskId":39847695,"decisionTaskStartedEventAttributes":{"scheduledEventId":444,"identity":"118@agent7469-dca8@cadence-bench-tl-14","requestId":"586f1a87-018d-4ef6-9443-996a9783d72b"}}
+++++++++++++++++++++++++
{"eventId":446,"timestamp":1625824794041353307,"eventType":"DecisionTaskTimedOut","version":0,"taskId":39847690,"decisionTaskTimedOutEventAttributes":{"scheduledEventId":444,"startedEventId":0,"timeoutType":"SCHEDULE_TO_START"}}
{"eventId":447,"timestamp":1625824794041363129,"eventType":"DecisionTaskScheduled","version":0,"taskId":39847691,"decisionTaskScheduledEventAttributes":{"taskList":{"name":"cadence-bench-tl-14"},"startToCloseTimeoutSeconds":30,"attempt":0}}
+++++++++++++++++++++++++
{"eventId":448,"timestamp":1625824842947111568,"eventType":"TimerFired","version":0,"taskId":40894464,"timerFiredEventAttributes":{"timerId":"259","startedEventId":413}}
++++++++++++++++++++++++
{"eventId":449,"timestamp":1625824861261294527,"eventType":"DecisionTaskStarted","version":0,"taskId":40894467,"decisionTaskStartedEventAttributes":{"scheduledEventId":447,"identity":"110@agent9392-dca8@cadence-bench-tl-14","requestId":"5ebd733d-f57f-48a3-8e5b-4fd3c2b83f27"}}
```

The first history event branch overwrites the second history event branch, but the following history event follows the second history event branch. So as a result, eventId 447 is missing in workflow history. The expected result is that the first event branch does NOT overwrite the second event branch.

Here is a theory explaining how this happens:

event id 444 decision task scheduled to start timed out, event id 446 and 447 is created
TX1: History event persisted
TX2: MS persist timed out -> but still in progress in database 
Close shard

-------------------------------

Reload shard, does NOT see next event id = 448, because TX2 is not committed, and next event id = 446
A decision started event arrives, and we set the event id = 446
TX3: History event persisted
TX4: Could not update MS because shard is still being locked by the `phantom` transaction
Close shard

-------------------------------

TX2 committed
Reload shard, because TX2 is commited, not the next event id = 448, but the history events does NOT contain event id 447 (the branch created by TX1 was overwritten by TX3)
TX5: History event persisted and History is corrupted
TX6: MS persisted

**Comment by yycptt** [comment]
My understanding (at least for cassandra based persistence implementation) 
TX2 is a CAS operation on range_id field. When shard is reloaded, then range_id will be increased. So either TX2 succeeds before the shard is reloaded or it is guaranteed to fail since the range_id is changed.

**Comment by Shaddoll** [comment]
The issue is because we allow a closed shard to append history events to a workflow. And it was fixed by https://github.com/uber/cadence/pull/4547
