### ISSUE TITLE
Trying to run cadence  using docker compose prometheus is exitting with code 2

### ISSUE THREAD

**Issue by niteshbisht** [uber/cadence#4331]
we are using 
below option
network_mode: host

and dependencies
prom/prometheus/:v2.26.0
prom/node-exporter:v1.1.2
ubercadence:server:v0.21.0-auto-setup
cassandra:3.11
ubercadence/web:v3.25.0
grafama/grafana:7.5.10

**Comment by longquanzheng** [comment]
Please check logs to see what errors cause it

**Comment by longquanzheng** [comment]
https://github.com/banzaicloud/banzai-charts/blob/031c49f4f1f542f60a88bb9f5fc56c22a518d773/cadence/templates/server-configmap.yaml#L158

If you pass this env as true then the cluster will be “Primary” 

So it’s not a problem at all that a cluster name is not “active”.  Active is a bad word to describe cluster name as we want to use “active”/ passive(standby) to describe if a domain is processing  write request in that cluster under XDC (replication) mode. 

Cadence repo also update the config example recently to use “primary/secondary “ instead.

**Comment by niteshbisht** [comment]
cqlsh -u cassandra -p cassandra --cqlversion=3.4.4 cassandra

now we are getting 'Waiting for cassandra to start up'

does this error comes due to different service name 
my docker container name is nitesb_cassandra_1
but the above command is trying to search with cassandra

**Comment by longquanzheng** [comment]
There must be some other error on Cassandra container. you can do ‘docker prune -all’ command to clean up the environment and retry it

**Comment by niteshbisht** [comment]
finally we are able to bring up container.
but i see that the containers are trying to update the dns and not able to resolve that in the cadence front end
"Failed to update the DNS" , service: "cadence-frontend" "error":"lookup cadence on {ip}" no such host

**Comment by longquanzheng** [comment]
> finally we are able to bring up container.
> but i see that the containers are trying to update the dns and not able to resolve that in the cadence front end
> "Failed to update the DNS" , service: "cadence-frontend" "error":"lookup cadence on {ip}" no such host

Are you using the standard docker-compose? (can you show me the command)
Or what is the configuration if you are doing some customization ?

**Comment by niteshbisht** [comment]
we are using docker in premises and not pulling any images from docker hub directly . we request to onboard docker images from docker hub.
docker compose version is 1.18.0
we are using some additional options below in each image and some path we have to mount the volume in order to make it run.
like /var/lib/cassandra
and /prometheus directory

network_mode: host
cap_drop: 
  - NET_BIND_SERVICE
  - SETUID
  - SETGUID
 user: ${id -u}:$({d -g}
security_opt:
  - no-new-privileges
  

images are below 

cassandra:3.11
prom/prometheus:v2.26.0
prom/node-exporter:v1.1.2
ubercadence/server:v0.21.0-auto-setup
ubercadence/web:v3.25.0
grafana/grafana:7.5.10
