### ISSUE TITLE
[WFOptions]Why this workflow not execute every minute？

### ISSUE THREAD

**Issue by zhangkyou** [uber/cadence#4350]
I wanna this workflow execute every minute，so I set the StartWorkflowOptions.CronSchedule = "* * * * *", but the realistic is the First DecisionTaskScheduled start  after the WorkflowExecutionStarted over 2 minutes.
![image](https://user-images.githubusercontent.com/7250068/128987522-28645d87-c76a-4aa6-b620-c2fddf3ee6c4.png)

**Comment by longquanzheng** [comment]
Do you have more details of how this is happening ? If we can reproduce it it will be easy to fix.
