### ISSUE TITLE
Install cadence/cassandra on windows 10?

### ISSUE THREAD

**Issue by ryanwalls** [uber/cadence#439]
We are migrating to cadence from SWF so that we can have a desktop based workflow solution.  We have an existing cloud SaaS product and now we are delivering an Electron.js desktop app.  

One of our requirements is to run the desktop app on Windows (Windows 10 specifically).  Anyone  tried installing cadence on a local windows machine without using Docker?  Seems like it would be feasible since Cassandra is based on Java and cadence on Go which are all cross platform.

**Comment by mfateev** [comment]
We are not aware about anyone trying it, but I don't see any reasons it wouldn't work. Here are Cassandra on windows installation instructions: https://www.guru99.com/download-install-cassandra.html. Golang runs on windows as well.

Another longer term option would be implementing different database binding for a database that it native to Windows. Here is the list of interfaces that each database should implement: https://github.com/uber/cadence/blob/master/common/persistence/dataInterfaces.go#L919:1

**Comment by mfateev** [comment]
Here is the list available database drivers and embedded databases for Go: 

https://github.com/gostor/awesome-go-storage

**Comment by ryanwalls** [comment]
@mfateev Thanks.  I'll leave this open so that I can report back on how it worked out for us.  

I like the long-term idea of creating another database binding for something like sqlite.  Will have to explore that more in the future.

**Comment by ryanwalls** [comment]
@mfateev To update you.  We got the first alpha release of our electron app working with Cadence and Cassandra.  Seems to be working well.  We would like to remove the dependency on Java, so we are serious about implementing an embedded database for cadence.  

A few setup questions...  
* Are you interested in us submitting this back to the Cadence project?  
* It seems the data interfaces are mostly CRUD operations, but I do see a few that by name seem to imply more than just CRUD.  e.g. `AppendHistoryEvents`, `CompleteTask`, `LeaseTaskList`, etc.  Are there any operations that involve more than just CRUD operations?  Is there anything native to cassandra that we would have a hard time replicating in an embedded database?
* There's an interface defined for a `ShardManager`.  https://github.com/uber/cadence/blob/master/common/persistence/dataInterfaces.go#L713-L718 Could we just no-op the operations?
* Any technical hurdles that you foresee for us?  
* Any preference on which embedded database we target? 

Thanks in advance!

**Comment by mfateev** [comment]
_- Are you interested in us submitting this back to the Cadence project?_
Absolutely! We believe that having Cassandra as the only database option is slowing our adoption. And unless we get external contributions it is not a real open source project :).

_- It seems the data interfaces are mostly CRUD operations, but I do see a few that by name seem to imply more than just CRUD. e.g. AppendHistoryEvents, CompleteTask, LeaseTaskList, etc. Are there any operations that involve more than just CRUD operations? Is there anything native to cassandra that we would have a hard time replicating in an embedded database?_
Almost all operations are conditional updates on some field (like RangeID) to ensure that only master process can mutate data. The only hard database requirement is that it must support transactional updates across multiple records with condition check. I think most embedded databases should meet this requirement. If the database supports SQL then migration would be simpler as cassandra ([CQL](http://cassandra.apache.org/doc/latest/cql/)) that is used by [cassandraPersistence](https://sourcegraph.com/github.com/uber/cadence/-/blob/common/persistence/cassandraPersistence.go) implementation is a flavor of it.

_- There's an interface defined for a ShardManager. https://github.com/uber/cadence/blob/master/common/persistence/dataInterfaces.go#L713-L718 Could we just no-op the operations?_
Shard manager is required component as it is responsible for shards lifecycle. Even if you configure your service to have just one shard it is still needed. But Looking at its implementation it is pretty simple CRUD.

_- Any technical hurdles that you foresee for us?_
As we have just one implementation it is impossible to be sure that interface is indeed database agnostic. But we are interested in multiple implementations, so if any issue arises we are going to fix it.

_- Any preference on which embedded database we target?_
The only embedded database we have production experience with is RocksDB. But it is written in C, which means an additional runtime dependency. It is also a key-value store without an SQL interface. Ideally your implementation would use [database/sql generic SQL interface](https://golang.org/pkg/database/sql/) to support any [DB that implements it](https://github.com/golang/go/wiki/SQLDrivers). I see MS SQL Server, MS ADODB and ODBC in the supported list. I also found _[Package ql](https://github.com/cznic/ql)_ which is a pure Go embedded database. It  is not in the list but  apparently implements database/sql interface as well.

**Comment by ryanwalls** [comment]
Opened PR #848 for the initial design for this implementation.

**Comment by meiliang86** [comment]
Hey @ryanwalls thanks for your proposal. We (cadence team @uber) actually got some resource to work on this (Cadence on top of SQL) and some preliminary work is in [this branch](https://github.com/uber-qlam/cadence/tree/mysql).

At this point we are spending some time to design the sql schema for all the workflow execution related tables. We expect it to be done in couple of weeks. Once that's finished we will share the design with you and your team and then we can discuss more and see if you guys want to participate in some part of the implementation.

Does that sound good to you?

**Comment by meiliang86** [comment]
BTW create issue #854 for tracking.

**Comment by ryanwalls** [comment]
@meiliang86 Great to hear.  We are happy to help.  We have resources slated to this for a few weeks.  Just ping me if you find something we can tackle.

**Comment by meiliang86** [comment]
See if you can join https://join.slack.com/t/uber-cadence/shared_invite/enQtMzgwNjkzMzYwODE3LWQ3YjQxMmQwNmMwZDA1MzZlOTRhNzY0MzYzMDZhMWU2MTUxMWRhMzU3Y2JkN2NlYzU0MDEwYjkyMzg4ZmQ4OGM
We can chat more over there.

**Comment by dmetzgar** [comment]
As of release [0.5.7](https://github.com/uber/cadence/releases/tag/v0.5.7), MySQL support is now in beta. I think we can safely close this issue and file more specific bugs for Windows support when they came up.

**Comment by amitesh176** [comment]
I am not able to connect Cadence with external Cassandra service.As Cassandra is already running on my System, i want Cadence to use that cassandra but its throwing error saying -Connection refused.

cadence_1      | + cqlsh --cqlversion=3.4.4
cadence_1      | Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
cadence_1      | waiting for cassandra to start up
cadence_1      | + echo 'waiting for cassandra to start up'

**Comment by amitesh176** [comment]
> We are not aware about anyone trying it, but I don't see any reasons it wouldn't work. Here are Cassandra on windows installation instructions: https://www.guru99.com/download-install-cassandra.html. Golang runs on windows as well.
> 
> Another longer term option would be implementing different database binding for a database that it native to Windows. Here is the list of interfaces that each database should implement: https://github.com/uber/cadence/blob/master/common/persistence/dataInterfaces.go#L919:1

I am not able to connect Cadence with external Cassandra service.As Cassandra is already running on my System, i want Cadence to use that cassandra but its throwing error saying -Connection refused.

cadence_1 | + cqlsh --cqlversion=3.4.4
cadence_1 | Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
cadence_1 | waiting for cassandra to start up
cadence_1 | + echo 'waiting for cassandra to start up'
