### ISSUE TITLE
Prometheus Configuration Error in docker-compose.yml

### ISSUE THREAD

**Issue by sureshachary** [uber/cadence#4406]
Giving error during docker build. Changed the line 10 (` - ./prometheus_config.yml:/etc/prometheus/prometheus.yml`) in cadence/docker/docker-compose.yml to `./prometheus:/etc/prometheus` and it worked.

**Comment by longquanzheng** [comment]
Ahh thanks for the issue. Would you mind opening an PR? I will approve it for you.

**Comment by kapilgarg1996** [comment]
This is still failing. I see the following error
`
ERROR: for prometheus  Cannot start service prometheus: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/Users/kapg/cadence/prometheus_config.yml" to rootfs at "/etc/prometheus/prometheus.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
`

Changing the docker-compose as suggested fixed the problem. (I created a prometheus directory and moved the config file there)

**Comment by percybolmer** [comment]
I can confirm the same issue occurs when running Docker-compose Through WSL2.
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

The above mentioned fix works. Seems it has trouble if we specify files directly, only folders works

**Comment by lan-n-tran** [comment]
Confirm that I have the same issue and the suggested fix works for me.

**Comment by longquanzheng** [comment]
Hi all, I am making a fix here. Thanks for the feedback

https://github.com/uber/cadence/pull/4793

**Comment by Max-Oliver** [comment]
Hi, folks i had the same issue and the suggested fix solved the problem, thanks
