### ISSUE TITLE
RequestCancelWorkflowExecution does not work without RunID

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#453]
Cadence should allow cancelling workflow execution with just workflow ID.  If the workflow is running we should be able to lookup the runID of current execution. 
Seems like we have unnecessary validation on frontend as the history engine code already have logic for load running execution using just the workflow ID.
Current the RequestCancelWorkflowExecution call fails with the following error:
BadRequestError({Message:RunId is not set on request.})

**Comment by samarabbas** [comment]
Frontend just tries to validate the uuid if RunID is set.  So the behavior looks correct.  Maybe we should skip the check if RunID is set as empty string.

**Comment by wxing1292** [comment]
already solved 1 year ago
