### ISSUE TITLE
Always running workflow execution (Daemon workflows)

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#456]
Sometime there is a need for workflows which are always running.  Currently it is pretty hard to detect such a workflow has terminated due to various reasons so it can be started again.
It may make sense for Cadence to support this scenario more natively where it automatically restart such a workflow when it finishes due to any reason.
We need to consider few things like restarting workflows in tight loop while designing such a feature.

**Comment by dmetzgar** [comment]
@mfateev since we have server-side cron, do you see a need to keep this feature request open?

**Comment by mfateev** [comment]
I think retryOptions with cron cover it.
