### ISSUE TITLE
Allow passing timeout values for sql tool

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4571]
Changing schema like adding a new field could take some time. Currently the timeout is hardcoded.

This is a problem for sql tool because one of the steps could get timeout and fails. Then the sql couldn’t rerun because some steps are already executed. 

Making sql tool to be idempotent is ideal way but it’s a lot of work to do. The easier way to mitigate for now is allowing passing a timeout value for the command. The timeout value will be used for executing any sql query. 

This will be much easier done after this PR to introduce passing a context.Context into the interface https://github.com/uber/cadence/pull/4561

**Comment by ibarrajo** [comment]
While this has not been implemented, I found no reports of a timeout during a schema change. I think since we prefer adding new columns over changing data types for the fields.

https://github.com/uber/cadence/blob/c7dfbd634aaa89ca1131a8e668cab39b6df9c6d8/tools/sql/conn.go#L75-L80
