### ISSUE TITLE
Improve admin show history command to allow using workflow id runID instead of tree and branch I’d 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4592]
https://github.com/uber/cadence/blob/f182b8710b4476dba878edefa9d7973acc079eee/tools/cli/adminCommands.go#L60

It can call cadence service to describe mutable state to get that

**Comment by ibarrajo** [comment]
Closing this since this looks like its already supported:
```
cadence admin hist describe
2024/11/04 21:00:56 at least one of them is required to provide to lookup host: workflowID, shardID and host address
```
