### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by StarAurryon** [uber/cadence#4613]
**Is your feature request related to a problem? Please describe.**
We are using a IPv6 only kubernetes cluster hosted by a third party. Would it be possible to make cadence listen on v6 addresses for all the ports?

**Proposed Solution**
Would you accept PR for this?

**Comment by longquanzheng** [comment]
Hi @StarAurryon , could you describe the proposed solution? We would love to accept PRs for those improvements.

**Comment by StarAurryon** [comment]
The first things I saw is that bindOnIP does not support IPv6 addresses. And if we don't provide this entry in the yaml file, it choose not to listen on all interfaces but on the first ipv4 which is 127.0.0.1. So we are stuck with v4 for now (history, frontend, worker, etc).

In the same way specifying [::]:9090 for metrics fall back to Ipv4.

`{"level":"info","ts":"2021-11-02T16:48:22.419+0100","msg":"Listening for GRPC requests","service":"cadence-matching","address":"127.0.0.1:7835","logging-call-at":"rpc.go:106"}`

`{"level":"info","ts":"2021-11-02T16:48:22.495+0100","msg":"Add new peers by DNS lookup","service":"cadence-frontend","address":"cadence.cadence.svc.k8s","addresses":"[fd00:3:40:1:3::161:7933 fd00:1:40:1:3::19d:7933]","logging-call-at":"clientBean.go:321"}
{"level":"info","ts":"2021-11-02T16:48:22.496+0100","msg":"Add new peers by DNS lookup","service":"cadence-frontend","address":"cadence.cadence.svc.k8s","addresses":"[fd00:1:40:1:3::19d:7933 fd00:3:40:1:3::161:7933]","logging-call-at":"clientBean.go:321"}
`

There are no error for ringpop. So I believe, but correct me if I'm wrong, we just need to parse IPv6 correctly.

I'm starting to write something on my own to see if there is more errors after this.

**Comment by longquanzheng** [comment]
Sounds good. That sounds trivial. But I would encourage you to test it out first, following this instructions: https://github.com/uber/cadence/blob/master/CONTRIBUTING.md

**Comment by StarAurryon** [comment]
I just tested my ~3 lines fix on my K8S cluster. It is working like a charm on production for a trial activation workflow.

Basically, what the fix is doing: 
`-       hostAddress := fmt.Sprintf("%v:%v", d.getListenIP(), d.config.Port)
+       hostAddress := net.JoinHostPort(d.getListenIP().String(), strconv.Itoa(d.config.Port))

-              grpcAddress := fmt.Sprintf("%v:%v", d.getListenIP(), d.config.GRPCPort)
+               grpcAddress := net.JoinHostPort(d.getListenIP().String(), strconv.Itoa(d.config.GRPCPort))`

And allowing IPv6 with ip.To16() check in the config file.

I will make a PR in the coming days.

**Comment by StarAurryon** [comment]
Just a simple question : When will I see my fix in the Docker packages on Dockerhub?

At first, I did this PR in order to be lazy and not maintain my own builds ;-)

**Comment by longquanzheng** [comment]
> Just a simple question : When will I see my fix in the Docker packages on Dockerhub?
> 
> At first, I did this PR in order to be lazy and not maintain my own builds ;-)

I just made a 0.22.4 patch release. I wanted to include this but  I wasn't able to cherry-pick this commit into 0.22.x or 0.23.x release branch for v0.22.4 or 0.23.0 release.

https://github.com/uber/cadence/tree/0.23.x
https://github.com/uber/cadence/tree/0.22.x
Because the code change you made on top of files that don't exist in any of the two branches.

Would you mind waiting until 0.24.0 ?
If not you can make another PR for merging into any of the release branch and I will review it again.

**Comment by StarAurryon** [comment]
No worry, that was just to know. I don't have any issue with my current build.

Thanks again for merging me. Have a nice day.
