### ISSUE TITLE
what kinds of database do uber cadence 's production environment used ?

### ISSUE THREAD

**Issue by Allentent** [uber/cadence#4616]
I have seen many kinds of database in your demo, such as mysql、cassandra、es、postgresql，but which one is used in your production environment ?

I think the bottleneck of workflow execution QPS should be in database, especially mysql database. so, which database to used can improve the workflow execution QPS ? I want to borrow uber's experience, thank you.

**Comment by Shaddoll** [comment]
We're currently using Cassandra at Uber and we're migrating to sharded mysql.
