### ISSUE TITLE
cadence-worker crashed when elasticsearch is down

### ISSUE THREAD

**Issue by Shaddoll** [uber/cadence#4618]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: 0.22.0

**Describe the bug**
cadence-worker crashed when elasticsearch is down

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x21b13e4]

goroutine 5628 [running]:
github.com/uber/cadence/common/elasticsearch.fromV6toGenericBulkResponse(...)
	external/com_github_uber_cadence/common/elasticsearch/client_v6.go:389
github.com/uber/cadence/common/elasticsearch.(*elasticV6).RunBulkProcessor.func2(0x68911, 0xc0063b5b80, 0x3, 0x4, 0x0, 0x40dc7a0, 0xc002efa130)
	external/com_github_uber_cadence/common/elasticsearch/client_v6.go:267 +0xa4
github.com/olivere/elastic.(*bulkWorker).commit(0xc004445a80, 0x41749e0, 0xc0000780c0, 0x1, 0x1)
	external/com_github_olivere_elastic/bulk_processor.go:588 +0x287
github.com/olivere/elastic.(*bulkWorker).work(0xc004445a80, 0x41749e0, 0xc0000780c0)
	external/com_github_olivere_elastic/bulk_processor.go:501 +0x6f4
created by github.com/olivere/elastic.(*BulkProcessor).Start
	external/com_github_olivere_elastic/bulk_processor.go:336 +0x1ce
panic: send on closed channel

goroutine 5629 [running]:
github.com/olivere/elastic.(*BulkProcessor).Flush(0xc004470b60, 0xc002a32750, 0x2)
	external/com_github_olivere_elastic/bulk_processor.go:415 +0xa7
github.com/olivere/elastic.(*BulkProcessor).flusher(0xc004470b60, 0x3b9aca00)
	external/com_github_olivere_elastic/bulk_processor.go:431 +0x89
created by github.com/olivere/elastic.(*BulkProcessor).Start
	external/com_github_olivere_elastic/bulk_processor.go:342 +0x42d

**Comment by longquanzheng** [comment]
I have seen that too in my cluster. 
Looks like we need to return an empty struct when the response is nil:
https://github.com/uber/cadence/blob/master/common/elasticsearch/client_v6.go#L386

**Comment by ibarrajo** [comment]
I saw this is now covered by unit tests:
https://github.com/uber/cadence/pull/5748
