### ISSUE TITLE
what 's the function of table 'current_execution' ?

### ISSUE THREAD

**Issue by Allentent** [uber/cadence#4640]
**table 'execution' is used for workflow execution, but what 's the function of table 'current_execution' ?**

![image](https://user-images.githubusercontent.com/88436658/141785281-bb658016-b8cb-47a1-b7ed-a8b8a0a30b51.png)

**Comment by ibarrajo** [comment]
current_executions table stores the latest run_id of a workflow, say in the case a workflow needs to be retried, it will have a new run_id.

this is the current schema of the table
```
CREATE TABLE current_executions(
  shard_id INTEGER NOT NULL,
  domain_id BYTEA NOT NULL,
  workflow_id VARCHAR(255) NOT NULL,
  --
  run_id BYTEA NOT NULL,
  create_request_id VARCHAR(64) NOT NULL,
  state INTEGER NOT NULL,
  close_status INTEGER NOT NULL,
  start_version BIGINT NOT NULL,
  last_write_version BIGINT NOT NULL,
  PRIMARY KEY (shard_id, domain_id, workflow_id)
);
```
