### ISSUE TITLE
History Engine: Allow CreateTimer decision with 0 timeout

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#473]
History engine has validation logic to disallow timer creation with 0 timeout.  There are scenario where client may want to force a new decision immediately using a timer with 0 timeout.

**Comment by samarabbas** [comment]
We are already planning on updating the RespondDecisionTaskCompleted API to respond with decisions and keep the decision open.  Seems like this is a much better way to solve the use case of breaking up large decision into smaller ones, rather than create a timer with 0 timeout.

Let's keep this task open until we have the new RespondDecisionTaskComplete API in place.

**Comment by samarabbas** [comment]
PR #776 seems to address this issue.

**Comment by dmetzgar** [comment]
@samarabbas, can this issue be closed? Looks like #776 covers this.
