### ISSUE TITLE
UpdateShard timed out. Error: Operation timed out error

### ISSUE THREAD

**Issue by wozuo** [uber/cadence#4741]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: v0.23.2-auto-setup
- Client version: v0.18.3
- Client langauge: Go

**Describe the bug**
When deploying the [docker-compose-statsd.yml](https://github.com/uber/cadence/blob/master/docker/docker-compose-statsd.yml) with Docker Swarm: `docker stack deploy --compose-file docker-compose-statsd.yml example` the Cadence server sometimes (no always but about 50% of the time) prints the following error to the logs:
```

{"level":"error","ts":"2022-02-17T17:09:36.862Z","msg":"Operation failed with internal error.","service":"cadence-history","error":"UpdateShard timed out. Error: Operation timed out - received only 0 responses.","metric-scope":2,"logging-call-at":"persistenceMetricClients.go:242","stacktrace":"github.com/uber/cadence/common/log/loggerimpl.(*loggerImpl).Error\n\t/cadence/common/log/loggerimpl/logger.go:131\ngithub.com/uber/cadence/common/persistence.(*shardPersistenceClient).updateErrorMetric\n\t/cadence/common/persistence/persistenceMetricClients.go:242\ngithub.com/uber/cadence/common/persistence.(*shardPersistenceClient).UpdateShard\n\t/cadence/common/persistence/persistenceMetricClients.go:224\ngithub.com/uber/cadence/service/history/shard.(*contextImpl).renewRangeLocked\n\t/cadence/service/history/shard/context.go:1052\ngithub.com/uber/cadence/service/history/shard.acquireShard\n\t/cadence/service/history/shard/context.go:1581\ngithub.com/uber/cadence/service/history/shard.(*historyShardsItem).getOrCreateEngine\n\t/cadence/service/history/shard/controller.go:439\ngithub.com/uber/cadence/service/history/shard.(*controller).GetEngineForShard\n\t/cadence/service/history/shard/controller.go:204\ngithub.com/uber/cadence/service/history/shard.(*controller).acquireShards.func1\n\t/cadence/service/history/shard/controller.go:386"}
{"level":"warn","ts":"2022-02-17T17:09:36.863Z","msg":"UpdateShard failed with an unknown error.","service":"cadence-history","shard-id":0,"address":"10.0.31.6:7934","error":"UpdateShard timed out. Error: Operation timed out - received only 0 responses.","shard-range-id":26,"previous-shard-range-id":25,"attempt":0,"logging-call-at":"context.go:1069"}
{"level":"info","ts":"2022-02-17T17:09:37.629Z","msg":"First loading dynamic config","service":"cadence-matching","key":"matching.longPollExpirationInterval,domainName:cadence-system,taskListName:cadence-sys-failoverManager-tasklist,taskType:1,clusterName:primary","value":"1m0s","default-value":"1m0s","logging-call-at":"config.go:93"}
{"level":"info","ts":"2022-02-17T17:09:37.629Z","msg":"First loading dynamic config","service":"cadence-matching","key":"matching.numTasklistReadPartitions,domainName:cadence-system,taskListName:cadence-sys-failoverManager-tasklist,taskType:1,clusterName:primary","value":"1","default-value":"1","logging-call-at":"config.go:93"}
``` 

When this error occurs, the Cadence web client also doesn't work (times out) and the Go client has the same problem (also times out). With `docker-compose up --build` I haven't yet observed this error.

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
As described above (deploy docker compose file as stack to Docker swarm).

**Expected behavior**
No occurrences of this error.

Are there some changes needed for Cadence to work with Docker Swarm? I hope someone can point me in the right direction. Thanks a lot!

**Comment by ibarrajo** [comment]
I tried to quickly reproduce the issue, about 10 minutes, and didn't get that far to test, we should look into it if this is still an issue. Perhaps a health check that is too tight kills a node making the service unreachable. Or its a network issue.

When I attempted to test this out I saw the docker files were not compatible with docker stack deploy since in [docker v3](https://github.com/docker/compose/issues/4305#issuecomment-276527457) `depends_on` was removed. There is limited functionality with docker-compose
