### ISSUE TITLE
Documentation for Building CLI runs the wrong Make?

### ISSUE THREAD

**Issue by percybolmer** [uber/cadence#4752]
**Version of Cadence server, and client(which language)**
Cadence website

**Describe the bug**
[A clear and concise description of what the bug is.](https://cadenceworkflow.io/docs/cli/#using-the-cli)
Here it states that we should run `make tools` However that does not exist in the make

In the #contribution of the readme we can instead find `make bins`

**To Reproduce**
Is the issue reproducible? 
- Yes
````bash
git clone https://github.com/uber/cadence
cd cadence && make tools
```

**Expected behavior**
To build

**Comment by ibarrajo** [comment]
I see the [target on the Makefile](https://github.com/uber/cadence/blob/master/Makefile#L528) 

And it runs
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/c04c4e67-d3fa-433a-a679-2fdd5e12ce0f">
