### ISSUE TITLE
Matching Engine: API to list all Tasklist for a domain

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#476]
Currently we don't have a good way to list all the tasklist for a domain.  This becomes a problem when we are debugging issues for a particular domain and need to investigate metadata/stats for a tasklist.  We use domain_id, task_list_name, task_list_type as the partition key on tasks table and cannot even discover these by making queries to cassandra.
This is even a bigger issue with sticky tasklist as we can not even them even if the application logically uses a single tasklist for decisions.

**Comment by mfateev** [comment]
Was it implemented?
