### ISSUE TITLE
[Interpreter]Proposal]New way to write workflow using Cadence 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4785]
https://docs.google.com/document/d/1BpJuHf67ibaOWmN_uWw_pbrBVyb6U1PILXyzohxA5Ms

See also https://github.com/longquanzheng/iwf

**Comment by slater-ben** [comment]
Hi Long, can you give a pseudcode example of what a basic workflow implemented with this approach would look like?

**Comment by longquanzheng** [comment]
@slater-ben See this project https://github.com/longquanzheng/iwf
and  [prototype example](https://github.com/longquanzheng/iwf/blob/main/src/com/indeed/iwf/demo/SubscriptionWorkflow.java) as a translation of the [Example Subscription workflow](https://cadenceworkflow.io/docs/concepts/workflows/#example)

**Comment by slater-ben** [comment]
Hi @longquanzheng a few thoughts I had on this:
- For me at least, it was a lot harder to follow the workflow business logic in your prototype than in the standard example. For me, making it easy to follow the business logic is one of the key benefits of Cadence. So it would seem like a hard sell to make this the primary way of developing workflows in Cadence.
- I do feel like (without really having worked it through) that your new approach might be easier to deal with you if you were looking to build a DSL or visual workflow editor on top of Cadence
- It did get me thinking on the original goal of making it easier to develop repayable workflows: I feel like it might be possible to develop an automated framework for testing that workflow code is deterministic by simulating activity results and other Cadence interactions (might require a few more annotations on activities to give some hints on valid values). While this might not provide a 100% guarantee of determinism it would probably help most devs in understanding the concept and provide a useful testing tool even for experienced devs.

**Comment by longquanzheng** [comment]
Hey @slater-ben 
Super appreciate your comments and your time looking into my in-matured idea. 

* Yes, I do see that the business flow is getting less fluent in this format compared to original code. This is the trade off that I have put as "Limitation". 
* I don't mean the abandon Cadence. I am just hoping this will be a good supplement to this technology. 
* AWS Step Function, Airflow, Netflix Conductor are all letting developers to model business into this state machine fashion. In fact, those technologies are all more widely used than Cadence in the industry. I have seen this has been a big reason that Cadence cannot be popular. It's not perfect to model business in state machine, but based on the facts, I believe it's not a terrible idea either. 
* Many engineers don't have enough time or expertise to become good at writing reliable Cadence workflow. This idea should be good enough for lots of real world use cases. 
* I have been working with Cadence team to explore many ways to improve the experience. And will keep on doing it. 
* It's not only determinism. There are a lot more work than that when using Cadence workflow especially for operation & monitoring & debugging. Things are significantly improved with this proposal.

**Comment by slater-ben** [comment]
Makes sense, and you definitely have a lot more experience building real world workflows than me to understand the problem you are aiming to address. I think if this is an additional option rather than a replacement then it can really only be a good thing.

I hadn't picked up before that this completely removes the need for determinism in the workflow code. That certainly would make it easier to avoid tripping over hard to understand restrictions. I wonder however if it makes it easier to get working code at the expense of making it more likely to introduce subtle business logic bugs that are harder to track down? (Genuinely wondering - it feels to me like it probably does but I can't exactly pin down how.)

**Comment by longquanzheng** [comment]
@slater-ben to be more readable, I refactor the code a little bit, and also for this state machine fashion, we should be able to build a tool to generate the flow diagram like this: https://github.com/longquanzheng/iwf/tree/main/src/com/indeed/iwf/demo/subscription

**Comment by slater-ben** [comment]
I like the diagram and I definitely think the class per state is more readable than your previous example. One thing I can work out looking at the sample is how you specify what the starting state is? Is it just because it's the first state in the workflow getState() list or would it be specified when invoking the workflow?

**Comment by longquanzheng** [comment]
@slater-ben good question. It's TBD in this prototype. There are different ways to do it including what you mentioned. 

I would like to hear from you and other people to see which way they would love the most. 

Initially I thought we can allow letting users to start from any state, to be super flexible. But this could cause confusion. 

So we could implicitly make the first state in the list as starting state, or we can add use an annotation to mark certain states as starting states. 

I think allowing multiple states to be starting would be nice. This will make things a lot easier to change the workflow. E.g. ppl run into lots of problem when they wanted to change the Cadence workflow method to add a new input parameter. It's not allowed in Cadence because of backward compatibility.

**Comment by slater-ben** [comment]
I agree with your thought that allowing multiple, but restricted, starting states feels like the right approach. My inclination would be to have the allowed starting states defined in the workflow class (as I think you could potentially reuse state classes across multiple workflows and allowed starting states is logically a property of the workflow). I can think of a couple of alternative approaches for this:

- a getAllowedStartingStates() method that returns a list of states 
- a workflow.start() method (or maybe multiple annotated methods) which return a decision about the first state (I think I prefer this as it gives you an obvious place to start if you're trying to work through the logic of a workflow).

Another thought I had looking at this is I wonder if what you're calling states would better called steps? Looking through your example code, I was confused about how decide() could return multiple potentially states (given I'd normally only expect one state at a time) but I think it's actually returning next steps with the step being complete once the prepare() conditions are met. If you changed to "step" terminology then you might also change prepare() to execute() (as I found it a bit weird when I thought about it that prepare() was where the actual activities get kicked off)

**Comment by longquanzheng** [comment]
`a getAllowedStartingStates() method that returns a list of states` yeah this should work  and `a workflow.start() method ` I am not sure I follow this idea. 

Or I think a better way is to define if it's startable with the states, like below:
```
        return Arrays.asList(
                new StateDef( new WelcomeEmailState(), true),
                new StateDef( new CancelSubscriptionState(), false), 
                new StateDef( new WaitForPeriodState(), false), 
                new StateDef( new ChargeCurrentPeriodState(), false), 
                new StateDef( new SubscriptionOverState(), false), 
                new StateDef( new UpdateChargeAmountState(), false)
        );
```
Having them in the same place when defining states make it clear and easy to lookup.

**Comment by longquanzheng** [comment]
## About steps vs states
I do see that some people may get confused if they thought a workflow can only have one state at any time. Using steps can avoid this confusion. 
However, state is also standard term for this purpose, [AWS step function ](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-parallel-state.html) and Cadence SDK all call it `State` and a workflow execution can have multiple in-parallel states. 

So I want to reuse the same term and I think people will get used to it.

**Comment by longquanzheng** [comment]
about execute vs prepare -- 

I think execute may only fit for activity case. The other two condition types -- signal and timers are not quite fit as saying "executing a timer" or "executing a signal". So I call it "requesting activity/timer/signal as conditions". 

And in fact, the activity is not really executed here. It's executed in activity worker. WF is only scheduling it and waiting for the results. Though I agreed saying "executing activity"is also correct.

**Comment by slater-ben** [comment]
Those are all valid and logical reasons and I think the naming you've done will work perfectly well. Thinking about it a bit more though I realised the root of all three suggestions I made is that the point of a workflow is to do stuff (or at least cause stuff to be done) and there is nothing with a name that implies that it is doing things (with the possible exception of "prepare" although even that sounds more like getting ready to do something).  I think in trying to understand the code I was looking for something that was clearly the doing stage to anchor my understanding. (For example, look at the AWS step function doco you fairly quickly see there is a State type of Task.) 

So, up to you if you can find a way to accomodate that but thought it was worth giving you perspective as someone coming fresh to the code and trying to understand it.

**Comment by longquanzheng** [comment]
Yeah I agreed that “prepare” is not perfect. Though I feel like execute is also sorta misleading. 

I will think more about it and open to more ideas from you and anyone.

**Comment by longquanzheng** [comment]
Just got an idea that your suggestion of “execute “ will work perfectly if I changed “condition” to “command”. 

The method will execute some commands of activity, signal or timers — that sounds fluent enough 😃 @slater-ben

**Comment by slater-ben** [comment]
I think that works well. Feels to me like the naming now fits well with what is actually going on.

**Comment by slater-ben** [comment]
Next topic: it feels a bit weird to me that the State IDs are defined in the workflow rather than the State classes. I can see why you've done it that way but I think that will be a pain if you are reusing State classes across multiple workflow definitions (which feels like it could be useful).

Related, could it be possible/useful to have multiple State IDs map to one implementation class? I think that could make it really easy to use the model to write a DSL interpreter without having to do code generation.

**Comment by longquanzheng** [comment]
No they don't have to be in workflow classes.  In fact the sdk doesn't require it, I put them into the wf classes as public class constants and referred in state classes. I think putting them into state classes makes sense. 

Just updated the prototype.

**Comment by longquanzheng** [comment]
Some updates
Here is the [slides](https://docs.google.com/presentation/d/1CpsroSf6NeVce_XyUhFTkd9bLHN8UHRtM9NavPCMhj8/edit#slide=id.gfe2f455492_0_26) of a comparison

A design [doc](https://docs.google.com/document/d/1BpJuHf67ibaOWmN_uWw_pbrBVyb6U1PILXyzohxA5Ms/edit).

We have implemented the first version with Temporal: https://github.com/cadence-oss/iwf

And a Java [SDK](https://github.com/cadence-oss/iwf-java):
It could be easily extended to support Cadence and any other languages as the [API schema](https://github.com/cadence-oss/iwf-idl) is very lightweight

**Comment by longquanzheng** [comment]
implemented in https://github.com/indeedeng/iwf with Cadence
