### ISSUE TITLE
Unsupported CQL version?

### ISSUE THREAD

**Issue by melienherrera** [uber/cadence#4794]
**Describe the bug**
I am trying to connect Cadence with DataStax Astra DB using [cql-proxy](https://github.com/datastax/cql-proxy). I changed the configuration in the docker-compose file and received the following error: 

```
+ cqlsh -u cassandra -p cassandra --cqlversion=3.4.4 --protocol-version=4 cqlproxy

Connection error: ('Unable to connect to any servers', {'172.20.0.3:9042': ProtocolError("cql_version '3.4.4' is not supported by remote (w/ native protocol). Supported versions: ['3.4.5']")})
```

Looks like it forcing the cql version 3.4.4 although the cql version that is being used is 3.4.5. I was able to fork the project and change the start.sh script to:

```
wait_for_cassandra() {
    server=`echo $CASSANDRA_SEEDS | awk -F ',' '{print $1}'`
    until cqlsh -u $CASSANDRA_USER -p $CASSANDRA_PASSWORD --cqlversion=3.4.5 --protocol-version=$CASSANDRA_PROTO_VERSION $server < /dev/null; do
        echo 'waiting for cassandra to start up'
        sleep 1
    done
    echo 'cassandra started'
}
```
changing from `--cqlversion=3.4.4` to `--cqlversion=3.4.5`

**Steps to reproduce the behavior:**
- Create and Astra DB account 
- Create a database
- Create `cadence` and `cadence_visibility` keyspaces
- Get your Astra token and Astra database ID

In the docker-compose file, replace the "cassandra" section with:
```
cql-proxy:
    image: datastax/cql-proxy:v0.1.2
    ports:
      - "9042:9042"
    environment:
      - ASTRA_TOKEN=${ASTRA_TOKEN}
      - ASTRA_DATABASE_ID=${ASTRA_DATABASE_ID}
```

and make sure to change the:
```
depends_on:
- cassandra
```
to depend on cql-proxy

**Expected behavior**
Cadence should be able to connect to Astra database using cql-proxy and be viewed in the UI that everything is working. 

**Question**
Is this expected behavior? Is there a reason there is a flag for `--cqlversion`? Should this be updated to the latest version?

**Comment by ibarrajo** [comment]
I believe the reason was to ensure consistency in the queries and not have something change unexpectedly when a newer version of Cassandra comes out. 

Cassandra is backwards compatible, so in operations, the DB could be upgraded and then once ready clients connecting to it can upgrade their cql version at their own pace.
