### ISSUE TITLE
Cadence Helm Charts for K8s Depoyment Not working

### ISSUE THREAD

**Issue by kalrashubham49** [uber/cadence#4841]
I am trying to deploy cadence on production server in my k8s cluster using helm., but it is failing to start the pods , only pod running is cassandra

**Comment by ibarrajo** [comment]
Hi! we are pleased to announce that we recently released official Cadence Helm charts.

Here's the [announcement](https://cadenceworkflow.io/blog/2024/10/01/announcing-cadence-helm-charts-v0/) and [repo](https://github.com/uber/cadence-charts):
