### ISSUE TITLE
how to modify grpcMaxMsgSize configuration?

### ISSUE THREAD

**Issue by jxwuqingyan** [uber/cadence#4854]
I used k8s deploy Cadence cluster,now  I want to modify the grpcMaxMsgSize， is /etc/cadence/config/dynamicconfig/development.yaml? what should I do?

**Comment by longquanzheng** [comment]
See our documentation about how to use dynamic configuration https://cadenceworkflow.io/docs/operation-guide/setup/#static-configuration

**Comment by jxwuqingyan** [comment]
OK,I have read this document,but not see how to  set grpcMaxMsgSize

**Comment by ibarrajo** [comment]
Looking at the source, GRPCMaxMsgSize allows overriding default (4MB) message size for gRPC.

This is set in an int type that represents the number of bytes. I've seen the development.yaml set to `33554432` which is equivalent to 32MB
