### ISSUE TITLE
Support to show how many activities are waiting to be executed in a task list

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#4857]
It's been asked for many users.

**Comment by zedongh** [comment]
Is there any idea about this feature implementation?

**Comment by ibarrajo** [comment]
@longquanzheng could you share a little more of where you would like to see this information?

The first thing that came to mind were the grafana metrics, were we mainly look at schedule to start latency as well as task scheduled RPS. https://cadenceworkflow.io/docs/operation-guide/monitor/#cadence-default-persistence-monitoring

But I wanted to ask if this is something that could be more useful on the cadence-web ui

**Comment by longquanzheng** [comment]
It was a long time ago so my memory is vague.
But I got users asked me in the context of operations, seeing how may tasks
in ui directly would be easier than looking at the metrics


Thanks,
Quanzheng

**Comment by demirkayaender** [comment]
duplicate.
