### ISSUE TITLE
Domain Name and Ip Address getting concatenated

### ISSUE THREAD

**Issue by amanvaidya** [uber/cadence#4862]
Hi,
I'm trying to deploy cadence, the cadence -frontend is hosted in different server and application is hosted in different server.
When trying to connect the application domain name and ip address is getting concatenated resulting network error:
**Rpc error:<ErrorResponse id=-1 errorType=NetworkError message=Connection timeout on identification: domainName/xx.xx.xx.xx:xxxx/cadence-frontend::WorkflowService::RegisterDomain>**

I'm using ClientOptions.newBuilder() to set host and port
**var clientOptions = ClientOptions.newBuilder().setHost(host).setPort(port).setRpcTimeout(10000).build()
val cadenceService: IWorkflowService = WorkflowServiceTChannel(clientOptions)**

**Comment by ekomanurung** [comment]
hi @amanvaidya , i want to ask about the solution for above issue. how you solve that issue? since i face the same on my env. thank you
