### ISSUE TITLE
why not enable json type persistence parser?

### ISSUE THREAD

**Issue by zhangkyou** [uber/cadence#4893]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: 0.23.1
- Client version:
- Client langauge:

**Describe the bug**
common/constants.go
```
// Data encoding types
const (
	EncodingTypeJSON     EncodingType = "json"
	EncodingTypeThriftRW EncodingType = "thriftrw"
	EncodingTypeGob      EncodingType = "gob"
	EncodingTypeUnknown  EncodingType = "unknow"
	EncodingTypeEmpty    EncodingType = ""
	EncodingTypeProto    EncodingType = "proto3"
)
```

the constant encoding types include json type.But in getEncoder/getDecoder(common/presistence/serialization/parser.go) it only enable 'thriftrw' and 'proto3' type.

```
func getEncoder(encoding common.EncodingType) (encoder, error) {
	switch encoding {
	case common.EncodingTypeThriftRW:
		return newThriftEncoder(), nil
	case common.EncodingTypeProto:
		return newProtoEncoder(), nil
	default:
		return nil, unsupportedEncodingError(encoding)
	}
}
```

**To Reproduce**
Is the issue reproducible? 
- [Yes]

**Comment by ibarrajo** [comment]
The method in the present now only gives support to the thrift encoder which I found intriegieng. 

Seems like this [PR #3534](https://github.com/uber/cadence/pull/3534) does explain a bit that the encoder/decoders were being split, keeping here only thrift for common utils
