### ISSUE TITLE
Add dynamic config property to toggle validation of WF queries against the search attribute whitelist

### ISSUE THREAD

**Issue by charlese-instaclustr** [uber/cadence#4948]
**Is your feature request related to a problem? Please describe.**

When running Cadence in a multi-node setup, it may be desirable to be able to add custom search attributes via the CLI and **not** have to subsequently update the `frontend.validSearchAttributes` whitelist in the dynamic config on all of the Cadence nodes. This can be limiting if e.g. the dev. seeking to add the search attributes does not have the requisite access to the node configs, this can create limiting interdependencies hindering development.

**Proposed Solution**

One possible solution to this problem is to add an additional dynamic config property along the lines of `frontend.enableSearchAttributeValidation`. This would be:
- A boolean property, where search attributes would only be validated against `frontend.validSearchAttributes` by Cadence if the property were set to `true`
- `true` by default, so that for existing Cadence configs, no change in behaviour would be seen.

**Additional context**

This ticket is to replace https://github.com/uber/cadence/issues/4940 which was initially suggesting addressing this problem by allowing wildcard or regexp-like expressions in the attribute whitelist. However, following discussion in the Slack here: https://uber-cadence.slack.com/archives/C02HF9PP3PH/p1660313625170229 a separate property which enables/disables the validation entirely seems like a better fit with the initial intention of this feature. The preceding issue #4940 will be closed/cancelled in favour of this one.

**Comment by ibarrajo** [comment]
Closing this since the feature as added as `frontend.enableQueryAttributeValidation` in this PR https://github.com/uber/cadence/pull/5033
