### ISSUE TITLE
cadence bench panics: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by weusego** [uber/cadence#4986]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: branch 0.24.x-release
- Client version: Cadence Bench 0.0.1
- CLI feature version: 1.7.0 
   Release version: v0.16.0-dirty
   Build commit: 2022-05-06T11:46:25-07:00-3035b184d
- Client language: Go

**Describe the bug**

When running the config/bench/basic.json test from the README
with a few higher settings on my notebook,
the `ob` command panics.

```
  3142, 2022-09-01T13:41:46+02:00, ActivityTaskCompleted
  3143, 2022-09-01T13:41:46+02:00, DecisionTaskScheduled
  3144, 2022-09-01T13:41:46+02:00, DecisionTaskStarted
  3145, 2022-09-01T13:41:46+02:00, DecisionTaskCompleted

Time elapse: 25s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e7ec23]

goroutine 37 [running]:
github.com/uber/cadence/tools/cli.GetWorkflowHistoryIterator.func1({0x28bc008?, 0xc0000dc680?}, {0x1fbfee0?, 0xc000e2c240?})
        /home/weusego/learn_cadence/cadence/tools/cli/util.go:136 +0x3a3
github.com/uber/cadence/common/pagination.(*iterator).advanceToNonEmptyPage(0xc0001ae100, 0x0?)
        /home/weusego/learn_cadence/cadence/common/pagination/iterator.go:95 +0x58
github.com/uber/cadence/common/pagination.(*iterator).advance(0xc0001ae100, 0x3?)
        /home/weusego/learn_cadence/cadence/common/pagination/iterator.go:83 +0xaf
github.com/uber/cadence/common/pagination.(*iterator).Next(0x28a61c0?)
        /home/weusego/learn_cadence/cadence/common/pagination/iterator.go:66 +0x3f
github.com/uber/cadence/tools/cli.printWorkflowProgress.func1()
        /home/weusego/learn_cadence/cadence/tools/cli/workflowCommands.go:428 +0x1ae
created by github.com/uber/cadence/tools/cli.printWorkflowProgress
        /home/weusego/learn_cadence/cadence/tools/cli/workflowCommands.go:422 +0x385
```

**To Reproduce**
Is the issue reproducible? 
- Yes 

**Steps to reproduce the behavior:**
A clear and concise description of the reproduce steps.

1/ Settings in basic.json 
```
{
  "useBasicVisibilityValidation": true,
  "contextTimeoutInSeconds": 3,
  "failureThreshold": 0.01,
  "totalLaunchCount": 10000,
  "routineCount": 1000,
  "waitTimeBufferInSeconds": 300,
  "chainSequence": 4,
  "concurrentCount": 1000,
  "payloadSizeBytes": 1024,
  "executionStartToCloseTimeoutInSeconds": 10
}
```

2/ Start the benchmark

`cadence --do cadence-bench wf start --tl cadence-bench-tl-0 --wt basic-load-test-workflow --dt 30 --et 3600 --if config/bench/basic.json`

3/ Observe the benchmark

`cadence --do cadence-bench wf ob -w ddfa3129-3d75-4140-b36e-be04310ad008`

**Expected behavior**

To finish and print results.

**Screenshots**

See stacktrace above

**Additional context**
Add any other context about the problem here, E.g. Stackstace, workflow history.

**Comment by ibarrajo** [comment]
can confirm this is no longer an issue, could not replicate
