### ISSUE TITLE
Matching Service: TaskList throttling to allow users to limit activities per second

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#50]

**Comment by madhuravi** [comment]
Users want to throttle the number workflows (or activities) being executed per second. For eg. User has workflow with activity that calls downstream service foo. foo has a TPS limit that user has to abide by. We want to expose configuration to users that will limit how many workflows (and in turn calls to downstream services) are executed in a time duration.

**Comment by mfateev** [comment]
It should also accept 0 as a valid value. When 0 is specified no tasks should be dispatched on the given task list. It can be used to quickly shut down the dispatch to workers if some corruption problem with them is found.
