### ISSUE TITLE
Get event history timeout error after workflow started 

### ISSUE THREAD

**Issue by vancexu** [uber/cadence#505]
While using CLI to get history, I encountered this 
```
boweixu$ cadence --domain "samples-domain" show --wid signal_source_bd830b51-ffc2-4481-a23a-dbbf49debdc1
code:deadline-exceeded message:timeout
('export CADENCE_CLI_SHOW_STACKS=1' to see stack traces)
```
The cmd stuck for a few seconds and then show error timeout.
(I suspect when decision is started but yet completed, get history will have issue)

After workflow timeout, get history work as expected and return the following:
```
1, 2018-01-10T16:57:17-08:00, WorkflowExecutionStarted: (WorkflowType:(Name:code.uber.internal/devexp/cadence-samples.git/cmd/samples/recipes/signal.SampleSignalWorkflowSource), TaskList:(Name:signalGroup), Input:[], ExecutionStartToCloseTimeoutSeconds:180, TaskStartToCloseTimeoutSeconds:180, Identity:25769@boweixu-C02V61JZHTDG@)
2, 2018-01-10T16:57:17-08:00, DecisionTaskScheduled: (TaskList:(Name:signalGroup), StartToCloseTimeoutSeconds:180)
3, 2018-01-10T16:57:17-08:00, DecisionTaskStarted: (ScheduledEventId:2, Identity:25684@boweixu-C02V61JZHTDG@signalGroup, RequestId:9e5d3104-a210-4f33-9fdb-036d705cc97d)
4, 2018-01-10T17:00:17-08:00, WorkflowExecutionTimedOut: (TimeoutType:START_TO_CLOSE)
```

**Comment by vancexu** [comment]
Please hold on investigate this. I need to reproduce before investigate.

**Comment by vancexu** [comment]
This is not reproduced with lastest changes. closed.

**Comment by darshitakk** [comment]
On running the command - "docker run --platform linux/amd64 --network=host --rm ubercadence/cli:master --address {ADDRESS} --do simple-domain domain register", getting this error, any idea how to resolve?
Error: Register Domain operation failed.
Error Details: code:deadline-exceeded message:timeout
('export CADENCE_CLI_SHOW_STACKS=1' to see stack traces)
