### ISSUE TITLE
Expose current worker identity for started pending activity

### ISSUE THREAD

**Issue by zedongh** [uber/cadence#5058]
**Is your feature request related to a problem? Please describe.**
Small feature reqeust for user clearly find pending activity is executed by which poller

**Proposed Solution**
Expose more info from server internal pending activty info (StartedIdentity)

**Additional context**
Noop

**Comment by zedongh** [comment]
#5307

**Comment by ibarrajo** [comment]
Just to let you know, we do expose `lastWorkerIdentity` in case the activity previously failed.

The worker that started the task is persisted onto the database, but I'm unsure of the timing when the worker's id is stored. I thought it was until the task completed or failed, which if that is the case, the task would no longer be pending at that time.
