### ISSUE TITLE
Just trying to understand cadence

### ISSUE THREAD

**Issue by RameshRM** [uber/cadence#5068]
Please use [Discussion](https://github.com/uber/cadence/discussions) or [StackOverflow](https://stackoverflow.com/questions/tagged/cadence-workflow) for QA/Help/Support.
Do NOT use issue for this. 
How different is cadence compared to https://github.com/flowable , trying to understand, pls share if there is any comparisson to other workflow

**Comment by longquanzheng** [comment]
This article is for IWF(the abstraction layer on Cadence) but also applies for comparing Cadence vs other workflow engines
