### ISSUE TITLE
Let pollInterval to be configurable

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#5076]
https://github.com/uber/cadence/blob/7670ab23e4199039eb1a5ad25020418bc664af52/docker/config_template.yaml#L286

60s is too long...and it's not configurable

**Comment by ibarrajo** [comment]
@longquanzheng This is configurable in the config yamls: https://github.com/search?q=repo%3Auber%2Fcadence+%22pollInterval%3A+%22+path%3Aconfig%2F*.yaml&type=code

Or do you mean setting this template to read from an environment variable, like:

```
pollInterval: {{ default .Env.DYNAMIC_CONFIG_POLL_INTERVAL "60s" }}
```
