### ISSUE TITLE
Allow registering search attributes even when AdvancedVisibility is not enabled

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#5085]
https://github.com/uber/cadence/blob/3b5c2b622da7319c428b75ae199ea3a6c1c29a20/service/frontend/adminHandler.go#L220

This is already supported in Temporal.
With this, search attributes can be used as data fields and not for search. 
It's a convenient to test the search attribute API in the workflow code before using advanced visibility.

**Comment by lancezhao-ins** [comment]
Hi @longquanzheng , 
Does this ticket only require changing the validation around the line you mentioned?

**Comment by longquanzheng** [comment]
> Hi @longquanzheng ,
> Does this ticket only require changing the validation around the line you mentioned?

Yes I believe so.

**Comment by lancezhao-ins** [comment]
Cool, can I pick it up as my first Open-Source ticket?

**Comment by longquanzheng** [comment]
> Cool, can I pick it up as my first Open-Source ticket?

Sure, go ahead. Feel free to ask if you have more questions

**Comment by lancezhao-ins** [comment]
PR Opened: https://github.com/uber/cadence/pull/5185
