### ISSUE TITLE
is it possible to convert a local domain to a global domain

### ISSUE THREAD

**Issue by elopsod** [uber/cadence#5127]
hi 
is it possible to convert a local domain to a global domain ? 
If so, please tell me the commands by which this can be done.
thanks in advance

**Comment by longquanzheng** [comment]
No it’s not possible.

**Comment by elops-od** [comment]
@longquanzheng  any plans to add this ability ?

**Comment by ibarrajo** [comment]
While its not possible at the time. A [migration can be performed](https://cadenceworkflow.io/docs/operation-guide/migration/#migrate-with-naive-approach) from a local domain into a global domain.

**Comment by ibarrajo** [comment]
This is a related feature request: https://github.com/uber/cadence/issues/2371
