### ISSUE TITLE
RespondActivityTaskCompletedByID takes in domainID instead of domainName

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#515]
DomainID is an internal identifier to Cadence server.  We should not be leaking these identifiers to Cadence clients.  Update RespondActivityTaskCompletedByID API on server to take in domainName instead of domainID.

**Comment by ryanwalls** [comment]
@samarabbas @vancexu What is your timeline for looking at this issue?  If not in the next few days, I could try to take a look.  We just really need this change for our implementation to function.

**Comment by samarabbas** [comment]
@ryanwalls we are planning to take up this task next week.

**Comment by vancexu** [comment]
@ryanwalls This issue was fixed. Please let us know if anything else is needed.
