### ISSUE TITLE
Helm chart for Cadence

### ISSUE THREAD

**Issue by h7kanna** [uber/cadence#517]
Hi,
I am experimenting with deploying Cadence on Kubernetes. 
I find Jaeger has helm chart in development.
Any plan to create a helm chart for Cadence?

Thanks,
Harsha

**Comment by mfateev** [comment]
It would be nice. As we are not using Kubernetes internally I don't think our team would have time and expertise to create to create one. But a contribution is welcome :).

**Comment by orymate** [comment]
Hi,
we contributed our Cadence chart to incubator: helm/charts#12372. You can also use it from our charts repository listed here: https://hub.helm.sh/charts/banzaicloud-stable/cadence (built from https://github.com/banzaicloud/banzai-charts/tree/master/cadence). We are happy to get some feedback about it.

Greetings,
Mate from Banzai Cloud

**Comment by dmetzgar** [comment]
Closing this as the Helm chart is available and #2322 follows testing for it.
