### ISSUE TITLE
Feature Request: Publish Binaries

### ISSUE THREAD

**Issue by alexDrinkwater** [uber/cadence#521]
We would really love to be able to run the cadence server on a windows 10 machine without having to build the executable. Are there any plans for publishing a variety of OS/Arch binaries for each release?

**Comment by mfateev** [comment]
I believe you can run Cadence on Windows using Docker. But we will look into cross compilation to Windows as part of a release.

**Comment by alexDrinkwater** [comment]
Thanks @mfateev. We need to run cadence in a windows environment without docker due to project environment constrains. In the meantime I have made a shell script to build the binaries for us locally.
