### ISSUE TITLE
Server-side HTTP API

### ISSUE THREAD

**Issue by mantas-sidlauskas** [uber/cadence#5265]
**Is your feature request related to a problem? Please describe.**
To start Cadence workflow, you must use Cadence client SDK. Officially supported clients are Golang and Java based. It limits the way on how you can communicate with Cadence server.  Having HTTP based API opens more flexible way to start and control workflows. 

I propose to add HTTP API to Cadence server. This will allow start/terminate/etc workflows using any programming language, even scripting languages when you invoke `curl` request. 

### YARPC gRPC/TChannel over HTTP invocation method
I propose to use YARPC gRPC/TChannel over HTTP invocation method. This has several advantages:

- Quite easy to implement, open defined HTTP port 
- Using YARPC interceptor, config-based list of allowed API methods can be defined 
- Uses existing, RPC based implementation 
- IDLs dictates APIs and their parameters  

Theoretically, config part could look like this:
```
rpc:
  frontend:
    http_port: 8899
  http_accept:
      - uber.cadence.api.v1.WorkflowAPI::StartWorkflowExecution
      - uber.cadence.api.v1.WorkflowAPI::TerminateWorkflowExecution
```

### Separate, dedicated HTTP API handler in Cadence server 

Along with Thrift and Proto implementations, HTTP/json handler can be implemented.  

Pros: 
- Implementation can be different  
- Some arguments can be generated on server-side, smaller API surface 

Cons: 
- Need to reimplement API endpoints 
- Added maintenance is needed 
- Server redeployment is needed to release fixes 

### Side-car proxy service  

A new application/service can be built to act as a proxy to Cadence server 

Pros: 
- Granular control over list of API endpoints exposed  
- Some arguments can be generated on server-side, smaller API surface 
- No need to redeploy Cadence server, can be used for multiple Cadence clusters 
- Pick your own language 
- It is possible to hide Cadence server from access behind this proxy 

Cons: 
- Need to track API changes, more maintenance needed.  
- Side-proxy service is an additional/external deployment with monitoring, logging and alerting needs.

**Comment by longquanzheng** [comment]
Comment for alternative: if you run an IWF service, you have an HTTP service like that for APIs like terminate, cancel, reset etc 

https://github.com/indeedeng/iwf#architecture

https://github.com/indeedeng/iwf-idl/blob/main/iwf.yaml

**Comment by demirkayaender** [comment]
I like this idea and I think it's a bit overdue. REST was also a popular ask from users. To provide an option for any language, I think we should do this.

I'm okay with the proposed solution. Eventually we might want something more raw as your mentioned in the alternatives.
