### ISSUE TITLE
Search in Cadence-Web with workflow id

### ISSUE THREAD

**Issue by ehsansis0** [uber/cadence#5266]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: 3.29.6

**Comment by SoulPancake** [comment]
@ehsansis0 
Cadence provides a built-in feature via the UI to search by the workflow ID
![image](https://github.com/uber/cadence/assets/70265851/3a888807-631e-4517-9d45-67ba0a9ecef2)
Do you mean something else?

**Comment by Cloxy777** [comment]
Not really a user-friendly search since a fully identical workflow ID should be provided, even case is important 
Search definitely could be improved
