### ISSUE TITLE
Improve error message when activity completion fails due to workflow being completed

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#532]
Current we return the following error message on activity completion:
EntityNotExistsError({Message:Activity task not found.})

It would be great if we can return more context like cannot find the activity because workflow completed.

**Comment by anish531213** [comment]
I think we already have a message "EntityNotExistsError{Message: workflow execution already completed}" . I reproed by running a workflow and sleeping the activity for 30s. Here is the result.

<img width="1671" alt="Screen Shot 2019-11-07 at 3 47 04 PM" src="https://user-images.githubusercontent.com/14882675/68437520-19de7700-0176-11ea-8669-156263c633c6.png">
@longquanzheng @andrewjdawson2016 Pls verify this and we can close the Issue.

**Comment by rohit-singhal1** [comment]
@anish531213 I'm seeing this same error and couldn't find any solution for this . can you please let me know how it was fixed ?
