### ISSUE TITLE
Cadence fails to start when running as binary

### ISSUE THREAD

**Issue by alexDrinkwater** [uber/cadence#533]
Since #516 we are unable to start cadence running as a binary. The error output is: 
```
Incompatible versions%!(EXTRA *errors.errorString=unable to read expected schema version: open github.com/uber/cadence/schema/cadence/versioned: The system cannot find the file specified.)
```
It seems like the change in #516 hardcoded the project path to "github.com/uber/cadence/schema". What was the intention of this change? Cadence should be able to run in any directory as a binary. 

The offending line is here: https://github.com/uber/cadence/blob/master/tools/cassandra/version.go#L134

**Comment by madhuravi** [comment]
Fixed, let me know if you run into anything.
