### ISSUE TITLE
DLQ for signals

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#537]
Currently if signal cannot be processed for whatever reason (unsupported type, decoding error, invalid workflow state, etc) the workflow implementation has the following options:

1. Log the error and Ignore the signal, which is the same as loosing it.
2. Fail the workflow. It may be acceptable in some cases, but it is not very robust to fail long running workflow on a single bad signal received (from CLI from example).
3. Handle decoding error and execute some activity that notifies workflow owner about the problem or puts the signal into some external data store for further analysis.

None of the options is perfect. The proposal is to support special decision (strawman FailSignal) that would tell Cadence Service that signal cannot be processed. Then per workflow type it should be possible to configure a policy to handle the failure. It can be either ignore (drop the signal) or do some action like putting it into special area (DLQ) that can be accessed by other tools or some external storage (Kafka?).

**Comment by JuanPalacios** [comment]
Hello folks,
When is planned to solve this issue? For us, it is very problematic that a wrong signal doesn't respond to the client.

Best Regards
Thanks

**Comment by mfateev** [comment]
@JuanPalacios I believe you want the "synchronous update" feature, not this one. Signals by definition are asynchronous and their status cannot be reported to the caller.

**Comment by JuanPalacios** [comment]
Thanks Maxim,
Right, I was checking and it is the synchronous update what we need, Is it already implemented?

**Comment by mfateev** [comment]
AFAIK it was removed from the Cadence roadmap. We plan to add it in Temporal, but no ETA yet.
