### ISSUE TITLE
Prometheus client memory usage

### ISSUE THREAD

**Issue by mantas-sidlauskas** [uber/cadence#5398]
Prometheus client is keeping metrics emitted indefinitely in memory. 

Over the time, tasklist metrics (but not only), sticky tasklist with uuid name tag will take pretty big amount of RAM, and calling '/metrics' to collect them takes more than 20s. The only way to get rid of those metrics is to restart Cadence instance. 

I don't see any way how to control TTL for metrics or disabling part of metrics collection. Or, for example detecting uuid and converting them to a common __uuid__ tag.

Looking on opinions and ideas on how to overcome this situation

**Comment by demirkayaender** [comment]
Thanks for the feedback Mantas! I will discuss this with the team, have some folks share here too.

**Comment by Groxx** [comment]
Is the desire to have a no-op metrics client so this can just be dropped (hopefully we have a way to set that up easily), or is it more of a "we use Prometheus but it has problems" thing?

Assuming you _want_ to use Prometheus but it's being too costly... any chance a library upgrade would solve this?  It sounds kinda like a thing Prometheus's client should have a way to deal with tbh, though I think Tally has similar memory-bloat issues.  But it may also be a sign we're using it wrong / should change something.

**Comment by dkrotx** [comment]
Is that by design or Prometeus is not gathering those metrics and that's why they reside in memory?

**Comment by mantas-sidlauskas** [comment]
@Groxx the idea here is to reduce cardinality, basically. per tasklist metrics are pretty costly, especially when name label is a uuid.  Similar issue filled for prometheus go client: https://github.com/prometheus/client_golang/issues/791

@dkrotx once emitted, metric will be kept forever regardless if you are scraping them or not.

**Comment by dkrotx** [comment]
@mantas-sidlauskas got it! That's basically the same for Tally. I would recommend looking towards not having uuid-like values. Otherwise you gonna have this problem with storage + some requests will struggle at runtime.

**Comment by mantas-sidlauskas** [comment]
Just to close the loop. There was a bug in Cadence Java Client which is fixed now: https://github.com/uber/cadence-java-client/issues/856
