### ISSUE TITLE
v1.2.2 (latest) is not uploaded to docker hub

### ISSUE THREAD

**Issue by thle40** [uber/cadence#5416]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: v.1.2.2

**Describe the bug**
All versions which are pre-release or used to be pre-release are not uploaded to dockerhub

**To Reproduce**
Is the issue reproducible? 
- yes

**Steps to reproduce the behavior:**
The docker images of latest version (v1.2.2) is not uploaded to docker hub

**Expected behavior**
The docker image of all versions are uploaded to docker hub
<img width="1703" alt="image" src="https://github.com/uber/cadence/assets/111481482/dd9b30cb-870c-419c-9bc4-5d98b0ee3960">

**Comment by sonhuynhpham** [comment]
It looks like Cadence server `v1.2.2` was pre-released initially before it's officially released. The workflow that builds and publishes the server image is triggered once when the release is `published`: https://github.com/uber/cadence/blob/a253154e59d04048ea3aa6d77242d1a412b86688/.github/workflows/docker_publish.yml#L9

However, all of its steps are conditionally to not run for prereleases: https://github.com/uber/cadence/blob/a253154e59d04048ea3aa6d77242d1a412b86688/.github/workflows/docker_publish.yml#L35

After the release change its state from `prerelease` to `release`, no workflow is triggered. Hence, no image is published for `v1.2.2` as the result.

I believe the solution is to add the `released` condition to the workflow ([doc](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release)). Note that, this change will only take effect for the release drafted after this change. So, I think the Cadence team will have to manually build and publish the Docker image for this version.

**Comment by Nepoxx** [comment]
This seems to have been the case since 1.0.0 as it is the latest tagged released on dockerhub: https://hub.docker.com/r/ubercadence/server/tags?page=1&name=v1

**Comment by 3vilhamster** [comment]
Thank you for reporting!
We will try to fix it on the next release.
