### ISSUE TITLE
Why does worker not support uninstalling or updating WorkflowType?

### ISSUE THREAD

**Issue by 1059915154** [uber/cadence#5425]
**Is your feature request related to a problem? Please describe.**
My requirement requires work support for uninstalling or updating workflowType, and I need to check if they are registered through workflow name.

**Proposed Solution**
1. Provide an API for uninstalling workflowType.
2. Provide APIs for updating workflow types.
3. Provide an API for querying whether registered through workflow name.

**Additional context**
I have implemented these locally.

**Comment by 1059915154** [comment]
I implement these functions based on the registry structure cache mapping.

**Comment by 3vilhamster** [comment]
Hey. Could you elaborate what is your usecase?
I'm not sure I understand.

**Comment by 1059915154** [comment]
@3vilhamster Thanks.
My scenario is to combine multiple HTTP interfaces into a workflow, including registering, uninstalling, or updating workflows. I require the entire process to be dynamic, rather than sending new versions every time changes are made.
I have already implemented the corresponding requirements locally. The general processing process is as follows:

1. Dynamically generate corresponding functions based on GO plugins, where each plugin corresponds to a complete workflow processing logic.
2. Dynamically register, uninstall, or update workflows based on the above functions, although cadence currently does not support uninstallation or update workflows. So I implemented it by modifying the cadence source code, first defining three interfaces in the cadence/worker that correspond to uninstallation, update, and detecting whether the workflow has been registered through name. Then implement these three interfaces in cadence/internal/registry, mainly based on a series of operations on registry.workflowFuncMap.

I am not sure if dynamic updates or uninstallations are suitable for long-term or scheduled workflows. But in my scenario, it seems reasonable.

**Comment by ibarrajo** [comment]
This is probably because it was not a use case previously. I don't see a downside for unregistering workflows dynamically. Especially long running workflows, since the task is automatically matched by Cadence to any available worker that has the workflow registered and is polling the task list.
