### ISSUE TITLE
Incorrect Usage. flag provided but not defined: -root

### ISSUE THREAD

**Issue by Hayden-Chang** [uber/cadence#5586]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Docker image with bug: ubercadence/server:master-auto-setup

**Describe the bug**
I ran cadence server using docker compose as official suggested and got an error after executing the command: `docker-compose up`:

```
root-cadence-1        | flag provided but not defined: -root
root-cadence-1 exited with code 1
```

After I replaced `image:ubercadence/server:master-auto-setup` with `image: ubercadence/server:latestRelease-auto-setup` in file `docker-compose.yml`. Everything is going well.

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
[run-cadence-server-using-docker-compose
](https://cadenceworkflow.io/docs/get-started/installation/#_1-run-cadence-server-using-docker-compose)

**Expected behavior**
start cadence-server successfully

**Screenshots**
<img width="558" alt="image" src="https://github.com/uber/cadence/assets/62008508/f4947893-143e-46ae-8cfc-9078370e521d">

**Comment by mantas-sidlauskas** [comment]
Fixed in https://github.com/uber/cadence/pull/5587
