### ISSUE TITLE
Optimization: History may use lock with Frontend timeout

### ISSUE THREAD

**Issue by vancexu** [uber/cadence#560]
Currently, sync lock is used to ensure serialized transaction, like in CreateWorkflowExecution. 
There are cases when one call is holding lock (because of network/db issues) which blocks all the others calls, and then after lock released all calls start to run and cause a spike.

One thing we can do to optimize is: 
Instead of using native sync lock, use common.lock with frontend context. If frontend context deadline exceed, history calls can release lock immediately.

**Comment by wxing1292** [comment]
workflow execution context already honor the input context
