### ISSUE TITLE
Rethink permission requirements for Admin API DescribeCluster endpoint

### ISSUE THREAD

**Issue by mantas-sidlauskas** [uber/cadence#5683]
#### Context
Cadence WEB is using `admin.DescribeCluster` API call to check if advanced visibility options are available for a cluster. 
All `admin.*` calls require `admin` level token when OAuth is enabled. This makes WEB unusable for a user who has only "read" level access to specific domain(s).

There are multiple options how to resolve this issue:

* Change `DescribeCluster` to require read level, you can't change anything anyway
* Move this endpoint to "Frontend" API, change WEB to request Frontend API

**Comment by d-vignesh** [comment]
Hi @demirkayaender , does this require backend or frontend change. If backend, i would like to work on this, can you please provide some context on what are the required changes here.

**Comment by osho-20** [comment]
would like to work on this.

**Comment by mantas-sidlauskas** [comment]
For now, this is fixed with: https://github.com/uber/cadence/pull/6081

Thanks for your interest @osho-20 !
