### ISSUE TITLE
Add progress aggregation support for a workflow tree.

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#583]
The workflow query supports reporting of a single workflow state. But even it cannot include a current progress of activities it is running. But there is no direct support to provide aggregated progress report for workflow trees. For example if a workflow starts 1000 child workflows and each of them starts 1000 of its own activities there is no way to get an overall progress.
The strawman proposal is to provide a way to get a callback into workflow code that includes progress of each activity and child workflow and returns aggregated result. Then this result is passed to the parent workflow for the similar aggregation. Then then root workflow can be queried for the aggregated result. These aggregated callbacks shouldn't be included into history, but their results might be persisted in the history service mutable state.
The open question is how to trigger these callbacks. When number of the children is small it might be done synchronously via query mechanism. But for millions of children it wouldn't scale. I think in this case the triggering can be done periodically. For example once a few minutes and only if there was some change in the reported state of activities. Then user can query the aggregated state directly from the mutable state.

**Comment by Bethalaayyappa** [comment]
Hi Team,
Cadence will it support all databases or specific ?

**Comment by mfateev** [comment]
We try to make all features database agnostic.

**Comment by Bethalaayyappa** [comment]
Could you please share cadence currently implemented in  which technologies used for Client side and server side.

**Comment by mfateev** [comment]
Cadence service is written in Go and relies on Cassandra or SQL database for persistence. 

The supported client side libraries are in Go and Java.

**Comment by Bethalaayyappa** [comment]
Is it possible to implement with couchbase ? As per existing code so far available in github.

**Comment by mfateev** [comment]
Correct me if I'm wrong as I'm not couchbase expert. But looking through its documentation it appears that it doesn't support multirow transactions. So Cadence cannot run on it. Cadence requires single shard multirow transactions.

BTW: We have a [slack channel](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTI5Yzc5ODYwMjg1ZmI3NmRmMTU1MjQ0YzQyZDc5NzMwMmM0NjkzNDE5MmM0NzU5YTlhMmI4NzIzMDhiNzFjMDM) for ad-hoc questions. You are welcome to join.

**Comment by plaisted** [comment]
I'm experimenting with Cadence for some scenarios where workflows are started in batches and aggregate statistics must be reported about the individual instances. This seemed like a good fit for cadence, one master workflow for the batch that would spawn the individual workflows in some sort of tree (batches generally between 10,000 and 1,000,000 items). Everything seems good other than querying and reporting batch status. Currently, it seems like the individual workflows would need an activity to report their status to an external store for aggregation / querying. While not complicated it seems a little odd as cadence is storing the state of the workflows as well and is the source of truth, why duplicate this again in another persistence layer? Is there a better way to do this or would this be the recommended way? Dumping the results externally would have benefits as cadence/cassandra is not great for queries across multiple workflow instances. Querying a million records in standard relational database is trivial but trying to do the same on top of cadence doesn't seem possible unless I'm missing something.

**Comment by mfateev** [comment]
I think the support for counter CRDT would solve the issue in a scalable and generic manner: https://github.com/uber/cadence/issues/1384

**Comment by xiaodiannao** [comment]
HI all,
Has there been any progress on this? I would be interested in this functionality as well. And is there a way to get progress of a single workflow (e.g. which activities are done, in progress and running) when only activities are involved (and no workflow tree)?
Best regards

**Comment by mfateev** [comment]
@xiaodiannao For business use cases use queryWorkflowExecution feature. The workflow can return whatever information it contains. The describeWorkflowExecution call returns the status of currently running activities including the number of attempts and the last error if an activity is in a retry loop. Use getWorkflowExecutionHistory to get full information about all the executed activities. 
There is no way to predict future activities as workflows are very dynamic. But a workflow can always return something like this in a query, but the workflow implementer would need to populate that list manually.

**Comment by xiaodiannao** [comment]
Thanks for your quick response @mfateev. Ah so for business use cases I can use the SetQueryHandler function and query the results from that using queryWorkflowExecution, do I understand that correctly?

**Comment by mfateev** [comment]
Yes you do understand it correctly.
