### ISSUE TITLE
Should have a better story about domain deprecation

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence#584]
Currently, once a domain is deprecated, the UpdateDomain API does not change the status of the domain, which means DeprecateDomain API is a oneway door, we should have a better story about this.
Should also check the current logic about domain, especially the part which domain status should be checked

**Comment by mfateev** [comment]
Another option is to add ability to undeprecate domains. This could be useful in emergency situation to stop all activity on a domain by deprecating it. Or may be introduce "suspended" state.

**Comment by dmetzgar** [comment]
This is a duplicate issue of #874
