### ISSUE TITLE
Do not require heartbeat timeout

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#589]
It is surprising that heartbeat timeout is required:
https://github.com/uber/cadence/blob/master/service/history/historyEngine.go#L1903

Also I would not require other timeouts. My proposal is to require either:

ScheduleToClose or both ScheduleToStart and StartToClose.

**Comment by samarabbas** [comment]
This may already be fixed.  Make sure to add a test case and resolve the bug.

**Comment by arthurguber** [comment]
Just verified this not fixed. Will add test and send PR.
