### ISSUE TITLE
Publish multiplatform docker images on docker.io to support arm64

### ISSUE THREAD

**Issue by aran** [uber/cadence#5898]
**Is your feature request related to a problem? Please describe.**

Some cloud providers offer arm64 execution environments at good prices. All new macs offer arm64.  For developing on a mac, or targeting arm64 deployments, it would be useful to have multiplatform linux/arm64 + linux/amd64 docker images for releases.

**Proposed Solution**
Update ubercadence/server and ubercadence/web CI to build and publish multiplatform linux/arm64 + linux/amd64 docker images. 

**Additional context**
N/A

**Comment by demirkayaender** [comment]
@neil-xie can we include this in our release process?

**Comment by neil-xie** [comment]
https://github.com/uber/cadence/pull/5962 this will multiple platform docker images on server release
