### ISSUE TITLE
Cross DC - Should have a better story of UpdateDomain API deleting existing clusters

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence#591]
Currently, CrossDC UpdateDomain API does not support removing existing replicating clusters. This is due to the nature of CrossDC, i.e. multiple clusters can modify the domain record, causing the Master cluster have no idea whether a replicated cluster can be safely deleted or not. 
E.g. master cluster delete cluster1, in the mean time,  cluster1 is set to be the active by domain failover.

We should have a better story about this.

**Comment by demirkayaender** [comment]
Global domains support this for a long time. Closing this issue.
