### ISSUE TITLE
Add explicit Lock abstraction

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#593]
There are use cases when workflows operate on some shared resources. For example upgrade workflow operates on the box, upgrade network switch workflow operates on rack, etc. So when switch is updated all workflows that upgrade a box should wait.
The proposal is to introduce a "lock" abstraction. Workflow would be able to "aquire" and then "release" a lock. And aquire operation would ensure to return aquired only for a single workflow at a time. An extension would be to support read/write locks.

The strawman API proposal:

AcquireLockDecision name="lockName", mode=read, timeToWait=1minute
ReleaseLock name="lockName"

When lock is acquired the following event is inserted into the history:
LockAquiredEvent aquireEventId=<id of AquireLockEvent">
AquireLockTimeout if timed out.

Then provide visibility API to list workflows that are waiting on a lock. Also given list of lock names it should be possible to find out all deadlocks, so we could even identify them automatically.

**Comment by yiminc** [comment]
It needs to handle the case where the workflow that obtained the lock is closed without releasing it (like timedout).

**Comment by mfateev** [comment]
I think it should be released automatically once the workflow closes. No need for the timeout.
