### ISSUE TITLE
Cadence v1.2.11 release doesn't publish any image

### ISSUE THREAD

**Issue by sonpham96** [uber/cadence#6173]
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: `v1.2.11`
- Client version:
- Client langauge:

**Describe the bug**
The latest version `v1.2.11` is released without publishing the image to Dockerhub. The corresponding build that publish the image has failed: https://github.com/uber/cadence/actions/runs/9880171785.

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
A clear and concise description of the reproduce steps.
- Release a new version or rerun the failed `Publish Docker image` workflow will not publish any image.

**Expected behavior**
- The image `ubercadence/server:v1.2.11` is published to the Dockerhub https://hub.docker.com/r/ubercadence/server.

**Screenshots**

**Additional context**
Add any other context about the problem here, E.g. Stackstace, workflow history.

**Comment by neil-xie** [comment]
Github action version for publishing docker image was bumped to v5 in #6134, however multi-platform build is not supported for the docker driver and the action failed to build and push the image. We are currently working on manually building and publishing v1.2.11.

**Comment by neil-xie** [comment]
The issue has been fixed in #6187, next release should be pushed automatically. We are still working on manually building and publishing v1.2.11.

**Comment by neil-xie** [comment]
https://hub.docker.com/layers/ubercadence/server/v1.2.11/images/sha256-12e07e5619d4a879b8b752d9c29792a45f0410c2e7658a91f3bc172e72d2a3eb?context=explore v1.2.11 is published
