### ISSUE TITLE
Support for various ChildPolicy on Cadence server

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#629]
StartWorkflowExecution allows user to specify the following 3 type of ChildPolicy:
```
enum ChildPolicy {
  TERMINATE,
  REQUEST_CANCEL,
  ABANDON,
}
```

Current server implementation only supports ABANDON and does not have support for TERMINATE and REQUEST_CANCEL ChildPolicy for child workflow executions.  
This issue is to implement support for all types of ChildPolicy on Cadence server.

**Comment by wxing1292** [comment]
@longquanzheng can we close this?

**Comment by longquanzheng** [comment]
It's already done in latest master(shoudl be released soon).
