### ISSUE TITLE
[Best Practices] Eliminate the direct usage of ErrorAndExit in CLI command

### ISSUE THREAD

**Issue by shijiesheng** [uber/cadence#6317]
**Is your feature request related to a problem? Please describe.**
We recently upgraded urfave package to V2 which now supports error handling in a centralized way. For best practices, we should require every command line to return error instead of exit directly. 

**Proposed Solution**
Deprecate the usage of `ErrorAndExit` and propagate error to command line instead. 

**Additional context**
The function to remove is here https://github.com/uber/cadence/blob/605fc74ea8af939bbbaac230991404deed929991/tools/cli/utils.go#L555

**Comment by samkitshah1262** [comment]
Hi , I'm interested in solving this issue. Thanks
