### ISSUE TITLE
Cadence Feature: Support for Query Decision Task API

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#64]
This is for monitoring purpose, cli style scenarios.  This allows us to get call-stacks, debug stuck issues, etc without hosting decider implementation.

**Comment by samarabbas** [comment]
We are thinking about a more generic support for query which can be used by clients to issue custom queries to workflow execution, like expose current state of execution.

**Comment by dmetzgar** [comment]
@samarabbas since we already have query support, can we close this issue?
