### ISSUE TITLE
Cross DC - Temporary Transfer & Timer Cursor Should Be Persisted.

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence#646]
Current implementation has an assumption that during a domain failover, the host will not shutdown.

**Comment by wxing1292** [comment]
close in favor of #1272

**Comment by meiliang86** [comment]
@yux0 @wxing1292 Is this still relevant?

**Comment by wxing1292** [comment]
can be closed after @yycptt 's work on queue multi cursers
