### ISSUE TITLE
Add ability for workflow to wait for completion of an external workflow

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#656]
Currently a workflow code can wait for completion of its child workflow. 
It is also possible to wait for a completion of any workflow given its id from an external client.
Ability waiting for completion of any workflow from a decider code is missing.

Strawman proposal:

- Add a WaitForExternalWorkflowCompletion decision and the correspondent event.
- Add a WaitForExternalWorkflowCompletionFailed event
- Add ExternalWorkflowCompleted/Failed/Cancelled/Terminated/TimedOut events. Another option is to have an
ExternalWorkflowCompleted event that contains the termination event of the external workflow as a field.

**Comment by meiliang86** [comment]
What is the benefit of using child workflow if we have this?

**Comment by mfateev** [comment]
The waiting part is almost the same if this is implemented. But the child workflow creation part is still needed.

**Comment by Groxx** [comment]
lemme +1 this request.  I'm hoping to build a "nanny" workflow to do cleanup regardless of how another workflow exits, and at the moment the only ways to do this seem to be:
- use the nanny workflow to run the "real" workflow as a child-workflow, so it can wait on the completion.  works, but adds a layer of indirection, kinda hard to adapt existing code.
- long-poll with GetWorkflow(..) and wait on the completion, e.g. in a long-running activity.  fine for small numbers, but I'd be looking at millions of active workflows -> active long-polls.
- or this issue, which would let me launch the nanny / observer / cleanup from inside the workflow whenever needed.

**Comment by Groxx** [comment]
Specific to my case, where I want to run code based on the *completion* of another workflow:
@meiliang86 came up with the great idea of starting a child workflow with `ParentClosePolicyRequestCancel` and just sleeping for, like, a year or some other absurd length.  When the parent completes, the ctx will cancel and the sleep will unblock, at which point I can get a disconnected context and do whatever I like.

That's a pretty acceptable workaround for cases like mine.
A true "wait for any workflow" mechanism would still be great though, and far more flexible, so my +1 stands :)
