### ISSUE TITLE
Query should fail immediately if workflow history was deleted due to retention.

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#662]
Currently if a workflow history was deleted due to the retention the query times out.
The server logs the following error:

cadence_1      | time="2018-04-11T17:43:28Z" level=info msg=QueryWorkflowFailed. Domain=sample QueryType="GreetingWorkflow::queryGreeting" RunID=f17dc7e0-aa2f-4fe9-ac04-b811ae23deb5 Service=cadence-frontend WorkflowID=e1856720-3544-47f4-ab48-9bb1acff80ce wf-event-id=6001
cadence_1      | time="2018-04-11T17:43:28Z" level=error msg="Uncategorized error" Service=cadence-frontend err="code:deadline-exceeded message:timeout"

To reproduce, set the domain retention to 0 and run a query against a closed workflow.

**Comment by andrewjdawson2016** [comment]
```
~/Desktop/cadence(MatchingQueryRefactor) » ./cadence --do samples-domain wf query --wid helloworld_5adb33ef-c143-4af4-87f6-d633b119550d --qt __stack_trace
Error: Query workflow failed.
Error Details: EntityNotExistsError{Message: Workflow execution not found.  WorkflowId: helloworld_5adb33ef-c143-4af4-87f6-d633b119550d}
('export CADENCE_CLI_SHOW_STACKS=1' to see stack traces)
```

Resolved.
