### ISSUE TITLE
Optimize the history cache clearing strategy

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence#668]
#667 only fix the issue that whenever a err occur, the mutable state cache should be cleared.
However, there are cases which the mutable state is not touched, and the mutable state cache can be left intact.
We should optimize those cases, especially the EntityNotExists error case.

**Comment by meiliang86** [comment]
@wxing1292 Is this still relevant?

**Comment by wxing1292** [comment]
conditionally.

currently, there is no clean & reliably way to know that if an error is returned, no change is modified to mutable state. so each time an error happens, mutable state cache is cleared.

plz keep this issue open, to remind us of this potential perf improvement.
however there is nothing we can do for now (and probably even in the future)

**Comment by wxing1292** [comment]
we can add a `dirty cache` flag indicating that the mutable state is changed, the cost is refactoring the entire mutable state & corresponding logic: change everything to getter & setter.
