### ISSUE TITLE
Admin CLI for Cadence servicing operations

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#677]
We need admin commands like the following to support certain servicing scenarios:
1) Visibility into MutableState Database
2) Visibility into MutableState Cached
3) Induce DecisionTask
4) Induce ActivityTimeout for workflow execution
5) Force Reload Shard
6) Force Reload mutable state cache
7) Find host from workflow execution

**Comment by longquanzheng** [comment]
First admin CLI: https://github.com/uber/cadence/pull/762

**Comment by longquanzheng** [comment]
MutableState visibility 
https://github.com/uber/cadence/pull/805

**Comment by samarabbas** [comment]
History Host Level Analytics:
1) Number of Shards
2) Number of items in DomainCache
3) Number of items in HistoryCache for a specific shard

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence/pull/1601
https://github.com/uber/cadence/pull/1581
