### ISSUE TITLE
'go get' fails (error inside)

### ISSUE THREAD

**Issue by marzhall** [uber/cadence#689]
Hi Cadance team!

   I and a coworker are seeing an issue on just about any machine we try when we attempt to run the '[Developing Cadance](https://github.com/uber/cadence/blob/master/CONTRIBUTING.md)' instructions, specifically the first command, `go get github.com/uber/cadence/...`.

The error text is at the pastebin [here](https://pastebin.com/WUC3CDtp).

I've tried this on a Windows7, CentOS, and arch linux box; my coworker had the issue on a Windows 10 box.  

The go version we're using on windows is from the [golang](https://golang.org/dl/) download page:

```
$ go version
go version go1.10.1 windows/amd64
```
and is being run inside a cygwin environment, in which we've installed make. My machine has git version 2.17.0.

The arch box I'm using has go 1.9.2 installed, and git version 2.16.1; the centOS box has go 1.9.4, and git 1.7.1.

The arch box is on a separate (home) network from the other boxes.

Let me know if there's anything else I can provide that will help.

Thanks!

Marshall

**Edit:**

If I attempt the following command `make copyright`, the command succeeds; if I then try `make bins`, it fails with the error:

```
$ make bins
go get './vendor/go.uber.org/thriftrw'
package github.com/uber/cadence/vendor/go.uber.org/thriftrw: cannot find package "github.com/uber/cadence/vendor/go.uber.org/thriftrw" in any of:
        /usr/lib/go/src/github.com/uber/cadence/vendor/go.uber.org/thriftrw (from $GOROOT)
        /home/me/go/src/github.com/uber/cadence/vendor/go.uber.org/thriftrw (from $GOPATH)
```

The vendor directory, meanwhile, is empty, I'm guessing because of the failure of the `get`.

**Comment by mfateev** [comment]
Sorry, 
It looks like go get got broken by some external dependency.
I've updated the instructions to use git clone instead. Try the new ones:

https://github.com/uber/cadence/pull/690

**Comment by marzhall** [comment]
No problem! The issues I've mentioned no longer pop up. I'll need to grab glide to confirm the full build works. Thanks for the help!

**Comment by marzhall** [comment]
Those issues are confirmed gone, though it now looks like `make` fails with:

```
go get './vendor/go.uber.org/thriftrw'
go get './vendor/go.uber.org/yarpc/encoding/thrift/thriftrw-plugin-yarpc'
/bin/thriftrw --plugin=yarpc --pkg-prefix=github.com/uber/cadence/.gen/go/ --out=.gen/go idl/github.com/uber/cadence/cadence.thrift
make: /bin/thriftrw: Command not found
make: *** [Makefile:37: .gen/go/cadence/cadence.go] Error 127
```

The vendor/thrift directory is present, and populated;  Seems like the package isn't being placed in the path (should I have it installed separately?). Thanks!

**Comment by longquanzheng** [comment]
have you set GOPATH? If not you can try setting GOPATH before running it. 
https://github.com/golang/go/wiki/GOPATH

**Comment by marzhall** [comment]
The GOPATH is set, yup.

**Comment by longquanzheng** [comment]
I found that you have to run "glide up" before running "make bins". 
Can you pull the latest commit and try again?

**Comment by marzhall** [comment]
I pulled the latest commit and tried again after running `glide up`; same issue. I think you're correct in that the `GOPATH` isn't set, at least when the makefile is being run; I'm digging around in how to find out whether that env var is set in the makefile.

**Comment by mfateev** [comment]
Don't run glide up. It updates the dependencies in a rather random way. Run glide install which just installs the dependencies according to the glide.lock file.

**Comment by marzhall** [comment]
@mfateev - Thanks! I ran `glide install`, then reran `GOPATH=$GOPATH make`, but still received the same error log as before.

**Comment by marzhall** [comment]
Ha!
````
cd $GOPATH/src
cp -r github.com ../
GOPATH=$GOPATH make` 
```

did it - the tests are now running.

**Comment by mfateev** [comment]
Weird. Here is the output from my environment:

```
$ echo $GOPATH
/Users/maximfateev/external
$ pwd
/Users/maximfateev/external/src/github.com/uber/cadence

```

**Comment by marzhall** [comment]
Gotta echo your 'weird' here. At this point, I'm going to chalk needing to copy things up to PEBKAC. I'll be working with my coworker next week, so I'll end up running through again, and I'll report if we run into any other issues. This can probably be closed - thanks again for the help!

**Comment by mfateev** [comment]
I"m going to update Makefile to include linter. For now just run this command:

go get -u golang.org/x/lint/golint
