### ISSUE TITLE
[code cleanup]: emptyEventId/bufferedEventId defined in 2 places.

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#699]
one in common/constants.go, the other one history/historyBuilder.go
need to remove one of them.

**Comment by mudit3774** [comment]
@yiminc we are trying out cadence planning to contribute back. I'll be interested in taking up this issue, it will help us get started. I have identified changes. 

If I understand correctly, you suggest moving all constants in history/historyBuilder 

`const (
	emptyVersion int64 = -2234

	firstEventID     int64 = 1
	emptyEventID     int64 = -23
	bufferedEventID  int64 = -123
	transientEventID int64 = -124
)`

to common/constants.go and refactoring files that use them ?

**Comment by yiminc** [comment]
@mudit3774 , yes, that is what we want to do. Thanks for working on this. 👍

**Comment by mudit3774** [comment]
@yiminc : I have raised a pull request for the same : https://github.com/uber/cadence/pull/715 

All checks are passing and CLA is signed. It would be great if you can review it.

**Comment by mudit3774** [comment]
@yiminc thanks for your PR comments and approving the PR. I have resolved conflicts and it is ready to merge.
