### ISSUE TITLE
Prohibit DecisionTimeout larger than certain max value

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#701]
This seems to be a common problem clients run into where they set very large DecisionTimeout value when starting workflow execution.  This cause the workflow to appear it is stuck when decision is dropped by the worker for whatever reason.  Decision should be very fast and most of the time should take under a second.  We need to restrict DecisionTimeout to some reasonable value, like 60 seconds for instance.
Things to consider when restricting are:
1) Local Activity
2) Debugging experience is effected as decision will timeout when stepping through decider code

One idea is to log a warning when someone sets a decision timeout higher than a threshold.
Another idea is to reject request on docker with higher decision timeout for developers to catch these during development.

**Comment by samarabbas** [comment]
We can make decision timeout optional on the server and default to some reasonable value.  The default value needs to support override per domain.

**Comment by wxing1292** [comment]
decision mac start to close timeout is default to 4 min:
https://github.com/uber/cadence/blob/master/service/history/service.go#L196
