### ISSUE TITLE
CLI command to fail activities manually

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#738]
If workflow has incorrect timeout specific when activity is scheduled then it appears the workflow is stuck when someone restarts the worker while activity is running.  But in reality workflow is waiting on a timer to fire to timeout the activity in future.
It would be great to have a CLI command to manually fail an activity, considering we already expose all the information about outstanding activities using the describe command.  This will be really useful feature for operations where someone can manually unstuck workflows by failing such activities manually.

**Comment by mfateev** [comment]
I would also allow completing activity successfully through CLI

**Comment by dmetzgar** [comment]
@longquanzheng looks like this can be closed

**Comment by longquanzheng** [comment]
Yes, let me close it.
