### ISSUE TITLE
Allow filtering by close time in ListClosedWorkflowExecutions

### ISSUE THREAD

**Issue by nathanboktae** [uber/cadence#740]
Currently only start time is filterable. Needed for uber/cadence-web#17

**Comment by dmetzgar** [comment]
@longquanzheng, is this part of your work on visibility?

**Comment by vancexu** [comment]
This feature is completed. 
With dynamic config `EnableReadFromClosedExecutionV2` set to true (OSS default is false to avoid breaking change), ListClosedWorkflowExecutions will sort/filter by closeTime.
