### ISSUE TITLE
[Question] Workflow failure due to worker

### ISSUE THREAD

**Issue by MrSaints** [uber/cadence#751]
In the README:

> An individual activity execution is not fault tolerant as it can fail for various reasons. But the workflow that defines in which order and how (location, input parameters, timeouts, etc.) activities are executed is **guaranteed to continue execution under various failure conditions**.

Assuming a workflow worker receives a task, and crashes out midway. Are there any retry logic to "replay" a workflow in another worker? What are these "various failure conditions" ?

In a quick experiment using https://github.com/samarabbas/cadence-samples/tree/master/cmd/samples/cron, it looks like the workflow just times out naturally with `WorkflowExecutionTimedOut`, and `START_TO_CLOSE`.

I am just interested in understanding the internals a little bit more. Maxim's talk helped quite a bit, but I would love to know more about the architecture. _On a related note, what is a `DecisionTask` ?_

**Comment by mfateev** [comment]
Imagine a simple workflow that executes activity A then B.
Let's say the activity A is running and is about to complete. The following steps describe processing that happens in this case if there are no failures:

1. The activity worker calls [RespondActivityTaskCompleted](https://github.com/uber/cadence/blob/master/idl/github.com/uber/cadence/cadence.thrift#L202) with the result of A.
2. The Cadence server adds an ActivityTaskCompleted event into the workflow history.
3. Atomically with 2 it also schedules a DecisionTask by adding DecisionTaskScheduled event in the history and putting the task itself (which is essentially a message) into the workflow task list (which is essentially a queue).
4. A workflow worker that polls on the same decision task list picks up the decision task that contains the latest history. It records a DecisionTaskStarted event that contains identity of the worker that picked up the task into the workflow history.
5. Workflow state is recovered from the history and then workflow code executes until it is blocked, producing "ScheduleActivity B" decision.
6. RespondDecisionTaskCompleted Cadence service API is called with this decision. It records DecisionTaskCompleted into the history.
7.  Atomically with 6 an ActivityTaskScheduled event added to the history and an activity task for activity B is put into the activity B task list.
8. Activity worker that polls on this task list picks receives the activity B task and starts executing it.

If workflow worker crashes during step 5 the following happens:

5. WorkflowWorker crashes.
6. After a DecisionTaskTimeout seconds the DecisionTaskTimedOut event is written to the history and
atomically new DecisionTask is scheduled by putting DecisionTaskScheduled event and putting decision task into the an apropriate task list.
7. WorkflowWorker (possiblay different one as the first one crashed) picks up the decision task that contains the latest history. It records DecisionTaskStarted event into the workflow history.
7. Workflow state is recovered from the history and then workflow code executes until it is blocked, producing ScheduleActivity B decision.
8. RespondDecisionTaskCompleted Cadence service API is called with this decision. It records DecisionTaskCompleted into the history.
9.  Atomically with 6 an ActivityTaskScheduled event added to the history and an activity task for activity B is put into the activity B task list.
10. Activity worker that polls on this task list picks receives the activity B task and starts executing it.

As you see the steps from 7 to 10 are the same as the steps 5-8 in the happy case.

Note that is important to not set DecisionTask timeout too a large value as it is the time workflow is essentially stuck if workflow worker is crashed. As processing of a single decision task usually takes milliseconds we recommend setting it to an up to a minute value.

**Comment by samarabbas** [comment]
Can you paste the workflow execution history here? You can use the cli to dump history.

**Comment by MrSaints** [comment]
I've included two different, but possibly related failures: https://gist.github.com/MrSaints/c76a0fc215d2a720043a2f4ff26a6b45

But they both seem tied to the workflow getting _stuck_ at `ActivityTaskStarted` despite the activity task worker being active. And they were both triggered by prematurely killing off a running worker with a backup running to pick up the work when `DecisionTaskTimedOut`.

**Comment by samarabbas** [comment]
Did you kill the activity worker while it activity task was being executed?
I looked the at history of your second execution.  Here is what I see:
- Activity [sampleCronActivity] is scheduled by workflow at: 2018-05-18T09:55:06
- Activity is picked up by worker ID '65265@<omitted>@cronGroup' at: 2018-05-18T09:55:06
- Workflow timedout roughly 4 minutes later: 2018-05-18T09:59:20

I'm assuming you killed worker '65265@<omitted>@cronGroup' while activity was running.  If you look at the activity scheduled event, it is has all the timeouts associated with the activity.  The earliest timeout which can fire for the activity is 'startToCloseTimeout' or 'heartbeatTimeout' which are both set for 10 minutes (600 seconds).  So before any of the timeout can kick in Workflow timeout comes into play and times out the entire workflow after 4 minutes.
If you activity is long running and really need the 10 minutes 'startToCloseTimeout' I suggest to heartbeat from the activity and set the heartbeat timeout to a lower value like 10 seconds.  So your workflow code can react to worker restarts faster as the heartbeat timeout will kick in after 10 seconds if activity does not heartbeats and your workflow logic can reschedule the activity which will be picked up by another worker.

Hope this explains the semantics you are seeing with your workflow running on Cadence.

**Comment by MrSaints** [comment]
Thanks for a thorough explanation @samarabbas. I don't believe that I killed the worker while activity was running, nevertheless, I can see how the timeouts again are likely to be the _cause_ here for the behaviour.

My use-case is primarily leaning towards long-running workflows, DSLs, and cron jobs which is why I am curious about the overall architecture. Knowing the configuration options will help me to avoid potential quirks.

That said, I have several additional questions if you do not mind:

- As highlighted in the docs, and in this issue, a workflow receives a history of events, and only new events will be sent to the server. How exactly does deduplication work? Specifically:

1. I have a workflow with activity of type A, B , C
2. I run the workflow, and it executes A, and B
3. What happens if in the middle of the workflow execution, the workflow has been updated to be A, B, B? I take it that the second B will be executed because there is no event associated with it?
4. Similar to (3), what happens if the workflow has been updated to be B, B, C? The first B does not correspond to the original event with A I guess? So in such a case an error will be returned?

I know there are version flags to prevent this, but I am just curious about how Cadence exactly matches up an event with the underlying code that executed it, and will be potentially executing it.

- Does an activity's arguments get registered on the server? I had a cursory glance through the source, and it looks like it is only on the side of the client, and the server pretty much just behaves as an opinionated queue / broker

- Are there any plans / support for middlewares or hooks? I would love to index some "activity" for search, and at the moment, I was thinking of just wrapping `ExecuteActivity` or creating an activity that fires off an event

- I take it that inputs, and outputs are serialised as JSON for storage? I also see that there is a serialiser for Thrift structs?

**Comment by mfateev** [comment]
A possible cause of an activity task loss is https://github.com/uber/cadence/issues/709. The idea is that when a worker disconnects, the server doesn't process the socket disconnect correctly and can still dispatch a task to the zombie worker. This issue is expected to be fixed ASAP. But in any case there is possibility of a task loss due to a worker or network failure and a workflow has to rely on a timeout to deal with it.

You cannot change A, B, C to A, B, B or B, B, C without using the GetVersion API. The workflow history of A, B, C is not compatible with the updated code and it is going to fail without versioning. 

1. What do you mean by "registered on the server"? The workflow execution history contains ActivityTaskScheduled event with input property that contains serialized activity arguments.
2. The Java client does support the middleware already. For the Go one we have plans: https://github.com/uber-go/cadence-client/issues/375. Currently wrapping the ExecuteActivity call is the most reasonable workaround.
3. Correct. The current serializer uses Thrift serialization for thrift structures and JSON for all others. Here is the PR for making the serializer pluggable: https://github.com/uber-go/cadence-client/pull/463.

**Comment by mfateev** [comment]
We do plan to have metadata registry of workflows and activities. But I'm not sure that it would help in your use case.

**Comment by MrSaints** [comment]
Apologies, I have another Q.

I was digging around `getRegisteredActivityNames`, and `activityFuncMap`, and I was wondering if you could potentially run multiple, but different activity workers with an activity of the same name? 

e.g. "Worker1" runs an activity called "ActivityA" which behaves completely differently from another "ActivityA" running inside "Worker2"

From what I can tell, conflicts are prevented at the client-level (`return fmt.Errorf("activity type \"%v\" is already registered", registerName)`), but if two different "clients" are used, will there still be some global protection?

**Comment by dmetzgar** [comment]
@MrSaints, is there any other follow-up needed for this issue that it needs to stay open?

**Comment by MrSaints** [comment]
I'll close it for now :) It covered most of my questions. Thanks again all.
