### ISSUE TITLE
Failed to get current schema version from cassandra when starting cadence

### ISSUE THREAD

**Issue by pkrull** [uber/cadence#753]
We had a cadence pod in our k8s cluster fail. The pod repeatedly attempts to restart but cadence fails to start. 
The error message is 
```
Incompatible versionsunable to read cassandra schema version keyspace: cadence error: Failed to get current schema version from cassandra
```

The log from the pod is as attached.
[logs-from-cadence-in-cadence-6fbbf97d58-6v5m9.txt](https://github.com/uber/cadence/files/2018521/logs-from-cadence-in-cadence-6fbbf97d58-6v5m9.txt)

**Comment by pkrull** [comment]
Never mind. This is a cassandra issue.

**Comment by wzf1943** [comment]
Could you tell how to fix the cassandra issue. Cause I also meet this issue too.

**Comment by pkrull** [comment]
I'm afraid I don't remember how we fixed it. It was likely that we redeployed cassandra.
