### ISSUE TITLE
Ringpop error on start

### ISSUE THREAD

**Issue by alexDrinkwater** [uber/cadence#767]
Hey Guys, 

I am getting an intermittent error when trying to start cadence as a binary locally

```
Ringpop creation failed\" Service=cadence-frontend err=\"join duration of 45.2023763s exceeded max 30s\

```

What is ringpop? And what could cause this error?

I notice this issue more if I have chrome and slack open. It also will kill my network sometime too.

**Comment by vancexu** [comment]
Hi @alexDrinkwater , 
ringpop is a [library](https://github.com/uber/ringpop-go) Cadence used for service discovery. 
It looks like node take too long to join the ring, have you try using our docker image to start cadence locally? How did you start cadence as binary? We use binary all the time but we never seen this error before. (We do see similar errors when running our integration tests on Travis though https://github.com/uber/cadence/issues/737 ).

**Comment by alexDrinkwater** [comment]
@vancexu I compiled the binary into an exe for windows using this command:

```
go build -o cadence.exe
```

I am trying to start it with:

```
cadence.exe start
```

**Comment by samarabbas** [comment]
@alexDrinkwater we run Cadence server as an executable on our Macbook all the time for local development and have never ran into the issue you described above.  Unfortunately we don't have the expertise to debug this issue on Windows.
I suggest you use the docker we provide to run Cadence on Windows.  Otherwise you need to debug further to figure out why ring-pop is unable to bootstrap on a windows machine.

**Comment by alexDrinkwater** [comment]
@vancexu Is the service discovery used for discovering other cadence servers or Cassandra servers?

We are just running one instance of cadence, can we turn off service discovery?

**Comment by alexDrinkwater** [comment]
@samarabbas Unfortunately this is not for a development scenario but for a windows desktop app and it is a requirement to not have docker.

**Comment by vancexu** [comment]
@alexDrinkwater running even 1 instance of cadence will start multiple shards of frontend, history, and matching services, which ensure Cadence is scalable, so there is no way to shut it down. 
Could you try edit your config file (development.yaml) and change the ringpop maxJoinDuration to 60s and make clean build again and try?

**Comment by vancexu** [comment]
@alexDrinkwater Were you able to walk around this ringpop issue?

**Comment by vancexu** [comment]
This issue is there without news for sometime, close it for now, and let us know if more questions
