### ISSUE TITLE
Curious as to why keyspace in Cassandra sets replication factor of 1?

### ISSUE THREAD

**Issue by ryanwalls** [uber/cadence#787]
We have been having stability challenges with our cassandra cluster... which we are working on.  But we are noticing that if we lose one node in our cluster, we lose data.  When I describe the cadence keyspace it says the replication factor is 1.  What's the rationale there?  We are new to cassandra administration, but it would seem you would want a replication factor of at least 2 if you don't want to lose data when a node goes down.

```
cqlsh> describe keyspace cadence

CREATE KEYSPACE cadence WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
```

**Comment by samarabbas** [comment]
@ryanwalls replication factor of 1 is used for developer setup for running Cadence server on laptop.  For production cluster we recommend to use replication factor of 3.  Please use 'cadence-cassandra-tool' to create both the cadence and cadence_visibility keyspaces.  It already has an option to configure the replication factor.

```
cadence-cassandra-tool --ep $CASSANDRA_SEEDS create -k $KEYSPACE --rf $RF
```

**Comment by ryanwalls** [comment]
Going to leave this open until the README for the cadence-cassandra-tool is updated with this info.  https://github.com/uber/cadence/blob/master/tools/cassandra/README.md
