### ISSUE TITLE
Multi-master HA?

### ISSUE THREAD

**Issue by danielnorberg** [uber/cadence#795]
Does cadence support running in a multi-master HA setup or is only one cadence server supposed to be running at any one time?

Could not find any mention of this in the docs.

**Comment by samarabbas** [comment]
Currently each Cadence server deployment is standalone.  But we are working on support for replication of workflow execution state from one cluster to another.  When this feature is built, you can have multiple Cadence clusters and have then create a global domain across them.  The domain will be active in a single cluster but it will have an API to failover the domain to another cluster and continue processing of workflows where it left off.
