### ISSUE TITLE
API documentation 

### ISSUE THREAD

**Issue by mohelsaka** [uber/cadence#797]
I'm thinking of building a Perl or Ruby client for cadence, can you point me to some docs for the API or a guide of how to build new client?

**Comment by mohelsaka** [comment]
Any help with that?

**Comment by mfateev** [comment]
Sorry for the delayed reply, we missed the first notification.

We don't have complete documentation about how to build a new client, but I could clearly help building one. 
There is [AWS SWF Ruby Client](https://docs.aws.amazon.com/amazonswf/latest/awsrbflowguide/welcome.html) which can be used as a starting ground.
The service API is defined [here](https://github.com/uber/cadence/blob/master/idl/github.com/uber/cadence/cadence.thrift). It closely resembles the AWS SWF API, so I would recommend first checking its [API Reference](https://docs.aws.amazon.com/amazonswf/latest/apireference/Welcome.html) for structures and field descriptions. Cadence already diverged from that API and we can provide more info on the differences.

What is your use case? Do you plan to use the new client for some application or platform?

**Comment by mfateev** [comment]
Currently Cadence uses [TChannel](https://github.com/uber/tchannel) as a communication protocol. TChannel doesn't have Ruby or Perl library. We will need to enable HTTP/JSON endpoint on Cadence frontend to work around it.

**Comment by dmetzgar** [comment]
#348 covers the HTTP endpoint
