### ISSUE TITLE
XDC - Sign benchtest with failover testing

### ISSUE THREAD

**Issue by vancexu** [uber/cadence#807]
When start long running workflow in bench, perform a failover from clusterA to clusterB and then failover again back to clusterA, workflow events are not replicated completely in clusterB. 
Also, workers in clusterA didn't complete workflow as expected, which leads to workflow timeout.

This only happen when performing failover and then failover back immediately (within several seconds).

**Comment by samarabbas** [comment]
@vancexu can you verify after all the recent fixes.
