### ISSUE TITLE
XDC - Ability To Turn On And Off CrossDC Dynamically

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence#830]
1. Ability to turn on and off cross dc functionality, by dynamic config. (this requires a restart)
2. Ability to turn on and off the replication task generation & transmission to Kafka, by dynamic config. (this requires a restart)
3. Double check on the existing path which use domain's IsGlobalDomainEnabled & cluster metadata's IsGlobalDomainEnabled
4. Double check on the new component, i.e. standby transfer / timer processor, replication task processor, V2 domain table, worker, failover.

**Comment by vancexu** [comment]
Enable global domain added at https://github.com/uber/cadence/pull/858
Replication switch is decided not needed for now.
