### ISSUE TITLE
Add domain filter to history config MaximumBufferedEventsBatch

### ISSUE THREAD

**Issue by vancexu** [uber/cadence#852]
It is non-trival to add domain filter to dynamic config MaximumBufferedEventsBatch in history. Currently in mutableState, we only have domainID but no domainName or domainCache. 

There are 3 possible ways:
1. Add domainName to executionInfo, along with domainID. But this requires persist additional unimportant info. 
2. Add domainCache reference in mutableState
3. Add new type of filter domainID, which confuse people and sometimes hard to get domainID.

**Comment by wxing1292** [comment]
MaximumBufferedEventsBatch should not be domain specific, but rather a service level protection
