### ISSUE TITLE
Calling CreateDomain() with the same UUID concurrently would return error (V2)

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#871]
InternalServiceError{Message: CreateDomain operation failed. Inserting into domains table. Error: gocql: not enough columns to scan into: have 1 want 4

**Comment by longquanzheng** [comment]
This bug cannot be stable repro. We we fix it when it becomes an issue.
The test is in common/persistence/cassandraMetadataPersistenceV2_test.go#TestConcurrentCreateDOmain()

**Comment by wxing1292** [comment]
already fixed
