### ISSUE TITLE
Multi-cluster clients

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#888]
One way to improve availability of the Cadence service is running multiple Cadence clusters per region with replication between them.
To not require running a separate client worker pool per cluster the proposal is to enable workers to connect to multiple clusters and seamlessly switch to the active cluster for the given domain. There is no need to switch for task polls as they just return no tasks from passive clusters. But for StartWorkflowExecution, Signal, Query and similar calls clients need to know in which cluster a domain is active. Another option is to allow calling these operations on any cluster and just forward them internally to the active one.

**Comment by ibarrajo** [comment]
Closing this since Cadence built Global Domains which provide active/passive replication with failover between clusters.

https://cadenceworkflow.io/docs/concepts/cross-dc-replication/
