### ISSUE TITLE
retried activity should remember what was the failure reason

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#903]
When activity is scheduled with retry policy, and the execution failed, server would ignore that failure and schedule a new activity task. From user's point of view, there is no insight of what's going on. We need to keep the last FailedReason/FailedDetails in mutable state so when user do DescribeWorkflowExecution it could see that pending activity is retrying and what was the reason/details.

**Comment by Remedy441** [comment]
Can I work on this issue?

**Comment by yycptt** [comment]
This is a duplication of https://github.com/uber/cadence/issues/698
