### ISSUE TITLE
Metric to alarm on shard ack level falling behind

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#950]
Every shard has a background job which cleans up the timer and transfer tasks when all the cursors have moved beyond that point.  If for whatever reason a cursor does not moves than we could have shard not delete any timer/transfer tasks. One scenario this could happen is if we have very high traffic on one cluster and very low traffic on another.
This could become a problem when the failover comes in as now we have to scan over all those stale task for the failed over domain.
We first of all need to heartbeat from the shard to guarantee cursor will move and then also set up a metric to compute lag on delete cursor to trigger alert if it breaches a threshold.

**Comment by longquanzheng** [comment]
Done internally
