### ISSUE TITLE
common/messaging/kafkaClient.go:50:15: unknown field 'BrokerList' in struct literal of type kafka.Topic

### ISSUE THREAD

**Issue by alexbkx** [uber/cadence#969]
**BUG**
**It appears that _BrokerList_ has been deprecated in uber-go/kafka-client but this has not been propagated to kafkaClient.go in cadence.** 

Installing cadence on ubuntu 16.04 with cassandra, following https://github.com/uber/cadence/blob/master/CONTRIBUTING.md#building (building off of master branch):
'make bins' throws error when building cadence-cassandra-tool: 

```
github.com/uber/cadence/common/messaging
common/messaging/kafkaClient.go:50:15: unknown field 'BrokerList' in struct literal of type kafka.Topic
common/messaging/kafkaClient.go:55:15: unknown field 'BrokerList' in struct literal of type kafka.Topic
Makefile:84: recipe for target 'cadence-cassandra-tool' failed
make: *** [cadence-cassandra-tool] Error 2
```

Build environment:
```
go v1.8
glide v0.13.1
uname -a output: Linux mycadencehost 4.4.0-1060-aws #69-Ubuntu SMP Sun May 20 13:42:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alexbkx** [comment]
Can someone investigate this? Cadence can't built because of it.

**Comment by georgeteo** [comment]
https://github.com/uber-go/kafka-client/issues/61

**Comment by longquanzheng** [comment]
I will update kafka-client to 0.2.x later since internal client also need update on it. That will fix this issue.
Probably we should do it next sprint @samarabbas . It will be some refactoring in our code and config files.
